### ISSUE TITLE
缺少源码文件index.vue

### ISSUE THREAD

**Issue by we3ew** [jeecgboot/jeecgboot-vue3#10]
缺少文件
jeecgboot-vue3-master/src/views/dashboard/Analysis/index.vue

**Comment by zhangdaiscott** [comment]
你的文件夹应该是首字母小写`analysis ` 改成大写 `Analysis`  就行了

**Comment by YANGHAOHEHE** [comment]
> 你的文件夹应该是首字母小写`analysis ` 改成大写 `Analysis` 就行了

你有一次提交好像把那个index.vue删掉了，git回滚一下就好了。
