### ISSUE TITLE
DatePicker传值格式错误，少了秒钟

### ISSUE THREAD

**Issue by depthwood** [jeecgboot/jeecgboot-vue3#100]
##### 版本号：
v1.2.0

##### 问题描述：
DatePicker传值格式错误，少了秒钟

##### 截图&代码：
1.在表单中使用DatePicker组件
![image](https://user-images.githubusercontent.com/65118489/173780016-6b80ac87-79ca-4be5-ad5c-31521c28b855.png)
2.新增时界面时间显示正确
![image](https://user-images.githubusercontent.com/65118489/173780219-82352c30-b583-4255-8764-819d8d0d1fe6.png)
3.请求传时间格式错误
如图所示开始时间和结束时间的秒钟没有
![image](https://user-images.githubusercontent.com/65118489/173780376-cd28965c-f2c8-4f5d-a3a2-de47295bd257.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by depthwood** [comment]
![image](https://user-images.githubusercontent.com/65118489/173787342-698d1b1e-ae0e-4596-b444-61d38455fed4.png)
疑似代码生成器模板中缺少参数，导致生成的代码日期格式化错误
格式正确代码如下
![image](https://user-images.githubusercontent.com/65118489/173787709-8c7ffc27-07ef-4197-b5c7-ee9c74772644.png)

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
已修改
