### ISSUE TITLE
切换tab栏问题

### ISSUE THREAD

**Issue by cynail** [jeecgboot/jeecgboot-vue3#1001]
##### 版本号：

所有
##### 问题描述：
当菜单里配置角色管理不是缓存路由，从角色管理切到首页时，角色管理的接口还是会请求。不止角色管理会这样，其他页面也是一样

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你都不缓存路由，当然是重新加载啊
