### ISSUE TITLE
BasicTable自定义查询查询时参数带list参数时，传入后端参数异常

### ISSUE THREAD

**Issue by nyzplymh** [jeecgboot/jeecgboot-vue3#1002]
##### 问题描述：
table开启表单搜索时，参数传入后端异常，录了屏，这里不能直接传入，
1是修改参数后打断点的情况，这个时候正常请求后端的参数
2是没有修改源码的情况传参的情况，再合并参数后，会把参数中的list对象做处理传入后端

##### 截图&代码：
[录屏1](https://pan.baidu.com/s/1ad5PvaBPQDOUSI_wVvKuMA?pwd=eggh)

[录屏2](https://pan.baidu.com/s/1AHXi-cn-sgBzLXtejLcGwQ?pwd=x9m5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by nyzplymh** [comment]
<img width="1238" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/13833688/a667527a-85bb-4f9b-8bf9-16a543d7c11c">
http://localhost:3100/jeecgboot/score/smsScore/shardClassList?semester=202302&grade=1&classNumber=4&shardClassStrategyList[0].examName=0&shardClassStrategyList[0].proportion=50&shardClassStrategyList[1].examName=1&shardClassStrategyList[1].proportion=50&_t=1706706253707

**Comment by nyzplymh** [comment]
<img width="977" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/13833688/861ef7e1-5f4f-476a-81ac-b0b70b15dbcb">
用的这种方式 ，有动态生成的数组参数
hook用的useListPage，没有用beforeFetch进行参数合并
<img width="522" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/13833688/d91a965a-5f89-40e6-9f54-6fdea06c6c00">
<img width="571" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/13833688/6e1f49e6-a3af-4c97-9af1-2874aa178de3">

**Comment by lsqGitHub716** [comment]
测试，你说的参数是通过`opt?.searchInfo`导致的，你可以通过
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/3e9ba1ba-4e01-40da-a1d8-7b6486149c64)
进行参数处理
