### ISSUE TITLE
英文语言下锁屏弹框表单的label内容被遮住了

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/jeecgboot-vue3#1004]
##### 版本号：
3.6.2

##### 问题描述：
英文语言下锁屏弹框表单的label内容被遮住了，如下图：
<img width="1679" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/dd5aa205-30e4-47e8-a32a-a0de1a27c2c8">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
在src/layouts/default/header/components/lock/LockModal.vue文件，你可按如下图修改
<img width="888" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/b2066a39-0b91-4541-b6ad-eb5efbb4844e">

**Comment by liaozhiyang** [comment]
> 已修复，下一版本发布。 在src/layouts/default/header/components/lock/LockModal.vue文件，你可按如下图修改 <img alt="image" width="888" src="https://private-user-images.githubusercontent.com/8199499/298482807-b2066a39-0b91-4541-b6ad-eb5efbb4844e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjQ0NjcsIm5iZiI6MTcwNjE2NDE2NywicGF0aCI6Ii84MTk5NDk5LzI5ODQ4MjgwNy1iMjA2NmEzOS0wYjkxLTQ1NDEtYjZhZC1lYjVlZmJiNDg0NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDYyOTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk1OTBlYTk4YzBkNTJkNDk0ZTZiOGU1NWE3M2U1YmMyY2Y0NDE4NjY1YjFkZGY3NTA2ZDE5Yzc0ZWExZjFhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5V6u6LVNQ6QeRB27MkNf_aLhJgGl6mC_kG15T0YFefc">

后来我们放弃了如上这种修复方法（觉得界面不好看）。
把英文lock screen passwrod 改成了password
