### ISSUE TITLE
新版本无法使用JMarkdownEditor

### ISSUE THREAD

**Issue by Jarvisssss** [jeecgboot/jeecgboot-vue3#1009]
##### 版本号：
jeecgboot-vue3 3.6.2

##### 问题描述：
JMarkdownEditor组件加载不出来，没有报错，找不到原因

##### 截图&代码：

![295844525-bcea81bd-cbb8-47a1-8e66-b23ce5ee2709](https://github.com/jeecgboot/jeecgboot-vue3/assets/39944949/c48ecde1-fef2-4b7f-ab8c-411d36f1d362)

**Comment by zhangdaiscott** [comment]
可以打开，不联网不行
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/3d38dc2c-45b0-4ecd-aa4b-c6921f8e7fe6)
