### ISSUE TITLE
自动锁屏后无法解锁

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#1010]
版本号：
jeecgboot-vue3 3.6.2

问题描述：
自动锁屏后无法解锁，用上次锁屏密码和系统登录密码 均无法解锁

**Comment by zhangdaiscott** [comment]
ws

**Comment by liaozhiyang** [comment]
测试正常，有更详细的操作说明吗？

https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/c15d74cb-f2dd-4ec9-aa72-bc470efd7d3d
