### ISSUE TITLE
官方部署文档中nginx配置错误

### ISSUE THREAD

**Issue by Upppp** [jeecgboot/jeecgboot-vue3#1011]
##### 版本号：
官方文档链接：https://help.jeecg.com/publish/quick.html

##### 问题描述：
「快速构建&部署」部分nginx的配置文件错误，其中 “location  /jeecgboot/ {....” 应该修改为 “location  /jeecg-boot/ {” 才可以与后端接口匹配。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/26338724/c21362ef-6922-43dd-8068-35c69ef331dc)

**Comment by zhangdaiscott** [comment]
你说的是错误的
