### ISSUE TITLE
本地运行前端代码修改后保存，浏览器会刷新并且运行很慢

### ISSUE THREAD

**Issue by bzdqsmmzh** [jeecgboot/jeecgboot-vue3#1018]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新到最新版就好了
