### ISSUE TITLE
表单在线开发本地测试异常

### ISSUE THREAD

**Issue by linlin-coder** [jeecgboot/jeecgboot-vue3#102]
##### 版本号：
1.2.0

##### 问题描述：
以下均为个人所遇问题，如果存在，大佬有空辛苦修复修复，鞠躬~  
问题1：主表-附表 提供ERP主题、内嵌子表主题，和TAB主题，但是这些都没有生效，至少没有像vue2版本界面中，直接展示主子表信息。  
问题2：构建的表单，在测试表单预览时，报sys.api.errmsg404错误，没有搜索栏出现。  

##### 截图&代码：
![image](https://user-images.githubusercontent.com/77706356/174422350-d9f19502-0a3b-4fb7-982e-52d361e36fe8.png)

![NEB@}Z8}1 18$4@_D~BCHS0](https://user-images.githubusercontent.com/77706356/174422587-8d59318c-69bb-425e-ad68-fdf3dd9b8137.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
问题1 ，不同风格还未实现
问题2，后台代码未更新到最新
