### ISSUE TITLE
前端项目启动失败

### ISSUE THREAD

**Issue by zhaoyazhou** [jeecgboot/jeecgboot-vue3#1020]
##### 版本号：
jeecgboot-vue3 3.6.1

##### 问题描述：
环境：m1 mbp macos 14.2.1
node 16.20.2  npm 8.19.4

使用 npm run dev 失败，内容可参考截图

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/15082435/07a6abbb-8cfa-40eb-a933-48185da18328)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
使用pnpm i安装
