### ISSUE TITLE
我这个控件是哪里设置没对吗，为什么打开已有的记录，会触发提示“请输入”验证？

### ISSUE THREAD

**Issue by ve03** [jeecgboot/jeecgboot-vue3#1022]
##### 问题描述：我这个控件是哪里设置没对吗，为什么打开已有的记录，会触发提示“请输入”验证？就是第一次会出现，第二次再点就不会出现了
j-dict-select-tag标签增加type="radioButton"也会出现这个问题

##### 截图&代码：
![111](https://github.com/jeecgboot/jeecgboot-vue3/assets/157146280/da96b4f0-0022-4472-a3e8-7bd08575e304)
![222](https://github.com/jeecgboot/jeecgboot-vue3/assets/157146280/1d7192df-8e1a-4a2f-9c64-585e73db0472)
![selecttah](https://github.com/jeecgboot/jeecgboot-vue3/assets/157146280/3b9ab3f9-b534-46ea-93ac-3e76d38aaee1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ve03** [comment]
找到原因了，是nextTick方法的影响
![解决](https://github.com/jeecgboot/jeecgboot-vue3/assets/157146280/68cebcd8-9c0f-4a8c-b172-7dccb616f80a)

**Comment by ve03** [comment]
哪位大佬能解释一下为什么会这样吗？

**Comment by ve03** [comment]
排查发现是immediate参数的问题，请问这个参数是什么用途，立即执行验证吗？
![11](https://github.com/jeecgboot/jeecgboot-vue3/assets/157146280/106afdfd-2532-4303-9109-3dfce2f6376f)

**Comment by zhangdaiscott** [comment]
sq

**Comment by 1298191366** [comment]
已修复，待新版本发布，目前默认模板生成改成了false
