### ISSUE TITLE
仪表盘设计中json数据源href配置了，但是不生效，点击没反应

### ISSUE THREAD

**Issue by gentlemango2016** [jeecgboot/jeecgboot-vue3#1024]
##### 版本号：
3.6.2

##### 问题描述：
仪表盘设计中json数据源href配置了，但是不生效，点击没反应

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/19324969/728793ff-1d31-4e74-bc97-15b89677bacf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
描述请图文并茂

**Comment by gentlemango2016** [comment]
> 描述请图文并茂

已贴图谢谢

**Comment by zhangdaiscott** [comment]
那个组件

**Comment by gentlemango2016** [comment]
> 那个组件
快捷导航

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by gentlemango2016** [comment]
3.6.3版本中还是未生效啊，不好使

**Comment by gentlemango2016** [comment]
> 已修改，下版本发布

3.6.3版本中还是不生效，不起作用
