### ISSUE TITLE
popup设置宽度不起作用

### ISSUE THREAD

**Issue by mengrose** [jeecgboot/jeecgboot-vue3#1026]
##### 版本号：
3.6.1
##### 问题描述：
在componentProps配置了width属性，但是实际不起作用。
##### 截图&代码：
    componentProps: ({ formActionType }) => {
      const {setFieldsValue} = formActionType;
      return{
        setFieldsValue:setFieldsValue,
        //online报表编码
        code:"demo",
        //是否为多选
        multi:false,
        //字段配置
        fieldConfig: [
          { source: 'name', target: 'popup' },
        ],
        width:400
      }
    },

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/62c407ca-5a96-40b2-a5fe-5de63f1c4f17)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后期待规划，先收集到 https://github.com/jeecgboot/jeecg-boot/issues/1312
