### ISSUE TITLE
打包后 请求后台接口的路径， 不能背nginx 代理

### ISSUE THREAD

**Issue by Xiawen123** [jeecgboot/jeecgboot-vue3#103]
##### 问题描述：
打包后 项目请求地址 一直是 VUE_APP_API_BASE_URL 的值， nginx 代理不生效
VUE_APP_API_BASE_URL=http://localhost:80/jeecg-boot

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50976629/174449834-9ca20fdf-6d01-4b9b-aa9c-51f37434931b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
应该是你配置的不对，我们演示环境频繁发布，没有任何问题
