### ISSUE TITLE
表单标签默认在输入框上方无法修改

### ISSUE THREAD

**Issue by baichaya** [jeecgboot/jeecgboot-vue3#1032]
##### 截图&代码：
![Snipaste_2024-01-24_11-32-34](https://github.com/jeecgboot/jeecgboot-vue3/assets/87114900/ef476f77-5574-4b31-b62b-dbe036abba35)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
啥意思
