### ISSUE TITLE
附表中popup弹窗中的表格记录不对，已按照你们新版本修改，但bug依旧

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecgboot-vue3#1035]
##### 版本号：
v3.5.1

##### 问题描述：
在附表字段中配置了popup，弹窗载入配置报表中的表格；但是二者数据却不一致。当在配置报表中已经删除的数据后，点击附表popup却仍然保留。然而，当点击第二页，或者另外选择一页显示的条数的时候，却又能正确显示条目。比如，配置报表中，删除数据后只有17条数据，但附表popup弹窗的表格中却显示有18条数据，已经删除的数据还是在里面，但如果点击第2页，则有能显示17条数据了。。。我已按照你们的最新版本修改了popup子表不刷新的bug，#675，但此bug还依然存在。

请问要怎样修复？不全部更新软件的情况下，如何手动修改代码解决此bug？

##### 截图&代码：
![1](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/5b93015e-2de3-4edf-8a6c-77ac692ea942)
![2](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/26fd501e-41cd-49d2-b2f5-9b9e59c84409)
![3](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/49f3d079-862b-4bb3-900f-0a764e74de42)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
通过这个
[https://github.com/jeecgboot/jeecgboot-vue3/commit/63cea84cfc5c92d9525cc212866b8c7dbbe85bad]( https://github.com/jeecgboot/jeecgboot-vue3/commit/63cea84cfc5c92d9525cc212866b8c7dbbe85bad) 查看应该还少改了一个文件的代码。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/5d135871-d103-4acd-b122-4727d285b8a4)

点击[https://github.com/search?q=repo%3Ajeecgboot%2Fjeecgboot-vue3%20%E5%AD%90%E8%A1%A8%E5%AD%97%E6%AE%B5Popup%E5%BC%B9%E6%A1%86%E6%95%B0%E6%8D%AE%E4%B8%8D%E6%9B%B4%E6%96%B0&type=code](https://github.com/search?q=repo%3Ajeecgboot%2Fjeecgboot-vue3%20%E5%AD%90%E8%A1%A8%E5%AD%97%E6%AE%B5Popup%E5%BC%B9%E6%A1%86%E6%95%B0%E6%8D%AE%E4%B8%8D%E6%9B%B4%E6%96%B0&type=code)试试。

在 src/components/Form/src/jeecg/components/JPopup.vue 文件还有代码改动

**Comment by ciahua** [comment]
> 通过这个 [63cea84](https://github.com/jeecgboot/jeecgboot-vue3/commit/63cea84cfc5c92d9525cc212866b8c7dbbe85bad) 查看应该还少改了一个文件的代码。 ![image](https://private-user-images.githubusercontent.com/8199499/300329681-5d135871-d103-4acd-b122-4727d285b8a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzk5NzksIm5iZiI6MTcwNzI3OTY3OSwicGF0aCI6Ii84MTk5NDk5LzMwMDMyOTY4MS01ZDEzNTg3MS1kMTAzLTRhY2QtYjEyMi00NzI3ZDI4NWI4YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMDQyMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U3MTFjYWQwY2ZkYWUwNTQxNjBjNjE5NzViMzdhODViNDcwNjE5ODFmYTNjNGNjNGVhMWE2N2U2N2Q3OTdhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X-9u3Ty7xd62qhgqWIVxuzXiJq31HHCYOYQjgvd0oQo)
> 
> 点击https://github.com/search?q=repo%3Ajeecgboot%2Fjeecgboot-vue3%20%E5%AD%90%E8%A1%A8%E5%AD%97%E6%AE%B5Popup%E5%BC%B9%E6%A1%86%E6%95%B0%E6%8D%AE%E4%B8%8D%E6%9B%B4%E6%96%B0&type=code试试。
> 
> 在 src/components/Form/src/jeecg/components/JPopup.vue 文件还有代码改动

非常感谢！
