### ISSUE TITLE
用户属于多个租户和多个部门时，能在系统主界面顶部工具栏上显示当前登录的租户和部门

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#1039]
##### 版本号：
3.6.2

##### 问题描述：
当前登录后不清楚登录的是哪个租户和部门，需要到切换部门里看，很麻烦！

建议：
当用户属于多个租户时，能显示当面登录的租户名
当用户属于多个租户时，能显示当前登录的部门

如果只属于一个租户或部门，则不需要显示对应的租户名或部门名。

用户重新登录时，默认用最后一次登录的租户和部门登录。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
个性化的需求自己扩展吧
