### ISSUE TITLE
删除部门要判断org code是否已经被业务表使用，如果使用了就不能删除部门，这个判断逻辑有什么好的方案？

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#1040]
##### 版本号：
3.6.2

##### 问题描述：
所有的业务表都添加了 sys_org_code字段来实现数据权限。

问题一：
在删除部门记录时，如果部门的 org_code 已经被其他业务表使用，那就不能删除这个部门，否则业务数据因为关联不到部门发生异常。

业务表很多，不可能在删除部门的接口里一个一个判断，除了使用外键，有什么统一的解决方案么？

问题二：
公司部门有真实的并且有业务意义的代码，需要维护在部门代码中，并且在业务表的 sys_org_code 保存。

现在部门代码是自动生成的，无法保存自定义的部门代码。
现在部门代码最大的用途就是方便查找上下级节点，能否把这个自动生成的部门代码改成其他字段名，让用户自己填写部门代码，只要同一个租户里唯一就可以。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以把部门改成逻辑删除，发现有影响再恢复
