### ISSUE TITLE
代码生成后表单编辑的时候未传id过去

### ISSUE THREAD

**Issue by 191474639** [jeecgboot/jeecgboot-vue3#1043]
##### 版本号：
3.6

##### 问题描述：
生成的代码在列表点击编辑的时候，唯一校验未传id，编辑保存成功，但是其值没有变化，还有表单字典也显示失败

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/26876543/a7913dc7-0dca-4008-8b71-f7ac1e408f58)
![7e6a91287d8ebbce2b55e46f3604cde5](https://github.com/jeecgboot/jeecgboot-vue3/assets/26876543/dea1116a-c883-41af-92d7-9247cff81ee7)
![63a82bf1afa272c4340acea73bae9f09](https://github.com/jeecgboot/jeecgboot-vue3/assets/26876543/79ce3ccb-d489-4692-8475-182e01993f05)
![2a260413fb51f86637256ba12236662c](https://github.com/jeecgboot/jeecgboot-vue3/assets/26876543/f2acc40c-bf56-4de3-95ba-f6741eb3367d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
版本号写清楚，用的那个模板，vue几？
