### ISSUE TITLE
关于人大金仓数据库

### ISSUE THREAD

**Issue by bzdqsmmzh** [jeecgboot/jeecgboot-vue3#1046]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
直接用就行，不需要什么改动

**Comment by bzdqsmmzh** [comment]
> 直接用就行，不需要什么改动

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/83258750/433ccc4c-68b5-4860-8c9b-1300c163e58f)
我用的时候报了这个错是什么原因
