### ISSUE TITLE
对接人大金仓数据库报错

### ISSUE THREAD

**Issue by bzdqsmmzh** [jeecgboot/jeecgboot-vue3#1048]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/83258750/179700f5-4b0a-43fe-8d88-32d88d052687)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
数据库配置有问题

**Comment by 1298191366** [comment]
请参考人大金仓数据库配置：https://help.jeecg.com/java/setup/switchdb.html#5-%E4%BA%BA%E5%A4%A7%E9%87%91%E4%BB%93%E6%95%B0%E6%8D%AE%E5%BA%93
