### ISSUE TITLE
DatePicker 日期框组件在线上环境中选中后无效，在本地正常

### ISSUE THREAD

**Issue by szh18** [jeecgboot/jeecgboot-vue3#1052]
##### 版本号：

3.6.2
##### 问题描述：
DatePicker 日期框组件在线上环境中选中后无效，在本地正常

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/74402781/a6330ddc-c01a-4f3b-a5c4-84871321898c)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/74402781/f12e4d5f-05df-4090-95fa-bacba3e4c36c)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/74402781/2cf3e7d1-5cc2-4c05-a0c7-4fc5a2e60425)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by szh18** [comment]
是不是因为ant-vue版本的问题啊，你们官网上面的都可以，但是我这边线上所有日期框的都不行，包括你们组件实例中useForm里面的也不行

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/991
看看是不是这个问题

**Comment by szh18** [comment]
![1](https://github.com/jeecgboot/jeecgboot-vue3/assets/74402781/6b5675ca-1d45-423f-9f97-d7c47a866f42)


我把ant-design-vue 从4.0.8升到4.1.2的版本 vue版本不变 3.3.11，打包后部署到线上还是不能选择时间，而且弹出框弹出后不能收回,
jeecg 3.3.11版本

**Comment by szh18** [comment]
> #991 看看是不是这个问题

![1](https://github.com/jeecgboot/jeecgboot-vue3/assets/74402781/1e9566dd-8320-4069-8664-48348a1adbf8)
antd-vue由4.0.8升级到4.1.2，vue版本保持不变 3.3.11，打包部署到到线上DatePicker日期框还是不能被选择，

**Comment by szh18** [comment]
ant-design-vue 和vue版本多次更改还是无效，vue固定在3.3.11 ，ant-design-vue 固定4.0.8，生产环境下日期框DatePicker还是无法选择修改日期

**Comment by szh18** [comment]
> #991 看看是不是这个问题

已解决，vite不能使用 mode test,改一下名字就好了

**Comment by szh18** [comment]
> #991 看看是不是这个问题

已解决，vite不能使用 mode test,改一下名字就好了
