### ISSUE TITLE
JSelectUser传入表单参数一直是undefined

### ISSUE THREAD

**Issue by mwsdxe** [jeecgboot/jeecgboot-vue3#1053]
##### 截图&代码：

![微信图片_20240202141833](https://github.com/jeecgboot/jeecgboot-vue3/assets/119851393/96149468-1c8a-4dd4-b993-ab59bb50f2dd)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by mwsdxe** [comment]
你好，谢谢您的回复，但是我的组织部门是默认的（不能选择），不是动态选择的，如何传递选择用户的组件呢？

**Comment by 1298191366** [comment]
静态写死的也有值改变事件吧？只要是值发生改变不就会触发change事件

**Comment by mwsdxe** [comment]
哦，谢谢啊，我尝试下。

**Comment by 1298191366** [comment]
或者你在打开弹窗的时候，肯定有数据，那时候去更新
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/e1889d2b-0d20-4761-bad3-e57ad2aa7e5b)

**Comment by mwsdxe** [comment]
谢谢，我都尝试了，静态初始化的没有触发onchange，第二种的可以带人参数，谢谢了，收获不少，谢谢远方支持的你，我会更加努力的！！！
