### ISSUE TITLE
ApiTreeSelect组件入参变化时，不及时刷新数据

### ISSUE THREAD

**Issue by yuan0824** [jeecgboot/jeecgboot-vue3#1054]
##### 版本号：
3.6.2

##### 问题描述：
ApiTreeSelect组件的这段代码（如图），在入参变化且isFirstLoaded是false时调用fetch函数，再次请求接口，我觉得在入参变化的情况下，就应该再次调用fetch函数，不应该再次判断isFirstLoaded，不然这个监听就没有意义了。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34811957/07201002-480c-445a-a1a6-a5418a4f69f2)

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
