### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by machuang123** [jeecgboot/jeecgboot-vue3#1055]
##### 版本号：
3.6.2

##### 问题描述：
启动报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44514814/40c59d96-98a9-4434-9e46-e2118fe3ed4a)

**Comment by zhangdaiscott** [comment]
你使用pnpm i

**Comment by machuang123** [comment]
> pnpm i

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44514814/1aba1139-376f-41b5-877d-de3e9a12ff5b)
还是不行

**Comment by machuang123** [comment]
解决了 node版本问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44514814/c893c496-752e-4d13-9a54-d15ebffa57a7)
