### ISSUE TITLE
如何设置浏览器新起一个浏览页打开页面

### ISSUE THREAD

**Issue by 18237966658** [jeecgboot/jeecgboot-vue3#1056]
##### 版本号：

V 3.6.2
##### 问题描述：
在菜单管理中，将菜单的打开方式设置为“外部”，但是点击菜单的时候并没有在外部打开，还是在当前页面打开了菜单内容。
请问，如何设置新起一个页面打开页面内的东西，并且不显示原来的导航菜单？
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50265705/bcc06492-755f-4c5f-afc7-f72d9af14632)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50265705/1ddfa1c3-4edb-4e58-bce3-c0b2b5f68554)

**Comment by zhangdaiscott** [comment]
外部得是http开头的，得是外部链接

**Comment by 18237966658** [comment]
> 外部得是http开头的，得是外部链接

OK,了解
