### ISSUE TITLE
新增数据字典输入什么都提示校验失败

### ISSUE THREAD

**Issue by zyc8687** [jeecgboot/jeecgboot-vue3#1057]
##### 版本号：
3.6.1

##### 问题描述：
新增数据字典的时候 字典编码项输入什么都是 校验失败，存在SQL注入风险！白名单校验未通过！
在字典表白名单添加了对应的表 和字段但是无效
##### 截图&代码：
https://github.com/jeecgboot/jeecgboot-vue3/assets/84056161/f86f2993-4d77-4bf4-8461-62bcc2141842
https://github.com/jeecgboot/jeecgboot-vue3/assets/84056161/06b3e0a8-9cae-49a0-9bad-b8a1511a2cb7

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你怎么加的，截图
白名单的配置参考这个
https://help.jeecg.com/java/java/config/sqlwhitelist.html
