### ISSUE TITLE
浏览器刷新时，租户id被改为上一个用户的租户id

### ISSUE THREAD

**Issue by MRERDUO** [jeecgboot/jeecgboot-vue3#1058]
##### 问题描述：当从拥有多个租户的账户退出登录，登录到另一个账户，当这个账户没有上一个退出登录的账户的租户时，刷新后直接退出登录

原因：每次刷新时localStorage里的租户id（TENANT_ID）及登录信息（LOGIN__INFO__）都会被清空变为上一个登录的租户信息，导致请求时传的租户id不对从而退出登录

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
版本太老，如果有问题请自己排查吧或者参考最新的代码
