### ISSUE TITLE
接口查询数据量过多时，会出现接口超时，但是后端仍然在查询

### ISSUE THREAD

**Issue by mySoul8012** [jeecgboot/jeecgboot-vue3#1060]
##### 版本号：
[v3.5.5](https://github.com/jeecgboot/jeecgboot-vue3/releases/tag/v3.5.5)

##### 问题描述：

接口查询数据量过多时，容易出现接口超时，但是后端仍然在查询，如何更改前端的接口超时时间
##### 截图&代码：

![1708219492859](https://github.com/jeecgboot/jeecgboot-vue3/assets/34295098/670ace2c-28c5-4595-af1e-b983406875a6)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/1a4b5c78-53a2-421f-87ee-82aadca7f40f)
