### ISSUE TITLE
官方演示平台系统角色中问题

### ISSUE THREAD

**Issue by gengmengmeng** [jeecgboot/jeecgboot-vue3#1064]
##### 版本号：
"name": "jeecgboot-vue3",
"version": "3.4.2",
可能是这个版本，我在官方演示平台发现的问题。
##### 问题描述：
在官方演示平台系统角色中，点击角色列表中的列设置勾选保存后，会直接把用户里面的列设置给清空，只剩下操作列。在用户中重新列设置，重复上述操作，仍会清空。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/49386620/fecc3753-5a66-4a60-a99a-56b06ae99f5a)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/49386620/f4ee07ab-c181-4294-97c2-a5398ddf9975)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你可在本地 src/views/system/role/components/RoleUserTable.vue 文件按如下修改： 
<img width="1038" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/de126f5d-fad3-4fdf-b815-18c56cad5a30">
tableSetting.cacheKey 需要一个唯一标识（这个唯一标识也不能在底层生成，否则每次会不一样）。
页面中只有一个table时可不传入，取的是路由fullPath（后期会改成route.path的值）。页面中有多个table时，tableSetting.cacheKey需要填写否则本页面中所有table的cacheKey取的是同一个。




已知其他页面类似情况的：

<img width="1041" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/27cc5cee-a742-4ab2-beae-cc78800e442a">

<img width="1023" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/5eb247f9-0de8-479c-9f2a-5cdfe23df19f">

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/0a5c42a1-0e6d-4303-a7b4-7e3d0b356e72)

**Comment by gengmengmeng** [comment]
本地测试，bug已修复

**Comment by gengmengmeng** [comment]
本地测试，问题已解决，谢谢
