### ISSUE TITLE
JVxeInputCell小数输入有问题小数点后第一位是非0第二位是0就不能输入了 例如输入100.102会变成100.12

### ISSUE THREAD

**Issue by ITyaoji** [jeecgboot/jeecgboot-vue3#1065]
##### 问题描述：
使用JVxeTable组件 某一列的组件使用JVxeTypes.inputNumber时输入100.102会变成100.12调试如下：

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/24262180/7dea8a13-4748-41db-a16d-a6f58d066c20)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/24262180/41fafef4-3b43-43b0-9693-ed01f117f0f3)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/24262180/dcab50d2-9111-4d40-9790-aa475434597d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。（这是js特性引起的，小数点后面的最后一位0会被自动忽略）

你本地可在 src/components/jeecg/JVxeTable/src/components/cells/JVxeInputCell.vue 文件按如下图进行修改：
<img width="876" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/6c46c047-5dc1-4b95-a827-4fc435570593">

```
if (value.indexOf('.') != -1) {
              const result = value.split('.').pop();
              if (result && result.length >= 2 && result.substr(-1) === '0') {
                change = false;
                innerValue.value = value;
              }
            }

```
