### ISSUE TITLE
Online表单开发，功能测试报错

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/jeecgboot-vue3#107]
##### 版本号：
 1.2.0（版本发布时间：20220606）

##### 问题描述：
online表单开发功能，点击功能测试 报错，（官网的也报错）

##### 截图&代码：

![image](https://user-images.githubusercontent.com/50694382/175192027-109fa7bc-fa5d-4141-9305-c139728a9ee9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
怎么配置的，为什么我配置的例子没问题

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
未重现，请提供具体示例
