### ISSUE TITLE
JSelectUser、JSelectUserByDept设置为单选时选中效果出错问题

### ISSUE THREAD

**Issue by annong163** [jeecgboot/jeecgboot-vue3#1071]
##### 版本号：
 v3.6.2

##### 问题描述：
**JSelectUser、JSelectUserByDept设置为单选时选中效果出错，且选中的数据也会出错**

##### 截图&代码：
![1](https://github.com/jeecgboot/jeecgboot-vue3/assets/51952936/59dc1db0-a166-4ed9-875f-e982eafc3fd0)

![1708669220164(1)](https://github.com/jeecgboot/jeecgboot-vue3/assets/51952936/5dc4533a-7f8a-4481-8d8d-603ee0a35750)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
经测无法重现。感觉是rowKey填写的有问题，rowKey应该是唯一标识。
![aa](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/11cc6c37-d628-47a1-b0f0-49bd0bf0077a)
<img width="710" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/28df8f4e-7a8d-40c9-8e3d-4477be45dc59">

**Comment by annong163** [comment]
是rowKey为null的问题   感谢
