### ISSUE TITLE
【菜单管理】、【角色管理】功能未翻译本地化 key

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#1072]
##### 版本号：
3.6.2

##### 问题描述：
【菜单管理】、【角色管理】功能未翻译本地化 key
图片中的本地化 key 已经定义。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/a5ac3d64-3add-486b-a132-71f82777a766)

![1708672488428](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/1feed7bf-1665-4f59-a060-38274e09d809)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你本地可在 src/views/system/role/components/RolePermissionDrawer.vue 文件按如下进行修改

<img width="823" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/663b49b6-c88d-4468-9feb-c2cbf6f168a4">


```
import {useI18n} from "/@/hooks/web/useI18n";

if(roleResult.treeList?.length){
      roleResult.treeList.forEach(item => {
        if(item.slotTitle){
          const { t } = useI18n();
          if(item.slotTitle.includes("t(\'") && t){
            item.slotTitle = new Function('t', `return ${item.slotTitle}`)(t);
          }
        };
      });
    }
```

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你本地可在 src/views/system/role/components/RolePermissionDrawer.vue 文件按如下进行修改

<img width="998" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/5feddd94-a2f1-47c7-aabb-06c7fdc91017">

```
treeData.value = translateTitle(roleResult.treeList);

function translateTitle(data) {
    if (data?.length) {
      data.forEach((item) => {
        if (item.slotTitle) {
          const { t } = useI18n();
          if (item.slotTitle.includes("t('") && t) {
            item.slotTitle = new Function('t', `return ${item.slotTitle}`)(t);
          }
        }
        if (item.children?.length) {
          translateTitle(item.children);
        }
      });
    }
    return data;
  }
```
