### ISSUE TITLE
配置了字典表，为何显示的时候不能选中对应value的text呢

### ISSUE THREAD

**Issue by zjypp** [jeecgboot/jeecgboot-vue3#1074]
##### 问题描述：
在代码开发模式下，已经创建了一个状态字典表，在表设计的时候，对字典应用了这个字典。

在代码开始模式下，验证功能的时候，下拉框的读取和 回显示是正常的
生成代码以后，把代码文件复制到项目中，配置菜单以后，在读取到正确value的情况下，下拉框没有选中正确的text，如图示

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/4704158/09e787dc-f947-44e1-86e8-2366206d22ec)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/4704158/8295bac8-c457-48aa-abd2-628a9884eb69)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
类型匹配吗
