### ISSUE TITLE
请问怎样设置BasicTable表格中的字体为粗体和字体大小？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecgboot-vue3#1076]
##### 版本号：
v3.5.1

##### 问题描述：
请问怎样设置BasicTable表格中的字体为粗体和字体大小？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
默认没这功能，你只能自定义
