### ISSUE TITLE
列表枚举渲染方法（render.renderDict()）兼容问题

### ISSUE THREAD

**Issue by youngswell** [jeecgboot/jeecgboot-vue3#1079]
##### 版本号：
3.6.2

##### 问题描述：
列表枚举渲染方法（render.renderDict()）在chorme和edge内显示正常，在钉钉内置浏览器显示为空白

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/26730076/70b92424-98d3-4a58-bdd8-b299adb02064)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/26730076/8af3d672-04b6-4fc1-9c6a-08798c6c3758)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
经测试，未复现。还有没有其他特殊配置的地方
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/047805c3-efdb-4a69-be4f-d21fccd842ac)

**Comment by youngswell** [comment]
反复测试后，发现是权限的问题，不知枚举获取接口需要配置什么权限才行？另外，jeecg的权限分配功能似乎不能进行树操作，取消选择又全选后，有些权限会丢失。

**Comment by zhangdaiscott** [comment]
是权限问题的话，你提供下是那个接口具体代码位置

**Comment by youngswell** [comment]
枚举显示异常的账户权限分配情况
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/26730076/faa48d2b-0594-461b-b4bc-e039c6333bcf)
枚举显示正常的账户权限分配情况
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/26730076/7fae36ab-6e4d-4fd0-a766-5b2d5745c827)

**Comment by zhangdaiscott** [comment]
没明白

**Comment by zhangdaiscott** [comment]
一个一个勾选就行
