### ISSUE TITLE
bussi_package修改后生成代码报错，没有is_query字段

### ISSUE THREAD

**Issue by tom6q6** [jeecgboot/jeecgboot-vue3#1080]
##### 版本号：
3.6.2

##### 问题描述：
bussi_package=org.jeecg.modules.demo，修改为org.jeecg.modules，在vscode启动项目后，表不加is_query，online表单生成代码就会报错

##### 截图&代码：

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if po.isShow == "Y" && po.fieldName ...  [in template "default\\one\\java\\${bussiPackage}\\${entityPackage}\\vue\\modules\\${entityName}Form.vuei" at line 24, column 1]
----
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> po.isShow  [in template "default\\one\\java\\${bussiPackage}\\${entityPackage}\\vue\\modules\\${entityName}Form.vuei" at line 24, column 6]

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不是吧，isShow是干嘛的
