### ISSUE TITLE
角色配置首页，用户登录成功后一直卡在中转过渡页面，并且浏览器cpu和内存占用很高

### ISSUE THREAD

**Issue by anlem12** [jeecgboot/jeecgboot-vue3#1084]
##### 版本号：
3.6.2和3.6.0

##### 问题描述：
3.6.2和3.6.0都有这样的问题
角色配置首页，用户登录成功后一直卡在中转过渡页面，并且浏览器cpu和内存占用很高。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/32320086/c6cf60c9-19c2-452c-b949-34f243ae09dc)

一直卡在这里
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/32320086/24afbd49-eab7-40b1-83c3-8d3334b485c4)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/32320086/3a17ca5d-7c9d-4577-9669-a4e3a00ef668)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
![99](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/63852517-97a4-4a7f-99cc-319c70f53c18)
下载的最新版本哈，设定的admin角色的首页是/system/role，没重现哈。有更详细的信息吗
