### ISSUE TITLE
部门人员选择组件 点击重置按钮后无法取消人员选中

### ISSUE THREAD

**Issue by b1naryAKAsAsA** [jeecgboot/jeecgboot-vue3#1085]
##### 截图&代码：

![W3FA@L~AX JPVZN}5U51C7K](https://github.com/jeecgboot/jeecgboot-vue3/assets/119065477/3dfb4b48-8ff9-40d6-9456-629ae9d5f34d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
重置功能重置的只是查询条件

**Comment by b1naryAKAsAsA** [comment]
> 重置功能重置的只是查询条件

不是的哥 重置后对应数组已经是空数组了 我目前的解决方法是重新渲染列表 期待这边更好的解决方案

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/c2a9589f-6d06-437d-85ba-c665bdf1a188)

你本地可在 src/components/Table/src/hooks/useCustomSelection.tsx 文件按照如下修改


```

 // 监听传入的selectedRowKeys
watch(
    () => unref(propsRef)?.rowSelection?.selectedRowKeys,
    (val: string[]) => {
      // 解决selectedRowKeys在页面调用处使用ref失效
      const value = unref(val);
      if (Array.isArray(value) && !sameArray(value, selectedKeys.value)) {
        setSelectedRowKeys(value);
      }
    },
    { 
      immediate: true,
      deep:true 
    }
  );
function sameArray(a, b) {
    if (a === b) {
      if (a.length === b.length) {
        return a.toString() === b.toString();
      } else {
        return false;
      }
    } else {
      return false;
    }
  }

```

**Comment by b1naryAKAsAsA** [comment]
> 已修复，下一版本发布。 ![image](https://private-user-images.githubusercontent.com/8199499/310012883-c2a9589f-6d06-437d-85ba-c665bdf1a188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjI0MzEsIm5iZiI6MTcwOTYyMjEzMSwicGF0aCI6Ii84MTk5NDk5LzMxMDAxMjg4My1jMmE5NTg5Zi02ZDA2LTQzN2QtODViYS1jNjY1YmRmMWExODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDcwMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTcyNTM3ZDk5YmUwMDI0ZjMzMDkzNmU5OWMzODY2YTRkYWE1OTU0MDM0ZTBlZmJhMjkyOGQ2N2UzZTE2YTZjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._7OgnGc4BkFtUTSyzjMhoTPhzFgJCei2CM9i67smBh8)
> 
> 你本地可在 src/components/Table/src/hooks/useCustomSelection.tsx 文件按照如下修改
> 
> ```
> 
>  // 监听传入的selectedRowKeys
> watch(
>     () => unref(propsRef)?.rowSelection?.selectedRowKeys,
>     (val: string[]) => {
>       // 解决selectedRowKeys在页面调用处使用ref失效
>       const value = unref(val);
>       if (Array.isArray(value) && !sameArray(value, selectedKeys.value)) {
>         setSelectedRowKeys(value);
>       }
>     },
>     { 
>       immediate: true,
>       deep:true 
>     }
>   );
> function sameArray(a, b) {
>     if (a === b) {
>       if (a.length === b.length) {
>         return a.toString() === b.toString();
>       } else {
>         return false;
>       }
>     } else {
>       return false;
>     }
>   }
> ```

好的感谢

**Comment by b1naryAKAsAsA** [comment]
成功解决
