### ISSUE TITLE
vue 函数怎么用

### ISSUE THREAD

**Issue by 278469294** [jeecgboot/jeecgboot-vue3#1089]
##### 问题描述：
下图的代码是编译过后的  1.  add方法和subtract 用的是什么对象调用  ，2.evaluate方法是用什么对象调用的。有没有大神帮看看 谢谢

##### 截图&代码：
, n = v["a"].add(t.paidNumber, t.unpaidNumber, t.toleranceNumber)
                                , i = v["a"].subtract(n, a)
, n = g["a"].evaluate(r).toString();

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没看懂，如果是基础知识，自己百度或者看书吧
