### ISSUE TITLE
【菜单管理】页面未翻译本地化 key

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#1090]
##### 版本号：
3.6.2

##### 问题描述：
【菜单管理】页面未翻译本地化 key

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/be8f30a9-7e0a-415b-9044-5701fd13f157)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/e714a2e5-848d-4f5d-9ae6-b5f2a9444d88)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你可在本地按照如下图修改：
<img width="564" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/235208b9-201e-4ce2-b15c-b015c5678c52">

1. src/views/system/menu/index.vue
```
import { useI18n } from "/@/hooks/web/useI18n";

afterFetch:(data) => translateMenu(data, 'title')

function translateMenu(data, key) {
    if (data?.length) {
      const { t } = useI18n();
      data.forEach((item) => {
        if (item[key]) {
          if (item[key].includes("t('") && t) {
            item[key] = new Function('t', `return ${item[key]}`)(t);
          }
        }
        if (item.children?.length) {
          translateMenu(item.children, key);
        }
      });
    }
    return data;
  }

```
2.src/views/system/menu/MenuDrawer.vue
<img width="612" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/8378fc80-0068-4b4c-9588-efd896526881">

```
import { useI18n } from "/@/hooks/web/useI18n";

componentProps: { treeData: translateMenu(treeData, 'name') }

function translateMenu(data, key) {
    if (data?.length) {
      const { t } = useI18n();
      data.forEach((item) => {
        if (item[key]) {
          if (item[key].includes("t('") && t) {
            item[key] = new Function('t', `return ${item[key]}`)(t);
          }
        }
        if (item.children?.length) {
          translateMenu(item.children, key);
        }
      });
    }
    return data;
  }

```

**Comment by citynook** [comment]
@zhangdaiscott 相同代码的 translateMenu  函数在多个文件中重复，建议放到 menu.api.ts 中做为 export function 公共函数供外部调用，让代码最优化。
