### ISSUE TITLE
请求在本地好用发布之后却失效

### ISSUE THREAD

**Issue by yy0514** [jeecgboot/jeecgboot-vue3#1094]
##### 问题描述：
请求在本地是好的 ，部署上线后请求成功但是一直不返回数据

##### 截图&代码：
<img width="1244" alt="微信图片_20240305233428" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/100107431/0f9c9c29-cdc3-4f76-83f7-d90aa585e1ca">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
确认部署问题，按照我们的文档一模一样不会出问题
