### ISSUE TITLE
按钮设置权限v-auth 菜单中配置的是编辑 ，但是没有权限的时候还是会消失，而不是禁用

### ISSUE THREAD

**Issue by 18237966658** [jeecgboot/jeecgboot-vue3#1095]
##### 版本号：
 V 3.6.2

##### 问题描述：

 Vue3 
 
##### 截图&代码：
按钮设置权限v-auth 菜单中配置的是编辑 ，但是没有权限的时候还是会消失，而不是禁用
 <a-button class="submit_but" :disabled="!imagePreview || submitDisabled" type="primary"  v-auth="'image:recognition'" @click="submitContent">开始</a-button>

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50265705/9fe76f48-0020-40b0-a085-0602474e5018)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/vue3/auth/formdisabled.html
:disabled="isDisabledAuth('user:add')"

使用这个
