### ISSUE TITLE
useExportImage文件引入html2canvas模块报错, npmrc文件丢失, 部分依赖没装在node_modules中

### ISSUE THREAD

**Issue by qugemingzizhenmafan** [jeecgboot/jeecgboot-vue3#1096]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/45257656/5ef1cc57-08bd-40f4-be2b-3386aa50c075)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/45257656/120cd9f0-2c22-4640-bdeb-94bb53fddcf0)

**Comment by zhangdaiscott** [comment]
你加上这个依赖    "html2canvas": "^1.4.1",
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/38bed6d7-992b-4206-bc53-4b4222d04d79)

**Comment by qugemingzizhenmafan** [comment]
这样子也可以。我是手动复制.npmrc文件过去再重新安装依赖解决的。根本原因还是.npmrc文件没跟你们官方github保持一致, .npmrc文件是确实有必要在放入gitignore里吗? 我看一些开源项目gitignore里不写.npmrc文件。
如果只是在package.json里加个依赖, 后续可能也会有其他人或者其他功能模块出现类似的问题。
