### ISSUE TITLE
online表单控件的替换

### ISSUE THREAD

**Issue by hellpheonix** [jeecgboot/jeecgboot-vue3#1098]
##### 版本号：
3.5.0

##### 问题描述：
online表单默认的人员选择器不支持使用部门进行筛选，我自己写了一个，请问是否可以把online表单原始的的人员选择器替换成我自己写的？

##### 截图&代码：

![Snipaste_2024-03-08_09-37-24](https://github.com/jeecgboot/jeecgboot-vue3/assets/35069898/f565a294-944c-4206-a96a-883450f80896)
![Snipaste_2024-03-08_09-38-35](https://github.com/jeecgboot/jeecgboot-vue3/assets/35069898/01760728-2ceb-497c-b02d-dcdad110e793)
![Snipaste_2024-03-08_09-39-53](https://github.com/jeecgboot/jeecgboot-vue3/assets/35069898/2b34469f-29d9-4993-a22e-5f3f5069139b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
