### ISSUE TITLE
SpringBoot3 数据库导入表单 加载不出来列表

### ISSUE THREAD

**Issue by chiquanqing-214** [jeecgboot/jeecgboot-vue3#1099]
##### 问题描述：
从 数据库导入表单 加载不出来列表，SpringBoot2 的版本是正常的。
看接口报错404

##### 截图&代码：
http://localhost:3100/jeecgboot/online/cgform/head/queryTables/?_t=1709863290078
404 Not Found
```json
{
    "timestamp": "2024-03-08 10:01:30",
    "status": 404,
    "error": "Not Found",
    "message": "Not Found",
    "path": "/jeecg-boot/online/cgform/head/queryTables/"
}
```
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/51355278/5bdaa0cb-107f-47b2-8ad5-ed1fd261e76e)

**Comment by zhangdaiscott** [comment]
后台依赖没下载成功？
