### ISSUE TITLE
列表列展示问题

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecgboot-vue3#110]
##### 版本号：
1.3.0

##### 问题描述：
如图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55084864/176083986-bbf10146-267e-4bbc-97d1-dbfce21de2f5.png)
![image](https://user-images.githubusercontent.com/55084864/176084073-8f6409e2-438a-4369-a5b0-7c4583c72b85.png)
![image](https://user-images.githubusercontent.com/55084864/176084151-275b52eb-c566-4c75-8baf-c5f61edc9819.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by GitACDreamer** [comment]
更新后，我也出现这样的问题

**Comment by GitACDreamer** [comment]
在原监听函数添加个setTimeout定时器延时获取数据即可
`
watchEffect(() => {
        setTimeout(() => {
          const columns = table.getColumns();
          if (columns.length && !state.isInit) {
            init();
          }
        }, 0);
      });
`

**Comment by zhangdaiscott** [comment]
下个版本修复
