### ISSUE TITLE
JPopup的错误修改？！onChange事件又不能触发了？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecgboot-vue3#1100]
##### 版本号：
v3.5.1
v3.6.2

##### 问题描述：
原本希望实现JPopup在回填数据时，能够触发onChange事件。在issues/5213的修改中，可以实现这个操作，但却不能回填自身，产生了issues/5288的错误，后又进行了修改，用popUpChange取代了change，这回可以回填自身数据，但却不能触发onChange事件了！等于又改回原来的问题了。

请问要怎么处理？

##### 截图&代码：
![微信截图_20240308220858](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/16fcb243-0300-46e9-a15b-aa2592d13b5b)
![微信截图_20240308220935](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/b6d3965f-fe66-44e3-85ee-592070c0e48d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ciahua** [comment]
没有刷新缓存。

**Comment by yang-xianzhu** [comment]
> ##### 版本号：
> v3.5.1 v3.6.2
> 
> ##### 问题描述：
> 原本希望实现JPopup在回填数据时，能够触发onChange事件。在issues/5213的修改中，可以实现这个操作，但却不能回填自身，产生了issues/5288的错误，后又进行了修改，用popUpChange取代了change，这回可以回填自身数据，但却不能触发onChange事件了！等于又改回原来的问题了。
> 
> 请问要怎么处理？
> 
> ##### 截图&代码：
> ![微信截图_20240308220858](https://private-user-images.githubusercontent.com/37827583/311261341-16fcb243-0300-46e9-a15b-aa2592d13b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTExMTcsIm5iZiI6MTcxMTg1MDgxNywicGF0aCI6Ii8zNzgyNzU4My8zMTEyNjEzNDEtMTZmY2IyNDMtMDMwMC00NmU5LWExNWItYWEyNTkyZDEzYjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAyMDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZmJkODcwMTE2OGNhNzQ5ODYwZDdmNTRiMTRjZWJkYzg3NTNjNGU3OGIyYmNkODg2YjE5ZjA4MGMyYmJiMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzSNss5co3YWzvJCL9zHuauk_EMssy11b9Aw_YJ7ufU) ![微信截图_20240308220935](https://private-user-images.githubusercontent.com/37827583/311261354-b6d3965f-fe66-44e3-85ee-592070c0e48d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTExMTcsIm5iZiI6MTcxMTg1MDgxNywicGF0aCI6Ii8zNzgyNzU4My8zMTEyNjEzNTQtYjZkMzk2NWYtZmU2Ni00NGUzLTg1ZWUtNTkyMDcwYzBlNDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAyMDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YjNjNGE5YzMwMWQ3ZjcyMGQ1ZmVhYTcxYWZjZmY4YTk2ZTA5OWQ1ODFiNDA4MWIwZWU2ZDdjY2M3ODg1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkKe_AMfgQUSC25oi4vt8ZiPVf21lwl-6d7xImMMXJA)
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；

你好，请问怎么解决的
