### ISSUE TITLE
字典下拉异步出错

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/jeecgboot-vue3#1108]
##### 版本号：
3.6.3

##### 问题描述：
使用字典selectDictSearch ，会出现sql异常抛出，应该是条件里面and加在前面了。官网也是一样出错。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/82691864/5303ff27-8a60-4bab-99ec-563299f03804)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
cr

**Comment by afearboy** [comment]
新版一直没有处理这个问题，好像。应该是后台问题吧，把and放到外面去了，循环体外。

**Comment by zhangdaiscott** [comment]
用的那个控件，怎么配置截图看下

**Comment by afearboy** [comment]
当你输入测试的时候就会出错，代码如下：
const columns = ref<JVxeColumn[]>([
    {
      title: '下拉框_字典表搜索',
      key: 'select_dict_search',
      type: JVxeTypes.selectDictSearch,
      width: 200,
      async: true, // 异步搜索，默认为 true
      // 字典表配置信息：数据库表名,显示字段名,存储字段名
      dict: 'sys_user,realname,username',
      tipsContent: '请输入查询条件',
    },
截图如下：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/82691864/c874ef2d-0b31-4495-bd4a-9c49a4f24954)

**Comment by afearboy** [comment]
官网如此也会错。我以为我写错了的。旧版本不会有这个问题。
