### ISSUE TITLE
主附表启用联合查询后导入有问题

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecgboot-vue3#111]
##### 版本号：
1.3.0

##### 问题描述：
如图，用到处的文件填入内容再导入，附表内容是空的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55084864/176085348-10070bae-6ddf-42e5-bbd3-d435bc0bee31.png)
![1656387018881](https://user-images.githubusercontent.com/55084864/176085962-a93fc64b-078d-4333-92fb-a8d41aeae98b.jpg)
![image](https://user-images.githubusercontent.com/55084864/176086021-947d5833-2591-456b-8b92-794b6447e51f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by tygithub1** [comment]
接口已修改成旧的
