### ISSUE TITLE
生成原生treetable 样式错误，同样代码3.5.3显示正常

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/jeecgboot-vue3#1110]
##### 版本号：
3.6.3

##### 问题描述：
生成原生treetable 样式错误，同样代码3.5.3显示正常

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by cdbmfrcjj** [comment]
![1710144754562](https://github.com/jeecgboot/jeecgboot-vue3/assets/71683167/52804c11-6ffb-44c7-9f2e-0a73256d7fb5)

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
在新版本中需要增加一个`isTreeTable`属性，不知道你是不是原来生成的，最新版的代码生成器原生树已经加上了
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/7134010d-68db-49eb-ad20-e77f849f6795)
加上`isTreeTable`属性效果图展示
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/6f5e821e-e54a-4512-a37b-3badc70f74e3)

**Comment by cdbmfrcjj** [comment]
> 在新版本中需要增加一个`isTreeTable`属性，不知道你是不是原来生成的，最新版的代码生成器原生树已经加上了 ![image](https://private-user-images.githubusercontent.com/30997828/312282934-7134010d-68db-49eb-ad20-e77f849f6795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTcxOTUsIm5iZiI6MTcxMDI5Njg5NSwicGF0aCI6Ii8zMDk5NzgyOC8zMTIyODI5MzQtNzEzNDAxMGQtNjhkYi00OWViLWFkMjAtZTc3Zjg0OWY2Nzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YjE4MDBkZGFhMTE2ZDk0YTI4OGJkMWE2Y2UwMTlhNGQxYjZlZjk0YzRkNDM2MzllZDMyNGU2NmNkZjFjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixPyab7YyA3FQtNChZmh7fWx1RgA_2hm9KsC6ij6K10) 加上`isTreeTable`属性效果图展示 ![image](https://private-user-images.githubusercontent.com/30997828/312283508-6f5e821e-e54a-4512-a37b-3badc70f74e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTcxOTUsIm5iZiI6MTcxMDI5Njg5NSwicGF0aCI6Ii8zMDk5NzgyOC8zMTIyODM1MDgtNmY1ZTgyMWUtZTU0YS00NTEyLWEzN2ItM2JhZGM3MGY3NGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMTI5MTMwYzg1OTQzMDNmYTdmNTgwOTAyMmM5YjY0ZTAwZjcwNWU0NWFiYjkyOGY4MjAzOGQyYTgyYjEyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oSuKsahIikv91g7mQmmjh_iiTi9B4nw-mTqztrwfRBs)

这个是我从官网演示环境生成的代码，里面没有isTreeTable这个属性
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/71683167/0f60ae91-7c7f-42f2-a1b6-3ae9ea03d551)
