### ISSUE TITLE
BasicTable组件底部合计行，没有随着表格滚动

### ISSUE THREAD

**Issue by liufang1720** [jeecgboot/jeecgboot-vue3#1118]
##### 版本号：
3.5.4

##### 问题描述：
BasicTable组件 合计行与表格各有一个横向滚动条，将合计行的滚动条通过样式隐藏后，滑动表格的滚动条，合计行没有随着表格滚动
（3.6.3版本也有同样的问题）

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/62051116/06c08863-050f-4681-9e2f-a791fffdc742)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/62051116/ca6c14be-8049-44ec-8e12-2158395283f9)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/62051116/d8d00a9b-0925-4dee-b2a8-62914f51872b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yonisg** [comment]
解决方法：对useTableFooter.ts中的handleSummary函数进行修改。

**Comment by yonisg** [comment]
临时处理方法：修改useTableFooter文件handleSummary函数。滚动条出现在.ant-table-body元素上。
tableEl.$el.querySelector('.ant-table-content');修改为tableEl.$el.querySelectorAll('.ant-table-body')[0];
tableEl.$el.querySelector('.ant-table-footer .ant-table-content')修改为tableEl.$el.querySelector('.ant-table-footer .ant-table-body')
nextTick中因为异步无法获取到ant-table-body需要加装延时器。
完整代码：
![Snipaste_2024-03-13_15-51-34](https://github.com/jeecgboot/jeecgboot-vue3/assets/41579027/f1bb4f8e-c3c6-401a-8530-edb024b2bdda)

**Comment by benben120** [comment]
3.6.3 basicTable 行选择依旧会有 卡顿现象 你们遇到了吗

**Comment by benben120** [comment]
设置了默认表格高度 类名是ant-table-body, 没有设置的话是ant-table-content

**Comment by yonisg** [comment]
> 3.6.3 basicTable 行选择依旧会有 卡顿现象 你们遇到了吗

这个暂时没有遇到

**Comment by benben120** [comment]
本地调试不会 发布到测试环境dev就会出现

**Comment by zhangdaiscott** [comment]
修复了，升级到最新版
