### ISSUE TITLE
Vue3 在线开发的功能刷新当前页后表头排列会错乱

### ISSUE THREAD

**Issue by 280377485** [jeecgboot/jeecgboot-vue3#112]
##### 问题描述：
v1.3.0平台代码发布到服务器（非开发电脑）上后，打开一个开发好的在线开发的功能，然后直接刷新网页，表头的按钮排列会错乱。换成docker也是这种异常情况，只有本地开发环境正常。

异常情况的flex未作用，正常情况flex生效。

##### 截图&代码：
![79933be2370beaa08664af5ee04c418](https://user-images.githubusercontent.com/55683514/176836078-93cd4a45-9259-42b2-a713-9ff2a2612642.png)
![0a2199a1d8e755d708163ff01948c62](https://user-images.githubusercontent.com/55683514/176836318-175ab196-a956-4033-a8db-18aca83ccaf3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
修改下index.html 引入下
`<link rel=stylesheet href=/assets/BasicTable.7430a7b9.css>`
