### ISSUE TITLE
登录成功点击左侧菜单所有页面显示空白并报错

### ISSUE THREAD

**Issue by cui5782052** [jeecgboot/jeecgboot-vue3#1123]
##### 版本号：
3.6.3

##### 问题描述：
启动项目登录进去后，点击菜单报错，画面空白
SyntaxError: The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=75c52355' does not provide an export named 'default'

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/62142959/68a3300e-72a0-4a7a-8aa2-2c79bb1c0b41)

**Comment by zhangdaiscott** [comment]
清下vite缓存

**Comment by tengmankai** [comment]
**版本号：**
3.6.3

**nodejs版本:**
18.19.0

**npm版本:**
10.2.3

**pnpm版本:**
7.30.0

相同版本，同样的报错，清除缓存，删掉node_modules重装仍然报错

**报错截图：**
![报错截图](https://github.com/jeecgboot/jeecgboot-vue3/assets/19246732/f79d4a31-15c8-48c8-86c3-3922a058005f)

**Comment by STAR5201** [comment]
我也是这个问题不知道咋解决
