### ISSUE TITLE
3.6.3版本 basicDrawer isDetail详情模式下 没有默认定位到指定元素 而是全屏显示了

### ISSUE THREAD

**Issue by benben120** [jeecgboot/jeecgboot-vue3#1126]
##### 版本号：
3.6.3

##### 问题描述：
3.6.3版本 basicDrawer isDetail详情模式下 没有默认定位到指定元素 而是全屏显示了

##### 截图&代码：

![img_v3_0290_e1808077-2010-4637-9252-09ddf9a90fbg](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/99b8859d-d065-4218-aa68-cbaf47ff2c48)
![img_v3_0290_801c7c32-00ce-4f7a-b451-c472ec3f795g](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/681e15ec-7065-42ea-ac7d-a25babdf9d29)
![img_v3_0290_c81f5f8d-7938-45ee-b451-e101f4aeb42g](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/cfcab638-23c4-408f-98c4-5cfc93bacb08)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
isDetailshe设置为true，没给宽度就是全屏展示，设计如此。默认没有挂在在body上，如果你想更改可以通过getContainer挂载到相应的元素上。

**Comment by benben120** [comment]
> isDetailshe设置为true，没给宽度就是全屏展示，设计如此。默认没有挂在在body上，如果你想更改可以通过getContainer挂载到相应的元素上。

截图代码里不是已经设置了opt.getContainer了吗 就是设置了也没有挂载到响应元素上 3.6.3之前的版本都可以呀

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/595dedf7-aaef-452e-a462-5ff9f5430633)
经测试，getContainer是生效的哈，上图就指定挂载到了app元素下。能看下你的业务代码？你上面截图是底层代码。
