### ISSUE TITLE
打包后报错 Reflect.has called on non-object

### ISSUE THREAD

**Issue by JontyMin** [jeecgboot/jeecgboot-vue3#113]
##### 问题描述：
`yarn build`之后执行预览`yarn preview`运行报错：`TypeError: Reflect.has called on non-object`
debug不出来，有什么解决办法吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/51729732/177491554-7053f908-500e-48df-86be-93bae8a0831e.png)

![image](https://user-images.githubusercontent.com/51729732/177491596-d04a3f2a-540d-494a-a0bf-0bf6e370da29.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by JontyMin** [comment]
@zhangdaiscott 已经解决了嘛？麻烦告知下。

**Comment by wanggh1021** [comment]
@zhangdaiscott @JontyMin  同问，怎么解决的？

**Comment by JontyMin** [comment]
> @zhangdaiscott @JontyMin 同问，怎么解决的？
没有回复，issus关闭了

**Comment by huachen1988** [comment]
@zhangdaiscott  这个在本地是好的！打包发服务器上就不行了

**Comment by JontyMin** [comment]
目前来看 yarn 以及 yarn start是可以的
yarn build 并yarn preview:dist会报错

**Comment by bigbiglv** [comment]
预览的话我在.env.production把VITE_PROXY粘过来就正常请求了，部署服务器应该是nginx转发
