### ISSUE TITLE
表格选择100条/页,往下拉的时候会非常卡,上面一些数据还有复选框,往下划一会复选框就没了.

### ISSUE THREAD

**Issue by yidao2000** [jeecgboot/jeecgboot-vue3#1131]
##### 截图&代码：
![报错1](https://github.com/jeecgboot/jeecgboot-vue3/assets/12994137/d2aa9470-4374-4f6b-8fa5-840d43657907)

![报错2](https://github.com/jeecgboot/jeecgboot-vue3/assets/12994137/c01d1342-1062-4dbe-b6ce-3c1c7a4efd5a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么情况下？

**Comment by yidao2000** [comment]
我又试验了几个菜单,
有的菜单里面的表格显示100条/页的时候,往下拉就没事,
有的菜单下面表格里显示100条/页往下拉一会,后面的复选框就必没,
我暂时没看出来是什么条件下能必出,
我知道需要能复现才能定位bug,
我再看看吧
