### ISSUE TITLE
cas开启后无法加载路由

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/jeecgboot-vue3#1132]
##### 版本号：
3.6.3

##### 问题描述：
cas开启后无法加载路由，初步探查发现可能是下面代码顺序的问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/71683167/9f5bc43f-fbab-4eb2-8dfd-26187ba244b1)
sso开启后并未加载路由守卫

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/71683167/28dc8a89-ff41-4ebd-8bc8-7721f9cee506)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是怎么用的？

**Comment by yang-xianzhu** [comment]
> 你是怎么用的？

你好，想请教一个问题，SSO情况下，统一登录中心跟子应用不是同一工程，在登录统一登录中心后，进入子系统，然后在统一登录中心退出登录，这时子应用的token等信息是还没清空的，再次在统一登录中心去进入该子系统，会存在旧的登录数据，导致登录异常，请问有一些解决方案可以参考吗？感谢！！

**Comment by zhangdaiscott** [comment]
ws

**Comment by 2878547611yll** [comment]
开启单点登录后，首次进入页面404路由不加载，
![65e109e8d2f0331f463c33b600d425d1](https://github.com/jeecgboot/jeecgboot-vue3/assets/110088902/350a9162-aac2-4a62-b1eb-65d9c0893f39)

router.beforeEach不执行,二次刷新正常；在afterLoginAction开启这块代码路由借口加载了，页面进入正常，但是

**Comment by 2878547611yll** [comment]
开启单点登录后，首次进入页面404路由不加载，
65e109e8d2f0331f463c33b600d425d1

router.beforeEach不执行,二次刷新正常；在afterLoginAction开启这块代码路由接口加载了，
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/110088902/cd270f5c-1b0d-403b-863d-e8c510e2420b)
页面进入正常，但是菜单高亮样式缺失，二次刷新却正常...
怎么解决求大佬指点
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/110088902/7a3fcbac-92a8-42e0-b4b4-14b49a8d4cb0)

**Comment by 2878547611yll** [comment]
开启单点登录后，首次进入页面404路由不加载，
![65e109e8d2f0331f463c33b600d425d1](https://github.com/jeecgboot/jeecgboot-vue3/assets/110088902/b2ae8f43-1766-4498-85d1-962f59890c32)
router.beforeEach不执行,二次刷新正常；在afterLoginAction开启这块代码路由接口加载了，
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/110088902/dce167e5-fdd3-4b6f-a9d6-adcaa38d42d0)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/110088902/437ecec5-e4d0-418a-9c92-e046bc12cad4)

页面进入正常，但是菜单高亮样式缺失，二次刷新却正常...
怎么解决求大佬指点

**Comment by 2878547611yll** [comment]
> ##### 版本号：
> 3.6.3
> 
> ##### 问题描述：
> cas开启后无法加载路由，初步探查发现可能是下面代码顺序的问题 ![image](https://private-user-images.githubusercontent.com/71683167/314365610-9f5bc43f-fbab-4eb2-8dfd-26187ba244b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzA3NDEsIm5iZiI6MTcxMzc3MDQ0MSwicGF0aCI6Ii83MTY4MzE2Ny8zMTQzNjU2MTAtOWY1YmM0M2YtZmJhYi00ZWIyLThkZmQtMjYxODdiYTI0NGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3MjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODhkMWI3OWE0NDY1MDRjYTlmM2QzOWFkNTU4MTY2NTAyMmFmODU2YmU0NWJiMzk4ZDIyOWZiNGZjNzZhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJaqeuv7xq6qm3fDjDkwsqeA4gYgGPmf8blrZNiyvbQ) sso开启后并未加载路由守卫
> 
> ##### 截图&代码：
> ![image](https://private-user-images.githubusercontent.com/71683167/314365531-28dc8a89-ff41-4ebd-8bc8-7721f9cee506.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzA3NDEsIm5iZiI6MTcxMzc3MDQ0MSwicGF0aCI6Ii83MTY4MzE2Ny8zMTQzNjU1MzEtMjhkYzhhODktZmY0MS00ZWJkLThiYzgtNzcyMWY5Y2VlNTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3MjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYjVhZDhiMmQwOTE4Njc4OGNhZTY1MTQ0MTkyYmU4NzI2YThhMzcyZGM5NjZiMzE1MjU5NWE1Nzc3N2MxODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.94XuDPA1fhYclJ-kkgap0FcVxeLp7fIxHwynIm1PLyE)
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；

你好，问下你解决了吗

**Comment by zhangdaiscott** [comment]
提交了，你更新代码试试
