### ISSUE TITLE
系统管理的菜单管理表格性能问题

### ISSUE THREAD

**Issue by yang-xianzhu** [jeecgboot/jeecgboot-vue3#1133]
##### 版本号：
3.6.1

##### 问题描述：
系统管理的菜单管理里面的 展开全部、折叠全部会有些卡顿，有什么方案可以解决吗？谢谢！！

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/92789120/f143ad86-094c-426c-8b8b-5c795f7b5bb0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
这是因为表格插槽中的 TableAction 组件每一行都会执行，通过使用场景和使用次数综合考虑，暂不更改。如果你项目使用的地方较多确实需要更改，可以做一个假的，等用户鼠标划上去了再加载此组件。

**Comment by yang-xianzhu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/92789120/314472253-e9e552ab-2e78-4697-830f-8771eeac627a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDgyNzcsIm5iZiI6MTcxMTYwNzk3NywicGF0aCI6Ii85Mjc4OTEyMC8zMTQ0NzIyNTMtZTllNTUyYWItMmU3OC00Njk3LTgzMGYtODc3MWVlYWM2MjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OGZkYTNkNGQwMGNkMmY0MTBmMmEyMDRkMjRjMDEzMzU5MWY0YjU3MTIzNWYwZGZjNmJkMThiOGVkNjg3MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJvydeN4yWTyip-fEm1VlZYqux5iLTXPIKLTiD9NjV8)建议expandAll和collapseAll改成promise，暴露一个回调参数出来。
> > 实际效果如下： ![image](https://private-user-images.githubusercontent.com/92789120/314471190-3e36a85a-1d55-4ff0-9162-1bf3f960e2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDgyNzcsIm5iZiI6MTcxMTYwNzk3NywicGF0aCI6Ii85Mjc4OTEyMC8zMTQ0NzExOTAtM2UzNmE4NWEtMWQ1NS00ZmYwLTkxNjItMWJmM2Y5NjBlMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMDA5N2RhMzRhM2M3NDFhMWUxYTcxZDcyOTRiOGE5ZDQzY2Y2NTIyMGM1MWFmMjdlYzc2YTBhMjBjODg5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJiaD6x0ELl5pX_VwZaCCGiMTSmH8vTQ5xqsN62wQ6U)
> 
> resolve(), 你这是外面调想获取到什么？所有的key吗？

你好，不用获取任何参数，只是需要一个完全展开后的时机而已
