### ISSUE TITLE
BasicForm表单，多选值是否可以不要用逗号拼接

### ISSUE THREAD

**Issue by 1161325721** [jeecgboot/jeecgboot-vue3#1138]
##### 问题描述：
在BasicForm表单中，通过useForm()的getFieldsValue()方法，在获取数组类型的值时，会自动转成用逗号拼接的字符串。由于后端是使用数组接收的，这导致每次都要手动转回数组。能否加个字段，可以自由选择返回原数组值或用逗号拼接

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/61100025/c3a9d2ae-35c5-4f00-8c19-15f3660a10b3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yang-xianzhu** [comment]
在onChange事件重写这个字段的值应该是可以的，可以试试。

**Comment by zhangdaiscott** [comment]
ws

**Comment by havenothingtosay** [comment]
> 当前valueType 为String类型的时候才会拼接字符串（默认为`String`），当 valueType 为其他类型如`Array`是不会拼接字符串，你可以设置一下`valueType`属性
> 
> valueType 为 `array` 请求截图 ![image](https://private-user-images.githubusercontent.com/30997828/324401770-1df6add6-0e0e-41c3-a481-5d1a979aae1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzM1MTYsIm5iZiI6MTcxODg3MzIxNiwicGF0aCI6Ii8zMDk5NzgyOC8zMjQ0MDE3NzAtMWRmNmFkZDYtMGUwZS00MWMzLWE0ODEtNWQxYTk3OWFhZTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA4NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZGMxMzlkY2Y2YzYwOTUyMjc1MzI4ZTU5Y2I0YWRkMGRiZWQ1NmQ0MjVkMWM2MjEzZWMxNmRmOWY1N2QzMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmBqKwVjx0HzxyfjbxVaWaAFZHmSr880oSs46IQ8PS8) 设置valueType ![image](https://private-user-images.githubusercontent.com/30997828/324401824-ef68e369-396f-49ef-94ec-c43f42833855.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzM1MTYsIm5iZiI6MTcxODg3MzIxNiwicGF0aCI6Ii8zMDk5NzgyOC8zMjQ0MDE4MjQtZWY2OGUzNjktMzk2Zi00OWVmLTk0ZWMtYzQzZjQyODMzODU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA4NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMGE2ZjhmMTBhMjRjYjdjNDlmMDQ4OTU4OGI2MzA2ZTcxYjUyYWUxZWFjNDUyZjMyZDRlMzllOTcwM2QxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L0t0uwR402Cp7BgNaIX2xBR4MCQLDtE5IenI_m27Iok) 代码拼接逗号的位置 ![image](https://private-user-images.githubusercontent.com/30997828/324402182-ed58cea6-c39c-46c7-af7a-35dcfd25e1b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzM1MTYsIm5iZiI6MTcxODg3MzIxNiwicGF0aCI6Ii8zMDk5NzgyOC8zMjQ0MDIxODItZWQ1OGNlYTYtYzM5Yy00NmM3LWFmN2EtMzVkY2ZkMjVlMWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA4NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMGNkOGIzNGQxOThhYzg1OTc4Y2JjMjA5MjZiNDQzYTBjOWMzMGUwNDM5ZDA2OGVmZjU1OTVjM2E1Zjc2YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e89dWR3KTHhMs80DVrZcv3xMmQQUtJ6iadM9fjMO1Go)

请问你的版本号是多少？我的3.6.2，通过validate方法获取到的是数组类型，但是通过getFieldsValue获取到的还是字符串
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/19619291/fcd95fe2-5e97-4e15-9ebf-96128d0987c3)
