### ISSUE TITLE
目前我们前后端的版本都是3.4.4，请问只升级前端到3.6.3，后端不升级版本，是否会有什么影响或是错误？？

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecgboot-vue3#1139]
##### 问题描述：

问题1： 目前我们前后端的版本都是3.4.4，请问只升级前端到3.6.3，后端不升级版本，是否会有什么影响或是错误？？

问题2：目前3.4.4中菜单管理中添加菜单，路径不能重复，现在有需求，需要菜单名字不同但是组件和路径相同，给不同的人分配不同的菜单，请问如果路径重复，对菜单和路由有什么影响吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不兼容，需要同步升级
