### ISSUE TITLE
online表单开发多表关联应该如何操作

### ISSUE THREAD

**Issue by keweihero** [jeecgboot/jeecgboot-vue3#114]
##### 版本号：
版本号：v1.3.0

##### 问题描述：
表①表②是一对多关系，表②表③是一对多关系，但是不知道应该怎么把表②表③关联起来

##### 截图&代码：
![image](https://user-images.githubusercontent.com/39587185/177520294-61a6da15-6d61-4154-bdc7-354a33ac4363.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以通过下拉多选实现
