### ISSUE TITLE
登录重定向问题

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/jeecgboot-vue3#1147]
##### 问题描述：我之前已经提过很多次了 问题一直没有修复好
具体问题看截图吧

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/128006839/610b3f58-ad70-4b60-8578-eb8766463cef)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你实际需求是什么

**Comment by cym1231** [comment]
> 你实际需求是什么

当然是大佬们 下次发布新版本的时候吧这个问题修复了呗，不然每次都要手动改一次

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。

你本地可按如下进行修改：
src/store/modules/user.ts 文件：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/bea26c02-1614-4792-baef-37cedad0d8d0)


```
if (redirect && goHome) {
        //update-end---author:wangshuai ---date:20230424  for：【QQYUN-5195】登录之后直接刷新页面导致没有进入创建组织页面------------
          // update-begin--author:liaozhiyang---date:20240104---for：【QQYUN-7804】部署生产环境，登录跳转404问题
          let publicPath = import.meta.env.VITE_PUBLIC_PATH;
          if (publicPath && publicPath != '/') {
            // update-begin--author:liaozhiyang---date:20240506---for：【issues/1147】登录跳转时去掉发布路径的最后一个/以解决404问题
            if (publicPath.endsWith('/')) {
              publicPath = publicPath.slice(0, -1)
            }
            redirect = publicPath + redirect;
          }
          // update-end--author:liaozhiyang---date:20240506---for：【issues/1147】登录跳转时去掉发布路径的最后一个/以解决404问题
          // 当前页面打开
          window.open(redirect, '_self')
          return data;
        }

```

**Comment by cym1231** [comment]
> 已解决，下一版本发布。
> 
> 你本地可按如下进行修改： src/store/modules/user.ts 文件： ![image](https://private-user-images.githubusercontent.com/8199499/328076747-bea26c02-1614-4792-baef-37cedad0d8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjY4NjYsIm5iZiI6MTcxNjM2NjU2NiwicGF0aCI6Ii84MTk5NDk5LzMyODA3Njc0Ny1iZWEyNmMwMi0xNjE0LTQ3OTItYmFlZi0zN2NlZGFkMGQ4ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDgyOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMyZWE5YTYzN2EwYTYwYzA2Y2UzOTAwNzVlOWNhMWRkNmNkNWE5Yzk1Nzc5YTZmYjc1Zjc3YjczNzcyNDIwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b_a1SB9gDbJAjm3dOuZ9Ccp4J5rJZoXfF_pNVVw-UZg)
> 
> ```
> if (redirect && goHome) {
>         //update-end---author:wangshuai ---date:20230424  for：【QQYUN-5195】登录之后直接刷新页面导致没有进入创建组织页面------------
>           // update-begin--author:liaozhiyang---date:20240104---for：【QQYUN-7804】部署生产环境，登录跳转404问题
>           let publicPath = import.meta.env.VITE_PUBLIC_PATH;
>           if (publicPath && publicPath != '/') {
>             // update-begin--author:liaozhiyang---date:20240506---for：【issues/1147】登录跳转时去掉发布路径的最后一个/以解决404问题
>             if (publicPath.endsWith('/')) {
>               publicPath = publicPath.slice(0, -1)
>             }
>             redirect = publicPath + redirect;
>           }
>           // update-end--author:liaozhiyang---date:20240506---for：【issues/1147】登录跳转时去掉发布路径的最后一个/以解决404问题
>           // 当前页面打开
>           window.open(redirect, '_self')
>           return data;
>         }
> ```

好的 辛苦佬  希望框架能越来越好
