### ISSUE TITLE
qiankun 子应用组件未加载

### ISSUE THREAD

**Issue by liran-21** [jeecgboot/jeecgboot-vue3#115]
##### 版本号：
主应用jeecgboot-vue3  
"version": "1.0.0"
"qiankun": "^2.7.3"

子应用jeecgboot-vue3 
 "version": "1.0.0"
 "vite-plugin-qiankun":"1.0.14"

##### 问题描述：
 子应用加载后一直显示图片内loading样式，地址栏路由已更新，但是路由对应组件未加载。

##### 截图&代码：
<img width="960" alt="企业微信截图_16571856736311" src="https://user-images.githubusercontent.com/34502036/177740742-2b743176-8fb8-4d27-9453-63b6ae64be83.png">
<img width="541" alt="企业微信截图_16571863919464" src="https://user-images.githubusercontent.com/34502036/177742163-73b1524b-fe36-444d-9489-9156c415dec8.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by qinghechaoge** [comment]
同样的问题 vite 不支持 乾坤导致的
