### ISSUE TITLE
online表单开发页面打开报错 The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=53eb7e43' does not provide an export named 'default'

### ISSUE THREAD

**Issue by STAR5201** [jeecgboot/jeecgboot-vue3#1155]
##### 版本号：
jeecgbootVue3 3.6.3
node v18.1.0
npm 8.8.0
8.15.5
##### 问题描述：
1项目运行报错找不到src\common\mixin\Mixin.js
2路由打开在线开发报错
无法打开在线开发页面,点击菜单跳转,控制台报错
The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=53eb7e43' does not provide an export named 'default'
##### 截图&代码：
![QQ截图20240330194014](https://github.com/jeecgboot/jeecgboot-vue3/assets/53025758/dd121d50-b1c3-443a-9bb5-2a709aee4e89)
![QQ截图20240330194112](https://github.com/jeecgboot/jeecgboot-vue3/assets/53025758/65ece726-04c9-45ee-a72e-142dfbae9961)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
清下vite缓存看看

**Comment by STAR5201** [comment]
> 清下vite缓存看看

尝试清除npm&vite缓存并重新下载依赖无效,还是会报错打不开

**Comment by cyberfeipunk** [comment]
同样的问题，刚2.6.1升级过来有这个问题，新部署的没问题

**Comment by zhangdaiscott** [comment]
那就是升级的有问题

**Comment by zhangdaiscott** [comment]
node过高？

**Comment by gaojoe19** [comment]
我也遇到了同样的问题，把3.6.3的所有依赖的版本号保持一致后，删除node_modules重新pnpm install 恢复正常，应该是@jeecg/online下某个依赖的版本和项目现有版本有冲突，具体的没细究

**Comment by zhangdaiscott** [comment]
使用pnpm i

**Comment by EvanYou** [comment]
我也遇到类似的问题，之前是能正常打开的，突然就不能打开了，尝试清除缓存，重新下载依赖后仍然无法解决
