### ISSUE TITLE
JS 表单增强更改子表下拉options API出错，报 Uncaught (in promise) TypeError: this.changeSubTableOptions is not a function

### ISSUE THREAD

**Issue by libaoo** [jeecgboot/jeecgboot-vue3#1159]
##### 版本号：
3.6.3

##### 问题描述：
JS 表单增强 设置字表的下拉选项，按API进行设置，报API函数  this.changeSubTableOptions is not a function

##### 截图&代码：

loaded(){
 this.changeSubTableOptions('processroute','ci_solution',[{label:'上海静安',value:'100'}]);
}

VM1815:4 Uncaught (in promise) TypeError: this.changeSubTableOptions is not a function
    at Proxy.loaded (eval at _eval (index.ts:371:9), <anonymous>:4:10)
    at Z (OnlineForm-1fa2d893.mjs?v=02531280:424:26)
    at OnlineForm-1fa2d893.mjs?v=02531280:161:34

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前最新版还不支持这个api
