### ISSUE TITLE
vue3-1.0.0怎么升级到最新的vue3-1.3.0？

### ISSUE THREAD

**Issue by Xiaotian0617** [jeecgboot/jeecgboot-vue3#116]
##### 版本号：
vue3 1.0.0 

##### 问题描述：
目前在项目开发中发现有一些常见 bug，根据官方的 更新日志看已经修复，目前前端项目是否可以做到升级版本到最新的 1.3.0 ,具体方法是什么，望大佬告知下~谢谢。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
得自己通过git对比分析
