### ISSUE TITLE
富文本框上传图片频繁出现504 Gateway Time-out  该如何优化

### ISSUE THREAD

**Issue by yueguojian** [jeecgboot/jeecgboot-vue3#1160]
##### 版本号：
<jeecgboot.version>3.0

##### 问题描述：
富文本框上传图片频繁出现504 Gateway Time-out  该如何优化。有没有替换的富文本框组件。

##### 截图&代码：

用了是jeecg-boot自带的富文本框组件
<j-editor v-model="model.content" />

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
错误贴图
