### ISSUE TITLE
JVxeTable列过长（出现横向滚动条）时无法拖拽排序

### ISSUE THREAD

**Issue by RamboWu** [jeecgboot/jeecgboot-vue3#1162]
##### 版本号：

3.5.3
##### 问题描述：
JVxeTable 中 加入了Dragsort属性后，如果 columns的宽度过长，出现横条滚动条的时候，将无法拖拽，只能进行点击拖拽

##### 截图&代码：

![90293ecaa677a34b50a91fc9f60706e](https://github.com/jeecgboot/jeecgboot-vue3/assets/3425194/7c2dd813-a045-48ed-847c-78cd2a7062ac)
![7c7632e16cc6b7a97a195806e1fbd75](https://github.com/jeecgboot/jeecgboot-vue3/assets/3425194/69f3b290-818a-4bbb-9ac4-9f10db8de7b7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by RamboWu** [comment]
> zy

？？什么意思呀

**Comment by liaozhiyang** [comment]
确实有该问题，是因为columns中的dragSort和rowSelection默认是fixed:left导致。如果要解决该问题则fixed不可设置。

已修复，下一版本发布。
你本地可按如下文件进行修改


src/components/jeecg/JVxeTable/src/vxe.data.ts 文件:
<img width="1258" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/86c20694-264b-4b2e-bd16-490bb0d03f46">

```
  dragSortFixed: propTypes.oneOf(['left', 'none']).def('left'),
  rowSelectionFixed: propTypes.oneOf(['left', 'none']).def('left'),
```

src/components/jeecg/JVxeTable/src/hooks/useColumns.ts 文件中：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/5f0d29fb-e19c-4990-bcba-7a2e9fb7e525)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/bbfba5aa-94ba-4e09-b0d8-b9324b4690f5)

src/views/demo/jeecg/JVxeTableDemo/JVxeDemo3.vue 文件：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/71f9c7be-89db-438f-836a-365facb680d2)
