### ISSUE TITLE
添加外链菜单

### ISSUE THREAD

**Issue by 15698109983** [jeecgboot/jeecgboot-vue3#1163]
##### 截图&代码：
![XEK8IME_JLY$WB5K)8FSOXA](https://github.com/jeecgboot/jeecgboot-vue3/assets/59247799/159a1ff5-32e2-4c31-bed8-d0021bee917c)

![C8V2MT_~URMCL L78SWZO34](https://github.com/jeecgboot/jeecgboot-vue3/assets/59247799/6f744870-1b6a-434f-93cd-2d64ff4db97a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种方式是配置后台请求地址

**Comment by 15698109983** [comment]
那正确的该如何配置
