### ISSUE TITLE
升级到VUE3后online表单设计的报表做功能测试时报错：获取查询条件失败

### ISSUE THREAD

**Issue by 506764932** [jeecgboot/jeecgboot-vue3#117]
##### 问题描述：
升级到VUE3后online表单设计的报表做功能测试时报错：获取查询条件失败

##### 截图&代码：

![image](https://user-images.githubusercontent.com/6880877/177905543-d0124dec-5389-4327-a555-9039bbf622bc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
数据库是老的？

**Comment by 506764932** [comment]
数据库是按照升级过后的，使用的后端分支是v3.2.0的分支

**Comment by 506764932** [comment]
> 数据库是老的？

可能是后端的分支问题，我用的是 后端的 v3.2.0分支。
如果使用 后端的 master 分支 就没问题

**Comment by 280377485** [comment]
你的前端 env.development配置有改jeecgboot吗？我是改了后在线开发才出问题

https://github.com/jeecgboot/jeecgboot-vue3/issues/120#issue-1305571105
