### ISSUE TITLE
所有a-select组件 下拉定位不准问题

### ISSUE THREAD

**Issue by benben120** [jeecgboot/jeecgboot-vue3#1171]
##### 版本号：
3.6.2

##### 问题描述：
诸如api-selet、j-search-select、j-dict-select组件都存在如果select下拉框数据量过多出现滚动条而且屏幕分辨率过低(自己模拟实现可以放大浏览器显示尺寸，大概150%比例下)时，下拉框的定位getPopupContainer会出现定位失效的问题

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/8c3f4df3-7279-4e15-9462-71ef309b48c9)

![b909b92f-d560-4f0d-be3d-8c07bfae4b3b](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/4192576d-d34c-4b4e-a5c9-311d4fe6c725)
![88ddf88e-ff71-40be-85dc-ed01896ed3c8](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/d009a5ba-dff5-4b25-8ade-05442f1316cb)

![43248b25-6b7d-4d1e-96a7-b90e957907f3](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/5dc7d572-a340-47f5-84ef-81b123276b3f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by 1298191366** [comment]
根据 antdv 的官网组件描述，你可以手动调整`getPopupContainer` 指定区域，如 指定为`document.body`指定到body元素里面，getPopupContainer返回的是函数对象
**【代码：】**
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/749a8c07-9456-43dc-884b-2ab529e43c43)
**【效果：】**
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/5f1ec305-0536-45eb-837d-59ab77f87c58)
**【未指定：】**
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/7324dc19-cf1c-4beb-b9dc-1779d3ff44fe)

需要注意的是：当指定到document.body的时候 会发现下拉菜单跟随页面滚动

**Comment by benben120** [comment]
> 根据 Ant Design Vue的官网组件描述，你可以手动调整`getPopupContainer` 指定区域，如 指定为`document.body`指定到body元素里面，getPopupContainer返回的是函数对象 **【代码：】** ![image](https://private-user-images.githubusercontent.com/30997828/323161716-749a8c07-9456-43dc-884b-2ab529e43c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDE3NTcsIm5iZiI6MTcxMzQwMTQ1NywicGF0aCI6Ii8zMDk5NzgyOC8zMjMxNjE3MTYtNzQ5YThjMDctOTQ1Ni00M2RjLTg4NGItMmFiNTI5ZTQzYzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwNTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNjAzMmEzZjI1ZDgxMDFkY2NmMWM1Yzk4YmRmMGJhMjcwOWE4NjVkMWRiZWM1YTdiYzdmMDU3NmViYWYwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o43rTYatum2GqCc2LD_c4noLJRI_Z_osBex0UdRSzyM) **【效果：】** ![image](https://private-user-images.githubusercontent.com/30997828/323161643-5f1ec305-0536-45eb-837d-59ab77f87c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDE3NTcsIm5iZiI6MTcxMzQwMTQ1NywicGF0aCI6Ii8zMDk5NzgyOC8zMjMxNjE2NDMtNWYxZWMzMDUtMDUzNi00NWViLTgzN2QtNTlhYjc3Zjg3YzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwNTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZTc0NGViNTJjMWFhYzg0YTNiZjRkNDYyNzQzOTE0MzAyNThmZDQ3M2M1MDVkNGQ1NzlmMzU1ZTBkNmU3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-lWwAeJ58nPtOystVaX0gdv4MwEn9Bx_XGuZnHNbXps) **【未指定：】** ![image](https://private-user-images.githubusercontent.com/30997828/323161877-7324dc19-cf1c-4beb-b9dc-1779d3ff44fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDE3NTcsIm5iZiI6MTcxMzQwMTQ1NywicGF0aCI6Ii8zMDk5NzgyOC8zMjMxNjE4NzctNzMyNGRjMTktY2YxYy00YmViLWI5ZGMtMTc3OWQzZmY0NGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwNTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OGViNmZkYzU0NjlhZmZlOTIxYWVkODQxY2QyOTc1MjZkMzA5YWZmYjdhNDE1Y2EwNjY2ODc5Yjg3ZTU4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fMgDq5RDB40BnwK2Xqm95WT31YQ_SqA01mfPbszDglw)
> 
> 需要注意的是：当指定到document.body的时候 会发现下拉菜单跟随页面滚动
不是同一个问题 我有设置过getPopupContainer => document.body 在drawer和modal中还是一样定位不准确

**Comment by 1298191366** [comment]
那详细描述你的问题。我测着没问题。或者发个视频
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/45045acc-03be-4376-acf1-cfc7b26fafbf)

**Comment by benben120** [comment]
> 那详细描述你的问题。我测着没问题。或者发个视频 ![image](https://private-user-images.githubusercontent.com/30997828/323434103-45045acc-03be-4376-acf1-cfc7b26fafbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTA2NzcsIm5iZiI6MTcxMzc1MDM3NywicGF0aCI6Ii8zMDk5NzgyOC8zMjM0MzQxMDMtNDUwNDVhY2MtMDNiZS00Mzc2LWFjZjEtY2ZjN2IyNmZhZmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAxNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODg2NTIxZjVlOGUyNjdmOTFiZjFlMGMyZjgyYjAxNjY2ZmFiMGIzMjAyMmE2ZWU4YjM2YzExMGJlMWRkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c5XSE-OPNFu0OZYjq8I8jP7WF30bamUJIaE_heZkoC8)


https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/aa863e50-8344-4b8c-98e9-74b45d2edfa8

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/19bb6198-141d-4722-a0b4-9a8e9f890873)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/34fd1ce1-ea37-4e37-82ee-8d4f92d3be3f)
下拉的定位在可视区域位置足够时是可以支持的 可以查看视频 可视区域位置不足时就定位不准确了 这个可以优化的么？

**Comment by 1298191366** [comment]
因为可是区域不够展示，想要展示全那肯定会错位。您可以尝试设置一下最大高度，让下拉框的区域高度占比少一些

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/9b2fc1d9-7c5c-4c69-bdac-8d0ee1c7ba97)
解决方案：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/a9f27542-404a-43e0-9735-1af45cd195b4)

**Comment by benben120** [comment]
> 因为可视化区域不够展示，想要展示全那肯定会错位。您可以尝试设置一下最大高度，让下拉框的区域高度占比少一些
> 
> ![image](https://private-user-images.githubusercontent.com/30997828/324306825-9b2fc1d9-7c5c-4c69-bdac-8d0ee1c7ba97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjU1NTUsIm5iZiI6MTcxMzc2NTI1NSwicGF0aCI6Ii8zMDk5NzgyOC8zMjQzMDY4MjUtOWIyZmMxZDktN2M1Yy00YzY5LWJkYWMtOGQwZWUxYzdiYTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNjhmZTc5MzY4ZWU2ODBkZWY1OTc3MDYwYWM1YTk0N2NlMTUzNTE0MTdmNmJmOTdlNDdkMzA4Yjg2N2UyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h5S9Ru3HmoAP7mU3QlFisrIMOK88emj3fgYLZm2dqb8) 解决方案： ![image](https://private-user-images.githubusercontent.com/30997828/324306866-a9f27542-404a-43e0-9735-1af45cd195b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjU1NTUsIm5iZiI6MTcxMzc2NTI1NSwicGF0aCI6Ii8zMDk5NzgyOC8zMjQzMDY4NjYtYTlmMjc1NDItNDA0YS00M2UwLTk3MzUtMWFmNDVjZDE5NWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiODcwMDQzMDQ1OTg5ZjcwMWQ5YjAzYTA5ZGI0OWQ2OTdlZjc5ZDRiN2FlZjA4YmNlZTQzMWRkOGY2NmM0YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YT0pK4eXPNxkr1WsW82tR0P-lAay4IFTqAYsZ9lEZWA)

好的 那么在 drawer 或者modal 中使用select 组件 如果存在 屏幕分辨率小的情况 出现这种错位 目前是没解决方案吗

**Comment by 1298191366** [comment]
没有，因为你可视化区域不够，就没办法。你可以根据当前屏幕大小动态更改高度，也是一种解决方案
