### ISSUE TITLE
js增强代码中能获取当前登录信息吗？例如tenantId

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/jeecgboot-vue3#1176]
##### 版本号：
3.6.2

##### 问题描述：
js增强代码中能获取当前登录信息吗？例如tenantId，该字段在后续需要使用！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yang-xianzhu** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/92789120/fdaa56d3-6008-41ce-9332-607cc0b3231d)
有的啊

**Comment by zwjsoft** [comment]
> ![image](https://private-user-images.githubusercontent.com/92789120/320748075-af9283aa-cb25-46aa-a246-9f2202afe4bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDU5OTEsIm5iZiI6MTcxMjY0NTY5MSwicGF0aCI6Ii85Mjc4OTEyMC8zMjA3NDgwNzUtYWY5MjgzYWEtY2IyNS00NmFhLWEyNDYtOWYyMjAyYWZlNGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2NTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTFjZmYyYWJkMDYxYjQ5OTg3N2NmOTNlYzM4NmZiZTU2OWVkMzJmMmNmMjY2NjE4NWIzMGM0ZWYyMGE5OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2_PpLpanBS-PCtFNb-odP2VX1PrkgHEJv0nujFG-tDM) 有的啊

在online表单中的增强js代码中怎么使用？

**Comment by yang-xianzhu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/92789120/320748075-af9283aa-cb25-46aa-a246-9f2202afe4bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDU5OTEsIm5iZiI6MTcxMjY0NTY5MSwicGF0aCI6Ii85Mjc4OTEyMC8zMjA3NDgwNzUtYWY5MjgzYWEtY2IyNS00NmFhLWEyNDYtOWYyMjAyYWZlNGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2NTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTFjZmYyYWJkMDYxYjQ5OTg3N2NmOTNlYzM4NmZiZTU2OWVkMzJmMmNmMjY2NjE4NWIzMGM0ZWYyMGE5OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2_PpLpanBS-PCtFNb-odP2VX1PrkgHEJv0nujFG-tDM) 有的啊
> 
> 在online表单中的增强js代码中怎么使用？

目前还没用过这个功能，贴一下具体代码？

**Comment by zhangdaiscott** [comment]
cr

**Comment by zwjsoft** [comment]
启用租户隔离应该就行了，租户隔离后，表单里面都有tenant_id字段，菜单url中也支持${tenant_id}

**Comment by liaozhiyang** [comment]
目前已经支持了。
[文档地址 ](https://help.jeecg.com/online/enhanceJs/func.html)

js增强写法：
```
one_hook(){
   import {useUserStore} from "@/hooks/useUserStore"
   const userStore = useUserStore();

   function sayHi () {
     const userInfo = userStore.getUserInfo;
     const tenantId = userStore.getTenant
     console.log("用户信息", userInfo)
     console.log("租户id", tenantId)
   }

   sayHi();  
}
```
