### ISSUE TITLE
表格控件列固定功能保存后不生效

### ISSUE THREAD

**Issue by b1naryAKAsAsA** [jeecgboot/jeecgboot-vue3#1178]
##### 版本号：

jeecgboot-vue3 3.5.4

##### 问题描述：

表格控件列固定功能保存后不生效 再次进入页面时未保存列固定功能

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/119065477/b1f3cd51-8e16-4799-b834-d34fdd9fe73f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yang-xianzhu** [comment]
设计就这样吧，这些设置存放在内存里，刷新这些就没了，如果要做到永久保存要么就跟后端配合存一下，要么就直接存本地，存放本地的话也不太合理，每个界面的表格都不一样 。。。。

**Comment by zhangdaiscott** [comment]
最新版已经支持保存了
