### ISSUE TITLE
签名错误

### ISSUE THREAD

**Issue by jiangxiaozheng** [jeecgboot/jeecgboot-vue3#118]
##### 问题描述：新创建的模块,列表可以展示出来,但是编辑保存会爆两个错
1. vue3Native 中的代码和后台交互的代码
这个为什么post 请求参数写道了param 里面,加密的时候用 param 加密, 是不是和后台的加密对不上号

httputils 类
![image](https://user-images.githubusercontent.com/54165898/178227861-b3854a1a-04a0-4492-a208-9f6bc29819a9.png)
报错: java.lang.Integer cannot be cast to java.lang.String
修改为 String.valueOf(entry.getValue()) 后不报错了,但是签名错误了

生成的vue3Native 代码 用的post 请求,签名会错误,system 上的都用的get 就没有问题
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
你是如何定义的接口，你是直接用vueNative生成的代码，走的post请求吗，具体是哪一个接口

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/3873
