### ISSUE TITLE
前端启动失败

### ISSUE THREAD

**Issue by jjjjxiaojie** [jeecgboot/jeecgboot-vue3#1181]
##### 版本号：
 3.6.3（发布时间：2024-03-11）

##### 问题描述：
pnpm dev失败

##### 截图&代码：
<img width="1394" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/38858308/80659e0b-0bc9-419e-b552-8b7281e60ff3">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
依赖安装有问题吧，删除依赖使用pnpm i
