### ISSUE TITLE
jeecg-boot 3.6.2 分割菜单如何让一级菜单在左侧,二级菜单在右方顶部

### ISSUE THREAD

**Issue by 2869783364** [jeecgboot/jeecgboot-vue3#1182]
##### 版本号：
jeecg-boot 3.6.2
vue3
##### 问题描述：
jeecg-boot 3.6.2 分割菜单如何让一级菜单在左侧,二级菜单在右方顶部

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/104182261/ddcf505e-5d07-4672-b77d-91af3799335b)

变成这样
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/104182261/6720f35f-a6b1-4925-b10e-991ee6671a6b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/48909f77-585c-420f-af04-4e9d5480bf75)

**Comment by 2869783364** [comment]
这样会导致一级菜单在上面,我想要的是使一级菜单在左侧

**Comment by 2869783364** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/104182261/b63a7d83-0bd6-44ae-9245-be27c2969805)
