### ISSUE TITLE
BasicTable翻页后滚动条没有返回顶部

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#1188]
版本号：3.6.3

问题描述：
    BasicTable翻页后滚动条没有返回顶部,看了代码,表格配置中`scroll`的`scrollToFirstRowOnChange`是强制设置为`false`，当分页、排序、筛选变化后是不滚动到表格顶部,并且`BasicTableProps`的`scroll`配置中也是没有`scrollToFirstRowOnChange`，虽然可以无视`BasicTableProps`类型配置`scrollToFirstRowOnChange`,但ts类型检验会报错
    建议：`BasicTableProps`的`scroll`补上`scrollToFirstRowOnChange`，`scrollToFirstRowOnChange`默认值移至`componentSetting`中配置
   从个人使用习惯来说，翻页后还是滚动到表格顶部方便且合理

截图&代码：
![Dingtalk_20240415085811](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/48cfbf42-3862-4144-b692-9b86a64f4f2d)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修正，下一版本发布。

src/components/Table/src/props.ts 文件类型还需定义下。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/60cb49d4-55f0-4f2c-bc73-ac2f2b2f8892)
