### ISSUE TITLE
将管理员的首页配置为工作台时,会导致进入工作台菜单时首页菜单也会被选中,且之后无法进入首页界面

### ISSUE THREAD

**Issue by 2869783364** [jeecgboot/jeecgboot-vue3#1189]
##### 版本号：
3.6.2
vue3

##### 问题描述：
将管理员的首页配置为工作台时,会导致进入工作台菜单时首页菜单也会被选中,且之后无法进入首页界面
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/104182261/7350fb07-708e-46b2-9312-ee915858f104)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/104182261/ab720e30-a560-44f0-98f5-f22c0a943aa6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
最新版用法变了，你可以升级下看看
