### ISSUE TITLE
前端获取用户信息时有用到roles,但是后台返回的对象中并没有该属性

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#1191]
版本号：3.6.3

问题描述：登录成功时,`getUserInfoAction`的处理中有存入角色集合的方方法,但是后台返回的userInfo对象中却没有对应的roles属性

截图&代码：

![Dingtalk_20240416141138](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/b0bf3c55-0321-4c9f-9818-75e2aa873f27)

**Comment by zhangdaiscott** [comment]
目前前端权限主要是通过指令来控制，没有用到角色。
原架构vben好像有角色，我们没用
https://help.jeecg.com/vue3/auth.html
