### ISSUE TITLE
更改less的@namespace变量后，部分样式无效

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#1195]
版本号：3.6.3

问题描述：更改less的@namespace变量后，部分样式无效

截图&代码：

![Dingtalk_20240416141138](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/a55aecf7-ccc2-4074-8eda-4a8197097618)

**Comment by zhangdaiscott** [comment]
主体色这块我们大改了，等下个版本发布再提类似的问题吧
