### ISSUE TITLE
前端打包后部分样式丢失（暗黑模式）

### ISSUE THREAD

**Issue by ccinos** [jeecgboot/jeecgboot-vue3#1197]
##### 版本号：3.6.3
npm -v  8.19.4
pnpm -v 8.9.2

##### 问题描述：（暗黑模式）前端打包后部分样式丢失，在调试 vite时没问题
打包命令 cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 vite build && esno ./build/script/postBuild.ts

###### 调试样式：
![调试样式css](https://github.com/jeecgboot/jeecgboot-vue3/assets/37493483/15ca57ff-2203-4469-92de-7f7f1dc57239)
![调试样式](https://github.com/jeecgboot/jeecgboot-vue3/assets/37493483/0d77f8ce-b6fa-4128-999a-eca51821c878)

###### 打包样式：
![打包样式css](https://github.com/jeecgboot/jeecgboot-vue3/assets/37493483/14fce38d-06fe-419b-9d44-2248172bfbf8)
![打包样式](https://github.com/jeecgboot/jeecgboot-vue3/assets/37493483/663d0955-f754-4791-9f53-158902f725e9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ccinos** [comment]
不知道为啥我把 build/vite/plugin/theme.ts 里被注释的 extractCss: false 取消注释就好了。
但不知道有没有其他影响。

``` typescript
const plugin = [
    vite_theme_plugin,
    antdDarkThemePlugin({
      preloadFiles: [
        //path.resolve(process.cwd(), 'node_modules/ant-design-vue/dist/reset.css'),
        //path.resolve(process.cwd(), 'node_modules/ant-design-vue/dist/antd.dark.less'),
        path.resolve(process.cwd(), 'src/design/index.less'),
      ],
      filter: (id) => (isBuild ? !id.endsWith('antd.less') : true),
      extractCss: false,  //我把这里的注释打开就好了，但 不知道有没有其他影响
      darkModifyVars: {
```

**Comment by zhangdaiscott** [comment]
是切换暗黑模式不生效？

**Comment by ccinos** [comment]
> 是切换暗黑模式不生效？

打包发布后， 切换黑暗模式，表格样式出现了白边，tab页的字体颜色也不太对， 所以只有部分不生效

大部分还是变黑了

**Comment by zhangdaiscott** [comment]
你看看演示系统有问题吗
boot3.jeecg.com
