### ISSUE TITLE
修改Vue3配置文件VITE_PROXY、VITE_GLOB_API_URL的配置，导致在线开发的功能无法打开

### ISSUE THREAD

**Issue by 280377485** [jeecgboot/jeecgboot-vue3#120]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/55683514/179152451-0086b46a-b475-458b-8fb6-08b63ebbef49.png)
![image](https://user-images.githubusercontent.com/55683514/179152611-5387c94e-ee5c-4c31-a8e0-ab8d08cd8068.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不熟悉的情况下，不要随便改
