### ISSUE TITLE
关于表单验证的问题

### ISSUE THREAD

**Issue by zhangm-git** [jeecgboot/jeecgboot-vue3#1202]
##### 版本号：
3.6.3

##### 问题描述：
我使用代码生成器生成vue3 - antd原生代码后，使用v-if判断时候，已经不显示的字段还是会被表单验证拦截。请问我该如何写或者怎么解决。

##### 截图&代码：
// 表单代码
          <a-form-item v-show="formData.carouselChartType === '2'" label="链接" v-bind="validateInfos.url"  >
            <a-input v-model:value="formData.url" placeholder="请输入链接" :disabled="disabled"></a-input>
          </a-form-item>

// 表单验证
  const validatorRules = {
    carouselChartType: [{ required: true, message: '请输入轮播图类型!'},],
    url: [{ required: true, message: '请输入链接!'},],
  };
  const { resetFields, validate, validateInfos } = useForm(formData, validatorRules, { immediate: false });

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangm-git** [comment]
// 表单代码          
<a-form-item v-show="formData.carouselChartType === '2'" label="链接" v-bind="validateInfos.url"  >
            <a-input v-model:value="formData.url" placeholder="请输入链接" :disabled="disabled"></a-input>
</a-form-item>

**Comment by zhangm-git** [comment]
// <a-form-item v-show="formData.carouselChartType === '2'" label="链接" v-bind="validateInfos.url"  >
 //            <a-input v-model:value="formData.url" placeholder="请输入链接" :disabled="disabled"></a-input>
 // </a-form-item>

**Comment by zhangm-git** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/56628741/29a28446-caf1-463d-a284-99f63eba812d)

**Comment by zhangm-git** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/56628741/449ab3e3-0558-47e3-a847-03ca12355541)

**Comment by zhangdaiscott** [comment]
ws

**Comment by liaozhiyang** [comment]
这是使用antd纯原生的组件，需要看antd的文档。
你只是template中删除了，在useForm传参中也得删除对应的字段
```
<template>
  <a-form :label-col="labelCol" :wrapper-col="wrapperCol">
    <a-form-item v-if="nameVisible" label="Activity name" v-bind="validateInfos.name">
      <a-input v-model:value="modelRef.name" />
    </a-form-item>
    <a-form-item label="Sub name" v-bind="validateInfos['sub.name']">
      <a-input v-model:value="modelRef.sub.name" />
    </a-form-item>
    <a-form-item :wrapper-col="{ span: 14, offset: 4 }">
      <a-button type="primary" @click.prevent="onSubmit">Create</a-button>
      <a-button style="margin-left: 10px" @click="reset">Reset</a-button>
    </a-form-item>
  </a-form>
</template>
<script lang="ts" setup>
  import { reactive, toRaw, ref } from 'vue';
  import { Form } from 'ant-design-vue';

  const useForm = Form.useForm;

  const labelCol = { span: 4 };
  const wrapperCol = { span: 14 };
  const nameVisible = ref(true)
  const modelRef = reactive({
    name: '',
    sub: {
      name: '',
    },
  });
  const rules = {
    'name': [
      {
        required: true,
        message: 'Please input name',
      },
    ],
    'sub.name': [
      {
        required: true,
        message: 'Please input sub name',
      },
    ],
  };
  const { resetFields, validate, validateInfos } = useForm(modelRef,rules);
  const onSubmit = () => {
    validate()
      .then((res) => {
        console.log(res, toRaw(modelRef));
      })
      .catch((err) => {
        console.log('error', err);
      });
  };
  setTimeout(()=>{
    nameVisible.value =false;
    delete rules.name;
    delete modelRef.name;
  },3e3)
  const reset = () => {
    resetFields();
  };
</script>

```

**Comment by zhangm-git** [comment]
十分感谢，我已经去掉vben了，好麻烦。还要监听值表单里的值来控制删掉和加回去
