### ISSUE TITLE
考虑把商业版的收费模块（比如表单设计器，流程模块）放出来给免费试用？现在开源的低代码平台太多了，实在是太卷了

### ISSUE THREAD

**Issue by sunjie798893816** [jeecgboot/jeecgboot-vue3#1203]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://www.qiaoqiaoyun.com
