### ISSUE TITLE
canResize:false 注释后，合计列没有随着表格滚动

### ISSUE THREAD

**Issue by fireinjava** [jeecgboot/jeecgboot-vue3#1208]
##### 版本号：
v3.6.2 及 最新版

##### 问题描述：
// canResize:false,  
设置了表格高度不可调整后，固定了表头，但是表格列多有横向滚动条时，拖动时滚动条合计列不会跟着滚动。

使用最新的 src/component/Table 覆盖后，测试还是有问题

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
录个视频
