### ISSUE TITLE
【咨询】JEditor自动保存插件使用问题

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/jeecgboot-vue3#1209]
##### 版本号：
3.6.3

##### 问题描述：
JEditor组件导入自动保存插件后，配置参数不生效，配置如下图：
![BF78F560B9BEDCD4BB92A80474F0DCC3](https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/5da45d8b-7ede-48b9-b0a7-83150cf88a65)
如上图：配置了保存的key的前缀为：tinymce-autosave-review-reamrk，但实际还是按默认的规则生成的,如下图：
<img width="1417" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/4cc96030-52f3-4e57-ae58-58450eab6db0">

##### 截图&代码：
<img width="706" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/de4de9a3-c851-4af5-9d20-0176e3cc87ed">

<img width="896" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/11d4c2c2-d809-41d9-88e2-5352dd16d1b2">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
因为`Editor.vue`中props没有`autosave_prefix`属性，你需要自己手动加上 或者在`Editor.vue`中配置

在`initOptions`中`return`手动加上
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/9e5ae221-f680-47d4-a73e-f6564bd19544)

成功示意图：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/01a1f38e-dad8-4cd5-9948-68c5aba8fd30)

**Comment by 1298191366** [comment]
因为`Editor.vue`中props没有`autosave_prefix`等属性，你需要自己手动加上 或者在`Editor.vue`中配置

在`initOptions`中`return`手动加上
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/9e5ae221-f680-47d4-a73e-f6564bd19544)

成功示意图：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/01a1f38e-dad8-4cd5-9948-68c5aba8fd30)
