### ISSUE TITLE
自动生成的主附表功能   如何在附表实现自动显示隐藏字段的功能

### ISSUE THREAD

**Issue by 19134186282** [jeecgboot/jeecgboot-vue3#121]
##### 版本号：

1.3
##### 问题描述：
自动生成的主附表功能   如何在附表实现自动显示隐藏字段的功能
类似于主表的 ifShow

##### 截图&代码：

主表 ：
{
  field: 'deviceIds',
  label: '设备',
  component: 'JSelectDevice',
  componentProps: {
    rowKey: "id",
    labelKey: "hostName"
  },
  ifShow: ({values}) => (values.jobType == 'ROUTINEEXAM'),
}, 

附表 ： 
{
  title: '端口',
  key: 'port',
  type: JVxeTypes.input,
  width: "150px",
  placeholder: '请输入${title}',
  defaultValue: '',
},

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
可以通过`JVxeTypes.hidden`将附表的列设置成隐藏列，但是没有动态根据值显示与隐藏的，你可以在valueChange事件中处理（动态设置成`JVxeTypes.hidden`）
