### ISSUE TITLE
BasicDrawer弹框destroyOnClose属性不生效，当Drawer关闭后子元素未销毁，导致再次打开还展示上一次的内容

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/jeecgboot-vue3#1210]
##### 版本号：
3.6.3

##### 问题描述：
BasicDrawer弹框使用tabs标签，当Drawer关闭后，自已定义的数据对象未销毁，导致再次打开时还记录着上一次的值，如下图所示在BasicDrawer定义的两个数据对象。
<img width="628" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/c3591849-fe3f-465d-8bcd-8cbca76a3207">
当关闭弹窗后，没有销毁 Drawer 里的数据对象，再次打开还保留了上一次的数据，destroyOnClose配置不生效，如下图：
<img width="645" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/4a415e26-b3f1-443d-9f30-268f9c7b5a6b">

##### 截图&代码：
<img width="997" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/da40846b-423c-4beb-a88c-15da206dc541">
<img width="693" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/2850ba71-8d75-49b9-afab-a557888d1bc1">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这是正常的。
destroyOnClose销毁的是modal的子元素，而你的数据对象定义在 ContactsDetailDrawer.vue 中，关闭的时候除非你在ContactsDetailDrawer组件的父级销毁ContactsDetailDrawer组件。
两种方式解决：
1.关闭弹窗销毁ContactsDetailDrawer组件
2.关闭或者打开弹窗重置ContactsDetailDrawer里面的数据
