### ISSUE TITLE
3.6.2低代码开发打不开

### ISSUE THREAD

**Issue by 2869783364** [jeecgboot/jeecgboot-vue3#1211]
##### 版本号：
3.6.2 last

##### 问题描述：
拉取代码后 用 yarn 20.9.0 下包 ,然后 运行没问题 ,将自己的.git文件放入也没问题 ,然后删除yarn.lock文件,再删除 src/views/demo文件夹,报错,然后全部恢复 ,还是报错
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/104182261/cf9dfe16-6c15-4561-8b6d-f3a9c18e9aa4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
使用pnpm i
