### ISSUE TITLE
仪表板菜单配置

### ISSUE THREAD

**Issue by mengrose** [jeecgboot/jeecgboot-vue3#1212]
##### 版本号：
3.6.1
##### 问题描述：
使用仪表盘设计看板，在配置菜单时，采用官方文档的方式二：前端集成仪表盘的菜单配置。点击菜单界面时空白，浏览时报
[Vue Router warn]: Record with path "/drag/page/view/750938006131638272" is either missing a "component(s)" or "children" property。
![1713929855229](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/63d3ac1d-e4e0-4c17-8459-91a75e927dbd)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/290d12dc-a884-4b41-84a8-8d7a55d3d131)

这个vue页面不存在，就用不了老模式

**Comment by mengrose** [comment]
那3.6.1现在应该怎么处理，这个问题

**Comment by zhangdaiscott** [comment]
先确认这个页面是否存在

**Comment by mengrose** [comment]
全局搜索，没有找到这个dashboardPreview页面

**Comment by zhangdaiscott** [comment]
那就按照文档方式一配置

**Comment by mengrose** [comment]
就是按照文档来配置，版本是3.6.1，如果用方式一配置，报错签名不存在，登录时间超时；采用方式二配置，就是现在描述的问题。您可以测试一下

**Comment by zhangdaiscott** [comment]
贴错误

**Comment by mengrose** [comment]
**版本3.6.1
### 预览是正常的**
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/68ac4453-417c-4050-a985-49618995c4b9)
### **采用文档方式一配置菜单**
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/1ff26b8b-da8d-444a-9bae-695666046946)
报错截图
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/3a03d6ff-8f79-4df8-aef9-15a20c385f29)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/9333d0da-3c97-4d23-8b2f-de676d483280)
### **采用文档方式二配置菜单**
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/c2be015d-9135-4205-9da3-c99084f1f17b)
报错信息，只有前台有，后台无打印信息
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/ee864f78-aff1-44d9-a65b-6d97339570dc)

**Comment by mengrose** [comment]
@zhangdaiscott 还请看一下这个问题
