### ISSUE TITLE
JDictSelectTag 这个组件获取到选中的值，这个具体要怎么用

### ISSUE THREAD

**Issue by AlibabaP8Developer** [jeecgboot/jeecgboot-vue3#1213]
##### 版本号：
jeecgboot 3.6.3
vue3

##### 问题描述：
JDictSelectTag 这个组件获取到选中的值，这个具体要怎么用

##### 截图&代码：
JDictSelectTag 这个组件获取到选中的值，这个具体要怎么用
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/39144819/427683a9-dd8b-47e0-b25f-39a72977d341)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/39144819/d66b89b0-00f7-4c45-9113-a85589a3bbc4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
我不太明白你说的意思，我就简单介绍一下用法
参考文档：https://help.jeecg.com/component/JDictSelectTag.html
注意这里是`v-model:value` ,dictCode为字典（字典管理中配置）或者表字典(表名,文本字段,取值字段)的方式，返回的值就是你字典中配置的值或者表字典配置的取值字段

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/64f67061-a31e-4b80-b91f-7af8c63fc208)

你可以在jeecg组件实例，原生表单示例中查看效果，对应前端代码`OneNativeForm.vue`
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/2f69376d-fcc4-4150-9f19-8253ad71a092)
