### ISSUE TITLE
useListPage 中使用selectedRowKeys设置了一个列表表中的没有的key后，再去选择列表某一行时页面崩溃

### ISSUE THREAD

**Issue by obj-Rui** [jeecgboot/jeecgboot-vue3#1214]
##### 版本号：

3.5.3
##### 问题描述：
使用BasicTable组件里使用selectedRowKeys设置了一个列表表中的没有的key后，再去选择列表页面崩溃，
我发现在useCustomSelection.tsx里面
<img width="759" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/66825538/260bd6fc-9369-4901-940e-ac1c78ed0b6f">
这个判断长度导致死循环，所以加了这一句希望有更好的方法
<img width="1148" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/66825538/3503d030-a183-41bc-85dc-3bf9ccb8480a">

##### 截图&代码：
使用方式
<img width="1101" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/66825538/b702cf54-a517-4b83-b8b5-6fb988c29053">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级到最新版看看
