### ISSUE TITLE
路由菜单（例如，大屏）如何在新窗口中打开？

### ISSUE THREAD

**Issue by annong163** [jeecgboot/jeecgboot-vue3#1215]
##### 版本号：
V3.6.2

##### 问题描述：
路由菜单（例如，大屏）如何在新窗口中打开？我该如何配置

**Comment by zhangdaiscott** [comment]
[参考百度菜单](https://help.jeecg.com/config/menu/new.html#2%E9%85%8D%E7%BD%AE%E5%A4%96%E9%93%BE%E8%8F%9C%E5%8D%95%E7%A4%BA%E4%BE%8B)
