### ISSUE TITLE
最新版本本地运行后online表单新增和编辑无法修改内容

### ISSUE THREAD

**Issue by tanxvyang** [jeecgboot/jeecgboot-vue3#1216]
##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/27222868/b4378fb0-9832-49dc-a817-7cca2e3dc774)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
前端和后端分别下载的那个分支

**Comment by tanxvyang** [comment]
前后端均使用master分支启动

**Comment by zhangdaiscott** [comment]
有报错吗

贴后台错误和F12浏览器错误

**Comment by tanxvyang** [comment]
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/27222868/63c48b56-3046-4a9d-aeaf-3877935dac02)
[runtime-dom.esm-bundler.js:19:19](http://localhost:3100/node_modules/.pnpm/@vue+runtime-dom@3.4.24/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js)
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/27222868/f4d032ee-71c3-43dd-af17-2679e0748b4a)
[CgformModal-5cf02d51.mjs:182:45](http://localhost:3100/node_modules/.pnpm/@jeecg+online@3.6.2-GA_bqljniokpymwfoop4nfjifahbm/node_modules/@jeecg/online/CgformModal-5cf02d51.mjs?v=65fd325d)
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/27222868/f9237244-6b1a-44d3-b72a-887853e597f7)
[runtime-core.esm-bundler.js:2464:32](http://localhost:3100/node_modules/.pnpm/@vue+runtime-core@3.4.24/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)

后台无报错,页面F12报错截图和报错位置如图,
Uncaught (in promise) TypeError: child is null
Uncaught (in promise) TypeError: l.value is null
Uncaught (in promise) TypeError: i.type is undefined

**Comment by zhangdaiscott** [comment]
node什么版本号

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/6246e56a-9177-444b-accf-57d010c24c94)
清下vite缓存试试

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/6095

**Comment by tanxvyang** [comment]
node版本为v18.17.0
根据上面方法进行修改,并修改node为 18.16.1,清除缓存,甚至重启电脑,依旧未解决问题;
重新拉取代码后问题没了...,目前不清楚具体原因
![325559067-b4378fb0-9832-49dc-a817-7cca2e3dc774](https://github.com/jeecgboot/jeecgboot-vue3/assets/27222868/0bd80869-3f41-46f7-98ff-e46fe8e6810d)
上图为有问题的截图,没有下方的默认数据字段表单部分
---------
下图为新拉取的代码,可以正常显示并进行操作
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/27222868/8f724c51-f95e-42f8-9989-bcd1c76a79a3)

**Comment by zhangdaiscott** [comment]
重新拉取问题没了？前个版本是什么时间下载的？下载地址是哪里？
