### ISSUE TITLE
BaiscTable中开启form搜索后，showActionButtonGroup=false时，将showAdvancedButton=true时，搜索区域查询条件超过3条时未显示“展开/收起”按钮

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/jeecgboot-vue3#1219]
##### 版本号：
3.6.3

##### 问题描述：
BaiscTable中开启form搜索后，showActionButtonGroup=false，showAdvancedButton=true时，搜索区域查询条件超过3条时未显示“展开/收起”按钮

##### 截图&代码：
<img width="547" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/398dd5c3-bbbf-45a3-8a2d-6ac95515161d">

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

##### 分支：
master？还是springboot3_sas

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by hhxyjsj** [comment]
意思是：我配置了4个查询属性，如下图：
<img width="602" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/83427cb0-17df-4b8e-a073-d5c1c4179bc7">

1、formConfig配置如下图时，能正常显示：展开收起按钮
<img width="757" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/1d8cc864-3a18-419d-bb1b-df85b870dcbc">
<img width="1401" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/d15f80c5-3f18-4c8f-979f-db45bc7ccd6b">
<img width="1447" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/7e775d38-8634-456a-89a4-e8d6bde7f949">

2.当把formConfig配置中的showActionButtonGroup改成false后，则不显示展开收起按钮，如下图
<img width="503" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/2bc71aaf-e9d0-48c1-b642-1f8ffe23f55d">
<img width="1426" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/6d5f3454-0eab-4a50-916d-9cf937815f81">

**问题：是否显示“展开收起”按钮只受“showAdvancedButton”参数的限制，而不应该同时受“showActionButtonGroup”参数的限制**

**Comment by hhxyjsj** [comment]
> ws

意思是：我配置了4个查询属性，如下图：
<img width="602" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/83427cb0-17df-4b8e-a073-d5c1c4179bc7">

1、formConfig配置如下图时，能正常显示：展开收起按钮
<img width="757" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/1d8cc864-3a18-419d-bb1b-df85b870dcbc">
<img width="1401" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/d15f80c5-3f18-4c8f-979f-db45bc7ccd6b">
<img width="1447" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/7e775d38-8634-456a-89a4-e8d6bde7f949">

2.当把formConfig配置中的showActionButtonGroup改成false后，则不显示展开收起按钮，如下图
<img width="503" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/2bc71aaf-e9d0-48c1-b642-1f8ffe23f55d">
<img width="1426" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/6d5f3454-0eab-4a50-916d-9cf937815f81">

**问题：是否显示“展开收起”按钮只受“showAdvancedButton”参数的限制，而不应该同时受“showActionButtonGroup”参数的限制**

**Comment by 1298191366** [comment]
showActionButtonGroup 是指整个按钮区域，包含展开和关闭
你可以单独设置 将查询和 重置按钮单独设置隐藏

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/9023a5b3-c34f-48f7-8443-540f7f8f19bf)

效果
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/30997828/84e4b74e-e7d3-4b3a-9355-6f0efed2e276)
