### ISSUE TITLE
部署到tomcat  刷新404

### ISSUE THREAD

**Issue by 19134186282** [jeecgboot/jeecgboot-vue3#122]
##### 版本号：

1.3.0
##### 问题描述：
部署到tomcat后   一刷新显示404  需要退回到一级页面 才可以访问

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2503893
