### ISSUE TITLE
【3.6.3】basicDrawer showFooter isDetail 同时使用 无法正常显示顶部header或者底部footer

### ISSUE THREAD

**Issue by benben120** [jeecgboot/jeecgboot-vue3#1227]
##### 版本号：
3.6.3

##### 问题描述：
basicDrawer showFooter isDetail 同时使用 无法正常显示顶部header或者底部footer

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/a566b929-6f95-4a39-9a12-892ea0a09526)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/ea3a22d9-d5c8-4cc7-a850-b5f794256a37)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/15e8a127-ff49-4398-bdf9-0c3e7a528d43)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by benben120** [comment]
> 经测没复现，你是否改过底层代码？你可克隆一份纯净的代码在试试。 ![image](https://private-user-images.githubusercontent.com/8199499/328101469-71138567-5bb1-4360-9b29-fc8b6040f6b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODAyMjUsIm5iZiI6MTcxNDk3OTkyNSwicGF0aCI6Ii84MTk5NDk5LzMyODEwMTQ2OS03MTEzODU2Ny01YmIxLTQzNjAtOWIyOS1mYzhiNjA0MGY2YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDcxODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmM0YTRhODlhZDBjMjAyYTVhNzEwNGVkZjljOTMzNTFiNDY1ODU2OGUzYTEyZTgwNGY1MjM1NmJkMTgzMjY5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lk_zV9d8NdJC3x5rqixT7gMPaVYTqU5Xlj0XNjyExVY)

分辨率较低屏幕 会出现这个问题

**Comment by benben120** [comment]
> 经测没复现，你是否改过底层代码？你可克隆一份纯净的代码在试试。 ![image](https://private-user-images.githubusercontent.com/8199499/328101469-71138567-5bb1-4360-9b29-fc8b6040f6b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODEyOTIsIm5iZiI6MTcxNDk4MDk5MiwicGF0aCI6Ii84MTk5NDk5LzMyODEwMTQ2OS03MTEzODU2Ny01YmIxLTQzNjAtOWIyOS1mYzhiNjA0MGY2YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDczNjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFhN2Y4YmJlNDFjNjU2YmMwM2Y0NzY3OTRkM2Q3NzgzYWRlZjc4NzQxZDRmNTc0M2Y2Zjk4YWNlY2NkM2UxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2RXdpWNJboFUuM4Nqxe1-juCO9703J7Nddy8-kk9Tf8)
电脑型号: ThinkPad L13
屏幕尺寸: 13.3英寸1920x1080

**Comment by benben120** [comment]
> 经测没复现，你是否改过底层代码？你可克隆一份纯净的代码在试试。 ![image](https://private-user-images.githubusercontent.com/8199499/328101469-71138567-5bb1-4360-9b29-fc8b6040f6b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODEyOTIsIm5iZiI6MTcxNDk4MDk5MiwicGF0aCI6Ii84MTk5NDk5LzMyODEwMTQ2OS03MTEzODU2Ny01YmIxLTQzNjAtOWIyOS1mYzhiNjA0MGY2YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDczNjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFhN2Y4YmJlNDFjNjU2YmMwM2Y0NzY3OTRkM2Q3NzgzYWRlZjc4NzQxZDRmNTc0M2Y2Zjk4YWNlY2NkM2UxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2RXdpWNJboFUuM4Nqxe1-juCO9703J7Nddy8-kk9Tf8)
电脑型号: ThinkPad L13
屏幕尺寸: 13.3英寸1920x1080

**Comment by liaozhiyang** [comment]
图列开了看不到。1920*1080分辨率不低了，我之前测试的就是在这个分辨率下。麻烦提供更相信的信息

**Comment by benben120** [comment]
> 图列开了看不到。1920*1080分辨率不低了，我之前测试的就是在这个分辨率下。麻烦提供更相信的信息
![img_v3_02al_02336003-1b70-4cf5-9b6c-2959331fecag](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/484c1ced-40e3-4b7f-9c77-9901de37ac45)

这是窗口大小 稍等我录屏给您

**Comment by benben120** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/f16d0ff4-b565-43a5-ace4-90a723bb5cbe

**Comment by benben120** [comment]
![img_v3_02al_97788feb-58ca-4747-a17a-39f0b142864g](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/b9084224-428f-4ddf-8191-e529aa70e20d)
当前笔记本 显示器 谷歌浏览器显示大小

**Comment by liaozhiyang** [comment]
能用下载一份纯净的代码测试下吗？实在没复现出来
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/a077a243-42d2-400d-bd8b-a1cf7a4138a9)

**Comment by benben120** [comment]
> 能用下载一份纯净的代码测试下吗？实在没复现出来 ![image](https://private-user-images.githubusercontent.com/8199499/328359949-a077a243-42d2-400d-bd8b-a1cf7a4138a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTI2MzEsIm5iZiI6MTcxNTA1MjMzMSwicGF0aCI6Ii84MTk5NDk5LzMyODM1OTk0OS1hMDc3YTI0My00MmQyLTQwMGQtYmQ4Yi1hMWNmN2E0MTM4YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDMyNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQyNzczMzcxZTJmNzNjMTY1NzMwMDk0MTBlNjNlYzE1MGUxMDU0YzMwNDAzM2MzOWVhY2YyNTI3MDRmODc5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.znZXilNvkN7eGzUqtbz_Z44UGlRf5pbRL8B3nqDobJw)

是自身修改代码导致的问题 不好意思 另外问一句 basicDrawer 能实现 isDetail情况下 不要全屏 而是 控制在 侧边栏 以及顶部菜单栏 下边位置吗
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/b32e8fd8-38c3-408d-a032-803e95a05ba6)
