### ISSUE TITLE
JPopup弹窗选择组件 搜索字段只有两个的时候，如何移除收起展开

### ISSUE THREAD

**Issue by shen-wenlong** [jeecgboot/jeecgboot-vue3#1229]
![image](https://github.com/jeecgboot/jeecg-boot/assets/75566817/f6b66588-e691-482a-8e1c-2d108ceb5a18)

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布。下个版本支持`showAdvancedButton(true或false)`是否显示展开和关闭，默认显示(true)
