### ISSUE TITLE
JVxeTable，字典下拉框列，使用固定左侧 ，就只显示id

### ISSUE THREAD

**Issue by anlem12** [jeecgboot/jeecgboot-vue3#1230]
##### 版本号：
3.6.2

##### 问题描述：
JVxeTable，字典下拉框列，使用固定左侧 ，就只显示id

##### 截图&代码：
![微信截图_20240430195311](https://github.com/jeecgboot/jeecgboot-vue3/assets/32320086/f4869ab0-8ec5-42af-9b21-0e4acd4a1b25)

![微信截图_20240430195351](https://github.com/jeecgboot/jeecgboot-vue3/assets/32320086/0ef04151-4392-4a65-ba5c-955db1efa78f)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
官网上测试无法复现。有更详细的信息吗？你可测试下官网的例子
[综合示例](http://boot3.jeecg.com/jeecg/j-vxe-table-demo/normal)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/f1174905-730d-4b87-bf0d-7e7c9f9100eb)
