### ISSUE TITLE
tab标签页切换

### ISSUE THREAD

**Issue by 2846781956** [jeecgboot/jeecgboot-vue3#1233]
##### 问题描述：
tab路由标签页显示隐藏在哪配置

##### 截图&代码：
![7be8a14a651799e8017878f0b4993b5](https://github.com/jeecgboot/jeecgboot-vue3/assets/95627491/d123539a-1b13-43ee-bcdf-de0afb6de50f)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/93d41fb5-54c9-4b30-950b-857f46a798a1)
