### ISSUE TITLE
 【3.6.3】basicDrawer 详情模式isDetail 展开位置优化

### ISSUE THREAD

**Issue by benben120** [jeecgboot/jeecgboot-vue3#1234]
##### 版本号：
3.6.3

##### 问题描述：
basicDrawer 能实现 isDetail情况下 不要全屏 而是 控制在 侧边栏 以及顶部菜单栏 下边位置吗

##### 截图&代码：
类似之前3.6.2版本的效果
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/dc8efb17-23c7-4167-9eb9-bb53fc983e0d)
目前3.6.3是如下效果 全屏显示了
![oSgJaaGrv0](https://github.com/jeecgboot/jeecgboot-vue3/assets/162244360/ac7fd27d-8289-4332-acba-a36c50876130)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己扩展吧
