### ISSUE TITLE
在只有一个后台的情况下，有没有办法区分这个账号是登录后台的，还是登录手机端的，因为后台和手机端展示的数据和页面是完全不一样的，一个账号要么登录后台，要么登录手机端

### ISSUE THREAD

**Issue by zgya** [jeecgboot/jeecgboot-vue3#1246]
##### 版本号：
3.4.0

##### 问题描述：

在只有一个后台的情况下，有没有办法区分这个账号是登录后台的，还是登录手机端的，因为后台和手机端展示的数据和页面是完全不一样的，一个账号要么登录后台，要么登录手机端
##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以在header里加个额外的参数
