### ISSUE TITLE
如果登录后，修改代码使得不进入首页，而是另一个页面，在点击浏览器的返回键时，会出现后台页面

### ISSUE THREAD

**Issue by zgya** [jeecgboot/jeecgboot-vue3#1247]
##### 版本号：
3.4.0

##### 问题描述：
如果登录后，修改代码使得不进入首页，而是另一个页面，在点击浏览器的返回键时，会出现后台页面
修改处：![5UPIWDDYF_2JS~)2 E5SH3A](https://github.com/jeecgboot/jeecgboot-vue3/assets/52008657/add32243-126f-4112-bcda-5a4edacd867e)
登录后首先进入的页面：
![69L$QD8DNRW85FG58VE81`M](https://github.com/jeecgboot/jeecgboot-vue3/assets/52008657/727e5ac2-da14-48ef-8f82-21dca87ba045)
点击浏览器的返回按钮后：
![Z)R )99UKRDG}%V3I)CFQHN](https://github.com/jeecgboot/jeecgboot-vue3/assets/52008657/d146ce42-8c6b-46c7-a897-88bde340452c)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
src\enums\pageEnum.ts
src\router\routes\modules\dashboard.ts
src\store\modules\user.ts


### 前端修改这三个文件，写死你自定义的首页路由


1、src\enums\pageEnum.ts

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/6e4395c7-a8f4-4716-b1cc-424738a7113c)

2、src\router\routes\modules\dashboard.ts
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/f46b0a6d-f412-4d05-b05b-26dc3cde1be0)

3、src\store\modules\user.ts
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/ebd0c92e-0478-4e23-8484-b37d65b33c71)
