### ISSUE TITLE
BasicTable的columns如何进行动态处理？

### ISSUE THREAD

**Issue by wyx666518** [jeecgboot/jeecgboot-vue3#1248]
##### 版本号：
3.6.3

##### 问题描述：
useListPage函数放在远程回调中就报错。table无法渲染。这个如何处理？

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
描述过于简单
