### ISSUE TITLE
如何在代码层面通过orgCode来判断这个部门是否赋予了某个权限呢

### ISSUE THREAD

**Issue by zgya** [jeecgboot/jeecgboot-vue3#1249]
##### 版本号：
3.4.2

##### 问题描述：
如何通过orgCode来判断这个部门是否赋予了某个权限

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以考虑采用二级部门权限
https://help.jeecg.com/java/system/auth/depart.html
