### ISSUE TITLE
标签页右键菜单点击重新加载页面空白

### ISSUE THREAD

**Issue by peopleWander** [jeecgboot/jeecgboot-vue3#1256]
##### 截图&代码：
![H46QE8 I8 P_P T~}%A7LJM](https://github.com/jeecgboot/jeecgboot-vue3/assets/49889018/8dcb05e1-10ff-45c2-b019-b300383d8991)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by peopleWander** [comment]
在提交记录中找到 liaozhiyang---date:20231123---for：【QQYUN-7099】动态路由匹配右键重新加载404
根据提交记录修改本地文件后问题仍然存在

**Comment by zhangdaiscott** [comment]
下载最新版本试下
