### ISSUE TITLE
为什么请求成功了返回的值还是undefined

### ISSUE THREAD

**Issue by ayss-xjh** [jeecgboot/jeecgboot-vue3#1259]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55195263/7d82db58-7796-4a3b-b6b5-49953b645e90)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55195263/7f1a1ebb-0d6a-4139-a1dc-221343d4e250)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55195263/519d5269-eb03-41c1-85ad-5cb7378d58ae)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55195263/ffffac76-02f9-4550-bf3e-4cef8509add1)

##### 前端安装环境：node 18 

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己写的代码，请自行排查

**Comment by ayss-xjh** [comment]
> 自己写的代码，请自行排查
接口要添加isTransformResponse: false,我想问一下，像这种文档里面有吗，不然每次都要看源码排查问题
