### ISSUE TITLE
JVxetable能否实现列拖拽排序

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#1266]
##### 版本号：
3.6.3

##### 问题描述：
JVxetable能否实现列拖拽排序,现在只能固定左侧或者右侧，能否实现拖动排序或者输入序号排序

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/9e5f9485-f697-4578-a122-0bbbb05ca7f0)

**Comment by zhangdaiscott** [comment]
可以，参考online字段配置
