### ISSUE TITLE
ERP风格下列设置问题

### ISSUE THREAD

**Issue by 17782798075** [jeecgboot/jeecgboot-vue3#127]
##### 问题描述：
ERP风格下的列设置，修改主表列设置后刷新页面会导致其子表列设置为空
原因应该是因为列设置是以路由为主键存储到local Storage 中的，刷新页面加载出来的列设置就只有主表的列了
VUE2版本也存在这个问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/75563099/180373914-edcd2c72-355a-41b4-94b9-23da6663730c.png)
![image](https://user-images.githubusercontent.com/75563099/180373995-7756abbf-fba6-4659-aa72-1c44cb1651e4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 17782798075** [comment]
人呢？？？？

**Comment by FlawlessChen** [comment]
我也遇到了

**Comment by 17782798075** [comment]
@zhangdaiscott

**Comment by yejiangteng** [comment]
有解决这个问题的吗

**Comment by accpman** [comment]
table配置中加入如下配置   tableSetting:{
        cacheKey:'customer'
      }
来区分不同表格的缓存key
![image](https://user-images.githubusercontent.com/4446237/196584823-0c45f57a-29c0-42fc-a2e8-ddb588b033f8.png)

**Comment by zhangdaiscott** [comment]
下个版本发布
