### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by peak666** [jeecgboot/jeecgboot-vue3#1274]
##### 版本号：
3.6.3

##### 问题描述：
启动报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42790595/c5681004-66e8-4ce9-a1a7-3fe0eff7b91f)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn? pnpm
- node版本号：？v14.21.3
- pnpm版本号：？7.33.5

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
？

**Comment by peak666** [comment]
> ？

感觉应该是node版本和pnpm版本兼容性问题，但是看pnpm文档，node 14版本是支持pnpm 7版本的
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42790595/5b29ae3f-9db5-4139-b768-3eb7c93c0db8)
能给一个你们推荐的node和pnpm的版本吗？

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/032a5015-2cb2-4c05-a82b-b8ab9f678d88)
