### ISSUE TITLE
pnpm dev 启动报错 没法使用

### ISSUE THREAD

**Issue by rcw-code** [jeecgboot/jeecgboot-vue3#1275]
##### 版本号：
如图

##### 问题描述：
pnpm install 没有问题； pnpm dev 就报错了 没法启动

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/70672860/e4d90eaf-30f5-489a-9d56-b9fb0eafd1c3)

**Comment by zhangdaiscott** [comment]
先install
