### ISSUE TITLE
集成cas之后，总是自动刷新

### ISSUE THREAD

**Issue by 506764932** [jeecgboot/jeecgboot-vue3#128]
##### 问题描述：
vue3项目的端口设置了： 9200
设置了域名：映射的地址是【IP：9200】
遇到的问题是：
集成cas之后，总是自动刷新，通过截取视频的方式发现，他一直尝试 链接 【 域名:9200】其实 我的域名已经包含了【IP:9200】
导致每次链接都是失败一直restart 。
请问改怎么处理。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6880877/180443011-a8279351-1acc-45cf-a96f-3b460413433c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
cas服务端自己实现的，得自己分析

**Comment by 506764932** [comment]
> cas服务端自己实现的，得自己分析

这就过分了吧，我要是能分析出来还问你？连个大致问题可能的方向都没有？那我在这提个毛线，提了跟没提一样。

**Comment by 506764932** [comment]
你看问题了吗，这很明显跟CAS没关系。就是websockt访问会restart的问题。
