### ISSUE TITLE
列表界面 分页展示80和100条 多选框只显示几个 其他的不显示

### ISSUE THREAD

**Issue by cuitiangang** [jeecgboot/jeecgboot-vue3#1281]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50402322/7007dc70-9539-40f4-bde6-9c7602ab3e9b)

##### 前端安装环境：
yarn 1.22.10
node v18.18.2
pnpm 8.7.4
安装插件用的yarn install
启用程序用的 pnpm dev

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级到最新版试试

**Comment by cuitiangang** [comment]
> 升级到最新版试试

你是说代码升级到 最新的吗？ 因为这个代码版本挺旧的了 而且我们在上面也开发了挺多东西的 不太好升级合并最新的代码了。。

**Comment by zhangdaiscott** [comment]
那自己根据git历史去查看我们的修改
