### ISSUE TITLE
表头自定义字段配置的监听事件，监听不到setColumns方法设置的字段变化

### ISSUE THREAD

**Issue by huangjr1234** [jeecgboot/jeecgboot-vue3#1291]
##### 版本号：
3.4.4

##### 问题描述：
basicTable组件提供的setColumns方法，设置了字段之后，表头自定义字段组件ColumnSetting中监听了getColumns不生效

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/60591844/df4d4f20-5ed4-4750-bf79-678f5ce01758)

![QQ截图20240607145922](https://github.com/jeecgboot/jeecgboot-vue3/assets/60591844/dffcad2e-bfcc-4378-929b-e6d12b8b9278)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangkai123123** [comment]
把setTimeout去掉就好了

**Comment by zhangdaiscott** [comment]
请升级到最新版
