### ISSUE TITLE
仪表盘设计器 跳转链接不生效

### ISSUE THREAD

**Issue by testnet0** [jeecgboot/jeecgboot-vue3#1293]
##### 版本号：
V3.6.3

##### 问题描述：
仪表盘设计器里 快捷导航，如配置了跳转地址href，但是点击不生效：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/18673513/239efb4a-4cf6-43f2-8f57-c9f4a7d294bf)
还有卡片设置右上角的跳转地址，点击更多也没任何作用：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/18673513/8eb8f11f-85c7-451d-b716-39e558708335)
项目列表也是一样，配置了跳转，但点击无效：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/18673513/1055b8fd-4c52-4795-81f3-fa6fc51c401b)

##### 截图&代码：
  {
    "title": "首页",
    "icon": "icon-jeecg-homepage",
    "color": "#1fdaca",
    "href": "/test"
  },

**Comment by zhangdaiscott** [comment]
新版发布了，请验证
