### ISSUE TITLE
Js增强打开自定义弹窗，本地开发环境正常，服务器环境展示异常

### ISSUE THREAD

**Issue by 280377485** [jeecgboot/jeecgboot-vue3#130]
##### 问题描述：使用Js增强打开自定义弹窗异常，本地开发环境能够正常显示的弹窗，发布到服务器后无法显示，控制台异常提示：
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

##### 截图&代码：
Js增强打开自定义弹窗：
![image](https://user-images.githubusercontent.com/55683514/180919719-37ad444b-0213-47f0-8153-462c11a41603.png)

本地开发环境正常：
![image](https://user-images.githubusercontent.com/55683514/180919754-99430d5d-7e4d-458c-ad12-8bffaa8fe07c.png)
服务器无法显示：
![image](https://user-images.githubusercontent.com/55683514/180919767-e4253cf9-354d-407c-b368-874c6778004c.png)

错误提示：
![image](https://user-images.githubusercontent.com/55683514/180919781-6afa2d5e-618d-4334-aef9-c8db501c5bb6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持此功能
