### ISSUE TITLE
多租户模式下，【租户角色】新增角色后，列表中看不到新增记录，在【角色管理】中可以看到

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#1303]
##### 版本号：
3.7.0

##### 问题描述：
多租户模式下，【租户角色】新增角色后，列表中看不到新增记录，在【角色管理】中可以看到。

感觉和多租户相关的一些功能总是出问题，希望可以完整测试下。

##### 截图&代码：
![screenshots 1](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/8eaf5804-818f-4921-abd5-1c42f1ae0d1f)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/javaback.html
先好好看看文档

开启多租户了吗

**Comment by citynook** [comment]
@zhangdaiscott 
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/f685aff8-e8c3-4233-a6af-61ee7b219f38)

**Comment by citynook** [comment]
@zhangdaiscott 
1. 多租户已开启，添加租户角色
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/4c10fbc3-379f-48f4-8224-88a2a79110e4)

2. 后台接口中，并未根据多租户保存 role.tenantId = 当前租户 id，保存后数据库中的 tenant_id 值 为 0
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/1eb6b76e-71af-4dd2-9653-1e3b68e97417)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/5fefd14d-e427-439c-8ab0-fc5c6ebfde00)

3. 查询接口中，在多租户模式下添加了 where role.tenaitId = 当前租户 id 的条件，但第2步保存的时候，tenant_id 为0，所以查不出数据
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/a495cdee-b0b3-425a-9a4f-771a3d34bd5e)

**Comment by zhangdaiscott** [comment]
当前登录用户，有租户吗

**Comment by citynook** [comment]
@zhangdaiscott 18号下载的3.7.0 master 分支最新版本，初始化数据库后未对数据做任何修改，使用 jeecg 账号登录后做上述的操作发生的问题。下面截图是登录账号的信息，刚才又试着在租户角色中添加一笔记录，还是同样的问题。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/581d012e-7225-4b68-9ec2-b514e36b07ca)

**Comment by zhangdaiscott** [comment]
解决了，请更新代码
