### ISSUE TITLE
高级查询组件代码逻辑问题

### ISSUE THREAD

**Issue by 17782798075** [jeecgboot/jeecgboot-vue3#131]
##### 问题描述：
3.3.0发布后看到了新增了高级查询组件，但是按照文档的配置是无法实现高级查询功能的，会发生 TypeError: Cannot read properties of undefined (reading 'noChange') 的错误！
##### 截图&代码：
报错：
![image](https://user-images.githubusercontent.com/75563099/180940444-121feb59-855c-4e9a-9415-2405a1cb0d50.png)
useSuperQuery中的代码是这样的：
![image](https://user-images.githubusercontent.com/75563099/180939802-d7203f2d-a4bc-41c2-8a66-02c5752ab26a.png)
应该给item创建FormSchema实例：
![image](https://user-images.githubusercontent.com/75563099/180940683-40d8fa42-26d5-43ea-8796-9755f117e459.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
高级查询组件尚未正式发布
