### ISSUE TITLE
关于后端Online自动生成的前端代码，部署菜单后新增不显示数据

### ISSUE THREAD

**Issue by hnnhxy** [jeecgboot/JeecgBoot-vue3#1311]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/81a485ec-3045-4f98-a1af-128c770a60b4)
1、新增的表单添加数据不显示，在数据库可以查询到数据，不回显！！
![a58c05f16050a8fd188a4f40192666d3](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/e8dedb36-c3da-4d0b-b01a-872d607394db)
2、接口数据查询回显
![e3de74d8ce674cc111d7248d0c5daf03](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/78d47757-a6ad-4c41-92a8-4a5fa2bc7334)
3、前端data.ts里面查询数据的定义给出随便一个数字就会显示出来，
![03703b6de04553647371629ef96198de](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/0757d55b-b74d-4a8a-b061-e3c56713e093)
![4fd980c3686166a10831e9b9e1cac944](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/e5bd18b2-da39-4787-b793-86012a0db865)
前端就跟着显示了，这样子后期不会出现问题吧。
![b5140187086b60fef739e5a9c23776d4](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/11adc475-57c8-49c5-b2e3-06c7c37092da)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：V18.19.0
- pnpm版本号：9.1.3

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
？

**Comment by zhangdaiscott** [comment]
怎么重现呢，我测没问题

**Comment by hnnhxy** [comment]
后端部署环境，IDEA 2022.1.4 ，前端使用过的是WebStorm 2022.1.4，至于为什么会这样我不太清楚，就生成代码后执行SQL出现的菜单里面操作的。

**Comment by zhangdaiscott** [comment]
开发环境没问题？只是部署版本有问题？

**Comment by zhangdaiscott** [comment]
F12看看有报错吗

**Comment by hnnhxy** [comment]
不清楚，不知道是我这边依赖的问题，还是什么，我没有部署私域的MAVEN

**Comment by hnnhxy** [comment]
//查询数据
export const searchFormSchema: FormSchema[] = [
];

上面代码还原了没写数字。

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/43bccfa8-5051-4b84-8029-108f5ce3b59b)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/8725fc09-9725-4cf8-876d-d083b24223b8)

**Comment by hnnhxy** [comment]
![Uploading image.png…]()

**Comment by hnnhxy** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/173246353/a7673703-9688-41a6-aca6-080539de558a)

**Comment by zhangdaiscott** [comment]
你生成的代码打包给我们

**Comment by hnnhxy** [comment]
[admin.zip](https://github.com/user-attachments/files/15922198/admin.zip)

**Comment by hnnhxy** [comment]
LIST接口出不来
![b939ea1e2bc5c17a3c94a7a189e84515](https://github.com/jeecgboot/JeecgBoot-vue3/assets/173246353/661cfc46-f616-43a8-b8b8-95ac4fc91342)

但是吧查询数据添加上1，就能显示数据了
![29acdca76fd316761eb3ce18b8678ee4](https://github.com/jeecgboot/JeecgBoot-vue3/assets/173246353/2e48781e-4006-41cf-85d1-2b048aaa966d)

![21fc3f6c599fee23237562ba58d474bb](https://github.com/jeecgboot/JeecgBoot-vue3/assets/173246353/edb684a9-00f0-453c-8c80-7b3e1dd45b2a)

**Comment by zhangdaiscott** [comment]
少提代码， 已经改了，你更新下

**Comment by hnnhxy** [comment]
前后端都重新下载么？

**Comment by zhangdaiscott** [comment]
更新前端
