### ISSUE TITLE
外链出来的大屏图片资源失效了

### ISSUE THREAD

**Issue by ZedCoding** [jeecgboot/jeecgboot-vue3#133]
##### 问题描述：

图片资源失效了！
##### 截图&代码：

![image](https://user-images.githubusercontent.com/24578758/181178655-1490ed73-1f5e-47d5-8016-7f7584ee33a0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
现在还有问题吗，我们测无问题

**Comment by ZedCoding** [comment]
![image](https://user-images.githubusercontent.com/24578758/181402352-b86c0819-3e75-4bc8-b13c-cea9caebdbb3.png)
访问的这个地址http://api3.boot.jeecg.com/bigscreen/#/build/1552466733875359745  图片资源还是有些失效

**Comment by ZedCoding** [comment]
![image](https://user-images.githubusercontent.com/24578758/181402578-d3d603dc-deab-42fb-9438-91560c8cdb44.png)
这是控制台的报错
