### ISSUE TITLE
vue3版本

### ISSUE THREAD

**Issue by chengxiaozhu** [jeecgboot/jeecgboot-vue3#135]
##### 版本号：
vue3

##### 问题描述：
代码成功显示运行成功，但是打开页面，控制台报这个错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19968853/181927967-4bbbcb24-2ea3-44b8-aa9f-fc04606ffc4c.png)
![image](https://user-images.githubusercontent.com/19968853/181928240-e4a39d7b-3b03-4dd9-ab53-19e131a1e4a0.png)

return <InfoCircleFilled_default class="modal-icon-warning" />;

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
忽略就行，不影响功能
