### ISSUE TITLE
BasicTable 调用插入函数 默认插入两条记录

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/jeecgboot-vue3#136]
##### 版本号：
1.2.0

##### 问题描述：
1. tableProps中定义声明dataSource数据后调用insertTableDataRecord后 插入两条记录
2. tableProps中未定义声明dataSource数据后调用insertTableDataRecord后 没有记录插入

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50694382/182545058-6ed0cacf-8f16-4346-82fd-56e2aefc040e.png)

![image](https://user-images.githubusercontent.com/50694382/182545019-17216829-6870-4823-b8b4-37afedcd5847.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by sjlei** [comment]
问题已修复
