### ISSUE TITLE
高级查询报错不能用

### ISSUE THREAD

**Issue by BYNepenthe** [jeecgboot/jeecgboot-vue3#137]
##### 版本号：
JeecgBoot 3.3.0 版本

##### 问题描述：
高级查询不能用

JeecgBoot 3.3.0 版本中，我看已经加入了高级查询的相关代码，但是使用时有报错，是还没有完善吗？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7778022/182981882-f5b58dbf-5926-4ef6-b161-42b7d56f9df4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
还没开发完
