### ISSUE TITLE
表格展示 右侧选项时,列选项为空

### ISSUE THREAD

**Issue by jiangxiaozheng** [jeecgboot/jeecgboot-vue3#139]
##### 问题描述：
![image](https://user-images.githubusercontent.com/54165898/183385405-bbe976d8-fff7-4ba8-ab28-e06ce29e6a93.png)

代码里展示更多.列数据就会为空,不展示则有数据

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sfox-xg** [comment]
3.4依然有这个问题
