### ISSUE TITLE
最新代码报错

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecgboot-vue3#142]
##### 版本号：
3.4.0

##### 问题描述：
代码是最新的，没做修改，如下删除后，重新build
```
rm -rf node_modules yarn.lock
```

![image](https://user-images.githubusercontent.com/14859466/185844995-f2ccdd21-4a18-42aa-b4b1-3c0970d718b6.png)

其他都没改，就yarn.lock变了，试了好几遍，还是无法启动，控制台报错如下

##### 截图&代码：

![image](https://user-images.githubusercontent.com/14859466/185844897-90655c20-a721-436d-81c5-cb05ab8c7451.png)

代码
![image](https://user-images.githubusercontent.com/14859466/185844946-fe1012d5-7e03-4590-b592-eeef540a7135.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不要删除lock ，用yarn install

**Comment by hdtopku** [comment]
> 不要删除lock ，用yarn install
为什么要用你们那边的lock才可以，是因为node版本不同的缘故吗？这边的node版本是16.14.2
```
node -v
v16.14.2
```
