### ISSUE TITLE
::v-deep usage as a combinator has been deprecated. Use ::v-deep(<inner-selector>) instead

### ISSUE THREAD

**Issue by TomYule** [jeecgboot/jeecgboot-vue3#143]
##### 版本号：
3.4.0

##### 问题描述：
警告信息
```
::v-deep usage as a combinator has been deprecated. Use ::v-deep(<inner-selector>) instead
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  

解决办法:
https://stackoverflow.com/questions/63986278/vue-3-v-deep-usage-as-a-combinator-has-been-deprecated-use-v-deepinner-se

原因https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md
::v-deep 已经弃用

**Comment by zhangdaiscott** [comment]
jl

**Comment by accpman** [comment]
哪个页面报的警告

**Comment by accpman** [comment]
已修复
