### ISSUE TITLE
Token超时无法跳转到登录页

### ISSUE THREAD

**Issue by sfox-xg** [jeecgboot/jeecgboot-vue3#145]
##### 版本号：
3.4

##### 问题描述：

Token超时无法跳转到登录页
if (e && (e.message.includes('timeout') || e.message.includes('401'))) 无法为true
##### 截图&代码：

/src/api/sys/user.ts 

export function getUserInfo() {
  return defHttp.get<GetUserInfoModel>({ url: Api.GetUserInfo }, { errorMessageMode: 'none' }).catch((e) => {
    // update-begin--author:zyf---date:20220425---for:【VUEN-76】捕获接口超时异常,跳转到登录界面
    if (e && (e.message.includes('timeout') || e.message.includes('401'))) {
      //接口不通时跳转到登录界面
      const userStore = useUserStoreWithOut();
      userStore.setToken('');
      setAuthCache(TOKEN_KEY, null);
      router.push(PageEnum.BASE_LOGIN);
    }
    // update-end--author:zyf---date:20220425---for:【VUEN-76】捕获接口超时异常,跳转到登录界面
  });
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
测试没问题，token超时，点击菜单，会调整登录页
![image](https://user-images.githubusercontent.com/3162115/190975284-a63d9e7a-5951-42f6-882a-0806fc72b084.png)
