### ISSUE TITLE
问题讲解

### ISSUE THREAD

**Issue by wyz2017** [jeecgboot/jeecgboot-vue3#150]
##### 问题描述：
想知道我如何从其他外部页面跳转到某一条在线表单的新增页面，和查看页面

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
