### ISSUE TITLE
无法使用年份范围选择器

### ISSUE THREAD

**Issue by depthwood** [jeecgboot/jeecgboot-vue3#153]
##### 问题描述：
1.FormSchema设置 component: 'RangePicker',想要作为年份选择器，如下配置后无法选择正确年份
![image](https://user-images.githubusercontent.com/65118489/189096622-c88c3a8a-a424-410c-993e-b44d48493e4d.png)
2.选择后数据不回显，也没有开始年份小于结束年份校验
![image](https://user-images.githubusercontent.com/65118489/189096966-c0e5502e-ae5b-4420-8117-7734ad500e69.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
新版升级到antd3，现在可以用了
