### ISSUE TITLE
jeecg3.4 online表单导入数据库表bug

### ISSUE THREAD

**Issue by findAgem** [jeecgboot/jeecgboot-vue3#154]
##### 截图&代码：
配置：
![image](https://user-images.githubusercontent.com/41536144/191492730-8d799be6-b873-4fca-9e07-2a604a6c3bc6.png)
数据库表：
![image](https://user-images.githubusercontent.com/41536144/191492917-c3a1f85d-cb54-47e8-8f2f-d5cd24c5d77e.png)

系统L:
![image](https://user-images.githubusercontent.com/41536144/191493059-95a585e2-0589-4747-ad1a-89a41a59f17d.png)

请处理

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
注释掉org/jeecg/config/init/CodeGenerateDbConfig.java
就走你的配置
