### ISSUE TITLE
菜单配置增加功能

### ISSUE THREAD

**Issue by laozhu001** [jeecgboot/jeecgboot-vue3#156]
##### 版本号：

3.4.0
##### 问题描述：

菜单配置，增加一项数据：参数，可以根据，页面可以根据获得的参数，决定页面的数据内容
##### 截图&代码：

![@E(T0XC}M)$7T$GQ_B %@{Q](https://user-images.githubusercontent.com/31055677/191907833-170441a8-a2ae-4f90-a170-d3abd59ccc7c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
项目里面不是有示例吗
![image](https://user-images.githubusercontent.com/3162115/191908610-8bee226c-1e3d-448d-8486-e3252c69cfe6.png)

**Comment by laozhu001** [comment]
我的需求不完全像demo演示的那样。demo是打开菜单后用户输入参数，写代码切换。我得意思能直接取到sub1，sub2.
我现在有办法取到，只是看起来不太好看。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecgboot-vue3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 下午3:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecgboot-vue3] 菜单配置增加功能 (Issue #156)





 
项目里面不是有示例吗
