### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined

### ISSUE THREAD

**Issue by tucke** [jeecgboot/jeecgboot-vue3#158]
##### 版本号：
3.4.2

##### 问题描述：
无法启动

##### 截图&代码：
vite-plugin-mkcert  这个依赖没有锁定版本号，现在默认使用的是 1.10.0 导致项目无法启动报错 
···
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
  at new NodeError (node:internal/errors:387:5)
  at fileURLToPath (node:internal/url:1434:11)
···

**Comment by zhangdaiscott** [comment]
修复了
