### ISSUE TITLE
开发环境启动非常慢

### ISSUE THREAD

**Issue by zhangyongxuan** [jeecgboot/jeecgboot-vue3#160]
##### 截图&代码：
<img width="361" alt="image" src="https://user-images.githubusercontent.com/47049216/194498427-b5e048e7-98ea-4842-9f2e-0f6d416224cc.png">

**Comment by zhangyongxuan** [comment]
就网络请求好几百个 一直转圈
<img width="770" alt="image" src="https://user-images.githubusercontent.com/47049216/194498756-ead632f2-13bf-4df6-a2d3-4c007518501c.png">

**Comment by zhangyongxuan** [comment]
chrome版本
<img width="137" alt="image" src="https://user-images.githubusercontent.com/47049216/194498920-850260bd-d38e-412b-bc47-9e8d271fa065.png">
用的master代码

**Comment by zhangdaiscott** [comment]
vue3 vite实际上比webpack是慢，没办法目前vue3官方问题

**Comment by zhangyongxuan** [comment]
官方给出的解释就是加载太多less文件,并不是其他vue+vite项目都这么慢,希望可以提供一个优化方案
