### ISSUE TITLE
关于编辑菜单中的是否缓存路由功能的疑问

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecgboot-vue3#161]
##### 版本号：
当前最新版本： 3.4.2

##### 问题描述：

编辑菜单中的勾上缓存路由，菜单来回切换，还是会调用onmounted()生命周期，请求列表数据，这是缓存路由没生效吗？还是缓存了还是会调用onmounted生命周期？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/14859466/194687465-d1afd333-96fc-467c-a384-eca5edb75bb3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2561635
