### ISSUE TITLE
Online表单开发中，多表关联主题，除默认主题外erp，内嵌等全部无效

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/jeecgboot-vue3#162]
##### 版本号：
 3.4.2

##### 问题描述：
Online表单开发中，多表关联主题，除默认主题外erp，内嵌等全部无效，除默认主题外关联到菜单后均显示404，官方演示环境有同样问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/71683167/194736976-98f1cecd-f53d-4f6f-89cc-d8778ec28423.png)
![image](https://user-images.githubusercontent.com/71683167/194736999-c39ac47f-465d-48da-a722-a163a6d35ff4.png)
![image](https://user-images.githubusercontent.com/71683167/194737010-ce66ea52-2711-4920-bcbe-76dde8fcf706.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
vue3版本一对多目前暂时还未实现其他风格
