### ISSUE TITLE
用户编辑中所属部门与负责部门不显示部门名称，只显示departIds

### ISSUE THREAD

**Issue by GitACDreamer** [jeecgboot/jeecgboot-vue3#163]
##### 版本号：
3.4.2

##### 问题描述：
其中JSelectDept文件已经对照过GitHub上最新的代码，完全一致。
目前vue环境相关版本：
vue `3.2.37`
ant-design-vue `3.2.12`

问题1：编辑用户中，选择所属部门，选择后，会显示 departId，而不是 departName，并且身份设置为上级，负责部门下拉列表为空，只有点击确认更新用户信息，再次点击编辑用户，所属部门名称显示正常，负责部门显示正常。
问题2：选择所属部门，有些名称是岗位，在JSelectDept中，岗位也被当做部门可被选择

##### 截图&代码：
第一次点击编辑用户，选择用户所属部门，设置此身份为上级的截图表现
![image](https://user-images.githubusercontent.com/19402747/194810430-d4a502f5-eaeb-4d65-a0e1-3f0acdd31c0c.png)
保存所属部门数据后，再次进入用户编辑，显示正常
![image](https://user-images.githubusercontent.com/19402747/194810866-a905f22a-0956-4c23-bf48-621e8c033990.png)

部门选择（会把岗位也列举出来当做部门）
![image](https://user-images.githubusercontent.com/19402747/194810685-7912c2bc-80c1-4e2c-a371-948a5c64b8c7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
1 部门选择，目前是没区分部门和岗位的，都可以选
2 显示ID的问题，请确认最新版是否还存在，我们测试无问题
