### ISSUE TITLE
在线表单 列设置内容缺失

### ISSUE THREAD

**Issue by RazorWang** [jeecgboot/jeecgboot-vue3#164]
##### 版本号：
前端 3.4.2 
后台 3.4.2

##### 问题描述：
在线表单 列设置内容缺失

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20596694/194985300-cae176e4-a587-41ca-9026-0b41150bde6c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级到3.4.3就好了
