### ISSUE TITLE
clearSubRows时报错TypeError: instance.getNewDataWithId is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by stevenlee810** [jeecgboot/jeecgboot-vue3#166]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/115564653/195114606-4a01f30f-d52f-44b9-aacb-ab367d1c84bb.png)

![image](https://user-images.githubusercontent.com/115564653/195114113-00483645-e9f0-43cb-9af7-343f5cd20c66.png)

![image](https://user-images.githubusercontent.com/115564653/195122998-54efd352-503f-49b3-adf9-fffc9ba5eb09.png)

**instance.getNewDataWithId() 、 instance.addRows 两处都报这个bug。**

**js源码如下：**
loaded(){
  this.$nextTick(()=>{
      //更新子件清单
       let params2 ={}
       params2 = {'typeId':'1'}
       console.log('参数---------------',params2)
       getAction('/mesProcessCheckContent/mesProcessCheckContent/getProcessCheckContentlList',params2).then(res=>{
        this.clearSubRows('mes_process_check_item');
        this.addSubRows('mes_process_check_item', res);
              })
   })
}

**Comment by stevenlee810** [comment]
![image](https://user-images.githubusercontent.com/115564653/195115042-acf20cfa-69a9-4af7-bddb-1bdb34d1689d.png)
b补充一下报错的代码。

**Comment by stevenlee810** [comment]
![image](https://user-images.githubusercontent.com/115564653/195119510-c8a8c7e9-f874-48dc-808b-819bce7601e0.png)
instance.getNewDataWithId() 、 instance.addRows 两处都报这个bug。

**Comment by stevenlee810** [comment]
![image](https://user-images.githubusercontent.com/115564653/195120599-de7b43d6-9452-4874-886c-0efe9b7fec0d.png)

instance.getNewDataWithId() 、 instance.addRows 两处都报这个bug。

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
