### ISSUE TITLE
标签页样式更多下拉显示样式错乱问题

### ISSUE THREAD

**Issue by playInfo** [jeecgboot/jeecgboot-vue3#169]
##### 版本号：
3.4.2

##### 问题描述：
标签页样式更多下拉显示样式错乱问题

##### 截图&代码：

![20221014104756](https://user-images.githubusercontent.com/3364726/195750758-0d3e066c-79fb-4394-a837-0ffecfffc1f9.png)

**Comment by zhangdaiscott** [comment]
请试下3.4.3测试无问题
![image](https://user-images.githubusercontent.com/3162115/196448895-5a4412b3-af30-4b27-a046-864356fc4503.png)

**Comment by zhangdaiscott** [comment]
确认

**Comment by sjlei** [comment]
问题已修复，下版本发布
