### ISSUE TITLE
配置聚合路由的地址时，报系统已存在该值的错误。

### ISSUE THREAD

**Issue by lm356536** [jeecgboot/jeecgboot-vue3#176]
##### 问题描述：
配置菜单时，根据官网文档所描述的进行聚合路由地址配置时，会产生系统已存在该值已存在的错误。（vue2版本的，此功能正常。）
```
父级菜单配置如下
（1）配置聚合路由，选择是；
（2）菜单地址配置其子菜单中的一个菜单地址，作为默认跳转的地址；
```

##### 截图&代码：
<img width="459" alt="image" src="https://user-images.githubusercontent.com/20919577/197955510-724bf058-d822-483a-8bc9-3a379ca1a9f6.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请求路径重复了，换个地址

**Comment by lm356536** [comment]
这个是父级菜单， 按官方对聚合路由的说法不是选一个子菜单的地址来作为默认跳转的吗？

**Comment by lm356536** [comment]
> 请求路径重复了，换个地址

这个是父级菜单， 按官方对聚合路由的说法不是选一个子菜单的地址来作为默认跳转的吗？

**Comment by zhangdaiscott** [comment]
你这是vue3 还是vue2

**Comment by lm356536** [comment]
vue3版本的聚合路由出问题了。 vue2版本ok的。 
现在vue3版本，子菜单设置为隐藏路由后，在页面里面点击按钮进行路由调整的时候，首次会有404页面找不到的问题。刷新浏览器才可以看到该页面。
菜单的配置：
<img width="321" alt="image" src="https://user-images.githubusercontent.com/20919577/198173288-209348ef-4197-4414-a083-ed32a9ed9a22.png">
出问题的页面：
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/20919577/198173340-04e7eb04-96f1-4301-ae31-cc7568876d2f.png">
该页面再次刷新：
<img width="810" alt="image" src="https://user-images.githubusercontent.com/20919577/198173390-363ccf23-d207-4e5d-8fcd-adc10a82d609.png">

**Comment by zhangdaiscott** [comment]
yf

**Comment by accpman** [comment]
已修复 等新版

**Comment by zhangdaiscott** [comment]
已经修复，请更新代码
