### ISSUE TITLE
online表单

### ISSUE THREAD

**Issue by zdwxt1** [jeecgboot/jeecgboot-vue3#18]
##### 版本号：
latest

##### 问题描述：
我们这边新项目，计划使用vue3版本，但没有online表单会增加很多工作量，请问online表单计划什么时候上线，如果项目工期能hold住就用vue3，否则只能用vue2版本了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
1-3个月

**Comment by qn2060** [comment]
加油，同样需求
