### ISSUE TITLE
vxe-table有全屏功能，JVxeTable默认隐藏了吗？怎么开启呀

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecgboot-vue3#182]
##### 版本号：
3.4.0

##### 问题描述：
vxe-table有全屏功能，JVxeTable默认隐藏了吗？怎么开启呀

##### 截图&代码：
![输入图片说明](https://foruda.gitee.com/images/1665451591200191658/d9a1e297_11043196.png "屏幕截图")

**Comment by sjlei** [comment]
根据官方配置，可以通过`toolbarConfig`调出来全屏按钮，
![image](https://user-images.githubusercontent.com/34293221/230901537-f2e6f5da-b831-408e-b000-67a038eb75c6.png)

但是JVXETable没有适配该功能，所以使用时会有各种问题，所以暂未开放全屏功能。
