### ISSUE TITLE
下拉搜索，使用动态字典，在线页面不报错，生成的代码报错

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecgboot-vue3#183]
##### 截图&代码：
![输入图片说明](https://foruda.gitee.com/images/1664514343632971783/37ff00ec_5432045.png "1664514166459.png")
![输入图片说明](https://foruda.gitee.com/images/1664514068026859215/0f3d86c3_5432045.png "屏幕截图")

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法分析处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by zhangdaiscott** [comment]
修复了，请更新代码
