### ISSUE TITLE
在线开发，auto在线表单模块操作按钮位置默认位置不对

### ISSUE THREAD

**Issue by lm356536** [jeecgboot/jeecgboot-vue3#188]
##### 版本号：
3.4.3

##### 问题描述：
在线开发，auto在线表单模块操作按钮位置默认位置不对
##### 截图&代码：
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/20919577/198293630-baa1a19e-fe1f-47eb-86fc-91ed67866a70.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不对是什么意思，故意放到左边的

**Comment by lm356536** [comment]
这个设计不太符合一般人的的交互习惯。建议做成可选的吧。第一反应还以为是bug。

**Comment by zhangdaiscott** [comment]
允许自定义
![image](https://user-images.githubusercontent.com/3162115/198498583-853fc38f-04a2-49da-a0d7-cc6229cf70bc.png)
