### ISSUE TITLE
项目中添加本地的json数据文件，打包后json文件被忽略了

### ISSUE THREAD

**Issue by soDoEasy** [jeecgboot/jeecgboot-vue3#189]
##### 截图&代码：
mapBase.value = (await (await import("/@/views/dashboard/components/map/610000.json")).default) as any
打包后 610000.json.json 文件报404

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以这么玩吗
