### ISSUE TITLE
vscode提示ts报错

### ISSUE THREAD

**Issue by lucas270** [jeecgboot/jeecgboot-vue3#19]
##### 版本号：
[jeecgboot-vue3](https://github.com/jeecgboot/jeecgboot-vue3)

##### 问题描述：
几乎每个页面，编辑器都提示这个错误：JSX 元素类不支持特性，因为它不具有“props”属性， 但vben里相同的页面就不会报

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29675411/159658042-1d153d39-008d-4ceb-bcb1-1fa58364ea5a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
没有遇到类似问题，确认是否安装了最新版的Vetur插件。

![image](https://user-images.githubusercontent.com/34293221/161266893-df243e64-422a-4258-a40e-9cedc54890af.png)


![image](https://user-images.githubusercontent.com/34293221/161266831-4a226dd9-d9b4-4680-88a0-35ce83689bc6.png)

**Comment by DaiZero** [comment]
@lucas270 我遇到相同的问题，你应该是用了 TypeScript Vue Plugin (Volar) 这个插件，把它卸载就行了

**Comment by lucas270** [comment]
> @lucas270 我遇到相同的问题，你应该是用了 TypeScript Vue Plugin (Volar) 这个插件，把它卸载就行了

是用了，问题vben项目就没这些提示。这不是在vben上开发的吗

**Comment by LantzShaw** [comment]
遇到了相同的问题，参考一下这篇https://github.com/johnsoncodehk/volar/discussions/592

**Comment by lucas270** [comment]
> 遇到了相同的问题，参考一下这篇[johnsoncodehk/volar#592](https://github.com/johnsoncodehk/volar/discussions/592)

我按照那样弄，还是不行。现在还是报“xxxx不能作为JSX组件”

**Comment by LantzShaw** [comment]
> 

我采用的是这种方式:
项目根目录下新建`stub/empty.d.ts`
```ts
export {}
```

然后配置`tsconfig.json`
```json
{
  "compilerOptions": { 
     "paths": {
      "preact/*": ["./stub/empty.d.ts"]
      }
   }
}
```
这样就可以了，我不知道你采用的是哪种方案

**Comment by LantzShaw** [comment]
> > 遇到了相同的问题，参考一下这篇[johnsoncodehk/volar#592](https://github.com/johnsoncodehk/volar/discussions/592)
> 
> 我按照那样弄，还是不行。现在还是报“xxxx不能作为JSX组件”

我采用的是这种方式:
项目根目录下新建`stub/empty.d.ts`
```ts
export {}
```
然后配置`tsconfig.json`
```json
{
  "compilerOptions": { 
     "paths": {
      "preact/*": ["./stub/empty.d.ts"]
      }
   }
}
```
