### ISSUE TITLE
在线开发，页面属性中控件长度不起作用

### ISSUE THREAD

**Issue by lm356536** [jeecgboot/jeecgboot-vue3#190]
##### 版本号：
3.4.3

##### 问题描述：
在线开发，页面属性中控件长度不起作用，默认120，改为40，长度不变

##### 截图&代码：

<img width="932" alt="image" src="https://user-images.githubusercontent.com/20919577/198516707-bf64edd6-491c-4a1d-827c-b37c58257dc1.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/20919577/198516768-95e79b1c-16bb-44c7-89f8-aafc2834f2b7.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自适应的，不做控制
