### ISSUE TITLE
在线表单》数据库属性模块，对字段跨多字段进行拖拽排序时，无法成功。

### ISSUE THREAD

**Issue by lm356536** [jeecgboot/jeecgboot-vue3#191]
##### 版本号：
3.4.3
##### 问题描述：
在线表单，数据库属性模块，对字段跨多字段进行拖拽排序时，无法成功。
##### 截图&代码：
<img width="911" alt="image" src="https://user-images.githubusercontent.com/20919577/198525506-149d0062-74e8-4df3-8abd-a5761281d466.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl
