### ISSUE TITLE
在线报表配置，有配置数据字典的查询条件无法出现下拉框

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecgboot-vue3#192]
##### 问题描述：

在线报表配置，有配置数据字典的查询条件无法出现下拉框

##### 截图&代码：

![image](https://user-images.githubusercontent.com/24811278/198528051-fa7465c8-5c20-4b79-b1d4-0c06d72b0f0a.png)
![image](https://user-images.githubusercontent.com/24811278/198528113-579a9f3d-f2df-4047-bcef-4bf2cbe0d02a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
补充版本号，目前最新代码已经支持这个功能
