### ISSUE TITLE
online表单生成，附表的表单值关闭没重置

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#193]
##### 问题描述：
1：online表单生成，附表的行编辑区域，选择行点击编辑弹出modal，modal中表单值未正确读取选中行的数据，且表单遗留值没重置
2：online表单生成，附表的行编辑区域，点击新增弹出modal，modal中表单遗留值没有重置

##### 截图&代码：
![微信图片_20221029194906](https://user-images.githubusercontent.com/35988128/198829964-e5bcbda1-7d90-45a1-91d3-06b43506d73c.png)

![微信图片_20221029194912](https://user-images.githubusercontent.com/35988128/198829968-c163035b-bbde-4024-ba0b-305a4926b2e3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 18612962616** [comment]
补充：对于问题1  我发现可能是因为我这个附表是导入表形式进入系统的 不是在线创建的表  导入的附表的编辑就会读不到数据，新建表单也不会清除数据

**Comment by zhangdaiscott** [comment]
你是什么时间下载的代码？我们在近期频繁的更新补丁，有这个相关的处理，可以更新最新看看

**Comment by 18612962616** [comment]
> 你是什么时间下载的代码？我们在近期频繁的更新补丁，有这个相关的处理，可以更新最新看看

每天的commit文件  我都有同步覆盖  目前看到的现象是：如果附表是通过“导入已有表“形式进入配置的 就会有此问题，

**Comment by zhangdaiscott** [comment]
ok

**Comment by tygithub1** [comment]
经测试，无此问题，请使用最新版

**Comment by zhangdaiscott** [comment]
如果附表是通过“导入已有表“形式进入配置的 就会有此问题
具体如何操作的，或者你提供这个表单相关的升级sql，便于我们重现
