### ISSUE TITLE
online在线表单生成，附表形式表单没有联动组件或省市区组件，有什么其他方式可以方便实现例如省市区选择？

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#194]
##### 截图&代码：
![微信图片_20221029195517](https://user-images.githubusercontent.com/35988128/198830041-dea3d15b-c91d-41e6-a513-b60ba6166b9f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
省市区选择 有计划，后面我们会加上

**Comment by zhangdaiscott** [comment]
已安排  ty

**Comment by 18612962616** [comment]
感谢！ 期待

**Comment by zhangdaiscott** [comment]
已实现，下个版本发布
