### ISSUE TITLE
online在线生成表单，弹窗modal可以调整为抽屉风格么？

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#195]
##### 截图&代码：
![微信图片_20221029195824](https://user-images.githubusercontent.com/35988128/198830156-797d7faa-97ad-4c3a-a116-fcb21862fb1f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前没这功能
