### ISSUE TITLE
online在线表单生成，附表的查询字段设置没有生效

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#196]
##### 截图&代码：
![微信图片_20221029200353](https://user-images.githubusercontent.com/35988128/198830557-27a8b695-8955-43ce-bf03-14eda93af6c3.png)
![微信图片_20221029200356](https://user-images.githubusercontent.com/35988128/198830561-27408455-1de8-4d31-9862-f61c23eb3ddc.png)
![微信图片_20221029200359](https://user-images.githubusercontent.com/35988128/198830567-25632163-bfd8-49ef-bc6d-765bb1ee4de7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没这功能，只支持主表查询或者启动联合查询

![image](https://user-images.githubusercontent.com/3162115/198860566-3367f362-aa94-4013-a8c9-c23f96a22f64.png)
