### ISSUE TITLE
online主副表代码生成，获取主表id置入附表外键的代码，取的字段名错了，取的是附表外键的名称，应为主表id字段名

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#197]
##### 截图&代码：
![微信图片_20221029212352](https://user-images.githubusercontent.com/35988128/198833951-24b6aef0-bdcc-47fa-bbcd-e2f56de7fd3b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请截图看下你的外键配置

**Comment by 18612962616** [comment]
> 请截图看下你的外键配置
![微信图片_20221030174110](https://user-images.githubusercontent.com/35988128/198875602-a0c8e9d9-17fb-47ce-a2d4-9725bb1afd08.png)
如果  附表关联的是主表id字段 生成的代码里写的是全都是附表的字段名

**Comment by zhangdaiscott** [comment]
你这个配置完，功能测试好用吗
目前应该不支持这么配置

```
3.2 online表单一对多，外键配置注意
// 子表外键参数配置
/* 说明: 
 * a) 子表引用主表主键ID作为外键，外键字段必须以_ID结尾，例如 ORDER_ID
 * b) 主表和子表的外键字段名字，必须相同（除主键ID外）;
*/
```
