### ISSUE TITLE
online在线表单主附表生成，生成的代码没有获取设置的modal宽度

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#198]
##### 截图&代码：

![微信图片_20221029213337](https://user-images.githubusercontent.com/35988128/198834587-f307481b-6238-4c79-bbbd-de926cd3a462.png)
![微信图片_20221029213339](https://user-images.githubusercontent.com/35988128/198834592-a5604d26-c8a6-4499-9858-709c0f62b851.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
宽度设置是在线用的，生成代码没有这个逻辑，手工加上就行很简单
![image](https://user-images.githubusercontent.com/3162115/198860814-e47bb2ad-f77f-43f1-934c-93e826405f86.png)
