### ISSUE TITLE
嵌套路由实现

### ISSUE THREAD

**Issue by YANGHAOHEHE** [jeecgboot/jeecgboot-vue3#20]
##### 版本号：

1.0 beta
##### 问题描述：
如何实现路由跳转时保留在当前组件，不要新增一个tab，也就是嵌套路由功能
路由跳转时vben好像会监控路由，自动添加到标签页，组件也切换到菜单管理中指定的组件
jeecg能不能实现在某个路由组件内部进行路由跳转，只切换组件的content内容

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl
