### ISSUE TITLE
前端启动报类型找不到

### ISSUE THREAD

**Issue by striving0** [jeecgboot/jeecgboot-vue3#200]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/56588460/198843395-2f13fa1f-117f-4758-8d86-712704a87daf.png)

![image](https://user-images.githubusercontent.com/56588460/198843349-dde23288-3d68-4149-aa34-45cc39ceda2d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
修复了，请更新代码

**Comment by striving0** [comment]
FTRJRED5S
***@***.***



&nbsp;好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecgboot-vue3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月30日(星期天) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecgboot-vue3] 前端启动报类型找不到 (Issue #200)





 
修复了，请更新代码
