### ISSUE TITLE
online表单生成的预览之后放在菜单表单里面不可以用

### ISSUE THREAD

**Issue by Galivin** [jeecgboot/jeecgboot-vue3#201]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/49386264/198870519-a7dc93c3-74ae-4adc-b4e9-d952db349e76.png)
这个是onlin菜单

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
修复了

https://github.com/jeecgboot/jeecgboot-vue3/commit/b7da59c0b73b849ac33fe916cb2adadac19d4b10
https://github.com/jeecgboot/jeecg-boot/commit/3eab5ee9e6a31438bb0dd1154e51d2e3c9fd0153

**Comment by Galivin** [comment]
你好，现在有事等下在和你说。
