### ISSUE TITLE
首页配置不正常

### ISSUE THREAD

**Issue by zhengjiahaowork** [jeecgboot/jeecgboot-vue3#202]
##### 版本号：
v3.4.3-GA

##### 问题描述：
登录默认打开角色管理好像没有展开对应的菜单，展开的还是首页，以下截图是 官方在线演示网址测试截图
##### 截图&代码：
![image](https://user-images.githubusercontent.com/68040559/198941492-2e5dd246-0bec-471d-9755-c5ffeed19e8c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
截图看看你的首页配置，我这边测试是好使的

**Comment by zhengjiahaowork** [comment]
> 截图看看你的首页配置，我这边测试是好使的 你是vue2 还是 vue3

vue3，我截图是官方在线演示地址，一打开没有展开系统管理，展开的还是首页

**Comment by zhangdaiscott** [comment]
一登录弄人打开的是角色管理，配置是生效的
![image](https://user-images.githubusercontent.com/3162115/198967510-205edee6-8d01-4c4d-8efd-58e5bcd8cba8.png)

**Comment by zhengjiahaowork** [comment]
> 配置是生效的

配置是生效了的，不过不是应该默认展开配置的这个菜单，但是没有展开，展开的是首页的菜单

**Comment by zhangdaiscott** [comment]
是有问题，数据问题。
演示系统已经修复

**Comment by zhengjiahaowork** [comment]
> 是有问题，数据问题。 演示系统已经修复

演示地址好像开始报错了

**Comment by zhengjiahaowork** [comment]
> 是有问题，数据问题。 演示系统已经修复

具体跟哪列值有关方便说一下么，演示地址好像开始报错了

**Comment by zhengjiahaowork** [comment]
> 是有问题，数据问题。 演示系统已经修复

![image](https://user-images.githubusercontent.com/68040559/198972187-bb6d3420-d440-43e1-aec3-d1b6c7c3e066.png)
我看演示地址目前还是展开的是首页的菜单，没有展开系统管理，是就这样的么
