### ISSUE TITLE
打包到服务器上，定时任务点“立即执行“报错

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#204]
##### 问题描述：打包到服务器上，定时任务点“立即执行“报错

服务器上前后端均为https，本地开发环境均为http，本地开发执行定时任务没问题，服务器上报此错，请问该修改哪里？

##### 截图&代码：
![微信图片_20221031173806](https://user-images.githubusercontent.com/35988128/198977878-40fbc8b9-d5bd-4d41-b75f-ba693db88dcf.png)
![微信图片_20221031173810](https://user-images.githubusercontent.com/35988128/198977929-7588fad3-bb90-4606-a425-4da73fa7a09c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个错误是websocket的，跟定时任务没关系


HTTPS站点使用WebSocket的常见错误及解决方案
http://t.zoukankan.com/bkhdd-p-13224251.html

**Comment by 18612962616** [comment]
> 修改了nginx配置  websocket请求不报错了   配置如下
![微信图片_20221031190816](https://user-images.githubusercontent.com/35988128/198994525-e24316b2-d73c-49c6-8745-27220910495d.png)


但执行定时任务还是报另一个错(本地不报错)
![微信图片_20221031190821](https://user-images.githubusercontent.com/35988128/198994595-93596f5c-a5c1-46ce-bdc5-924f7df9e239.png)

**Comment by zhangdaiscott** [comment]
前面补上斜杠
![image](https://user-images.githubusercontent.com/3162115/198995005-3607cc95-b97f-430f-b561-e0360d232a30.png)

**Comment by zhangdaiscott** [comment]
修改了

**Comment by 18612962616** [comment]
> 

可以了 多谢
