### ISSUE TITLE
JVxeTable综合示例-滚动页面后表格的tooltip显示错位

### ISSUE THREAD

**Issue by Jamboy** [jeecgboot/jeecgboot-vue3#209]
##### 问题描述：
JVxeTable综合示例，拉窄某一列使其省略，滚动页面后，再hover省略的单元格，显示的tooptip错位。详情见截图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13913768/199481309-a0d6d71c-6b75-4a50-a5ad-b2f5626fd1c8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收到

**Comment by lsqGitHub716** [comment]
更新到最新版本试试
