### ISSUE TITLE
2.4.5 升级到3.10

### ISSUE THREAD

**Issue by leohao1018** [jeecgboot/jeecgboot-vue3#21]
##### 版本号：
2.4.5 

##### 问题描述：
老的项目是基于2.4.5开发的，后端升级应该还好，想问问前端可以升级到3.1.0版本吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
7

**Comment by leohao1018** [comment]
可能我的描述有问题，我的意思是2.4.5的前端是否能升级到 jeectboot-vue3

**Comment by zhangdaiscott** [comment]
升不了
jeectboot-vue3 非在Vue2版上简单升级，而是完全重写。
所以只能新项目用新版本
