### ISSUE TITLE
JDictSelectTag组件选择的值未赋值到BasicForm组件的字段中

### ISSUE THREAD

**Issue by wesley-wang-cn** [jeecgboot/jeecgboot-vue3#212]
##### 版本号：
3.4.3

##### 问题描述：

JDictSelectTag组件选择的值未赋值到BasicForm组件的字段中，在保存时，这个字段中的值是null
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by wesley-wang-cn** [comment]
defaultValue， BasicForm配置的默认值，也没有显示出来

**Comment by zhangdaiscott** [comment]
贴代码
