### ISSUE TITLE
在线表单开发JA增强中建议增加控件只读控制方法

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#214]
##### 版本号：
JeecgBoot 3.4.0、3.4.3 前端Vue2、vue2

##### 问题描述：
目前在线表单开发中，提供了控制控件字段显隐的方法（this.sh），但实际业务需求中会要求控件不要隐藏，只是不能编辑输入（根据不同的条件），可不可以也能提供相应方法在JS增强中处理？
（能在JS增强中方便地控制控件显示颜色，那就更好了！）

##### 截图&代码：
![1667472741842](https://user-images.githubusercontent.com/36326638/199702809-17df0b06-2a7a-4041-871c-355d9e184aa5.png)
目前vue2版我使用setAttribute来实现，但是Vue3不支持这种setAttribute，目前也没有找到办法。
vue2版：
![1667473043329](https://user-images.githubusercontent.com/36326638/199703773-48ca6a95-be3c-4b53-9694-bb505b6ede0b.png)
vue3版：（不起作用）
![1667473248979](https://user-images.githubusercontent.com/36326638/199704491-c4c0aef8-613b-4711-85e0-1bb656fbbce7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by tygithub1** [comment]
this.updateSchema({ field: 'name', componentProps: { disabled: true } })

**Comment by gxzhou** [comment]
谢谢。this.updateSchema()有文档说明吗？

**Comment by tygithub1** [comment]
> 谢谢。this.updateSchema()有文档说明吗？

https://vvbin.cn/doc-next/components/form.html#methods:~:text=%E7%AC%AC%E4%B8%80%E4%B8%AA%E4%BD%8D%E7%BD%AE-,updateSchema,-%E7%B1%BB%E5%9E%8B%3A%20(data

**Comment by gxzhou** [comment]
谢谢您！

**Comment by gxzhou** [comment]
> this.updateSchema({ field: 'name', componentProps: { disabled: true } })

老师好，这个在Vue3版本可用，想请问一下，在Vue2版本有没有类似的有效的将控件属性置为“只读”的语句呢？使用以下的方法似乎不稳定，有时候起不了作用，也不知道啥原因，而且，对下拉框控件肯定是没有效果的。望赐教，多谢。
![image](https://user-images.githubusercontent.com/36326638/200991437-7610fe5a-50b0-49f8-a5a0-dcc2086710c3.png)

**Comment by zhangdaiscott** [comment]
vue2不支持，没有disabled api

**Comment by gxzhou** [comment]
> vue2不支持，没有disabled api

好的。现在找到了document.getElementById("ship_point_id").setAttribute('disabled', true); 有时候设置不生效的原因了，是因为由于某些原因导致表单数据又刷新显示了一下，于是这个设置“只读”就不起作用了。比如：表单中又一个字段为“省市区”控件，就会失效，那这个“省市区”控件字段设为不显示，“只读”就能生效。因为，在编辑状态，这个“省市区”控件会把代码转换为汉字，会刷新表单数据的。
唉，那就没办法，只能先迂回了。多谢。
