### ISSUE TITLE
FIX 修复在消息中心，信息模板中编码为空提示重复问题

### ISSUE THREAD

**Issue by xiaolinhaha** [jeecgboot/jeecgboot-vue3#217]
##### 问题描述：
https://github.com/jeecgboot/jeecgboot-vue3/pull/216
FIX 修复在消息中心，信息模板中编码为空提示重复问题
##### 截图&代码：
https://user-images.githubusercontent.com/36000601/199908640-63b904fb-fe1d-4916-b4e6-659498092819.png

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已合并
