### ISSUE TITLE
所有功能表单的下拉搜索框搜索无效

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#218]
##### 截图&代码：
![微信图片_20221105172345](https://user-images.githubusercontent.com/35988128/200113121-65d2ae7a-8e72-4539-ad0b-081c297df0d6.png)
![微信图片_20221105172349](https://user-images.githubusercontent.com/35988128/200113124-ff7f3927-b936-4d67-8871-7c67e21102b0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 18612962616** [comment]
> 角色下拉，用的可不是下拉搜索组件，只是下拉组件

我是拿用户管理下的角色下拉举例子，其他我通过online生成的新页面的下拉搜索组件也是不能用的，都是下拉搜索组件(下拉组件是不允许输入的)，几天前都是可用的
![微信图片_20221106172034](https://user-images.githubusercontent.com/35988128/200163166-9e86b60e-e65a-43b8-adcd-b10124faec34.png)
![微信图片_20221106172038](https://user-images.githubusercontent.com/35988128/200163171-1ff97c8f-ad81-4657-ac5f-2116dfd2c04f.png)

**Comment by zhangdaiscott** [comment]
角色下拉，用的可不是下拉搜索组件，只是下拉组件

**Comment by 18612962616** [comment]
> 角色下拉，用的可不是下拉搜索组件，只是下拉组件

补充：我将J-search-select标签添加async="true" 改为异步是可以搜索的，但效率明显慢，本地过滤是失效的，不确定是哪天的commit导致的

**Comment by acmesimple** [comment]
弃坑吧 满地bug

**Comment by zhangdaiscott** [comment]
修复了，请更新代码
