### ISSUE TITLE
执行jarn install出现了错误npm ERR! gifsicle@5.3.0 postinstall: `node lib/install.js`

### ISSUE THREAD

**Issue by cnmit** [jeecgboot/jeecgboot-vue3#219]
版本号：

node.js 版本v12.13.1
yarn 版本1.21.1
代码github：下载的jeecgboot-vue3-3.4.3.zip

问题描述：
按照教程下载的jeecgboot-vue3-3.4.3.zip解压后cd 到jeecgboot-vue3-3.4.3目录下执行jarn install出现了错误提示如下：
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@5.3.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1

截图&代码：

![image](https://user-images.githubusercontent.com/3706327/200173230-09e01236-eaba-426e-b2f8-4f2bc92acb0f.png)

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2426559
3
