### ISSUE TITLE
主页右上角锁屏解锁bug

### ISSUE THREAD

**Issue by walkTtalk** [jeecgboot/jeecgboot-vue3#220]
##### 版本号：
3.4.3

##### 问题描述：
点击右上角锁屏没有问题，点击解锁出现dayjs调用错误

##### 截图&代码：
useNow.ts:37 Uncaught (in promise) TypeError: localData.meridiem is not a function
    at update (useNow.ts:37:32)
    at start (useNow.ts:41:5)
    at useNow.ts:51:18
![image](https://user-images.githubusercontent.com/20769982/200179706-79bec54a-ae3a-4bd6-9d32-f6f31b09a23d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个问题修复过了，更新最新代码
