### ISSUE TITLE
online代码自动生成级联问题

### ISSUE THREAD

**Issue by shiyongcui** [jeecgboot/jeecgboot-vue3#221]
##### 版本号：
3.4.2

##### 问题描述：
online表单，选择联动组件，功能测试联动组件出不来

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55284347/200211817-3723b4eb-1e6b-4484-996e-c2da9250b75c.png)
![image](https://user-images.githubusercontent.com/55284347/200212044-423d4b24-faec-4438-9b74-ea51eacec837.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by acmesimple** [comment]
弃坑吧   满地bug

**Comment by zhangdaiscott** [comment]
有些控件是给online在线使用的，代码生成器并不支持生成
https://github.com/jeecgboot/jeecg-boot/issues/3689
