### ISSUE TITLE
原则上不会限制任何代码用于商用？

### ISSUE THREAD

**Issue by icoco** [jeecgboot/jeecgboot-vue3#222]
##### 问题描述：
关于
[jeecgboot-vue3](https://github.com/jeecgboot/jeecgboot-vue3) 是一个基于Vue3.0、Vite、 Ant-Design-Vue 、TypeScript 的后台解决方案，目标是为中大型项目开发,提供现成的开箱解决方案及丰富的示例,原则上不会限制任何代码用于商用。

请问，vue3 以及相关后台，收费可商用？

谢谢！

**Comment by zhangdaiscott** [comment]
apache开源协议，可以商用，但是不得基于该平台软件的基础，修改包装成一个与JeecgBoot平台软件功能类似的产品进行发布、销售，或与JeecgBoot参与同类软件产品市场的竞争。


具体看这个

https://github.com/jeecgboot/jeecg-boot/blob/master/LICENSE
