### ISSUE TITLE
VUE3 3.4.3版本 online报表参数无效

### ISSUE THREAD

**Issue by chendejiang2018** [jeecgboot/jeecgboot-vue3#225]
##### 版本号：

3.4.3
##### 问题描述：

online报表参数无效
##### 截图&代码：

url中传输的参数，在online报表中未获取到

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新到最新版本，最近处理过

**Comment by chendejiang2018** [comment]
> 更新到最新版本，最近处理过

刚刚更新代码，测试过，BUG依然存在

**Comment by zhangdaiscott** [comment]
补充详细如何使用的，图文并茂

**Comment by zhangdaiscott** [comment]
测试无问题
![image](https://user-images.githubusercontent.com/3162115/200714648-71f619df-b381-474f-9fe5-fe28a78a905a.png)

**Comment by chendejiang2018** [comment]
教程中的例子
select name,age,birthday,sex from demo where sex='${sex}'


***@***.***
 
发件人： JEECG
发送时间： 2022-11-09 09:32
收件人： jeecgboot/jeecgboot-vue3
抄送： chendejiang2018; Author
主题： Re: [jeecgboot/jeecgboot-vue3] VUE3 3.4.3版本 online报表参数无效 (Issue #225)
测试无问题

**Comment by chendejiang2018** [comment]
> 测试无问题 ![image](https://user-images.githubusercontent.com/3162115/200714648-71f619df-b381-474f-9fe5-fe28a78a905a.png)

教程中的例子
select name,age,birthday,sex from demo where sex='${sex}'
问题依然存在，今天刚更新的代码，sex无论url传什么参数，都不起作用，取的依然是默认值
![image](https://user-images.githubusercontent.com/38061831/200720111-dd7b1ba6-c69f-4748-9bbc-67aab34123d7.png)
![image](https://user-images.githubusercontent.com/38061831/200720112-a4fa4bf8-4348-4c86-98d1-54fb471359a8.png)
![image](https://user-images.githubusercontent.com/38061831/200720352-6a062ced-4513-4b17-95cc-ae0e89dc697a.png)

**Comment by chendejiang2018** [comment]
全部删除本地代码，重新git clone，重新install ，浏览器缓存清除
问题依然存在



***@***.***
 
发件人： JEECG
发送时间： 2022-11-09 11:01
收件人： jeecgboot/jeecgboot-vue3
抄送： chendejiang2018; Author
主题： Re: [jeecgboot/jeecgboot-vue3] VUE3 3.4.3版本 online报表参数无效 (Issue #225)
确认保证前后端代码都更新到最新，并且重新install

**Comment by zhangdaiscott** [comment]
已修复升级依赖

```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>hibernate-re</artifactId>
  <version>3.4.3-GA2</version>
</dependency>
```
