### ISSUE TITLE
JSelectMultiple搜索问题

### ISSUE THREAD

**Issue by zhengjiahaowork** [jeecgboot/jeecgboot-vue3#227]
##### 版本号：
3.4.3-GA

##### 问题描述：
1、JSelectMultiple无法搜索
2、默认文字好像颜色有点不一样

##### 截图&代码：
1、![动画1](https://user-images.githubusercontent.com/68040559/200720934-26a41441-5e51-4936-8a33-aec498672bb6.gif)

2、
![image](https://user-images.githubusercontent.com/68040559/200721086-50c619ff-d4aa-4233-9aaf-388eeaf05cf8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
昨天修复了，更新

**Comment by zhengjiahaowork** [comment]
@zhangdaiscott 拜托我这个就是最新的代码，两个问题都在的

**Comment by zhangdaiscott** [comment]
昨天刚提交的代码，你什么时候下载的

**Comment by zhengjiahaowork** [comment]
> 昨天刚提交的代码，你什么时候下载的
> 
> [a9aadae](https://github.com/jeecgboot/jeecgboot-vue3/commit/a9aadae545b62fad05908e3b97edca005861f6c3)

我寻思提交的记录也不是我说的这个组件啊

**Comment by zhengjiahaowork** [comment]
还有第二个问题，下拉的默认消息提示颜色比正常的深多了

**Comment by zhangdaiscott** [comment]
？

**Comment by zhengjiahaowork** [comment]
> ？
昨天那个提交的记录修复的是JSearchSelect组件，我说的是JSelectMultiple组件

**Comment by zhengjiahaowork** [comment]
![image](https://user-images.githubusercontent.com/68040559/200750947-d04deba2-4691-45a5-8011-edf28e844a9d.png)
还有这两种默认提示的文字颜色都不一样是什么情况，我这个截图是官方演示地址截来的

**Comment by zhangdaiscott** [comment]
这个效果是antd的，不是我们做的
下拉搜索更新代码，已处理

**Comment by zhengjiahaowork** [comment]
> 这个效果是antd的，不是我们做的 下拉搜索更新代码，已处理

@zhangdaiscott 麻烦gitee同步下

**Comment by zhengjiahaowork** [comment]
@zhangdaiscott 
![image](https://user-images.githubusercontent.com/68040559/200770336-bc664e25-73d6-48a5-83ed-66d90a92f621.png)
好像还是报错

**Comment by zhangdaiscott** [comment]
你截图用的不是这个组件

**Comment by zhengjiahaowork** [comment]
> 你截图用的不是这个组件

不对把，我看了提交记录改的都是JDictSelectTag这个组件的，JSelectMultiple这个组件我寻思也没修复啊

**Comment by zhengjiahaowork** [comment]
@zhangdaiscott 你搞错了把，我一直说的是JSelectMultiple这个组件的搜索有问题
