### ISSUE TITLE
经常报错 Cannot access 'pageWrapper' before initialization 卡死，只能重启

### ISSUE THREAD

**Issue by zzb8** [jeecgboot/jeecgboot-vue3#229]
##### 问题描述：
     经常出现这个报错 Cannot access 'pageWrapper' before initialization
    然后卡死，只能重启

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20678480/201010935-246ea957-f777-4847-8d31-0682b81d2034.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你升级到最新看看，这个错一般是antd底层依赖与外面不兼容导致

**Comment by zzb8** [comment]
> 你升级到最新看看，这个错一般是antd底层依赖与外面不兼容导致

首次加载慢如何优化？

**Comment by zhangdaiscott** [comment]
你的首屏需要多久


http://vue3.jeecg.com/2426559

**Comment by zhangdaiscott** [comment]
刚刚提了补丁升级vite3

https://github.com/jeecgboot/jeecgboot-vue3/commit/3c3353da4fb828f50806056085af933fc3c76e9a

**Comment by zzb8** [comment]
> 你的首屏需要多久
> 
> http://vue3.jeecg.com/2426559

![image](https://user-images.githubusercontent.com/20678480/201571277-203fb4eb-7759-4b48-b70e-db4f819e1929.png)

求助，如何优化

**Comment by zhangdaiscott** [comment]
不太清楚，重启就好了
