### ISSUE TITLE
添加外部菜单动态参数该如何处理

### ISSUE THREAD

**Issue by leohao1018** [jeecgboot/jeecgboot-vue3#23]
##### 问题描述：
添加外部链接，如果链接中有些参数是动态的，该如何配置;比如：http://vue3.jeecg.com/2398845
最后 2398845 这个参数是动态；

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
如果配置参考，你只能传递当前系统已有的变量，比如token，其他的得自己根据需求 扩展

`{{ window._CONFIG['domianURL'] }}/bigscreen/#?token=${token}`

![image](https://user-images.githubusercontent.com/3162115/161879490-f8804449-08d9-4e01-bf06-4c49d755bd14.png)
