### ISSUE TITLE
搜狗浏览器下固定列显示bug

### ISSUE THREAD

**Issue by ruchonggithub** [jeecgboot/jeecgboot-vue3#230]
##### 版本号：
3.4.2

##### 问题描述：
在搜狗浏览器，固定列不能被正确识别。
另外：相同代码，在edge和chrome下运行正常。

##### 截图&代码：
代码：
![image](https://user-images.githubusercontent.com/54145659/201049676-68ba0f91-2a42-435d-a83b-5d38fd4bc3da.png)
正确效果：
![image](https://user-images.githubusercontent.com/54145659/201049952-af79a757-0a05-49f4-9a3c-a4091dfcffc5.png)
错误效果：
![image](https://user-images.githubusercontent.com/54145659/201049854-c34dc9a6-4d77-4a23-9800-d9e0db3a929c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
搜狗的哪个版本？内核用的什么

**Comment by ruchonggithub** [comment]
搜狗官网下载的最新稳定版，Chromium内核

**Comment by zhangdaiscott** [comment]
截图看版本号

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
使用搜狗浏览器11 未测出

**Comment by 1298191366** [comment]
使用搜狗浏览器11本地测试未复现，你用的是`useListPage`还是`useTable`表格组件，这两个我都没测出来，如有详细步骤请回复
![}MYODXF`8VZGZQ01386%AML](https://user-images.githubusercontent.com/30997828/201930710-24ac1178-77f3-4e1e-91fb-7400c8f81399.png)
