### ISSUE TITLE
"version": "3.4.3" 换肤功能无效

### ISSUE THREAD

**Issue by Dora-L** [jeecgboot/jeecgboot-vue3#236]
##### 版本号：
"version": "3.4.3"

##### 问题描述：
换肤无效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34502036/201622242-0d853eb4-c93b-4469-9b06-4f55e26d8c9e.png)

**Comment by zhangdaiscott** [comment]
你指的是换主题？

**Comment by zhangdaiscott** [comment]
已修复
