### ISSUE TITLE
必看常见问题

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecgboot-vue3#24]
1、官方网站
http://www.jeecg.com
2、在线文档
http://vue3.jeecg.com/2398845
3. 入门教程视频
https://www.bilibili.com/video/BV1V34y187Y9

**Comment by qsyj** [comment]
**版本号：**
3.4.4
**问题描述**
1.Oneline表单开发，页面属性->控件类型-->下拉搜索框
2.Oneline表单功能测试-->新增，弹出表单后，点击下拉搜索框，下拉搜索框的数据无法滚动
**截图&代码：**
![Uploading 1670552727433.jpg…]()

![1670553341129](https://user-images.githubusercontent.com/16165991/206611239-0a04e362-0fd2-4329-b564-5bc9d3473034.jpg)
