### ISSUE TITLE
打完包后，上传功能无法使用了

### ISSUE THREAD

**Issue by jhonboHou** [jeecgboot/jeecgboot-vue3#240]
##### 版本号：
v3.4.0

##### 问题描述：

打完包后，上传组件无法使用，不打包正常
##### 截图&代码：
异常信息：
![image](https://user-images.githubusercontent.com/49391942/201822453-1921445a-267b-4262-94c6-9c9a4203b7d9.png)
代码：
![image](https://user-images.githubusercontent.com/49391942/201822525-d1dc7d74-113a-4349-bf9a-77dc94c1295c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
老版本，我们不好处理，你可以下载最新版看是否有问题。没问题可以尝试更新

**Comment by jhonboHou** [comment]
生产环境关闭mock就可以了
