### ISSUE TITLE
vue3启动报错

### ISSUE THREAD

**Issue by fangliang12** [jeecgboot/jeecgboot-vue3#241]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/41010401/201886656-db060947-4a8d-4d8e-b4e2-9770fca1c10e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
依赖安装有问题，用的是官方的lock吗

**Comment by fangliang12** [comment]
> 依赖安装有问题，用的是官方的lock吗

都是直接git上面拉下来的，然后pnpm install安装的

**Comment by fangliang12** [comment]
> 依赖安装有问题，用的是官方的lock吗

安装依赖的时候没有报错，都是很正常的

**Comment by zhangdaiscott** [comment]
[Node.js](http://nodejs.org/) 版本要求Node 14.18+ / 16+ 版本以上，不再支持 Node 12 / 13 / 15。
https://blog.csdn.net/weixin_42164539/article/details/126312929

**Comment by fangliang12** [comment]
> [Node.js](http://nodejs.org/) 版本要求Node 14.18+ / 16+ 版本以上，不再支持 Node 12 / 13 / 15。 https://blog.csdn.net/weixin_42164539/article/details/126312929

我node是14.15.5，是不是因为这个版本，我升级下试试
