### ISSUE TITLE
“用户选择”控件的单选控制没有效果

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#242]
##### 版本号：
3.4.3 前端Vue3

##### 问题描述：
“用户选择”和“部门选择”控件可以通过扩展参数中配置“{"multiSelect":false}”实现单选控制，但是现在部门选择时可以的，用户选择则没有控制住，仍然可以多选。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/36326638/201898339-9ec26197-5220-430e-9c70-c2ecbdbbfce5.png)
![image](https://user-images.githubusercontent.com/36326638/201899175-ad36d23b-d9dd-4efa-9567-6171519ebc2b.png)
部门选择控件可以控制的。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前测本地无问题，待新版发布看看

**Comment by gxzhou** [comment]
好的
