### ISSUE TITLE
JSwitch组件直接使用了 props 中定义的value，vue3应该不支持这样的写法吧

### ISSUE THREAD

**Issue by mrhuangyong** [jeecgboot/jeecgboot-vue3#243]
##### 版本号：
3.4.3

##### 问题描述：
JSwitch组件直接使用了 props 中定义的value，启动报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20205636/202078325-07d98b97-53d8-4188-a39f-a07800ca0e73.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/235
