### ISSUE TITLE
1.online表单开发、2.积木报表集成

### ISSUE THREAD

**Issue by youliliang** [jeecgboot/jeecgboot-vue3#244]
##### 问题描述：
1.online表单开发，查询配置，选下拉搜索框，取数据库表单-字段，会把本字段内重复的值取出，看到说明里写到只显示不同值，这种问题怎么设置下，只想要不同的值。图1、2
![1](https://user-images.githubusercontent.com/118331143/202092274-1813859a-9055-4466-a915-01df33f64627.jpg)
![2](https://user-images.githubusercontent.com/118331143/202092278-a01d9435-7bc3-455c-8c46-e214e62b8e07.jpg)

2.积木报表集成，按说明配置，{{ window._CONFIG['domianURL'] }}，配置好后，打不开需要的路径，并且路径是错的，没解析出来。请问怎么修改？图3、5
![5](https://user-images.githubusercontent.com/118331143/202092198-1eba4251-a9ff-45c9-ba4b-9c2d6fda091e.jpg)
![3](https://user-images.githubusercontent.com/118331143/202092193-bfb56744-d104-434b-8479-9b3c567f0a3a.jpg)

**Comment by youliliang** [comment]
1.如果想过滤数据，我应该怎么设置下
2.没明白哪里错了，我也是看说明文档设置的。没带token？

**Comment by youliliang** [comment]
1.如果想过滤数据，我应该怎么设置下
2.没明白哪里错了，我也是看说明文档设置的。没带token？我试过了。
请指教，感谢
![4](https://user-images.githubusercontent.com/118331143/202095469-f0a39713-b88f-4c7d-9f9d-3a2069be4881.jpg)

**Comment by zhangdaiscott** [comment]
1、可以用popup控件，online报表写sql

http://vue3.jeecg.com/2765988#3_Popup_39

2、菜单配置错误，仔细看文档，参数填错

**Comment by youliliang** [comment]
问题2，是真不知道哪错啦，修改无数遍了。说明文档是view里，我这个积木就在index里，路径没错把
![6](https://user-images.githubusercontent.com/118331143/202098328-194030d1-a2c8-4773-a30c-13e9fd8fd965.jpg)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/202108399-3cbeab4e-3fd2-43c2-8f61-8a92f73bbf46.png)

**Comment by youliliang** [comment]
这是vue3，主要是没在说明文档看到这个啊，文档还是vue2 的。可以更新一下啦。感谢，系统开发很不错，加油，牛

**Comment by youliliang** [comment]
这是vue3，主要是没在说明文档看到这个啊，文档还是vue2 的。例子可以看到，才看见，不好意思。可以更新文档一下啦。感谢，系统开发很不错，加油，牛
