### ISSUE TITLE
表格的宽度无法像vue2 那样，根据每列最长内容自适应宽度

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecgboot-vue3#245]
##### 版本号：

最新版本
##### 问题描述：
表格的宽度无法像vue2 那样，根据每列最长内容自适应宽度

##### 截图&代码：
这是vue3的
![image](https://user-images.githubusercontent.com/24811278/202378928-b914e8ed-d746-4289-8841-ec38bf7cc0cd.png)

这是vue2的
![image](https://user-images.githubusercontent.com/24811278/202379002-3480d4e2-c8e8-42a2-ae8e-155976246c1f.png)

效果要像vue2一样，按照最长的内容来适应宽度

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
截全了看看

**Comment by jinbear** [comment]
![image](https://user-images.githubusercontent.com/24811278/202387348-f8828b9e-52ce-424a-af81-f371672f71a4.png)
出现省略号
![image](https://user-images.githubusercontent.com/24811278/202387479-31851329-586b-4ba7-a073-a89137b090a1.png)
全部显示内容

**Comment by zhangdaiscott** [comment]
改成false看看
![image](https://user-images.githubusercontent.com/3162115/202397890-3ddbf4d8-7447-48cc-b1fe-64e4cd3987fe.png)
