### ISSUE TITLE
主子表，子表弹窗“新增”功能存在问题，配置的控件默认值均未取用

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#246]
##### 版本号：
3.4.3 前端vue3

##### 问题描述：
子表弹窗“新增”时，配置的控件默认值均没有取用。而且，表单输入信息并保存后，有某些字段的数据没有保存下来的情况。

##### 截图&代码：
![1668669636015](https://user-images.githubusercontent.com/36326638/202381659-7cdb2b46-13b8-4140-844a-7ceaa1fd7ef3.png)
![1668669130009](https://user-images.githubusercontent.com/36326638/202380663-1fef1a5a-ddda-4483-aac6-649c2bced3f9.png)
正常“新增”应该是这样的：
![1668669931367](https://user-images.githubusercontent.com/36326638/202382580-d53b6026-772a-483e-b0f1-790c2597aca9.png)
online配置：
![1668670039209](https://user-images.githubusercontent.com/36326638/202382952-f0a6d31f-473c-4357-b381-082fff1eeb17.png)

弹窗“新增”输入数据，JS增强是起作用的，但是保存后数据不完整：
![1668670423758](https://user-images.githubusercontent.com/36326638/202384308-842b93de-aefb-4e8a-ab6f-147aa3d0ce48.png)
![1668670671759](https://user-images.githubusercontent.com/36326638/202385010-e1f50604-a992-4aaf-9e7b-244995ab0b12.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
弹窗新增默认值设置问题 已修改
弹窗新增js增强不走主表的配置，需要单独在子表上配置，配置规则同单表的配置，即将其当成一个单表配置js增强
弹窗新增输入数据，无法回填到子表table上的问题 经测试不存在

**Comment by gxzhou** [comment]
> 弹窗新增默认值设置问题 已修改 弹窗新增js增强不走主表的配置，需要单独在子表上配置，配置规则同单表的配置，即将其当成一个单表配置js增强 弹窗新增输入数据，无法回填到子表table上的问题 经测试不存在

需要怎样做才能使用到您修改过的版本？
另外，您说“弹窗新增输入数据，无法回填到子表table上的问题经测试不存在”，我怕是因为我本地下载安装的版本有问题导致，故而今天使用官方vue3演示版模拟主子表做了一下，问题明显是存在的，过程如下：
1、创建主子表单logi_order_info和logi_order_line,如下：
![1669087090113](https://user-images.githubusercontent.com/36326638/203212870-8d126375-0ffa-4bb5-ac69-7633d782142a.png)
![1669087162221](https://user-images.githubusercontent.com/36326638/203213054-ee46cd2a-e0b6-43fb-a9b1-be1d9e40e230.png)
![1669087272238](https://user-images.githubusercontent.com/36326638/203213261-8be6b036-9064-47b7-ad9d-45bfe73d9108.png)
2、主子表的JS增强：
![1669087417910](https://user-images.githubusercontent.com/36326638/203213529-78164650-1a3b-4972-b193-d4b93f3e10bc.png)
![1669087543585](https://user-images.githubusercontent.com/36326638/203213840-e2b7ad38-7a4d-4539-a4e6-574b6ca19c2a.png)
3、目前子表有3填记录，下一步演示“弹窗新增”一条记录的过程：
![1669086704580](https://user-images.githubusercontent.com/36326638/203212752-206100ed-a674-49d7-8442-478494b6273b.png)
弹窗新增：
![1669088085766](https://user-images.githubusercontent.com/36326638/203215014-dff78092-1807-43d5-a30a-7052aa425ff5.png)
点击“确定”后，新增了一行记录，但是请注意看，其中的数据与上图不一样了，说明回填有问题：
![image](https://user-images.githubusercontent.com/36326638/203215859-57a5b78f-87d6-42c0-a9b7-c8b522bc3959.png)

**Comment by fireinjava** [comment]
> 收录 ty

这个弹窗新增建议换个图标，看着像是复制...
