### ISSUE TITLE
可编辑表格可否根据前面的某个固定数据做修改

### ISSUE THREAD

**Issue by 850817673** [jeecgboot/jeecgboot-vue3#247]
##### 问题描述：
前面的  长  是写死的数据，后面的  默认值  通过这个  长或者其他的值   来实现动态   editComponent

##### 截图&代码：
![微信图片_20221117171735](https://user-images.githubusercontent.com/52116507/202405840-ea3b918b-63d9-4453-918f-81c707ca3b1e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个自己写js 实现
