### ISSUE TITLE
Vue3原生代码, 表单内使用图片组件,关闭弹窗图片组件值不会被清空

### ISSUE THREAD

**Issue by cl1169451697** [jeecgboot/jeecgboot-vue3#248]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/47232009/202625803-ae517b80-ed11-46ea-9afe-729512b1f144.png)

##### 自己的解决方法:
![image](https://user-images.githubusercontent.com/47232009/202626649-68de4b5e-89f4-4171-be12-51e79f9931e1.png)

![image](https://user-images.githubusercontent.com/47232009/202626341-701e5c78-4cac-40b9-8089-c00676711abd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
