### ISSUE TITLE
热更新的问题

### ISSUE THREAD

**Issue by leohao1018** [jeecgboot/jeecgboot-vue3#25]
##### 问题描述：
生成的基础增删改查页面，配置菜单后能正常访问，本地开发的情况下，修改 .ts 文件无法热更新，需要手工yarn run serve ，然后刷新网页才能更新；和浏览器有没有关系

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by YANGHAOHEHE** [comment]
开两个终端，一个tsc -w
