### ISSUE TITLE
列表查询-下拉框选择值后都不会自动触发执行查询

### ISSUE THREAD

**Issue by BruceOuyang** [jeecgboot/jeecgboot-vue3#253]
版本号：
3.4.3

前端版本：vue3版？还是 vue2版？
vue3

问题描述：
代码生成生成的代码，任意字典类型的下拉字段设为查询条件，选择值后都不会自动触发执行查询。

截图&代码：
代码生成生成的代码

友情提示（为了提高issue处理效率）：
未按格式要求发帖，会被直接删掉;

**Comment by zhangdaiscott** [comment]
没实现自动触发，需要的话，自己写js 事件
