### ISSUE TITLE
3.4.4版本官网演示online报表主题模板无法选择

### ISSUE THREAD

**Issue by zouxuyang** [jeecgboot/jeecgboot-vue3#255]
##### 版本号：
3.4.4

##### 问题描述：
online报表主表主题模板无法选择

##### 截图&代码：
![image](https://user-images.githubusercontent.com/57665992/203004604-91091936-81ba-4274-8b55-1f99d75d014a.png)

**Comment by zhangdaiscott** [comment]
目前vue3 暂时只支持一套模板
