### ISSUE TITLE
接口一直在重试

### ISSUE THREAD

**Issue by Greax** [jeecgboot/jeecgboot-vue3#257]
##### 版本号：
3.4.4

##### 问题描述：
访问的官方demo网站http://boot3.jeecg.com/ token失效访问后，退回到login页面，但接口一直在访问

##### 截图&代码：
<img width="601" alt="image" src="https://user-images.githubusercontent.com/3661671/203022164-c0572d4d-ded1-40c0-9aee-60310df41b17.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个不影响，是一个定时任务
