### ISSUE TITLE
npm run dev: Cannot find module 'node:path

### ISSUE THREAD

**Issue by wangmengyang0504** [jeecgboot/jeecgboot-vue3#258]
##### 版本号：
3.4.4
##### 问题描述：

npm run dev: Cannot find module 'node:path
##### 截图&代码：

![image](https://user-images.githubusercontent.com/96861314/203201038-cabcab7d-8fc6-42dc-ac43-5e3855434b25.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
删除依赖


```
# 安装依赖
pnpm install

# 运行项目
pnpm dev
```

**Comment by wangmengyang0504** [comment]
> 

不能够解决，依然是这个问题，怀疑是node版本问题，现node版本为 14.15

**Comment by zhangdaiscott** [comment]
[Node.js](http://nodejs.org/) 版本要求Node 14.18+ / 16+ 版本以上，不再支持 Node 12 / 13 / 15。
必须使用[Yarn1.x](https://yarnpkg.com/)，否则依赖可能安装不上。
