### ISSUE TITLE
iframe 打开本地目录html文件无效问题。急急急急！！！！！

### ISSUE THREAD

**Issue by luo969** [jeecgboot/jeecgboot-vue3#261]
##### 问题描述：最新3.4.4版本的。iframe 配置src 为本地路径的html。无法打开，直接跳转回首页。

旧的v1.2.0 | Vue3前端UI 2022-06-06 的版本就可以正常打开。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/15951772/203685590-1b97e16c-961c-4ffb-992f-59d02c2c9399.png)
就直接调回首页，如下图
![image](https://user-images.githubusercontent.com/15951772/203685801-14bf0c24-a142-4ef7-b475-0de56701050d.png)
![image](https://user-images.githubusercontent.com/15951772/203685847-37f22b95-1856-4b99-9b3c-ce70e858aaad.png)

测试的index2.html的本地路径和Index.html同级
![image](https://user-images.githubusercontent.com/15951772/203686674-9148c409-3a79-46fd-a4bd-7c1722c703cf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没这么用的，你可以看看是不是升级vite导致的

**Comment by luo969** [comment]
我试试用1.2.0对应的VITE版本看看，因为我们有个第三方的WEB控件，只能在没有任何你们样式的html页面上才可以正常使用，在你们的框架上使用，就样子全部变样了。所以需要在frame内嵌一个的独立html页面使用。

**Comment by luo969** [comment]
3.4.4版本将了VITE 版本，有引发其他问题。我测试了。1.2.0版本的可以直接访问http://localhost:3100/index2.html。但是到了3.4.4版本就不可以，就直接返回首页了。是不是1.2.0之后的版本对html访问做了什么过滤和限制了？

**Comment by zhangdaiscott** [comment]
没有

**Comment by luo969** [comment]
1.2.0版本的 index2.html 发起程序是其他
![image](https://user-images.githubusercontent.com/15951772/203760138-018ca82e-159a-4e2f-a2f1-3f8a17a2b65c.png)

**Comment by luo969** [comment]
但是3.4.4版本的index2.html 发起程序 是vite什么的。是为什么呢？

**Comment by zhangdaiscott** [comment]
这个你去研究vite3 我们没做任何处理

**Comment by zhangdaiscott** [comment]
无回复，关闭

**Comment by axinger** [comment]
@luo969 你解决了吗? 我也遇到这个问题了
