### ISSUE TITLE
更新到从3.4.3更新到最新代码3.4.4出现，所有界面用到updateSchema失效

### ISSUE THREAD

**Issue by GitACDreamer** [jeecgboot/jeecgboot-vue3#264]
##### 版本号：
3.4.4

vue: 3.2.44
ant-design-vue: 3.2.14
vite: 3.2.4

其中我也做了将官方的package.json覆盖我的，重新编译发现问题还是存在

##### 问题描述：
更新到最新代码出现所有地方使用到updateSchema，控制form字段都无效果，其中包括不限于：用户管理，部门管理等

##### 截图&代码：
用户管理 userDrawer 密码并不隐藏
![image](https://user-images.githubusercontent.com/19402747/203925900-ddc6b3c9-8110-421a-a67f-b56637611dc2.png)
![image](https://user-images.githubusercontent.com/19402747/203925799-b5b058c1-772d-4c1d-b768-9c2f236498dc.png)
调试代码（第一个图有console打印，发现isUpdate.value = false ,他并不会隐藏）
![image](https://user-images.githubusercontent.com/19402747/203926462-1def3dec-3d61-42b1-b353-20336052e78f.png)

部门管理DepartFormTab中的 updateSchema
![image](https://user-images.githubusercontent.com/19402747/203926640-57296c48-bb7a-4e39-ba73-6fdfeb6572d5.png)
![image](https://user-images.githubusercontent.com/19402747/203926990-839d1e3d-5834-4a37-9230-43bc10c0e789.png)

**其他的模块我也测试了，发现updateSchema失效了。**

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你直接下载我们的master版本看看是否存在问题
不存在，就是你升级不彻底

**Comment by zhangdaiscott** [comment]
无回复，关闭
