### ISSUE TITLE
打包后接口访问404，打包和开发环境都是服务器的api地址，但是打包后无法请求

### ISSUE THREAD

**Issue by aivinli** [jeecgboot/jeecgboot-vue3#266]
##### 问题描述：
打包后接口访问404，打包和开发环境都是服务器的api地址，但是打包后无法请求

##### 截图&代码：
打包后 获取验证码接口图片
![image](https://user-images.githubusercontent.com/67623937/204078508-555c6161-ffd3-4094-8b97-dde5bb0b841f.png)
开发环境 获取验证码接口图片
![image](https://user-images.githubusercontent.com/67623937/204078706-508b8a39-f17c-40fb-8e60-d5057efe6577.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by aivinli** [comment]
打包后测试用的 live-server, nginx,tomcat,这个web环境都是404

**Comment by zhangdaiscott** [comment]
需要配置ngnix，配置了吗
http://vue3.jeecg.com/2503893
