### ISSUE TITLE
启动后，启动初始化页面时报错，依赖也已安装正常

### ISSUE THREAD

**Issue by 903249871** [jeecgboot/jeecgboot-vue3#267]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/14256585/204083591-7c61be10-fe76-4892-957d-6028dbb14f9f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/204084287-2630b0ff-52fd-468d-ac16-5d7fdbca0d3d.png)

怎么是这个版本？

**Comment by 903249871** [comment]
> 

不知道呀，我刚装完的pnpm，install完就这样了

**Comment by 903249871** [comment]
> ![image](https://user-images.githubusercontent.com/3162115/204084287-2630b0ff-52fd-468d-ac16-5d7fdbca0d3d.png)
> 
> 怎么是这个版本？

是合并的时候旧版本package.json新版本直接叠加进去了，但是git也没有报冲突，旧版本没删，换了之后就可以了
