### ISSUE TITLE
JVxeTbale  内容编辑数据回显时，序号和行内容错位

### ISSUE THREAD

**Issue by XiaoJian-CMYK** [jeecgboot/jeecgboot-vue3#269]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/57388318/204218684-e635a358-44aa-424d-a2a5-55d2ce309c57.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
目前没有遇到这个问题。
你是在`a-tabs`组件里面用的吗？如果是的话，给`a-tabs`组件加上`animated`参数试试。

![image](https://user-images.githubusercontent.com/34293221/205652187-9ddaedc3-748c-4a12-a136-a0693a80ba67.png)
