### ISSUE TITLE
BaseTable无法自适应高度

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/jeecgboot-vue3#270]
##### 版本号：
3.4.4

##### 问题描述：
BaseTable无法自适应高度，Vben原版是可以的

##### 截图&代码：
**jeecg：**
![image](https://user-images.githubusercontent.com/10290156/204223915-61598f8e-f140-461e-9270-a7c44efc057b.png)

**Vben原版：**
![image](https://user-images.githubusercontent.com/10290156/204223938-d4ca657b-edcb-4329-a627-6f81243f947b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by q060831** [comment]
同问。
问题大概出现在`src/components/Table/src/hooks/useTableScroll.ts`的67-70行，找不到表格的tbody.
```
    if (!bodyEl) {
     // 这里得到null 
      bodyEl = tableEl.querySelector('.ant-table-body');
      if (!bodyEl) return;
    }
```
貌似只有设置粘性头部和滚动条`sticky`才会有`ant-table-body`这个节点。

**Comment by lsqGitHub716** [comment]
新版测试暂未发现问题，请更新到最新版测试一下
