### ISSUE TITLE
多租户重新登录后清除缓存问题

### ISSUE THREAD

**Issue by Gq66** [jeecgboot/jeecgboot-vue3#272]
##### 版本号：
vue3

##### 问题描述：
切换租户后需要登录两次，重新登录后清除缓存问题

##### 截图&代码：
![@R2UYMEV$U93012D{X `%H9](https://user-images.githubusercontent.com/67729007/204424866-90821381-9480-4e81-95f5-a80d48e7afb9.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Gq66** [comment]
求告知~

**Comment by zhangdaiscott** [comment]
？

**Comment by Gq66** [comment]
> ？

你没有遇到过切换租户后，被退出后。登录出现问题吗

**Comment by zhangdaiscott** [comment]
没有，租户这块逻辑有问题，我们后面会重现提交一版

**Comment by Gq66** [comment]
> 

我这边按照csdn官网上改过。同一个用户切换完租户后，强退登录的话，就会报异常，要连续登录两次才可以成功登录。

**Comment by Gq66** [comment]
> 



> 没有，租户这块逻辑有问题，我们后面会重新提交一版

我这边按照csdn官网上改过。同一个用户切换完租户后，强退登录的话，就会报异常，要连续登录两次才可以成功登录。

**Comment by zhangdaiscott** [comment]
按哪个改的？

**Comment by Gq66** [comment]
> 按哪个改的？

https://blog.csdn.net/zhangdaiscott/article/details/119780074?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522166970488216800215044178%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=166970488216800215044178&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-119780074-null-null.142^v67^control,201^v3^control_1,213^v2^t3_esquery_v2&utm_term=jeecgboot%E5%A4%9A%E7%A7%9F%E6%88%B7&spm=1018.2226.3001.4187
这个jeecg官方博客

**Comment by Gq66** [comment]
> 按哪个改的？

https://blog.csdn.net/zhangdaiscott/article/details/119780074?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522166970488216800215044178%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=166970488216800215044178&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-119780074-null-null.142^v67^control,201^v3^control_1,213^v2^t3_esquery_v2&utm_term=jeecgboot%E5%A4%9A%E7%A7%9F%E6%88%B7&spm=1018.2226.3001.4187](https://blog.csdn.net/zhangdaiscott/article/details/119780074?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522166970488216800215044178%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=166970488216800215044178&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-119780074-null-null.142%5Ev67%5Econtrol,201%5Ev3%5Econtrol_1,213%5Ev2%5Et3_esquery_v2&utm_term=jeecgboot%E5%A4%9A%E7%A7%9F%E6%88%B7&spm=1018.2226.3001.4187)
这个jeecg官方博客

**Comment by Gq66** [comment]
> 按哪个改的？

登录的时候。有时候，tenantId默认拼接0。permission表里设置的都是1就很头疼

**Comment by zhangdaiscott** [comment]
你参考的方案并不好，我们正在改造，你可以参考下

https://my.oschina.net/jeecg/blog/5600947

**Comment by Gq66** [comment]
> 你参考的方案并不好，我们正在改造，你可以参考下
> 
> https://my.oschina.net/jeecg/blog/5600947

好的，那等版本更新吧，大概要多长时间呢
