### ISSUE TITLE
drop_console

### ISSUE THREAD

**Issue by kewab** [jeecgboot/jeecgboot-vue3#273]
##### 问题描述：
vite.config.ts文件里的`drop_console`为`true`打包之后发现并不能删掉console.log打印

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
已修复，下一个版本发布。当minify指定esbuild时，terserOptions选项不生效可删除，顶层对象加入esbuild: {drop: ['console', 'debugger']}即可。

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/u012733501/article/details/124883222
