### ISSUE TITLE
修改控件值从改主，运行报错

### ISSUE THREAD

**Issue by wangshihui** [jeecgboot/jeecgboot-vue3#274]
##### 版本号：
[v3.4.4](https://github.com/jeecgboot/jeecgboot-vue3/releases/tag/v3.4.4)

##### 问题描述：
功能：修改控件值，从改主
按照文档操作：控制台报错，debug发现that.$refs对象值为空

原文：
http://doc.jeecg.com/2186818
##### 截图&代码：
![code](https://raw.githubusercontent.com/wangshihui/images/main/jeecg/vue3/2022-1130/screenshot-20221130-170152.png)

runtime  debug

![code](https://raw.githubusercontent.com/wangshihui/images/main/jeecg/vue3/2022-1130/screenshot-20221130-170432.png)

debug console check

![code](https://raw.githubusercontent.com/wangshihui/images/main/jeecg/vue3/2022-1130/screenshot-20221130-170518.png)

**Comment by tygithub1** [comment]
vue3请参考文档： https://www.kancloud.cn/zhangdaiscott/vue3/2743577
