### ISSUE TITLE
自定义表单控件，如何发送数据给顶层表单呢？

### ISSUE THREAD

**Issue by siyu-deng** [jeecgboot/jeecgboot-vue3#276]
##### 版本号：

3.4.3
##### 问题描述：
封装新的自定义表单控件后，如何把自定义表单控件的数据，传递给顶层的表单呢？

##### 截图&代码：
<img width="259" alt="image" src="https://user-images.githubusercontent.com/72716606/204959150-d692cc61-f608-4ff7-9a67-e9f0126378bf.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/72716606/204959318-966301b7-3345-4db2-9671-3451d21fb408.png">

<img width="895" alt="image" src="https://user-images.githubusercontent.com/72716606/204959600-047a5b94-d9f8-445d-9b5b-228d0b5a9033.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
在fileChange事件里面加上 `emit('input', 要发送给顶层表单的数据)`
