### ISSUE TITLE
字段Href代码生成以后不生效

### ISSUE THREAD

**Issue by liuzhihong123** [jeecgboot/jeecgboot-vue3#277]
##### 问题描述：
字段Href代码生成以后不生效   功能测试的时候是可以的  生成代码以后不行了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49625917/205007132-a364e268-5b87-4eed-b9f7-a6942101fd9f.png)
![image](https://user-images.githubusercontent.com/49625917/205007201-11e4c32f-6ad9-4f12-852d-d16196799ab8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码生成不支持href生成，生成完代码，手工补充逻辑吧
