### ISSUE TITLE
打包后时间控件无法选择

### ISSUE THREAD

**Issue by mujun1209** [jeecgboot/jeecgboot-vue3#278]
##### 版本号：
3.4.3

##### 问题描述：
打包发布后时间控件无法选择

##### 截图&代码：
 <a-col :lg="8">
              <a-form-item label="到仓提货开始时间">
                <a-time-picker
                  placeholder="请输入到仓提货开始时间"
                  value-format="HH:mm:ss"
                  v-model:value="queryParam.pickTimeStart"
                  style="width: 100%"
                />
              </a-form-item>
            </a-col>

![image](https://user-images.githubusercontent.com/1551206/205542329-68577423-bfa0-493c-924d-bada98cfde8e.png)

点击时间选择组件后，组件就消失了。怀疑是有事件冲突了，日期选择也有相同问题。在本地开发启动不存在该问题。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
生成的代码？

F12看看有错没有

**Comment by mujun1209** [comment]
是生成的代码，选择的原生vue3 ;
  <a-col :lg="8">
              <a-form-item label="到仓提货开始时间">
                <a-time-picker
                  placeholder="请输入到仓提货开始时间"
                  value-format="HH:mm:ss"
                  v-model:value="queryParam.pickTimeStart"
                  style="width: 100%"
                />
              </a-form-item>
            </a-col>
没有报错， 怀疑是有全局的点击事件冲突；

**Comment by mujun1209** [comment]
> 生成的代码？
> 
> F12看看有错没有

是生成的代码，选择的原生vue3 ;
没有报错， 怀疑是有全局的点击事件冲突；
![image](https://user-images.githubusercontent.com/1551206/205544136-ec68cca5-6cd0-43af-a1f2-68a5b4c7b14a.png)

**Comment by zhangdaiscott** [comment]
你去看看我们官网演示环境例子有问题吗

**Comment by mujun1209** [comment]
> 生成的代码？
> 
> F12看看有错没有

> 你去看看我们官网演示环境例子有问题吗

刚去看了，官网演示里面没有问题；会不会有可能我本地环境的工具版本问题？特别是跟打包相关的

**Comment by mujun1209** [comment]
> > 生成的代码？
> > F12看看有错没有
> 
> > 你去看看我们官网演示环境例子有问题吗
> 
> 刚去看了，官网演示里面没有问题；会不会有可能我本地环境的工具版本问题？特别是跟打包相关的



> 你去看看我们官网演示环境例子有问题吗

找到问题了， 确实是打包方式的问题， yarn build 导致的； 换成了 pnpm 就好了。

**Comment by jiangyuhui0922** [comment]
生成代码选择的vue3    同样的问题
时间选择框点击后 组件就消失了
<img width="452" alt="image" src="https://user-images.githubusercontent.com/23249919/213107162-861eb51d-5cf7-425c-8cd9-59f63ae66de1.png">
改用pnpm打包还是不行
