### ISSUE TITLE
JVxeTable columns type=‘html’  功能不好使？

### ISSUE THREAD

**Issue by HALOUXGQ** [jeecgboot/jeecgboot-vue3#279]
##### 问题描述：
JVxeTable columns 列配置 type=‘html’ 会渲染成文字？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/112674198/205564375-afa47a62-04c3-48ed-9409-d3e5fc9b3768.png)
![image](https://user-images.githubusercontent.com/112674198/205564596-a0ee2f3f-e9c3-450c-9ceb-86385ce4c0a1.png)
![image](https://user-images.githubusercontent.com/112674198/205564552-5af3f240-5f2f-4e3e-b9af-7d248479a7ef.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by HALOUXGQ** [comment]
> jl

？

**Comment by HALOUXGQ** [comment]
@zhangdaiscott  ？

**Comment by HALOUXGQ** [comment]
> jl

？

**Comment by sjlei** [comment]
JVxeTable 没有支持该属性，可以使用`slot`解决
