### ISSUE TITLE
多租户的情况下，admin怎么能看到所有数据

### ISSUE THREAD

**Issue by Gq66** [jeecgboot/jeecgboot-vue3#281]
##### 版本号：
最新

##### 问题描述：
多租户的情况下，admin怎么能看到所有数据

##### 截图&代码：
![1670396240340](https://user-images.githubusercontent.com/67729007/206114712-d727ea73-e8e0-4883-826c-5b59234b31eb.jpg)
![image](https://user-images.githubusercontent.com/67729007/206114804-52346222-82ad-40a5-8b12-22be436b58e9.png)
![image](https://user-images.githubusercontent.com/67729007/206114841-7df778fc-a3ce-47a1-a6cb-1e32a5eb8368.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
有几个私聊
1、你单独写一个sql方法，加排除租户拦截 注解 `	@InterceptorIgnore(tenantLine = "true")`
2、采用硬编码方式实现数据隔离，不用默认的配置
