### ISSUE TITLE
可编辑行，只要点击查询后进行可编辑行编辑，点击保存会报数据错误

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecgboot-vue3#284]
##### 版本号：

3.4.3
##### 问题描述：
可编辑行，只要点击查询后进行可编辑行编辑，点击保存会报数据错误
![image](https://user-images.githubusercontent.com/24811278/206341865-68734ed4-d849-4a4f-bacc-68fedb49ad93.png)
原因是record里面的validCbs没有了
![image](https://user-images.githubusercontent.com/24811278/206341990-eb023eee-8229-48cd-a8d0-da2836bf4589.png)
正常的情况是这样：
![image](https://user-images.githubusercontent.com/24811278/206342112-133d3d18-79d7-41f5-8ad3-e0bfe8de28b4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
操作界面，截图再详细补充下

**Comment by jinbear** [comment]
![image](https://user-images.githubusercontent.com/24811278/206365234-fe749c3f-76a2-4004-a8f6-438ff4ffb196.png)
![image](https://user-images.githubusercontent.com/24811278/206365268-037f2f75-2518-4f22-816c-720894aa7c53.png)
![image](https://user-images.githubusercontent.com/24811278/206365285-24984438-4fa8-4084-974a-c9e1706e708c.png)
以上是页面加载完操作正常，但是一旦点击查询或者重置之后
![image](https://user-images.githubusercontent.com/24811278/206365392-de55b00c-248a-4efc-92dc-c3ff57d72d91.png)
![image](https://user-images.githubusercontent.com/24811278/206365456-dc85d390-4273-4615-861d-20974be27761.png)

**Comment by jinbear** [comment]
我编辑了，失败了，点击查询都不会覆盖我的数据
![image](https://user-images.githubusercontent.com/24811278/206367958-a0fda09d-3bf7-42f4-aa31-eecf0cb1e5f1.png)
![image](https://user-images.githubusercontent.com/24811278/206367989-cb6d0a1e-45b5-40e0-b886-100444dfcd07.png)
![image](https://user-images.githubusercontent.com/24811278/206368002-1f3e4da1-befe-453f-9373-6116224e1f36.png)

**Comment by zhangdaiscott** [comment]
你用的是我们哪个例子？为什么不用我们封装的行编辑组件 JVXETable
