### ISSUE TITLE
开关控件配置了扩展参数不可用

### ISSUE THREAD

**Issue by cocoamu** [jeecgboot/jeecgboot-vue3#285]
##### 版本号：
3.4.4

##### 问题描述：
在online表单上配置开关控件 ，字段数据库类型设置为int
在控件那边选择开关控件，配置了扩展参数[0,1]，进行功能测试的时候发现点击开关控件没反应

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
改成string类型看看
