### ISSUE TITLE
下拉搜索框问题

### ISSUE THREAD

**Issue by liuxiaofan** [jeecgboot/jeecgboot-vue3#286]
##### 版本号：
3.4.4

##### 问题描述：
在自动生成的`vue3`代码中，下拉搜索框，没办法输入，被出现的数据遮挡住了输入框。只有把页面最大化才能出现输入的地方

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8596255/206383026-6d3b3dce-66b9-469d-a65f-fb585a27e0fb.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lsqGitHub716** [comment]
请说明一下具体是哪一个组件，下拉搜索具体是指的是哪个

**Comment by lsqGitHub716** [comment]
已修改
