### ISSUE TITLE
下拉搜索框无法滚动

### ISSUE THREAD

**Issue by qsyj** [jeecgboot/jeecgboot-vue3#287]
**版本号：**
3.4.4
**问题描述**
1.Oneline表单开发，页面属性->控件类型-->下拉搜索框
2.Oneline表单功能测试-->新增，弹出表单后，点击下拉搜索框，下拉搜索框的数据无法滚动
**截图&代码：**
![1670552727433](https://user-images.githubusercontent.com/16165991/206611337-6e3f99e3-369f-4222-8f15-32c43eeab42d.jpg)

![1670553341129](https://user-images.githubusercontent.com/16165991/206611239-0a04e362-0fd2-4329-b564-5bc9d3473034.jpg)

_Originally posted by @qsyj in https://github.com/jeecgboot/jeecgboot-vue3/issues/24#issuecomment-1343765323_

**Comment by zhangdaiscott** [comment]
没做滚动，你可以输入查询
