### ISSUE TITLE
点击列表的操作栏查看显示的也是编辑

### ISSUE THREAD

**Issue by 490937333** [jeecgboot/jeecgboot-vue3#288]
##### 版本号：
3.4.3

##### 问题描述：
用户管理 - 列表-详情 点击后 抽屉头 显示的是编辑用户 ，同时用online生成的也都有这个问题 
没有对于查看的标题做处理

##### 截图&代码：
  //获取标题
  const getTitle = computed(() => (!unref(isUpdate) ? '新增用户' : '编辑用户'));  
![123](https://user-images.githubusercontent.com/78095446/206633650-3dc06107-9b3d-44a5-aa5a-8722432188d3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
如果需要，你可以参考角色的效果，自己写详情页面
![image](https://user-images.githubusercontent.com/3162115/206849099-26c60fde-c56a-46c8-8fb7-d3b6914739b6.png)
