### ISSUE TITLE
多菜单同时没有数据查询到会一直请求查询接口

### ISSUE THREAD

**Issue by zyy-zhangfaming** [jeecgboot/jeecgboot-vue3#290]
##### 版本号：
3.4.4

##### 问题描述：
多个菜单都没有数据的情况下。切换很快的时候。会一直调用查询接口

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41783339/206679392-6c816041-fa78-481a-a97a-3424038fa81e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
？
