### ISSUE TITLE
IDEA打开前端VUE3项目ts爆红怎么解决？？？

### ISSUE THREAD

**Issue by lm627691338** [jeecgboot/jeecgboot-vue3#296]
##### 版本号：
3.4.4

##### 问题描述：
IDEA打开前端VUE3项目ts爆红怎么解决，看着不舒服，不知道怎么去掉，求解决？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20734673/207536334-3ec9585b-324d-429b-bb80-268308c1790b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
关闭eslint 校验

**Comment by lm627691338** [comment]
> 关闭eslint 校验

eslint的关闭了还是报错啊

![image](https://user-images.githubusercontent.com/20734673/207569956-87b78a0f-77e7-465c-b579-85f1766a9526.png)
![image](https://user-images.githubusercontent.com/20734673/207570011-706223be-6a85-4737-abe8-fc1b6835d466.png)
