### ISSUE TITLE
低代码开发 table支持自定插槽吗？

### ISSUE THREAD

**Issue by 873485077** [jeecgboot/jeecgboot-vue3#300]
##### 版本号：
Ant Design Jeecg Vue  2.4.3

##### 问题描述：
online开发的自动生成的页面，可以支持表格自定义的插槽吗？例如title列，我想增加一个插槽，使文本转成<a>标签，或自定义文本颜色。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是说在线模式？还是生成的代码

**Comment by 873485077** [comment]
> 你是说在线模式？还是生成的代码

是在线模式，不是生成的代码，请问可以实现吗？

**Comment by zhangdaiscott** [comment]
在线不支持
