### ISSUE TITLE
Online报表，编辑修改后popup页面无变化，功能测试页面正常

### ISSUE THREAD

**Issue by HALOUXGQ** [jeecgboot/jeecgboot-vue3#301]
##### 问题描述：
Online报表，添加popup显示正常， 编辑修改后popup页面无变化，功能测试页面正常

##### 截图&代码：
正常
![image](https://user-images.githubusercontent.com/112674198/208010884-05a8f96a-ded5-496d-8a51-95fd108666cc.png)

没有变化
![image](https://user-images.githubusercontent.com/112674198/208011170-7fc4934a-fa63-4273-b9d7-86a533224f14.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by artfirst** [comment]
我也遇到差不多的问题，popup的页面不回显勾选状态，每次都要重新再选择

**Comment by zhangdaiscott** [comment]
编辑修改后popup页面无变化 ?

**Comment by zhangdaiscott** [comment]
无回复，关闭
