### ISSUE TITLE
sysAllDictItems 这个字典数据较多，登录超时反馈

### ISSUE THREAD

**Issue by 490937333** [jeecgboot/jeecgboot-vue3#303]
##### 版本号：

V3.4.3
##### 问题描述：
代码字典数据非常多，2w条左右已缓存到redis中，用户登录时获取到数据sysAllDictItems ，在动态引入组件时候循环 需要1-2分钟，导致登录页面在提示登录成功后 卡顿1-2分钟后才跳转到主界面

##### 截图&代码：
![5bd0b6061f6d38c206e8de5fa233869](https://user-images.githubusercontent.com/78095446/208375272-6cba3546-d0a6-4321-a0b4-6822e0efeb48.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
如果的确很大，可以改成异步加载，不再登录的时候一次性加载
