### ISSUE TITLE
表单配置，字段href

### ISSUE THREAD

**Issue by wenwan1** [jeecgboot/jeecgboot-vue3#304]
##### 版本号：
v3.4.4

##### 问题描述：
表单配置界面，字段href 采用内部组件出错，提示文件未找到

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
online不支持href
