### ISSUE TITLE
表单控制的label宽度如何设置

### ISSUE THREAD

**Issue by weidadong** [jeecgboot/jeecgboot-vue3#305]
##### 版本号：
jeecgboot-vue3，v3.4.4

##### 问题描述：
表单控件label的长度超过4个字会隐藏，请问如何设置可以显示全部的文字

##### 截图&代码：
![image](https://user-images.githubusercontent.com/64127503/208412149-40dc2313-27dc-4a14-ae20-20dfed18780b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by weidadong** [comment]
> 代码生成可以自定义宽度
在线表单（不生成代码）是不是不支持自定义宽度呢？

**Comment by zhangdaiscott** [comment]
在线模式不支持
