### ISSUE TITLE
表格表头自定义问题

### ISSUE THREAD

**Issue by JSON777818** [jeecgboot/jeecgboot-vue3#306]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/51874546/208570772-45c114b6-5118-4283-b643-f4b25da0cc92.png)

![image](https://user-images.githubusercontent.com/51874546/208570873-9e750dd0-dfa6-4436-8075-b4f20515b4f8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
他这个是异步的，不是动态不好使，你得让你的columns优先加载
