### ISSUE TITLE
退出登录功能失效，this.$confirm不起作用

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#308]
##### 版本号：
3.4.3 vue2

##### 问题描述：
“退出登录”点击后弹出确认框，但显示的信息把"title"和“content”也都显示出来了，点击“确定”按钮只是关闭弹出框，没有进入新的登录界面。
看程序代码都是没改变过的，会不会是某个组件的版本问题？
因为项目中要加入百度地图，需要安装相关的组件，安装过程中版本依赖关系各种方法解决，结果可以编译通过了，但发现这个confirm的地方就这样了。

##### 截图&代码：
![1671595559952](https://user-images.githubusercontent.com/36326638/208819951-bc552e3f-0bcf-4fd3-83c2-10f0f9643535.png)
还有就是列表页面的按钮等居中了，不知问题出在哪里？
![1671596343493](https://user-images.githubusercontent.com/36326638/208820528-36e450ee-85f4-45e5-8669-fd6b40be6d35.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
每次都会重现？

**Comment by zhangdaiscott** [comment]
把依赖删除，重新 下载呢

**Comment by zhangdaiscott** [comment]
你是vue2 还是vue3?

**Comment by gxzhou** [comment]
vue2
那个项目一旦能编译后，每次都是这样的。
如果我重新下载源码后，不会有这个问题。但因为要用到百度地图等，安装是sass_loader、webpack等会有版本冲突，好不容易改成不冲突了，就又变成这样了。

**Comment by zhangdaiscott** [comment]
哪就是加百度地图 导致的冲突？

**Comment by gxzhou** [comment]
用百度地图要加装一些组件，过程中会遇到很多版本依赖性问题，一顿乱弄解决了版本冲突，就变成这样了。所以不知道哪个组件出问题了。

**Comment by zhangdaiscott** [comment]
那还得靠你自己啊，我们无法重现

**Comment by gxzhou** [comment]
好的。好像是sass_loader的版本问题，版本太高了会出现“Syntax Error:TypeError: this.getOptions is not a function”的错，于是降版本，直到可以编译通过，然而$confirm就这样了。

**Comment by gxzhou** [comment]
经反复实验后发现，与element-ui有关，因为地图处理使用到了element-ui框架，所以在main.js中要引入相关组件安装，然后以使用就出现$cofirm不起作用的问题，网上也有人提出过此类问题，并且又相关的解决办法，但我们这里不能因为使用element-ui而去修改太多本已成熟的程序，所以只能不使用element-ui了。这里说明一下，供参考。也希望看看能不能有好的解决办法，使得能够使用到element-ui. （el-dialog,el-form,el-button可以用哪些代替，我还要再研究。）
![1672364985802](https://user-images.githubusercontent.com/36326638/210027752-9ba46434-c0d7-481b-9f33-2d0251d8996f.png)
![1672365401432](https://user-images.githubusercontent.com/36326638/210027768-3659137f-9d25-48e6-bc4c-94feaffab102.png)
![1672366077108](https://user-images.githubusercontent.com/36326638/210027782-8c2a9036-acf4-4b7f-8e7c-76290a1bade3.png)
注释掉相关语句后，“退出登录”就正常了。
![1672368438803](https://user-images.githubusercontent.com/36326638/210029474-b326da05-17da-44c3-8637-1fd883edbcdf.png)
![1672368520167](https://user-images.githubusercontent.com/36326638/210029508-fa1c13e5-2beb-4028-b84e-321841b51636.png)

**Comment by gxzhou** [comment]
至今没有找到element-ui的替代组件，没有找到与<el-dialog>类似的dialog功能，没法弹窗显示地图处理。还望能提供一些帮助，不胜感激！
