### ISSUE TITLE
如何升级前端版本

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecgboot-vue3#309]
##### 版本号：
3.4.3

##### 问题描述：
如何升级到3.4.4？直接更改package.json版本？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
git 对比合并代码
