### ISSUE TITLE
项目设置中分割菜单bug

### ISSUE THREAD

**Issue by XeonSid** [jeecgboot/jeecgboot-vue3#31]
##### 版本号：
1.0.0（20220321）
##### 问题描述
用户设置，1.0版本右上角项目配置中无分割菜单，手动在代码里设置成split：true后，部分一级菜单点击后无响应，如系统监控等
##### 截图&代码：
![image](https://user-images.githubusercontent.com/11872517/161972741-39368206-9c57-4541-915f-4824f6e8804e.png)
![image](https://user-images.githubusercontent.com/11872517/161972787-95b01eff-7422-4285-b55e-8875f93946ac.png)
![image](https://user-images.githubusercontent.com/11872517/161973068-2d724a8e-863e-448a-b6d4-d7043eef679e.png)

**Comment by lucas270** [comment]
没有吧，我没这问题

**Comment by XeonSid** [comment]
页面的按钮好像被删除了，laytouts/page/index 里面的组件是不是无法开启transition

**Comment by zhangdaiscott** [comment]
已修复
