### ISSUE TITLE
vue3版本-开启路由缓存,动态打开多个详情页, 点击导航栏上的刷新按钮,导致页面出现404的情况

### ISSUE THREAD

**Issue by liguoye** [jeecgboot/jeecgboot-vue3#313]
##### 版本号：
3.4.4

##### 问题描述：
使用动态路由打开多个详情页后,前提是开启路由缓存功能,路由配置可查看图片;  点击导航栏上的刷新按钮,导致页面出现404的情况
类似于: 组件&功能->基础组件-->tab操作-->打开1详情页的功能,但是这里的打开详情页功能没有开启路由缓存功能,

##### 截图&代码：
路由配置
![企业微信截图_1672025386929](https://user-images.githubusercontent.com/27951326/209496762-c0fa9baa-7126-41be-a91b-59b489227e79.png)
点击tab页签的刷新前效果
![企业微信截图_16720254661980](https://user-images.githubusercontent.com/27951326/209496798-c20a00b0-89a4-4e40-8283-3364bffd5743.png)
点击刷新按钮后的效果
![企业微信截图_16720255133066](https://user-images.githubusercontent.com/27951326/209496807-8a5d0523-5b2c-4c1c-975c-da22b3e13dbd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lsqGitHub716** [comment]
动态路由名称设置成 **craft-technicalCraft-detail-@id**试试
