### ISSUE TITLE
导入数据原表中无该数据

### ISSUE THREAD

**Issue by Gq66** [jeecgboot/jeecgboot-vue3#314]
##### 版本号：
最新

##### 问题描述：
字段是对应的表映射的值，数据库里存的是id。导入数据时候，字段对应的表中没有这个值的话，会存入导入模板中的值，该如何处理。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/67729007/209618764-2f36a681-5a1a-4816-8e3b-a1710df0c79f.png)
![image](https://user-images.githubusercontent.com/67729007/209618655-814c71aa-06af-4ada-80e0-418aa3375f8a.png)
![image](https://user-images.githubusercontent.com/67729007/209618681-f53af422-4ac3-45d2-9732-4f02091188e5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这不是对的吗？匹配不上肯定是原值保存
