### ISSUE TITLE
Online报表，编辑修改后popup页面无变化，功能测试页面正常 #301

### ISSUE THREAD

**Issue by HALOUXGQ** [jeecgboot/jeecgboot-vue3#316]
##### 版本号：
3.4.4

##### 问题描述：
Online报表，编辑修改后popup页面无变化，功能测试页面正常

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你改了什么？
