### ISSUE TITLE
这是拿veben项目改的吧，代码都一模一样。。。https://github.com/vbenjs/vue-vben-admin

### ISSUE THREAD

**Issue by Laowui** [jeecgboot/jeecgboot-vue3#318]
##### 版本号：
https://github.com/vbenjs/vue-vben-admin

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Lcmolin** [comment]
是的
