### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by github262302** [jeecgboot/jeecgboot-vue3#319]
##### 版本号：
官网最新

##### 问题描述：
一直点击右上角页面刷新 会一直内存增加

##### 截图&代码：

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/71603326/210179610-88078667-bb6b-4127-b56c-6c9700c6fbe5.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by RowgerGo** [comment]
第一次打开，得加载个几十秒，哈哈哈哈哈

**Comment by zhangdaiscott** [comment]
这不是正常的吗
