### ISSUE TITLE
表单数据更新

### ISSUE THREAD

**Issue by Kyle13145** [jeecgboot/jeecgboot-vue3#322]
##### 版本号：
3.3.4

##### 问题描述：
上面下拉框选择时，如何让下面的输入框禁用和启用，我试着用“formSchema”来修改，发现没有实时更新，得重新打开该页面。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34505623/210316125-18e3675b-f030-487c-8507-66f5700286c9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这边有例子，可以多参考下
![image](https://user-images.githubusercontent.com/3162115/211130895-3bf67480-9ba6-4676-b8ca-bcc5be4f602a.png)
