### ISSUE TITLE
一坨狗屎，抄别人代码提都不带提一下的

### ISSUE THREAD

**Issue by nick2834** [jeecgboot/jeecgboot-vue3#324]
##### 版本号：

[vue-vben-admin](https://github.com/vbenjs/vue-vben-admin)
##### 问题描述：
一坨狗屎，抄别人代码提都不带提一下的

##### 截图&代码：
一坨狗屎，抄别人代码提都不带提一下的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你确定没有吗
![image](https://user-images.githubusercontent.com/3162115/210501364-114f1214-e0b0-4a7d-a7e1-eca0c0acc77b.png)
