### ISSUE TITLE
online表单开发中表单只显示4个字

### ISSUE THREAD

**Issue by zhaozhiqiang2038** [jeecgboot/jeecgboot-vue3#326]
##### 截图&代码：

![图片](https://user-images.githubusercontent.com/26137250/211522152-c27cedab-f9aa-4aec-81c6-e67c324be018.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhaozhiqiang2038** [comment]
图片出错

**Comment by gxzhou** [comment]
vue3就是这样的，鼠标移上去会显示完整的。vue3的相关技术文档中有说明的。
