### ISSUE TITLE
首页功能搜索功能，当搜索结果为菜单含子菜单时，选中此菜单，路由前端错误。

### ISSUE THREAD

**Issue by zhangshun0530** [jeecgboot/jeecgboot-vue3#33]
##### 截图&代码：

1. 问题复现 
首页点击右上角搜索按钮，例如搜索 “页面” 两字。
2. 原始页面
![image](https://user-images.githubusercontent.com/32405854/162378810-77568427-1455-4f0e-b3c6-71ffaa90dcd5.png)
3. 点击任意一个不含子菜单的页面显示 如原始页面 第一个或者第二个时
结果正常
![image](https://user-images.githubusercontent.com/32405854/162379124-5813464c-c2e4-461c-a832-c7e9dfebc3e3.png)

4. 点击任意一个含子菜单的页面显示 如原始页面 第三个时
页面错误 前端报错
![image](https://user-images.githubusercontent.com/32405854/162379322-6b5fe6f7-6f7c-45f4-bceb-513f9b3be549.png)

5. 代码位置
src/components/Application/src/search/useMenuSearch.ts
红框内为新增是否包含子菜单 
![image](https://user-images.githubusercontent.com/32405854/162379578-912c784c-d3ce-45bd-9da9-12b4246bfa05.png)

6. 问题修改后效果
不再出现，如原始页面，第三个菜单结果。
![image](https://user-images.githubusercontent.com/32405854/162379714-de62d63a-5538-4fb3-9d34-9720ee82a672.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
