### ISSUE TITLE
pnpm版本pnpm@7.25.0，本地windows拉代码可以build成功，linux不行

### ISSUE THREAD

**Issue by 903249871** [jeecgboot/jeecgboot-vue3#333]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/14256585/212450490-e374c21b-cc7b-45e7-b9e8-3ee5b1d0cfb6.png)

![image](https://user-images.githubusercontent.com/14256585/212450501-3f98ac1f-c988-4078-afce-63e7b972cd5e.png)

![image](https://user-images.githubusercontent.com/14256585/212450424-8fd4f74c-78ae-4916-8610-c8796a7061d1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
百度把，环境问题诡异的很多
