### ISSUE TITLE
时间得插件显示英文得

### ISSUE THREAD

**Issue by wangxs2** [jeecgboot/jeecgboot-vue3#336]
##### 版本号：
v3.4.7  vue3版本

##### 问题描述：
时间得插件显示英文得，我需要中文显示得
##### 截图&代码：
![image](https://user-images.githubusercontent.com/37064079/212814566-c5b98563-2f3f-47e7-9430-260380715e1c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
哪有你说的版本号啊
