### ISSUE TITLE
数据库默认字符集导致兼容性问题

### ISSUE THREAD

**Issue by 1107535538** [jeecgboot/jeecgboot-vue3#338]
##### 问题描述：
online表单默认创建数据库String字符为varchar类型，默认的latin1字符集导致无法存储中文，需手动修改为utf8mb4

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58760322/213379778-8921ee6f-8536-4b48-a742-331cd3b43226.png)

![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这是因为你库默认的字符集是latin1吧
