### ISSUE TITLE
.env.production配置的接口域名是www一级域名，最终上到服务器接口却是使用二级域名调用接口

### ISSUE THREAD

**Issue by 903249871** [jeecgboot/jeecgboot-vue3#339]
##### 截图&代码：

![1674116606681](https://user-images.githubusercontent.com/14256585/213391563-7b8a5d82-955f-48cb-bca2-da9664ab72e9.jpg)
![1674884873239](https://user-images.githubusercontent.com/14256585/215248578-b970319c-289c-45b8-87bd-1aa94eed774f.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个得你自己分析下服务器上的配置
