### ISSUE TITLE
系统自动恢复原始数据库表问题

### ISSUE THREAD

**Issue by wpb498** [jeecgboot/jeecgboot-vue3#343]
##### 版本号：
3.4.4

##### 问题描述：
系统自动恢复原始的数据库表数据
菜单管理中的路由删除年前设计的路由地址
包括导入的自建导入的数据表也消失了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59943849/215375232-f2845350-9b36-45bb-8401-ea47e7d786a0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么意思？

**Comment by wpb498** [comment]
就是框架原本的库表在年后都恢复成初始化的模样了，比如设置的路由数据消失了，导入的库表也消失了，设置的字典字段也没了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月30日(星期一) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecgboot-vue3] 系统自动恢复原始数据库表问题 (Issue #343)






什么意思？

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by zhangdaiscott** [comment]
平台没有恢复数据的功能，只有一个表切的功能，具体问题自己排查
![image](https://user-images.githubusercontent.com/3162115/215376155-bc021a5f-0888-465b-8635-a25eac478c30.png)
