### ISSUE TITLE
自定义弹窗提交前后不能添加JS语句进行附加处理

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#344]
##### 版本号：
3.4.4
vue2
在线开发

##### 问题描述：
自定义弹窗提交前后不能添加JS语句进行一些附加的处理，使用当前表单，不执行beforeSubmit(row)中的语句，也不能使用then的处理。

##### 截图&代码：
按照文档设计自定义按钮并使用自定义弹窗处理，打开当前表单，控件与字段数据使用在线的配置，一切都正常的。
![image](https://user-images.githubusercontent.com/36326638/215405076-d468ff10-8356-464a-9d45-cdaf4d33dfb6.png)
自定义按钮uploadResultImage
![1675060759513](https://user-images.githubusercontent.com/36326638/215405787-9fa9deb9-755a-4b48-98ce-51b1906c394d.png)
JS增强中list下uploadResultImage(row)
其中想加then处理，that.openCustomModal({...}).then(res=>{...})，不行。
弹窗使用当前表单，修改数据后点击确认，form中的beforSubmit(row)中的语句也不执行，而该表单正常的“编辑”操作是执行的。
![1675061658951](https://user-images.githubusercontent.com/36326638/215408036-27c8f4e1-1750-4d05-a0b4-6cf9b3b1bd1c.png)

当使用自定义弹窗时，可不可以在哪里添加一些附加处理的JS语句？
如果使用的是当前表单，可不可以能执行beforeSunmit()中语句，这样也可以在此处添加一些语句，就能处理了。

或者，是不是有别的办法能够处理我这样的需求？望多指教，谢谢！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by tygithub1** [comment]
这种情况只能自己定义一个vue页面，在页面中自行处理提交逻辑，参考文档示例2：
https://www.kancloud.cn/zhangdaiscott/jeecg-boot/2585365
