### ISSUE TITLE
我想更改暗黑主题的很多颜色，不知道怎么做

### ISSUE THREAD

**Issue by pjy1711040554** [jeecgboot/jeecgboot-vue3#345]
##### 版本号：
1.2.0

##### 问题描述：
我想更改暗黑主题的很多颜色，不知道怎么做

##### 截图&代码：
![L SU80@RH`W`BBKTH3UQ376](https://user-images.githubusercontent.com/50440825/215644716-9e4a6206-8dd8-4058-a632-da10a3a5ac84.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2426560
