### ISSUE TITLE
pnpm run build报错

### ISSUE THREAD

**Issue by super094** [jeecgboot/jeecgboot-vue3#346]
##### 版本号：
SHA-1: 30855ad4a0204b85d6cc97162b98b1e3481ae3b

##### 问题描述：
pnpm run build报错，pnpm run dev可以正常运行

##### 截图&代码：
![image](https://user-images.githubusercontent.com/124009707/215656148-e41130b3-a9a6-4623-8b31-304554f707b7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没有遇到过，你可以百度下

类似的看看
https://www.jianshu.com/p/935d23e61176

**Comment by super094** [comment]
重装了nodejs
