### ISSUE TITLE
JDictSelectTag组件使用时，浏览器给出警告提示：Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array

### ISSUE THREAD

**Issue by sxx412** [jeecgboot/jeecgboot-vue3#347]
##### 版本号：
v3.4.4

##### 问题描述：
JDictSelectTag组件使用时，提示警告信息：
Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array...

##### 截图&代码：
访问菜单：jeecg组件示例-单表原生示例，为了便于演示，此处屏蔽了其他组件
![image](https://user-images.githubusercontent.com/51403156/215686880-c1388ac2-0048-4546-b276-41bff8dcedf4.png)
![image](https://user-images.githubusercontent.com/51403156/215686961-6c8370b9-d02f-4d41-8eaf-8b3999d9874b.png)
![image](https://user-images.githubusercontent.com/51403156/215687011-53889d4e-a311-492d-99db-fbe82182278a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by walt-xu** [comment]
我也遇到了相同的问题

**Comment by zhangdaiscott** [comment]
应该新版修复了，可以更新看看
