### ISSUE TITLE
online表单生成的视图开启评论后，在页面添加评论成功，但在评论记录列表中显示用户为未知

### ISSUE THREAD

**Issue by cdgsj** [jeecgboot/jeecgboot-vue3#349]
##### 版本号：

3.4.4

##### 问题描述：
online表单生成的视图开启评论后在编辑或详情页面添加评论成功后，在评论记录列表中显示用户为未知，但在同一online表单的编辑或详情页面添加评论成功后，能正常显示用户的名称和头像。

##### 截图&代码：
下图为同一online表单生成的视图，在编辑或详情页面添加评论成功后的截图，评论用户显示为未知。
![snap_screen_20230201114706](https://user-images.githubusercontent.com/78125943/215940439-b13d26ca-15d3-4fa6-9ea7-27f7f08d6de3.png)

下图为在同一online表单的编辑或详情页面添加评论成功后的截图，评论用户显示正常。
![snap_screen_20230201115155](https://user-images.githubusercontent.com/78125943/215941337-4f72d386-f676-4c58-90e0-3acc9a7fe6de.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
我们测没问题，等下个版本发布看看
