### ISSUE TITLE
前端请求报错，Network Error 

### ISSUE THREAD

**Issue by jsf0433** [jeecgboot/jeecgboot-vue3#35]
##### 问题描述：前端偶尔报错Network Error 
                              前后端分离之后，偶尔会请求报错 Network Error ，没进入到后台请求

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55685162/162662969-e6b56f7d-636f-4fbe-83f8-073de814dfc5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种问题无法分析
