### ISSUE TITLE
表格使用多级表头，无法开启表格编辑

### ISSUE THREAD

**Issue by lshhuhongtao** [jeecgboot/jeecgboot-vue3#351]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/46209677/215976255-f1f1961b-7f54-4ff5-80b5-caae26bc0d7b.png)
![image](https://user-images.githubusercontent.com/46209677/215976300-42472dc2-6d0f-437d-99c6-c548c4ea9820.png)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
你用的是BasicTable还是原生写法？

**Comment by lshhuhongtao** [comment]
BasicTable






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月17日(星期一) 下午2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecgboot-vue3] 表格使用多级表头，无法开启表格编辑 (Issue #351)





 
你用的是BasicTable还是原生写法？

**Comment by lsqGitHub716** [comment]
经测试，antdvue 表格在多级表头下是无法直接开启表格编辑的
