### ISSUE TITLE
VUE角色授权重复保存

### ISSUE THREAD

**Issue by jiawei5807** [jeecgboot/jeecgboot-vue3#352]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/101109349/216206199-fdaaa9db-0686-4bc6-a0b4-040de089e83e.png)
全部都是重复的数据，只是id不一样，如下图
![image](https://user-images.githubusercontent.com/101109349/216205964-81b69526-3f4a-4e59-9fbb-91f666aa1a0f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
已修改
