### ISSUE TITLE
antd3 表格动态数据及合并行报错，数据过大时页面卡动，怎么解决

### ISSUE THREAD

**Issue by sltjsj** [jeecgboot/jeecgboot-vue3#353]
版本号：
v3.4.2

问题描述：
1：table语法报错
2：Jeecg自定义组件示例

截图&代码：
![image](https://user-images.githubusercontent.com/45745028/216269648-38af6327-970a-45ea-9170-32937aa4dbe4.png)
动态加载行数据红色警告
![image](https://user-images.githubusercontent.com/45745028/216271154-b5aa3bd4-61a5-4fc3-99c5-198fa73490ca.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
用antd原生的表格，不用封装的
