### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by hear-ct** [jeecgboot/jeecgboot-vue3#357]
##### 问题描述：
运行报错，目录下无此文件

##### 截图&代码：
<img width="562" alt="image" src="https://user-images.githubusercontent.com/55691724/217130989-51cd1096-4f1e-4b20-9d93-a5daf57eb0c5.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
说下你的环境
