### ISSUE TITLE
vite版本升级后打包构建丢失入口js文件

### ISSUE THREAD

**Issue by CasonJiang** [jeecgboot/jeecgboot-vue3#358]
##### 问题描述：
vite版本升级为 4.x后，build构建的index.html文件内没有有效的入口js文件

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49610398/217172844-73e8eeaa-089c-48ce-b2b6-191b3abe5202.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前我们还没升级，等后面我们看看
