### ISSUE TITLE
低代码开发-online在线表单-新增编辑文本显示异常

### ISSUE THREAD

**Issue by a792883583** [jeecgboot/jeecgboot-vue3#359]
##### 版本号：
前端3.4.4（发布时间：2022-11-21）
后端3.4.4（发布日期：2022-11-21）

##### 问题描述：
node版本：16.17.0
yarn版本1.22.19
使用yarn安装依赖，然后启动前后端。
使用online在线表单新增了一个主表数据，然后配置了权限，在功能测试的时候，发现新增和编辑弹窗只会显示4个字的字符内容，比如我的文本是：上周工作内容，但是实际只显示：上周工作
但是我在线上的boot.jeecg.com版本测试的时候，并没有发现这样的情况出现。

##### 截图&代码：
这是本地的截图
![企业微信截图_864c8950-2d36-41b2-9a31-ba77db27f77a](https://user-images.githubusercontent.com/34535722/217189856-1d7461f6-4a3d-444d-bc24-8efdb8a62fb9.png)

这是线上的截图
![20230207001948](https://user-images.githubusercontent.com/34535722/217190063-5b9c6382-aaab-4ffa-86ed-748260c6e6bc.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
鼠标放上去会显示全，默认截取了，不然太长肯定很丑
