### ISSUE TITLE
如何获取动态的路由地址，或者如何改成为顶部主菜单 配合左侧次级菜单

### ISSUE THREAD

**Issue by LamantYC** [jeecgboot/jeecgboot-vue3#36]
##### 版本号：
3.1.0

##### 问题描述：

如何获取动态的路由地址，或者如何改成为顶部主菜单 配合左侧次级菜单
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已修复
