### ISSUE TITLE
如何将当前版本的jeecg前端框架升级到最新的3.4.4呢

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecgboot-vue3#362]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
版本升级方法？

  JeecgBoot属于平台级产品，每次升级改动内容较多，目前做不到平滑升级。

  这里给用户的升级建议是这样的：
  1.代码升级  => 本地版本通过svn或者git做好主干，在分支上做业务开发，jeecg每次版本发布，可以手工覆盖主干的代码，对比代码进行提交；
  2.数据库升级 => 针对数据库我们每次发布会提供增量升级SQL，可以通过增量SQL实现数据库的升级。
  3.兼容问题 => 每次版本发布会针对不兼容地方标注说明，需要手工修改不兼容的代码。

  注意： 升级sql目前只提供mysql版本，执行完脚步后，新菜单需要手工进行角色授权，刷新首页才会出现。
