### ISSUE TITLE
主子表默认主题风格时子表处理数据初始及保存问题

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#364]
##### 版本号：
3.4.4  vue2

##### 问题描述：
主子表默认主题风格时子表处理存在两个问题，建议能够予以改进：
1、子表库表字段在online配置页面属性的“表单显示”或“列表显示”均去掉，也即表单页面中的子表数据列表行上不显示此字段时，提交后，数据库表中改字段原有数据将备清空。（主表同样情况则不会，业务处理上也应该是不被清空的）
2、子表数据不能像主表表单的loaded()中那样对某些字段数据进行初始化处理，比如：发货单明细“期望发货时间”已经有值，希望在进入编辑状态时，预先初始设定“计划发货时间”与“期望发货时间”同，或者设定为当前系统时间，现在无法处理。

##### 截图&代码：
在线表单配置子表“销售件号”为可显示：
![1675910046934](https://user-images.githubusercontent.com/36326638/217702908-0e492de2-4135-4a74-8138-abfa577dc002.png)
编辑表单页面操作，填入各明细行“销售件号”数据：
![1675910255340](https://user-images.githubusercontent.com/36326638/217703533-9d7b4362-f6be-412a-aeab-15757ec63bd9.png)
确定提交后，查看数据库表中数据：
![1675910435265](https://user-images.githubusercontent.com/36326638/217703890-d0287e12-792d-4100-89b9-59107b75a16f.png)
在线表单配置子表“销售件号”为不显示：
![1675910655578](https://user-images.githubusercontent.com/36326638/217704325-9b32ec62-48c6-4857-8c3c-2063dcb86b8b.png)
编辑表单页面操作，“销售件号”字段已不可见，希望是修改其它数据时，“销售件号”原有数据页面上不要被人看到，也不能修改：
![1675910928108](https://user-images.githubusercontent.com/36326638/217705063-50b9bebb-e093-43e4-91fc-ecf59be9d28f.png)
确定提交后，查看数据库表中数据，发现原想控制不让更改的“销售件号”数据，全部已被清空：
![1675911121773](https://user-images.githubusercontent.com/36326638/217705554-100947ec-d508-46cb-a241-86232a8887cc.png)

关于子表数据初始化，希望进入表单编辑界面后，所有子表明细行的某字段能给与初始化设置并显示：
![1675911784691](https://user-images.githubusercontent.com/36326638/217707366-2fe28d60-8fac-423f-a2a1-05aab5fe913b.png)
我曾经想在主表form的JS增强loaded()中进行处理，但是，通过以下语句，在等待子表数据装载完成后，可以读出子表各明细行的数据，却找不到可以更改页面上子表数据的方法：
![1675912436495](https://user-images.githubusercontent.com/36326638/217708613-40d235a9-9930-4efe-a2b6-e8569f8f8d68.png)
想使用类似以下语句吹，但不知道在form的loaded()里如何获取这个row.id和target：
      let rowValues = {'deli_qty': qty}
      that.triggleChangeValues(rowValues, event.row.id, event.target)

还望大神们予以指导。最好是能够修正online的相关实现，多谢！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by gxzhou** [comment]
这个问题没人回答吗？是因为你们重现不了，还是说这个不是问题不需要解决呢？
存在这个问题，我们使用子表时很不方便，必须要把一些无关的数据显示在子表列表行上，很乱。

**Comment by zhangdaiscott** [comment]
你是生成的代码还是online在线的方式

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
问题1. 主表和子表在数据处理上不一样，子表之所以数据被清空，是因为子表的数据是先删除后新增，如果想动态的控制显示和隐藏，建议使用权限配置。
![image](https://user-images.githubusercontent.com/27989856/230887611-0a7b724b-4c27-4135-bba6-0af49318dd04.png)

**Comment by tygithub1** [comment]
问题2. 默认值设置方式有很多，参考文档：
https://www.kancloud.cn/zhangdaiscott/jeecg-boot/2044088
但是默认值只会是新增时生效，你说的这种场景，不应该在编辑时数据回显之后做，而是应该在数据保存的时候，判断哪些数据应该赋默认值。 实现方法：java增强-新增操作；js增强-beforesubmit。二者选1

**Comment by gxzhou** [comment]
> 问题1. 主表和子表在数据处理上不一样，子表之所以数据被清空，是因为子表的数据是先删除后新增，如果想动态的控制显示和隐藏，建议使用权限配置。 ![image](https://user-images.githubusercontent.com/27989856/230887611-0a7b724b-4c27-4135-bba6-0af49318dd04.png)

问题的原因已经知道，是由于子表数据是线删除后新增导致的。那么字段动态显隐也确实可以通过权限控制进行，但如此处理必然相当麻烦的，当角色多的时候需要进行数据授权处理的。
关键还有，这种先删除后新增的办法似乎是一种偷懒的处理办法，对于典型的明细子表，仅有数的几行数据，但也问题不突出。如果我需要几个子表用于查询对照（不可修改，且数量不少）时，这种处理方式势必也会将这些大量的记录删除后新增，一浪费资源影响效率，二，这些表明明是只用于显示参考的（表数据本身就是从别处导入的），但经过这么已处理后，这个表的所有记录的id都会全部重新更新一遍。这样合理吗？

**Comment by gxzhou** [comment]
> 问题2. 默认值设置方式有很多，参考文档： https://www.kancloud.cn/zhangdaiscott/jeecg-boot/2044088 但是默认值只会是新增时生效，你说的这种场景，不应该在编辑时数据回显之后做，而是应该在数据保存的时候，判断哪些数据应该赋默认值。 实现方法：java增强-新增/编辑操作；js增强-beforesubmit。二者选1

配置默认值在新增时生效，这个在大部分场景都在用，而且很有效。但我说的这种是在数据装载后，要根据主表不同的情况进行初值更改处理，而且最好显示给操作者看到，或者参与字段关联或者计算之用，比如不同的公司可能有不同的税率，当主表为A公司时，税率为0.1，新增子表明细行时，此费率0.1要初始填值，然后输入金额后，自动计算税额，当主表为B公司时，税率为0.15，就要设置不同的初值。反正有类似需求，要寻求比较好的解决办法才行。

**Comment by liaojiyuan** [comment]
问题2，默认值设置可以使用更高级JS表达式，例如定义变量、逻辑判断等，则需要你写一个自定义方法来调用。
自定义方法必须要写到 src/utils/CustomExpression.js 文件中，且要 export 才能在表达式中使用
