### ISSUE TITLE
build项目失败 显示无效数组

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/jeecgboot-vue3#365]
##### 版本号：
1.2.0

##### 问题描述：
buil项目失败显示无效数组

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50694382/217749905-8da39e8e-7f69-4a35-9e14-dad73dadd5c4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个百度下，应跟你的环境有关
