### ISSUE TITLE
绑定远程数据的单选下拉框联动和默认选中第一项

### ISSUE THREAD

**Issue by JerryYu2014** [jeecgboot/jeecgboot-vue3#367]
##### 版本号：
3.4.4

##### 问题描述：
1、页面是通过代码生成的，由搜索表单和列表组成，如何通过手动调整实现两个单选下拉框的联动功能，其中两个下拉框的数据都是通过服务接口获取的？
2、页面是通过代码生成的，由搜索表单和列表组成，绑定远程数据（通过服务接口获取）的单选下拉框，如何设置进入页面默认选中第一项，并触发列表显示相应的数据结果？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个自己编码啊，不要过分依赖代码生成器
