### ISSUE TITLE
单元编辑和行选择一起使用时爆警报

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#369]
版本号：3.4.4

问题描述：单元编辑和行选择一起使用时爆警报，并使整个页面卡住

 截图&代码：

![Dingtalk_20230214110001](https://user-images.githubusercontent.com/23691018/218627921-a689e3cb-aa30-4e56-8903-8d4b078c5cf2.jpg)

**Comment by zhangdaiscott** [comment]
描述过于简单，请配合代码和截图
