### ISSUE TITLE
VSCode 好多地方都提示 'AppProvider' is declared but its value is never read.Vetur(6133) Vetur(6192) 

### ISSUE THREAD

**Issue by Feike1993** [jeecgboot/jeecgboot-vue3#37]
##### 问题描述：
VSCode 好多地方都提示报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/103425261/162730328-26546470-fa2c-4dd1-b458-0a4563e14f34.png)
![image](https://user-images.githubusercontent.com/103425261/162730284-28e89359-29da-4eb4-a4d2-3f963de23356.png)
![image](https://user-images.githubusercontent.com/103425261/162730370-11ffd71f-bd17-4155-932f-421fa9cccf8d.png)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/19

**Comment by zhangdaiscott** [comment]
jl 再分析
