### ISSUE TITLE
新版演示demo的登录页面很好看，请问怎么切换

### ISSUE THREAD

**Issue by heyijx2** [jeecgboot/jeecgboot-vue3#371]
新版演示demo地址：http://boot3.jeecg.com/login
这个登录很好看，请问如何能修改成这样？
![image](https://user-images.githubusercontent.com/15224621/218671731-efda9650-da22-4fb4-ad68-db740d7227db.png)

**Comment by zhangdaiscott** [comment]
下个版本就发布了
