### ISSUE TITLE
发布到nginx环境后，积木报表，不能正常打开

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#372]
##### 版本号：
3.4.4

##### 问题描述：
发布到nginx环境后，积木报表，不能正常打开，报vue运行错误

##### 截图&代码：

![image](https://user-images.githubusercontent.com/3311840/218691900-8a29bc9c-6b3c-4e06-ab82-e9287772e40a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后台接口地址配置不对，不要通过nginx映射
