### ISSUE TITLE
vue3 本地启动 404

### ISSUE THREAD

**Issue by noodlesbuddy** [jeecgboot/jeecgboot-vue3#378]
##### 版本号：
vue 3 最新代码

##### 问题描述：
分别启动后端、前端代码，访问 localhost:3100, 提示 404 找不到资源，（完全按照官方教程操作）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/124578454/220606621-f42273bc-fab6-4296-a91a-ba6a4be10d83.png)

![image](https://user-images.githubusercontent.com/124578454/220606413-7f6dda30-3801-4c08-aa7f-6c12b8773135.png)

当我修改

**Comment by zhangdaiscott** [comment]
后台地址配置不对

**Comment by sleeeeeeepa** [comment]
我也有同样的问题，验证码应该走后台的接口获取吧，默认情况是走的nginx，本地启动还要在本地配置好nginx
