### ISSUE TITLE
局域网内访问另一台主机中的项目，打开运行时浏览器报错

### ISSUE THREAD

**Issue by wpb498** [jeecgboot/jeecgboot-vue3#379]
##### 版本号：
3.4.4

##### 问题描述：
开发环境下运行起来项目后，在同一个局域网的其他主机打开该端口后，浏览器中能够正常运行，但是浏览器中有报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59943849/220843017-786aa548-a811-41d8-a142-532504b18210.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后台地址怎么配置的
