### ISSUE TITLE
VUE3 启用CAS SSO后项目打包后无法获取到配置环境变量

### ISSUE THREAD

**Issue by heweilong** [jeecgboot/jeecgboot-vue3#38]
##### 版本号：
1.0.0

##### 问题描述：
CAS SSO集成环境变量参数定义错误导致无法获取到环境变量中配置的参数，导致浏览器无限跳转

##### 截图&代码：

![QQ截图20220412150613](https://user-images.githubusercontent.com/24644988/162900923-48b1be91-566e-4836-ad4d-4cc866266f2b.png)
打包过程过滤了环境变量参数前缀导致打完包之后 VITE_GLOBE_APP_CAS_BASE_URL 无法获取到，应将所有VITE_GLOBE_APP_CAS_BASE_URL 改为VITE_GLOB_APP_CAS_BASE_URL
![QQ截图20220412150917](https://user-images.githubusercontent.com/24644988/162901529-d880a9c2-49eb-4283-98aa-16d07148145d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by accpman** [comment]
已修复，感谢
