### ISSUE TITLE
请问时间选择器底部这些按钮能取掉吗，不用点确认，选择时间后直接关闭下拉框回填选择时间？把这个下拉框怎么设置跟input框齐宽？

### ISSUE THREAD

**Issue by sltjsj** [jeecgboot/jeecgboot-vue3#384]
版本号：3.4.3

问题描述：

请问时间选择器底部这些按钮能取掉吗，不用点确认，选择时间后直接关闭下拉框回填选择时间？把这个下拉框怎么设置跟input框齐宽？

截图&代码：
![image](https://user-images.githubusercontent.com/45745028/221745654-65a1e760-9d34-4cc5-9b08-cfef94b51475.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个你看下antd底层组件参数
