### ISSUE TITLE
npm i时报错

### ISSUE THREAD

**Issue by ZzYAmbition** [jeecgboot/jeecgboot-vue3#385]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/54825098/221746868-bd5136ee-74c0-477e-b933-f79b912671c7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
现在默认请用pnpm i
