### ISSUE TITLE
如何将Online表单开发中列表操作中的删除功能去掉

### ISSUE THREAD

**Issue by Sheshuaishuai** [jeecgboot/jeecgboot-vue3#386]
##### 版本号：
3.4.4

##### 问题描述：
我想将Online表单开发中列表操作中的删除功能去掉，应该如何修改

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41417216/221809991-e8f6af9c-428e-4361-8081-e89ca5c78104.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前改不了
