### ISSUE TITLE
Editor 中使用useListPage会报错

### ISSUE THREAD

**Issue by xiangbenguo** [jeecgboot/jeecgboot-vue3#391]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/46557994/222741146-693b5bc7-bba8-4076-8a10-c2cbe991990e.png)

**Comment by zhangdaiscott** [comment]
说的太抽象了，怎么用的，截图看代码

**Comment by xiangbenguo** [comment]
> 说的太抽象了，怎么用的，截图看代码

![image](https://user-images.githubusercontent.com/46557994/224734534-9db7ff33-58cb-4130-b5f5-043e427e3341.png)

**Comment by zhangdaiscott** [comment]
这个你得自己研究下
