### ISSUE TITLE
JSelectDept组件无法清除已选择的数据

### ISSUE THREAD

**Issue by Sheshuaishuai** [jeecgboot/jeecgboot-vue3#393]
##### 版本号：
3.4.4

##### 问题描述：
JSelectDept组件，选择部门之后，点击x无法清除数据

##### 截图&代码：
使用方式：
<j-select-dept  v-model:value="formData.executeOrgCode" type="array" :multiple="false" :defaultExpandLevel="1" rowKey="orgCode" checkStrictly :disabled="disabled" />

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by hml110** [comment]
同遇到这个问题，求解决方案！

**Comment by 1298191366** [comment]
未复现，你说的点击x无法清除数据是什么意思
![selectDept删除不掉](https://user-images.githubusercontent.com/30997828/229668285-5acc0a3a-a315-4ae3-8303-0be86d9901b6.gif)
