### ISSUE TITLE
所属部门树操作全部勾选不生效

### ISSUE THREAD

**Issue by yuyang-ai** [jeecgboot/jeecgboot-vue3#394]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/75102229/223366214-088e3f39-5858-413f-a438-9fb153df0923.png)
![image](https://user-images.githubusercontent.com/75102229/223366307-46576a94-62da-43d5-aef1-5be218d3586b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 1298191366** [comment]
已修复，待新版本发布
