### ISSUE TITLE
eslint 8.13.0 版本在idea中报错 

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#395]
##### 版本号：
3.5.0

##### 问题描述：
eslint 8.13.0 版本在idea中报错 
8.22.0 版本正常 下次升级可以改一下

##### 截图&代码：

![image](https://user-images.githubusercontent.com/3311840/223382103-94dc5c84-0fad-420a-8eca-881d94655e0f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
好的
