### ISSUE TITLE
鼠标移入到用户名称处不显示下拉菜单 控制台报错

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#396]
##### 版本号：
3.5.0

##### 问题描述：

鼠标移入到用户名称处不显示下拉菜单 控制台报错

频率还是比较高的，刷新就好了
##### 截图&代码：

![image](https://user-images.githubusercontent.com/3311840/223475214-c9dcc0d9-51bd-410b-b906-60ddfa505b33.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
重新步骤如何？
