### ISSUE TITLE
TreeSelect 控件 fieldNames无法正常替换

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/jeecgboot-vue3#398]
##### 版本号：
3.5.0
##### 问题描述：
把fieldNames里的 key与value改成字段id 就正常了 。改成code就报错

##### 截图&代码：
![W2XR(XSB)$T9O(TC_H2) 2T](https://user-images.githubusercontent.com/50694382/224218759-4521c4e8-948d-49d3-946c-367d4c24c9d6.png)
![5PHW2S03`C68I@LLB8KQ`AD](https://user-images.githubusercontent.com/50694382/224218773-1c9e649a-46b7-4f5d-aee0-c5a7ab125160.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lsqGitHub716** [comment]
![image](https://user-images.githubusercontent.com/65587928/229460335-a93a5e0e-97ba-41b8-b55a-331862ad8093.png)
尝试一下使用这种替换方式是否正常
