### ISSUE TITLE
能不能不生成sql文件，把sql文件中的语句自动导入到mysql数据库中？

### ISSUE THREAD

**Issue by Lifayong-lfy** [jeecgboot/jeecgboot-vue3#399]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
哪样很危险，而且用户也没办法自己做调整
