### ISSUE TITLE
有偿找一个会这个框架的前端改点页面

### ISSUE THREAD

**Issue by Wizhiai** [jeecgboot/jeecgboot-vue3#403]
##### 版本号：
有偿找一个会这个框架的前端改

##### 问题描述：
有偿找一个会这个框架的前端改点页面，价钱好商量。有意愿加q：630806244

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by qinghechaoge** [comment]
改什么？
