### ISSUE TITLE
可编辑表格

### ISSUE THREAD

**Issue by sun-scy** [jeecgboot/jeecgboot-vue3#405]
##### 版本号：

3.4.3
##### 问题描述：
在使用可编辑表格 使用插槽方式，并且添加行内校验，整个table不显示组件边框

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59079541/224873871-68b248ea-6099-43b9-ae81-927478e82439.png)
期望在增加校验的同时，让表格显示组件边框

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码截图看下
