### ISSUE TITLE
生成代码里面没有高级查询，要如何配置？目前只看到自定义列表的说明书？有ListPage的配置说明吗

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecgboot-vue3#406]
##### 版本号：
3.4.4

##### 问题描述：
生成代码里面没有高级查询，要如何配置？目前只看到自定义列表的说明书？有ListPage的配置说明吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
常用示例里面有例子
