### ISSUE TITLE
配置下级菜单为隐藏路由后，二级菜单无法点击，并且显示了三角符号

### ISSUE THREAD

**Issue by wangda2000** [jeecgboot/jeecgboot-vue3#407]
##### 版本号：

3.4.3
##### 问题描述：
和vue3一样的问题，但我没看见vue3的提交记录
[https://github.com/jeecgboot/jeecg-boot/issues/4013](https://github.com/jeecgboot/jeecg-boot/issues/4013)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lsqGitHub716** [comment]
更新到最新版试试
