### ISSUE TITLE
JVxeTable.time弹框显示有问题

### ISSUE THREAD

**Issue by zhangpeng52** [jeecgboot/jeecgboot-vue3#408]
##### 问题描述：
JVxeTable.time弹框显示有问题，不能显示再最上面 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49219405/225569293-4b20c6fa-4ab7-47b2-ab21-d15e00f5376c.png)
`{
			title: '起始时间',
			key: 'startTime',
			align: 'center',
			required: false,
			type: JVxeTypes.time,
			defaultValue: '14:52:22',
			laceholder: '请选择',
		}`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
这种情况是因为数据太少，导致没显示全，可以给表格设置个高度来撑开

![image](https://user-images.githubusercontent.com/34293221/231136113-1beac28e-3763-4f90-897b-81c07319e3a5.png)
