### ISSUE TITLE
关于vue3 JS增强 方法定义相关的几个问题

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#410]
##### 版本号：
3.5.0  vue3

##### 问题描述：
将vue2上的在线表单移至vue3中，发现原$message显示提示信息的相关功能在vue3中不行了，看vue3的文档，可以使用import的方式使用createMessage()进行替代处理。按照文档的例子进行尝试，发现以下问题。

##### 截图&代码：
1、文档例子原样写js增强one_hook()，报内置变量context没有定义
   文档中这样写的：
![1679283836682](https://user-images.githubusercontent.com/36326638/226241702-146c4679-61f5-4cab-b93e-c3575c5b614a.png)
![image](https://user-images.githubusercontent.com/36326638/226241576-b870d79d-a6b3-4d73-b186-02f46e128c5d.png)
  我的JS增强中这样写，one按钮（Button-js），原样复制的，但报错：
![1679284133168](https://user-images.githubusercontent.com/36326638/226242252-643e5688-e7ec-495e-817c-f36f306b4cd3.png)
![1679284173673](https://user-images.githubusercontent.com/36326638/226242290-d6d7e72a-5392-4676-911f-778252dd31c4.png)
![1679283952992](https://user-images.githubusercontent.com/36326638/226241906-0f3db249-4e28-4d5a-bd48-f9e5f972bc79.png)
报错context没有定义：
![1679284629254](https://user-images.githubusercontent.com/36326638/226243124-cf625319-448e-45cc-b445-efaeaec0e688.png)

2、link-js按钮时，JS增强two_hook()参数row报没定义，没有办法获取当前列表行数据：
![1679284854301](https://user-images.githubusercontent.com/36326638/226243579-383f976c-3488-418a-967d-3a3aa65e9b52.png)
![1679284792868](https://user-images.githubusercontent.com/36326638/226243463-ed4753da-3eca-4d6b-8c73-0c09a57fd0f7.png)
而不用_hook时，一切都正常的。但是不用_hook就没办法import，也就没办法显示体制信息，点击按钮执行一项任务，可能会调用到后端程序处理，时间可能会长，不给个提示，黑灯瞎火地干活，终归是说不过去的。

3、vue3的_hook存在问题，似乎还会有其它问题，比如在3.4.4版时_hook中都会报getAction()没有定义等，这些问题在升级3.5.0后不存在了。会不会还有其它，待慢慢出来吧。
感觉上，vue2的许多在线开发功能都比较完善，而且文档描述也比较详细精准，只是列表以及表单处理上不如vue3的好，所以我们就像移至到vue3上。
但是，vue3似乎处理不完善，许多vue2解决好好的问题会出现不支持的情况，很头疼。最重要的一点是，vue3的开发文档几步完善，好多地方说的和实际不一致，更有许多新的功能或与vue2大部相同的处理方法，文档中均没有很好地予以说明。

  

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by tygithub1** [comment]
经测试，问题1，文档有误，直接context直接用this就行，console.log(this);会打印当前对象可以调用的属性**p**或是方法**m**
![image](https://user-images.githubusercontent.com/27989856/230864418-64afe615-69ad-41f6-b370-e3b32465bd6e.png)
问题2，如1回复的图，通过调用this.selectedRowKeys可以获取选中的数据行ID

**Comment by gxzhou** [comment]
> 经测试，问题1，文档有误，context直接用this就行，console.log(this);会打印当前对象可以调用的属性**p**或是方法**m** ![image](https://user-images.githubusercontent.com/27989856/230864418-64afe615-69ad-41f6-b370-e3b32465bd6e.png) 问题2，如1回复的图，通过调用this.selectedRowKeys可以获取选中的数据行ID

问题2--我现在确实只能使用this.selectedRowKeys来处理，但是，我的自定义按钮是列表行上的按钮，link-js，是想对当前行的数据进行处理的，未加_hook时，通过row就可以读取到当前行数据，而现在加了_hook后，使用selectedRowKeys的话，操作时必须对本行进行勾选，然后再点击此按钮才能正常处理。这一来麻烦（操作本行之前还得点选一下），二来显然不很合理（我如果点选了别的行，然后点击本行此按钮，那就会执行错了的！因为没法把link按钮与当前行数据关联）。我觉得这个应该优化下才对。

**Comment by gxzhou** [comment]
> 经测试，问题1，文档有误，context直接用this就行，console.log(this);会打印当前对象可以调用的属性**p**或是方法**m** ![image](https://user-images.githubusercontent.com/27989856/230864418-64afe615-69ad-41f6-b370-e3b32465bd6e.png) 问题2，如1回复的图，通过调用this.selectedRowKeys可以获取选中的数据行ID

还有，问题1，文档有误，但是，现在在线文档没有更新。这就是为什么我们感觉到vue3文档极不专业极不完善的原因。正常来讲，vue2已经使用好久，文档也相当专业相当完善，现在升级到vue3后，至少对于哪些与vue2明显不同的地方，应该有比较详尽准确的说明。现在在使用vue3的过程中，文档基本没用，有的没说明，有的还有明显的错漏，好多地方都要靠猜。我觉得这个问题应该得到重视。
