### ISSUE TITLE
ReferenceError: Cannot access 'pageWrapper' before initialization

### ISSUE THREAD

**Issue by 2011ci** [jeecgboot/jeecgboot-vue3#411]
##### 版本号：
  当前版本

##### 问题描述：
打开页面一直转圈，不定期就弹出这个所有列表页面均无法显示
ReferenceError: Cannot access 'pageWrapper' before initialization
    at index.ts:7:40

##### 截图&代码：
  
![image](https://user-images.githubusercontent.com/5737868/226264344-a9e38130-0166-4468-9dda-5cde291cd51f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Mr-Vash** [comment]
3.5版本同问，出现这种情况之后，改下页面（比如去掉一个空格）热更新之后就又好了

**Comment by zhangdaiscott** [comment]
可能是热部署的问题

**Comment by zhangdaiscott** [comment]
重启就好了

**Comment by tawen** [comment]
这个问题我也遇到并且解决，是因为模块循环引用导致的这个问题。
![image](https://user-images.githubusercontent.com/6141318/234502123-927ed01e-a9d7-4ebc-8ce8-ba38f464dbfe.png)

解决方法有两个：

**Comment by tawen** [comment]
这个问题我也遇到并且解决，是因为模块循环引用导致的这个问题。
![image](https://user-images.githubusercontent.com/6141318/234502541-cf86b0b1-d753-41b0-a55b-63d7bb1f2118.png)
解决方法：
1、添加setTimeout：
![image](https://user-images.githubusercontent.com/6141318/234502823-e3734bf4-0c43-4f12-83c6-39f2ee4dd4d5.png)
2、export const PageWrapperFixedHeightKey = 'PageWrapperFixedHeight'这段代码拆到新文件中
![image](https://user-images.githubusercontent.com/6141318/234503324-70c35ac4-1583-41fb-a293-73859d68a69e.png)

**Comment by zhangdaiscott** [comment]
3Q
