### ISSUE TITLE
代码生成的条件默认值怎么赋

### ISSUE THREAD

**Issue by WZander** [jeecgboot/jeecgboot-vue3#414]
##### 截图&代码：
![W6BDR2QA7YTDJH$AGZM2{N3](https://user-images.githubusercontent.com/30968914/226830113-899052bd-5f64-4cd4-9261-4d189a864ccc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
生成后手工改代码

**Comment by WZander** [comment]
> 生成后手工改代码

怎么改？我不知道怎么给这日期选择器动态赋值
