### ISSUE TITLE
VUE3 前端打包报错

### ISSUE THREAD

**Issue by MoneyNotFoundException** [jeecgboot/jeecgboot-vue3#416]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/37855142/226962391-8999b1e8-7be4-4fa1-a421-354f5d77e079.png)
![image](https://user-images.githubusercontent.com/37855142/226962576-2ae5964d-dbb2-4357-858a-aac6968b8505.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
百度下吧，这个错误不了解
