### ISSUE TITLE
生成的代码条件里时间选择器有问题

### ISSUE THREAD

**Issue by WZander** [jeecgboot/jeecgboot-vue3#417]
##### 截图&代码：
![QE GBY~J}3E41KC{$A8VH_O](https://user-images.githubusercontent.com/30968914/227095712-d0a88428-42db-4831-a68f-160cb09cbbd5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
版本很老？

**Comment by WZander** [comment]
3.4.4版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月23日(星期四) 下午2:10
收件人: ***@***.***&gt;; 
抄送: "活动中心 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecgboot-vue3] 生成的代码条件里时间选择器有问题 (Issue #417)





 
版本很老？

**Comment by WZander** [comment]
> 版本很老？

3.4.4版本，我刚刚去下载最新的3.5.0，把代码都覆盖一边，还是有这个问题

**Comment by lsqGitHub716** [comment]
请把你的配置 和 生成代码的截图发一下

**Comment by WZander** [comment]
> 

已经改成不传时分秒了，不传时分秒就没了
