### ISSUE TITLE
windows 运行pnpm reinstall报错

### ISSUE THREAD

**Issue by codeh2o** [jeecgboot/jeecgboot-vue3#418]
##### 版本号：
 node -v
v16.13.0
pnpm -v
6.11.0

##### 问题描述：
windows 运行pnpm run reinstall
> jeecgboot-vue3@3.5.0 reinstall E:\web\modoc\jeecgboot-vue3
> rimraf pnpm-lock.yaml && yarn.lock && rimraf package.lock.json && rimraf node_modules && npm run bootstrap

'yarn.lock' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
 ERROR  Command failed with exit code 1.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6487457/227123052-b5b7fe87-ea8d-4371-9cb2-3544e7a188cb.png)

**Comment by zhangdaiscott** [comment]
命令不对吧
