### ISSUE TITLE
Jeecg-boot Vue3: captch code - 404

### ISSUE THREAD

**Issue by reedexiao** [jeecgboot/jeecgboot-vue3#419]
##### 问题描述：
1. 下载前端代码到本地
2. pnpm install
3. pnpm build
4. 将dist目录拷贝到nginx的html目录下
5. 配置nginx.conf，新建server（80端口），将其root指向html/dist目录
6. 重启nginx服务
7. 启动jeecg-boot后端

在浏览器上打开http://localhost/，进入登录界面，但是验证码图片无法显示。

启动浏览器的开发模式，查到获取验证码图片的get请求成功返回，但是无法显示验证码图片

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52494199/227133969-4dea473e-b25e-4bcb-be7d-63c02399a20c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
3.5.0的前端登录页面不是这个样子
