### ISSUE TITLE
打包后内存溢出

### ISSUE THREAD

**Issue by qq807061169** [jeecgboot/jeecgboot-vue3#42]
##### 问题描述：
打包后内存溢出

##### 截图&代码：

![R)B%JH2HRICQ3I2)(`7E{TV](https://user-images.githubusercontent.com/33020045/164213088-2ccfc484-d986-4674-9c3c-688da03c5605.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecgboot-vue3/issues/I530MB
