### ISSUE TITLE
修复356时候引入的回归错误 JPopupOnlReportModal.vue 中未修改

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecgboot-vue3#426]
##### 版本号：
3.5.0

##### 问题描述：
使用Jpop，引用的
/modal/JPopupOnlReportModal.vue
132 行 少参数 tableRef  会报错 

##### 修改意见：
/modal/JPopupOnlReportModal.vue 

132 行 
`      ] = usePopBiz(getBindValue,tableRef); `

另外 
/components/jeecg/OnLine/hooks/usePopBiz 中 

564行 可以改成
`  tableRef?.value?.setPagination({ `

**Comment by lsqGitHub716** [comment]
已修改
