### ISSUE TITLE
asyncLoader相关错误

### ISSUE THREAD

**Issue by denga1** [jeecgboot/jeecgboot-vue3#427]
##### 版本号：
3.4.4

##### 问题描述：
关闭表单时，出现asyncLoader相关错误

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32947376/227493205-0d2ae489-01e3-4822-a0c9-150335523be7.png)
点击取消、确认或者右上角X关闭
窗口未关闭，并会提示Cannot read properties of undefined (reading '__asyncLoader')错误
![image](https://user-images.githubusercontent.com/32947376/227492830-7936872a-e84c-44a0-acc3-74e4e92abcf3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lsqGitHub716** [comment]
表单配置内容较多，请将表单内容精简后，测试一下是因为配置的哪个控件导致出现的这个问题，便于我们的问题追踪
