### ISSUE TITLE
请问JVxeTable如何实现表头分组

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/jeecgboot-vue3#428]
##### 版本号：
最新版

##### 问题描述：
JVxeTable如何实现表头分组，BaseTable有children参数实现分组，JVxeTable如何实现？
看了代码好像没封装vxe-colgroup，
而如果采用传统标签方式来实现分组的话，
jeecgboot的自定义组件JVxeTypes.select等就无法使用。
以上，请确认。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没实现这功能
