### ISSUE TITLE
在centos7中下载依赖pnpm i时 mozjpeg依赖下载不下来

### ISSUE THREAD

**Issue by flowerburied** [jeecgboot/jeecgboot-vue3#433]
##### 版本号：
3.5.0

##### 问题描述：

在centos7中下载依赖pnpm i时
mozjpeg依赖下载不下来

看过别人的issues替换依赖包,但没有解决根本问题
https://github.com/jeecgboot/jeecgboot-vue3/issues/375

希望官方解决在centos7下依赖不能pnpm i一键下载的问题

##### 截图&代码：

```
└─ Failed in 9.7s at /opt/front_end_project_address/passengertransport/passengerTransport_vue3/node_modules/.pnpm/registry.npmmirror.com+mozjpeg@7.1.1/node_modules/mozjpeg
 ELIFECYCLE  Command failed with exit code 1.
```
![image](https://user-images.githubusercontent.com/35652270/228418264-474f8b7d-4f0b-4f9b-b649-869f476f8163.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by flowerburied** [comment]
使用yarn 好了...官方你不pnpm没用明白建议不要用

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/weixin_42023748/article/details/123225936

http://doc.vvbin.cn/other/faq.html#%E4%BD%BF%E7%94%A8-yarn-%E5%AE%89%E8%A3%85-imagemin-%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E5%A4%B1%E8%B4%A5

**Comment by flowerburied** [comment]
> https://blog.csdn.net/weixin_42023748/article/details/123225936
> 
> [http://doc.vvbin.cn/other/faq.html#%E4%BD%BF%E7%94%A8-yarn-%E5%AE%89%E8%A3%85-imagemin-%E4%BE %9D%E8%B5%96%E5%AE%89%E8%A3%85%E5%A4%B1%E8%B4%A5](http://doc.vvbin.cn/other/faq.html#%E4%BD%BF%E7%94%A8-yarn-%E5%AE%89%E8%A3%85-imagemin-%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E5%A4%B1%E8%B4%A5)

我想要的是pnpm后就可以运行，而不用别的设置，如果pnpm不能完成我的需求，请不要推广它

**Comment by slin1972** [comment]
yum install nasm 
然后删除node modules
pnpm install

**Comment by qfilsdv731** [comment]
> 使用yarn 好了...官方你不pnpm没用明白建议不要用

我 pnpm 和 yarn 都不好使呢

yarn 的，安装 zlib 
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/132372876/8519d3ba-044f-41ef-a5de-f7b3f354d718)

pnpm 的，确认安装了 nasm，并删除了 node_modules 后重写跑的
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/132372876/bb2543dc-f4aa-4b89-8264-9bc9aa048c33)

**Comment by qfilsdv731** [comment]
再 yum install libtool automake autoconf 

通过 yarn install 解决了
