### ISSUE TITLE
showTableSetting设置完表头之后 再次打开总是乱掉

### ISSUE THREAD

**Issue by wangxs2** [jeecgboot/jeecgboot-vue3#434]
##### 版本号：
3.4.4

##### 问题描述：
showTableSetting设置完表头之后 再次打开总是乱掉

##### 截图&代码：

![image](https://user-images.githubusercontent.com/37064079/228452047-67e74f9b-e877-42cc-a529-32e8589be197.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
vue几？
