### ISSUE TITLE
代码生成的日期控件赋默认值报错

### ISSUE THREAD

**Issue by WZander** [jeecgboot/jeecgboot-vue3#435]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/30968914/229005073-32c26cac-ef37-4145-97b1-126d320d9dd5.png)

![image](https://user-images.githubusercontent.com/30968914/229005104-91183dc5-e00c-4b2f-871b-f5acc3324aea.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 1298191366** [comment]
需要赋值`valueFormat`即可解决
![image](https://user-images.githubusercontent.com/30997828/230847564-763c0676-e3ec-446b-a0eb-104b7dc618ab.png)
