### ISSUE TITLE
本地运行没有问题，Nginx部署之后页面报错，而且跳转到别的页面也会报错

### ISSUE THREAD

**Issue by Libpzzz** [jeecgboot/jeecgboot-vue3#437]
##### 问题描述：
页面在本地运行没有问题，Nginx部署之后这个页面报错，而且跳转到另一个页面也会报错，但是在另一个页面刷新之后就会显示正常，跳转到之前问题页面还是会报错

##### 截图&代码：
报错页面
![image](https://user-images.githubusercontent.com/91443254/229055075-50dbc293-3b6f-4f0c-8523-bc3764711802.png)
切换页面
![image](https://user-images.githubusercontent.com/91443254/229055198-5ad7d14c-9727-4d96-967e-34976c6da113.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种问题请自己排查把，我们都没明白你怎么用的
