### ISSUE TITLE
咱们得前端项目，经常打开登录页很慢，一直在加载中

### ISSUE THREAD

**Issue by wuchangrong** [jeecgboot/jeecgboot-vue3#438]
##### 版本号：
3.5.0

##### 问题描述：
咱们得前端vue项目，经常打开登录页很慢，一直在加载中， 但经常慢，在不同的电脑上也慢
但是 有时也挺快，
请问是否是架构问题，还是加载组件太多， 怎么清除多余的组件？
怎么保证每次打开都在3秒以内

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30275850/229070225-2d15681f-2d1e-4433-8a68-fef690d690bd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2426559
1
