### ISSUE TITLE
BasicTree的getSelectedNode方法无法获取title

### ISSUE THREAD

**Issue by Loren1999** [jeecgboot/jeecgboot-vue3#439]
##### 版本号：
3.5.0（发布时间：2023-03-08）

##### 问题描述：
BasicTree组件@select方法回调方法中的title值被改变了，无法直接获取到节点上的显示内容
原因为BasicTree组件中为了实现点击节点展开功能吧title字段给覆盖了
##### 截图&代码：
官方组件：
![官方](https://user-images.githubusercontent.com/20633409/229077050-f2d06d23-34d7-4f56-9724-11839e130eb9.PNG)
Jeecg-Boot的BasicTree组件
![自定义](https://user-images.githubusercontent.com/20633409/229077217-09637ad5-a5f4-481d-96af-eb7e87cbf0df.PNG)
代码：
![问题](https://user-images.githubusercontent.com/20633409/229077268-2f28f4f3-5b89-4a8f-ab2c-6389c0478093.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
vben官方组件问题，如需获取title，可以自行扩展绑定真实title，从而获取到title数值
![image](https://user-images.githubusercontent.com/65587928/233255571-9dc902d0-ecd1-4d15-a4cd-650403e6c015.png)
