### ISSUE TITLE
下一个版本计划什么时候上啊？

### ISSUE THREAD

**Issue by xxlngng** [jeecgboot/jeecgboot-vue3#44]
##### 问题描述：
ui更新会延续vben-admin的修改吗？vben目前已经更新蛮多了，jeecg下个版本计划什么时候上呢？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
1.1.0-beta 代码已经更新
