### ISSUE TITLE
数据列表列字段权限控制源代码文件缺失问题

### ISSUE THREAD

**Issue by 1124410990** [jeecgboot/jeecgboot-vue3#441]
版本号：jeecgboot-vue3 3.4.4

问题描述：权限管理要求引入 import { colAuthFilter } from "@/utils/authFilter" 但是 utils目录下找不到authFilter

截图&代码：
<img width="415" alt="image" src="https://user-images.githubusercontent.com/21375863/229301302-cabf22c1-c333-4500-b5ad-a3adfef1e8cf.png">

**Comment by 1124410990** [comment]
http://doc.jeecg.com/2044039 这是文档链接

**Comment by zhangdaiscott** [comment]
你看的是vue2文档
请看vue3文档
http://vue3.jeecg.com/2398845
