### ISSUE TITLE
BasicTable是否有行拖动属性，canRowDrag设置不生效

### ISSUE THREAD

**Issue by liuxiangp** [jeecgboot/jeecgboot-vue3#442]
##### 版本号：
3.5.0

##### 问题描述：
1.BasicTable是否有行拖动属性，canRowDrag设置不生效
2.使用封装的JVXETable表格，行拖动时只支持每行第一列的图标进行拖动，是否可以整行任意区域进行拖动排序

##### 截图&代码：
const { tableContext } = useListPage({
  tableProps:{
    title: '商品列表',
    api: list,
    columns,
    canResize: true,
    formConfig: {
      //labelWidth: 120,
      schemas: searchFormSchema,
    },
    defSort: {
      column: 'temp1',
      order: 'asc',
    },
    showIndexColumn:true,
    showActionColumn:false,
    pagination:{pageSize:100},
    canRowDrag:true,//此处设置行拖拽排序不生效
  },
})

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
vben已经不支持canRowDrag属性了，重复问题
