### ISSUE TITLE
online表单-关联记录控件：sign签名校验失败

### ISSUE THREAD

**Issue by zander92** [jeecgboot/jeecgboot-vue3#445]
##### 版本号：
后端版本：3.5.0
##### 问题描述：
通过online表单，页面属性配置字段控件类型为：关联记录，选择关联表，提示“Sign签名校验失败！”

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31072462/229494195-438db143-7faa-44d0-b6a1-386a1dbb04f7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看看你配置有什么特别的吗

**Comment by zander92** [comment]
配置是指哪里的配置？我想实现通过选择用户后，关联带出手机号

**Comment by zhangdaiscott** [comment]
ty

**Comment by healkerzk** [comment]
![image](https://user-images.githubusercontent.com/35994418/230847992-2d075c15-04fd-497d-a6f6-54b495f6ef57.png)

![image](https://user-images.githubusercontent.com/35994418/230848029-20ea4b36-5b74-426d-a500-880bc248a682.png)

![image](https://user-images.githubusercontent.com/35994418/230848097-008ad9b3-4995-4f42-9755-39153fb89059.png)

列表界面有表关联数据字典字段时，报“Sign签名校验失败！”

**Comment by healkerzk** [comment]
![image](https://user-images.githubusercontent.com/35994418/230848499-06b0fbe3-550a-4e2a-a19c-e8ce5d961db1.png)

**Comment by zhangdaiscott** [comment]
你改了后台的校验秘钥了吗

**Comment by tygithub1** [comment]
测试无误。
选择关联表 是下拉搜索组件，他的数据获取需要对参数签名，不通过说明是前后端签名结果不一致。跟一下代码吧

后端：
org.jeecg.config.sign.interceptor.SignAuthInterceptor
![image](https://user-images.githubusercontent.com/27989856/230902982-62a434d4-0b49-46b2-a04c-ba148c687944.png)

前端：
src/utils/http/axios/index.ts
![image](https://user-images.githubusercontent.com/27989856/230903313-6e95915d-4511-4513-9d3d-dbeb83be1a67.png)

**Comment by AAAGreenHand** [comment]
online表单，选择关联记录还是会报错“Sign 签名校验失败！”

**Comment by zhangdaiscott** [comment]
你的代码是最新的吗

**Comment by zhangdaiscott** [comment]
你录个视频吧

**Comment by AAAGreenHand** [comment]
> 你录个视频吧

是在微服务的模式下会出现“签名检验失败”这个报错的，大概的原因是这样的
gateway接受到url参数，url参数带 “%” ，转发到微服务之后，url上面的 “%” 被转义成 “%25” 了；所以在校验签名的方法里面后端生成的签名是不一致的。
这是gateway拿到的URL：/dict/loadDict/onl_cgform_head%20where%20copy_type%20=%200,table_txt,table_name
![27a761dbb1380e7f13a02ce54d370a2](https://github.com/jeecgboot/jeecgboot-vue3/assets/25574236/ab70e9cf-8291-4a05-9920-db9c51f375d1)

---
这是微服务下，HttpUtils的getAllParams方法下拿到的URL：onl_cgform_head%2520where%2520copy_type%2520=%25200,table_txt,table_name
decode之后的URL：onl_cgform_head%20where%20copy_type%20=%200,table_txt,table_name
![9a32f422f840dc98fb927ee5eab3ed5](https://github.com/jeecgboot/jeecgboot-vue3/assets/25574236/2d54e170-cd8e-423f-a5dd-403d1c09dc7d)


-----------------------


我现在的解决方法是
1.HttpUtils的getAllParams方法中，在URLDecoder之前将 “%25” 替换成 “%”
2.在src/main/java/org/jeecg/modules/system/service/impl/SysDictServiceImpl.java的loadDict方法中，将dictCode做一次URLDecoder.decode的操作

![32f2b94920db1d08704d80bb3193154](https://github.com/jeecgboot/jeecgboot-vue3/assets/25574236/47b50706-1433-4cc4-a7d1-b02eeca28fd7)

![4cd16502fcd48609d309ba7a7d99567](https://github.com/jeecgboot/jeecgboot-vue3/assets/25574236/d5d07410-3614-4885-a08f-339ea85e65dd)

**Comment by zhangdaiscott** [comment]
单体没问题？

**Comment by AAAGreenHand** [comment]
> 单体没问题？

单体的没有问题，springcloud的有问题

**Comment by tygithub1** [comment]
已修改
