### ISSUE TITLE
Oneline报表-功能测试-接口错误

### ISSUE THREAD

**Issue by qsyj** [jeecgboot/jeecgboot-vue3#447]
##### 版本号：
3.5.0

##### 问题描述：
打开“Oneline报表配置”，选中某个进行功能测试，提示“网络请求错误,未找到该资源!”。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/16165991/229719756-54ef74a8-8490-45a3-9a12-46b6f4d1f1b8.png)
![image](https://user-images.githubusercontent.com/16165991/229719972-3d7edd51-8374-4027-bbed-a33038160a95.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
online表单好使吗
