### ISSUE TITLE
 暗夜模式不完整，有bug

### ISSUE THREAD

**Issue by healkerzk** [jeecgboot/jeecgboot-vue3#448]
##### 版本号：
vue3.5.0

##### 问题描述：

暗夜模式不完整，有bug

##### 截图&代码：

![1680597215953](https://user-images.githubusercontent.com/35994418/229735256-22a5031a-b62d-4745-bf4c-c730eb0eb496.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 1298191366** [comment]
已修复，待新版本发布
