### ISSUE TITLE
JImageUpload及JselectUserByDept的小扩展

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecgboot-vue3#452]
##### 版本号：
3.5.0

##### 问题描述：
1 JImageUpload 应该添加类型限定：
在组件    <a-upload >上添加`accept="image/*" `

2 JselectUserByDept 可以添加属性  maxSelectCount 用来确定选几个人
在 UserSelectByDepModal 中添加 `:maxSelectCount="maxSelectCount"`
在props 中添加 `maxSelectCount: null,`(默认为空好像有专业写法，我不太会 )

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
