### ISSUE TITLE
给用户配置多个租户，多个部门，登录的时候没有提示选择租户和部门

### ISSUE THREAD

**Issue by RelaxAndNotIndulge** [jeecgboot/jeecgboot-vue3#453]
##### 问题描述：
两个问题：1、在用户管理列表，找到admin用户，编辑，关闭，编辑，关闭，这里租户回显就多出来了，事实上我只有2个租户；
                  2、我在这里给admin设置了2个租户，2个部门，但是登录的时候没有提示我选择租户，也没有提示我选择部门，这样是不是不对？？另外新建一个用户测试，还是有同样的问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32625268/230763369-5992dda2-9c58-46ae-a7a4-e394993c10bc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
问题1：已修复，待新版本发布
问题2：部门未复现，租户目前是默认租户，您可以在登录之后自动选择租户
部门问题：
请查看用户表里面的orgCode是否为空，目前是选择完一次就不会再次出现了
![image](https://user-images.githubusercontent.com/30997828/230821421-e7c05150-a3e6-4f41-a556-0ffd782a9f99.png)
新建的用户
![2](https://user-images.githubusercontent.com/30997828/230821689-1f8b6e5b-8765-4b7e-ada4-b5c85477bbe4.png)
设置部门
![3](https://user-images.githubusercontent.com/30997828/230821696-2cc314fd-8f7b-4176-af55-23a16bb3b037.jpg)
再次登录
![4](https://user-images.githubusercontent.com/30997828/230821706-464e2361-3396-4598-b55b-6e62134fd247.png)
如果已经登录过的可以点击头像切换部门即可，支持部门和租户的切换
![image](https://user-images.githubusercontent.com/30997828/230821743-c2f886b9-104f-47f0-89b7-c9f00f42024c.png)
