### ISSUE TITLE
ApiSelect 这个组件,每次下拉直请求一次后台,怎么修改下呢?

### ISSUE THREAD

**Issue by sishuiwuxie** [jeecgboot/jeecgboot-vue3#457]
##### 版本号：
VUE3 3.4.4版本

##### 问题描述：
ApiSelect 这个组件,每次下拉直请求一次后台,怎么修改下呢,具体需要添加或者修改什么参数麻烦您.
##### 截图&代码：
![](https://i.ibb.co/cCLpp13/Wechat-IMG918.jpg)

**Comment by zhangdaiscott** [comment]
这个组件没有作缓存功能
