### ISSUE TITLE
列表操作列，“删除”操作提示界面布局异常

### ISSUE THREAD

**Issue by healkerzk** [jeecgboot/jeecgboot-vue3#458]
##### 版本号：
vue3.5.0

##### 问题描述：

列表操作列，“删除”操作提示界面布局异常

##### 截图&代码：

![image](https://user-images.githubusercontent.com/35994418/231138226-bbff8e8a-400f-4245-8660-8e50d26de804.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 1298191366** [comment]
请参考文档：常见问题18
http://help.jeecg.com/qa.html#18%E5%88%97%E8%A1%A8%E6%93%8D%E4%BD%9C%E5%88%97%E5%88%A0%E9%99%A4%E6%93%8D%E4%BD%9C%E6%8F%90%E7%A4%BA%E7%95%8C%E9%9D%A2%E5%B8%83%E5%B1%80%E5%BC%82%E5%B8%B8
