### ISSUE TITLE
yarn build报错

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecgboot-vue3#46]
##### 版本号：
版本号：v1.0.0

##### 问题描述：

[11:35:35] ✨ [vite-plugin-theme] - extract css code file is successfully:
[11:35:35] Could not resolve './Position.data' from src/views/system/position/index.vue
[11:35:35] error during build:
[11:35:35] Error: Could not resolve './Position.data' from src/views/system/position/index.vue

##### 截图&代码：
![image](https://user-images.githubusercontent.com/14859466/165469401-9f1a55c5-34a5-41bd-a5e7-6ec28eb042cb.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
首字母大小写的问题，应该修复了
![image](https://user-images.githubusercontent.com/3162115/165499329-1be3d36e-8240-4ab5-a486-16bbfdf08257.png)

**Comment by hdtopku** [comment]
> 首字母大小写的问题，应该修复了 ![image](https://user-images.githubusercontent.com/3162115/165499329-1be3d36e-8240-4ab5-a486-16bbfdf08257.png)

没有修复

https://hub.fastgit.xyz/jeecgboot/jeecgboot-vue3/blob/master/src/views/system/position/index.vue

![image](https://user-images.githubusercontent.com/14859466/165500555-01efab16-0f83-4e5e-971b-7835b91ea5b4.png)

**Comment by zhangdaiscott** [comment]
更新代码吧

**Comment by hdtopku** [comment]
> 更新代码吧

最新代码也没有改过来，我pr了：https://github.com/jeecgboot/jeecgboot-vue3/pull/48
