### ISSUE TITLE
请教 slot 返回数据,.vue文件中,如何给ts formSchema字段赋值.

### ISSUE THREAD

**Issue by sishuiwuxie** [jeecgboot/JeecgBoot-vue3#460]
##### 版本号：

V3.4.4
##### 问题描述：
调用ApiSelect 组件,目前Vue文件能收到返回数据,想把ts文件中 formSchema 字段值同步变化
##### 截图&代码：

![vue文件](https://i.ibb.co/T4GpR4h/Wechat-IMG922.jpg)

![ts文件](https://i.ibb.co/VtYhHYr/Wechat-IMG921.jpg)

**Comment by zhangdaiscott** [comment]
啥意思？

**Comment by sishuiwuxie** [comment]
图1 ApiSelect 组件 onselect方法中返回当前选中值,我想把值里边id赋值 图2中field是子系统英文名称上. 第一次写前端还请指点一下.

**Comment by zhangdaiscott** [comment]
找个有经验的前端现场指导把，这种问题没办法通过这种模式回复你
