### ISSUE TITLE
vxe-table提示信息没有随着高度响应

### ISSUE THREAD

**Issue by harveyLXH** [jeecgboot/jeecgboot-vue3#461]
##### 版本号：
后端：jeecg 3.5
前端：vue3
##### 问题描述：
vxe-table提示信息没有随着高度响应(vue2版本没有这个问题)

##### 截图&代码：

![111111222222](https://user-images.githubusercontent.com/28383928/231377394-65e589b8-0a89-41ae-a525-76c6ceea2ca4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么意思？

**Comment by harveyLXH** [comment]
VxeTable的内容过长时，可以使用show-header-overflow以提示框的形式显示全部内容，但是升级到最新版本时，提示信息没有随着高度改变而实时显示位置（猜测是CSS冲突了）。当页面出现滚动条，滚动页面就会出现这个问题。

**Comment by harveyLXH** [comment]
截图显示的提示框内容应该是第1条数据的商品清单全部内容，但是出现滚动条，滚动页面位置就出错了。

**Comment by zhangdaiscott** [comment]
更新代码，昨晚有提交

**Comment by harveyLXH** [comment]
我使用最新的代码测试了，还是有这个问题

**Comment by zhangdaiscott** [comment]
最新效果截图

**Comment by zhangdaiscott** [comment]
最新效果截图

**Comment by zhangdaiscott** [comment]
最新效果截图

**Comment by harveyLXH** [comment]
![image](https://user-images.githubusercontent.com/28383928/231636743-c40f2379-8c89-4d22-a3ac-ee473c76b63d.png)

**Comment by zhangdaiscott** [comment]
你录个视频

**Comment by harveyLXH** [comment]
[](url)

https://user-images.githubusercontent.com/28383928/231638663-f60b7b42-f49b-4df8-aa87-4059fa82c16b.mov

**Comment by harveyLXH** [comment]
Vue2版本没有这个问题，升级到Vue3版本才有

**Comment by sjlei** [comment]
通过调试可以发现，vxe-table自带的tooltip的`top`属性是计算错误的，这个是style行内样式，而且可以通过截图看出来不存在样式冲突。
![image](https://user-images.githubusercontent.com/34293221/233833892-d49e45a5-2330-4342-9392-a9ee2f108f2e.png)

vue2的vxe-table是2.x版本（不支持vue3）
vue3的vxe-table是4.x版本
可能是vxe-table写新版本的时候出现的问题，目前没有好的解决方法，所以先替换成原生title来显示了。

**Comment by harveyLXH** [comment]
好的，谢谢
&nbsp;


ゾざ↗☆◇#
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 晚上6:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecgboot-vue3] vxe-table提示信息没有随着高度响应 (Issue #461)





 
通过调试可以发现，vxe-table自带的tooltip的top属性是计算错误的，这个是style行内样式，而且可以通过截图看出来不存在样式冲突。
 
 
vue2的vxe-table是2.x版本（不支持vue3）
 vue3的vxe-table是4.x版本
 可能是vxe-table写新版本的时候出现的问题，目前没有好的解决方法，所以先替换成原生title来显示了。
