### ISSUE TITLE
自定义按钮 js增强触发弹窗报错

### ISSUE THREAD

**Issue by icgreat** [jeecgboot/JeecgBoot-vue3#463]
##### 问题描述：
给online表单新增自定义按钮后绑定js增强时报错，peError: this.openCustomModal is not a function
 

##### 截图&代码：
![123](https://user-images.githubusercontent.com/44168085/231425358-09179d4b-e3d9-4efc-bf79-c1a54d5be259.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前开源版暂时不支持这个功能

**Comment by icgreat** [comment]
这是来自邮箱的自动回复邮件。您好，您的邮件已收到，如有需要本人会尽快回复。
