### ISSUE TITLE
Online报表 敏感字段如何解密

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecgboot-vue3#464]
##### 版本号：
3.5.5
##### 问题描述：
使用online报表，其中包含敏感字段，但是没有入口去进行字段解密。向各位请教怎么处理？ 只能用数据库的存储过程吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没这功能
