### ISSUE TITLE
online表单的modal字段名称 只能显示4个字符

### ISSUE THREAD

**Issue by icgreat** [jeecgboot/jeecgboot-vue3#468]
##### 问题描述：
online表单的新增-编辑等modal弹窗最多只有4个字符的信息内容

##### 截图&代码：
![123](https://user-images.githubusercontent.com/44168085/231676863-82ea36a8-d68d-4c11-9b66-4203a5d34a1a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
超长省略显示了
