### ISSUE TITLE
使用yarn build打包时出错

### ISSUE THREAD

**Issue by wpb498** [jeecgboot/jeecgboot-vue3#470]
##### 版本号：
3.4.4

##### 问题描述：
使用的是yarn build进行打包，打包过程中总是报错，前一个报错是Missing semicolon，现在报错[vite:build-import-analysis] Parse error @:4:19  
初步判断是代码格式检验的时候出的问题。但不知道怎么解决
##### 截图&代码：
![image](https://user-images.githubusercontent.com/59943849/231927937-7db1251c-fe9b-4a03-b618-a0d7b7f220be.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
前端诡异问题比较多，百度吧
