### ISSUE TITLE
online表单报错，新增表单无法加载初始化数据库属性，无法新增数据库属性

### ISSUE THREAD

**Issue by yuyujoke** [jeecgboot/jeecgboot-vue3#472]
##### 版本号：
3.5.0

##### 问题描述：
online表单报错，新增表单中无法加载初始化数据库属性，数据库属性的表格是空白的，点击新增按钮，无法新增数据库属性

##### 截图&代码：
进入新增表单界面：
Uaught (in promise) Error: [JVxeTable] hidden 组件尚未注册，获取增强失败
    at getEnhanced (enhancedUtils.ts:38:13)
    at useMethods.ts:314:29
    at Array.forEach (<anonymous>)
    at createRow (useMethods.ts:309:41)
    at useMethods.ts:341:33
    at Array.forEach (<anonymous>)
    at Proxy.addOrInsert (useMethods.ts:341:13)
    at Proxy.<anonymous> (useTableSync.js:62:30)
    at Generator.next (<anonymous>)
    at fulfilled (useTableSync.js:5:24)

点击新增按钮，新增数据库属性报错：
[Vue warn]: : Unhandled error during execution of component event handler 
  at <JVxeToolbar size="medium" disabled=false toolbarConfig= {slots: Array(2), btns: Array(3)}  ... > 
  at <ASpin spinning=false wrapperClassName="jeecg-j-vxe-table" > 
  at <JVxeTable ref="tableRef" rowNumber="" rowSelection=""  ... > 
  at <DBAttributeTable ref="dbTable" actionButton=true onAdded=fn<onTableAdded>  ... > 
  at <ATabPane tab="数据库属性" key="dbTable" forceRender=""  ... > 
  at <TabPanelList destroyInactiveTabPane=false id="rc-tabs-2" activeKey="dbTable"  ... > 
  at <InternalTabs activeKey="dbTable" onChange=fn<handleChange3> animated=true  ... > 
  at <ATabs key=0 activeKey="dbTable" onUpdate:activeKey=fn  ... > 
  at <ASpin spinning=false > 
  at <ASpin wrapperClassName="p-2" spinning=false > 
  at <Scrollbar ref="scrollbarRef" class="scroll-container" > 
  at <ScrollContainer ref="wrapperRef" > 
  at <ModalWrapper useWrapper=true footerOffset=0 fullScreen=true  ... > 
  at <ACol span=24 class="jeecg-modal-content" > 
  at <ARow class="jeecg-modal-wrapper" > 
  at <BaseTransition onBeforeEnter=fn<onBeforeEnter> onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave>  ... > 
  at <Transition name="zoom" appear=true enterFromClass="zoom-enter zoom-enter-prepare"  ... > 
  at <Content afterClose=fn<afterClose> footer=undefined zIndex=undefined  ... > 
  at <Dialog afterClose=fn<afterClose> footer=undefined zIndex=undefined  ... > 
  at <Portal getContainer=fn<getContainer2> ref=Ref< Proxy(Object) {…} > > 
  at <PortalWrapper visible=true forceRender=undefined getContainer=undefined > 
  at <DialogWrap afterClose=undefined footer=undefined okButtonProps=undefined  ... > 
  at <AModal width=1200 minHeight=undefined closeFunc=undefined  ... > 
  at <Modal width=1200 visible=true scrollTop=true  ... > 
  at <BasicModal ref="modalRef" title="新增" width=1200  ... > 
  at <CgformModal onRegister=fn<register> onSuccess=fn<reload> > 
  at <CgformIndex onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {…} > key="/online/cgform" > 
  at <KeepAlive key=0 include= ['dashboard-analysis'] > 
  at <RouterView> 
  at <PageLayout> 
  at <LayoutContent> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout class="jeecg-default-layout-main" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout class="ant-layout ant-layout-has-sider" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout class="jeecg-default-layout" > 
  at <DefaultLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {_pStores: {…}, …} > > 
  at <RouterView> 
  at <AppProvider> 
  at <ALocaleProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} > 
  at <App>

aught (in promise) Error: [JVxeTable] hidden 组件尚未注册，获取增强失败
    at getEnhanced (enhancedUtils.ts:38:13)
    at useMethods.ts:314:29
    at Array.forEach (<anonymous>)
    at createRow (useMethods.ts:309:41)
    at useMethods.ts:341:33
    at Array.forEach (<anonymous>)
    at addOrInsert (useMethods.ts:341:13)
    at Object.addRows (useMethods.ts:385:24)
    at onAdd (useToolbar.ts:19:32)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)

附上截图：
![联想截图_20230417092709](https://user-images.githubusercontent.com/39750670/232357507-5d1d662d-2b2f-49ac-a903-cee0044235d1.png)

![联想截图_20230417092732](https://user-images.githubusercontent.com/39750670/232357513-c9609518-5462-4441-be39-7267e3ffe95a.png)

![联想截图_20230417092827](https://user-images.githubusercontent.com/39750670/232357519-89fe62a5-5e98-494b-a6f2-0489c1f275f5.png)

附上log：
[localhost-1681694570822.log](https://github.com/jeecgboot/jeecgboot-vue3/files/11245357/localhost-1681694570822.log)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
hidden组件没有正确注册导致 ,JVxeTable组件已经修复，online下个版本发布

**Comment by zhangdaiscott** [comment]
已经修复 ，请更新代码
