### ISSUE TITLE
online生成下拉联动问题

### ISSUE THREAD

**Issue by fireinjava** [jeecgboot/jeecgboot-vue3#476]
##### 版本号：
3.5.0

##### 问题描述：
online页面，配置下拉联动，按配置文档操作后功能测试，下拉联动没问题，但是生成的代码只是普通的文本框 -___-
[下拉联动](https://help.jeecg.com/online/form/component1.html )

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不是所有的控件都支持生成的
