### ISSUE TITLE
如何将列表操作中的删除功能去掉

### ISSUE THREAD

**Issue by chenglutao** [jeecgboot/jeecgboot-vue3#477]
##### 版本号：
jeecgboot-vue3    v3.4.4last

##### 问题描述：
如何将列表操作中的删除功能去掉

##### 截图&代码：
![image](https://user-images.githubusercontent.com/51188496/232534981-bd6789cc-ad6f-4529-a048-76de2e99c289.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你搜索删除，删掉对应代码即可
