### ISSUE TITLE
online表单日期选择不了

### ISSUE THREAD

**Issue by slin1972** [jeecgboot/jeecgboot-vue3#479]
##### 版本号：

最新master分支

##### 问题描述：

配置表单字段为datetime 且为年月日，demo自带的表单，倒数第二个test_order_main，测试下拉时间选不了，F12没有任何错误输出

##### 截图&代码：
点击日期进行选择之后，选择框依然是空的
![image](https://user-images.githubusercontent.com/7867412/232842025-b26b00af-733c-46cb-bbbf-cf377945cbe8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
刚测试没问题
![image](https://user-images.githubusercontent.com/3162115/232943852-fbefee1b-7945-462f-a38f-eb54cd3b81e9.png)

**Comment by slin1972** [comment]
看我这个视频
https://user-images.githubusercontent.com/7867412/233652489-123427f0-60e2-4184-81cd-f0cd6d77802b.mp4
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
F12看看有错没，我们本地没问题，你自己排查下

**Comment by fireinjava** [comment]
> F12看看有错没，我们本地没问题，你自己排查下

本地开发没问题，但是运行“build:test”打包部署后，就有问题了

**Comment by fireinjava** [comment]
之前用yarn有问题，用pnpm后正常了

**Comment by slin1972** [comment]
@zhangdaiscott @fireinjava 
本地现在没问题， 用pnpm build:test 必现的

把.env.test 改成 .env.sanbox 去启动就正常了，很迷，现在正常了

**Comment by Zorachen2022** [comment]
修改失败，Bei der Konvertierung eines nvarchar-Datentyps in einen datetime-Datentyp liegt der Wert außerhalb des gültigen Bereichs.   保存日期报这个错是为什么呀？
