### ISSUE TITLE
jeecgboot-vue3 3.4.4 低代码平台配置的二级菜单，点击后自动合并

### ISSUE THREAD

**Issue by wallace46886799** [jeecgboot/jeecgboot-vue3#480]
##### 版本号：
3.4.4

##### 问题描述：
将低代码平台对应的功能配置为二级菜单后，点击后自动合并；而手动编写的vue页面配置到二级菜单后，点击后未合并。期望低代码平台对应的功能配置为二级菜单后，点击后保持菜单展开。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
问题已修复，下版本发布
