### ISSUE TITLE
如何实现Tab切换时，保持页面的筛选条件和表格数据不变。

### ISSUE THREAD

**Issue by wallace46886799** [jeecgboot/jeecgboot-vue3#481]
##### 版本号：
jeecgboot-vue3 3.4.4
##### 问题描述：
如何实现Tab切换时，保持页面的筛选条件和表格数据不变，谢谢！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
开启路由缓存

**Comment by wallace46886799** [comment]
但是如果功能是在线表单生成的，是没法用路由缓存的？

**Comment by wallace46886799** [comment]
试了一下，在线表单的功能菜单中设置为路由缓存的话， 还是会发起请求重新渲染页面，还有需要修改的地方吗？

**Comment by fireinjava** [comment]
> 的功能菜单中设置为路由缓存

确实有问题，vue2版本时菜单配置下路由缓存就好了，vue3的应该前端哪有bug
