### ISSUE TITLE
切换用户，权限控制出现问题。

### ISSUE THREAD

**Issue by lshhuhongtao** [jeecgboot/jeecgboot-vue3#482]
##### 截图&代码：{
        title: '计划完成时间',
        dataIndex: 'planEndTime',
        edit: hasPermission('ceshi:edit'),
        editable: true
      },

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
怎么切换的？

**Comment by lshhuhongtao** [comment]
就是退出有单元格编辑权限的用户，然后重新登录没有单元格编辑权限的用户，发现新登录的用户也有单元格编辑权限，刷新页面就没有了。


我们觉得是export const，导出常量的问题，截图是我们自己的解决办法，如果你们有更好的，麻烦能告诉一下，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecgboot-vue3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecgboot-vue3] 切换用户，权限控制出现问题。 (Issue #482)





 
怎么切换的？

**Comment by lshhuhongtao** [comment]
![Snipaste_2023-04-21_09-57-02](https://user-images.githubusercontent.com/46209677/233523365-398390c9-7207-4107-9220-f41d896992ff.png)

**Comment by zhangdaiscott** [comment]
未重现
