### ISSUE TITLE
前端在不登录的情况下可以实现菜单路由、页面显示吗？

### ISSUE THREAD

**Issue by lm627691338** [jeecgboot/jeecgboot-vue3#484]
##### 版本号：
3.4.4

##### 问题描述：

在不登录的情况下（即不启动后台的情况），开发前端页面，可以加载菜单路由吗，然后跳转页面吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以，自己排查前端权限拦截
