### ISSUE TITLE
online报表点击SQL解析，字段文本没有取备注

### ISSUE THREAD

**Issue by slin1972** [jeecgboot/jeecgboot-vue3#485]
##### 版本号：
master 分支

##### 问题描述：
online报表点击SQL解析，字段文本没有取备注

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7867412/233651404-9ba323b8-56b5-4375-8b5d-2013df30024b.png)
![image](https://user-images.githubusercontent.com/7867412/233651552-4a37848f-c8f1-466d-a89e-d073f3dd7e36.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没有取到，就手工设置即可
