### ISSUE TITLE
Table 的 dataIndex  form 的 field 对 a.b.c 形式的支持

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecgboot-vue3#487]
##### 版本号：
3.5.0

##### 问题描述：
Table 的 dataIndex 如果是是a.b.c 形式 看 antd 是支持 后来问了vben 得写出 [a,b,c] 这个形式
form 中field 如果是a.b.c  需要自己重新处理转换一下 

我不知道jeecg里 有没有更好的处理方法？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl
