### ISSUE TITLE
online表单，删除和编辑按钮可以隐藏吗

### ISSUE THREAD

**Issue by slin1972** [jeecgboot/jeecgboot-vue3#489]
##### 版本号：
最新代码

##### 问题描述：
online表单，删除和编辑按钮可以隐藏吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/online/auth/button.html
