### ISSUE TITLE
yarn install报错

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecgboot-vue3#49]
##### 版本号：
1.1.0-bate

##### 问题描述：
vue-print-nb-jeecg-1.0.11.tgz: Request failed 401 Unauthorized，如下图

##### 截图&代码：

![image](https://user-images.githubusercontent.com/14859466/165512902-c8ff524d-b2f8-4661-9ade-fd9e2cf75531.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://www.npmjs.com/package/vue-print-nb-jeecg

**Comment by zhangdaiscott** [comment]
更新代码吧

**Comment by hdtopku** [comment]
> 更新代码吧

已经是最新的，还是报错，vue-print-nb-jeecg改为最新的：^1.0.11，即可
pr：https://github.com/jeecgboot/jeecgboot-vue3/pull/50
