### ISSUE TITLE
动态路由菜单启用了“缓存路由”后，切换tab时页面依旧会刷新

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#490]
##### 版本号：
V3.5.1

##### 问题描述：
路由菜单在启用“是否缓存路由”后，切换tab时页面不会刷新，但动态路由菜单在换切tab时页面依旧会刷新。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
动态路由菜单不刷新那就不对了，数据永远是的老的？

**Comment by citynook** [comment]
如果正常手写代码生成CRUD的页面，开启“是否菜单路由”和“是否缓存路由”这两个选项后，切换tab是不会刷新页面的，能达到保存页面状态的效果。

若是用online表单配置了相同功能的CRUD页面，然后关闭“是否路由菜单”开关，开启“是否缓存路由”开关，在切换tab时依旧会刷新页面。
![image](https://user-images.githubusercontent.com/127393297/233882294-e57877a4-721d-428b-911d-0e86598f5af7.png)

我的目的是想让online表单配置的页面可以达到和手写页面相同的效果，在切换tab时保存页面状态。

**Comment by xiaogangya12138** [comment]
老哥.我们最近也提了一个需求 就是顶部tab栏 切换不刷新页面(都是手动写的页面) 我也打开了:是否路由菜单/是否缓存路由 但是呢 还是达不到页面不刷新的效果(切换时还是有请求) 请老哥指点一下

**Comment by zhangdaiscott** [comment]
动态路由不支持缓存

**Comment by ITyaoji** [comment]
> 

不行啊，非动态路由开启路由缓存，切换tab还是会刷新的

**Comment by xiaogangya12138** [comment]
经过不懈的努力找到了解决办法 是否缓存路由:

**Comment by xiaogangya12138** [comment]
经过不懈的努力找到了解决方法

**Comment by citynook** [comment]
@xiaogangya12138 能分享下解决方案吗？

**Comment by citynook** [comment]
@xiaogangya12138 多谢，我试下~

**Comment by xiaogangya12138** [comment]
@citynook 嗯嗯 试试吧 亲测有效

**Comment by citynook** [comment]
@xiaogangya12138 我试了下没有生效，web重启也一样，不知道啥情况，有空帮看下配置是否有错。

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/7033bc09-17d5-4b9e-b3e8-a6d7c9b7cb02)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/487ad185-66f6-4e1b-a142-4b65b6e4e5b2)

**Comment by citynook** [comment]
@xiaogangya12138 打开“是否路由菜单”开关，刷新后点击菜单，报如下错误：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/6a17e389-1150-40dd-a8fe-04e3fd464f89)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/ab3f9fc2-e7a8-44ec-86cd-f99372bf595a)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/9856ba21-2de3-4f4e-8dd8-8e7342b9de16)

**Comment by xiaogangya12138** [comment]
@citynook 能截图看一下你配置的菜单路径么?

**Comment by citynook** [comment]
@xiaogangya12138 /studio/online/amisPage 是一个vue界面，1404948482是表里保存的记录id，vue页面动态加载这个id的数据，所以是用这个页面可以配置出多个菜单项。

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/e1080ef8-6d0f-44b6-9f72-f66b2e5c6580)

**Comment by xiaogangya12138** [comment]
@citynook  你的访问路径是不是:192.168.31.198:3100/studio/online/amisPage/1 
这样的一个路径 然后后面的 1  可能会随机变?

**Comment by citynook** [comment]
@xiaogangya12138 “1”这个数字可以说是特殊指定的，配置不同的菜单时指定不同的id值，然后在vue页面中用这个id值动态加载后台的数据。我现在只配置了一个这样的动态路由菜单，在tab上切换的时候就会刷新，这两天用你提供的方法试了下，最终报了上午发的那个错误截图。

**Comment by xiaogangya12138** [comment]
@citynook 前一段时间我有看他们的路由逻辑大概是这样的(自己的理解)
1.我们在前端组件这一栏 填写路径后 会自动保存到路由中(相当于我们配置了一个路由路径)
2.在切换tab的时候系统会先去路由找这个路径 然后展示 (就是从新打开路由)
3.我们添加上组件名称 / 前端组件 /打开缓存路由.  应该是触发某种方法 然后把数据进行缓存(换句话说是就是切换tab时不在刷新路由而是切换)

综上所述 不知道 系统是否支持动态的  `前端组件`内的路径  因为你的 1 并不是路径(系统找到不到该路径 所以报错: undefined )
你可以尝试一下 写两个vue页面 然后配上 前端组件(vue页面路径),同时打开相互切换 查看效果
