### ISSUE TITLE
[DOM] Found 2 elements with non-unique id

### ISSUE THREAD

**Issue by Evan98521** [jeecgboot/jeecgboot-vue3#493]
##### 版本号：
3.5.1

##### 问题描述：

> 系统管理->用户管理->编辑

> 控件绑定的字段名相同，存在多个相同的

##### 截图&代码：
`<input placeholder="请输入名字" type="like" id="form_item_realname" trim="false" getpopupcontainer="trigger => trigger.parentNode" codefield="realname" formvalues="[object Object]" class="ant-input">`
`<input placeholder="请输入用户姓名" type="text" id="form_item_realname" getpopupcontainer="trigger => trigger.parentNode" codefield="realname" formvalues="[object Object]" class="ant-input">`

> id="form_item_realname" id重复，

> 编辑表单中的用户姓名realname和列表查询表单中的名字realname的id重复

> username、realname、phone等字段都重复

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Evan98521** [comment]
> 配合下截图



> 配合下截图

就第一次点击编辑的时候控制台才会出现这个警告，清空控制台后再点击编辑，警告不会复现；刷新页面再点击第一次会出现。
警告的原因是
编辑表单中的用户姓名realname（username、realname、phone）和列表查询表单中的名字realname（username、realname、phone）的id重复，但在user.data.ts文件中不能修改id

**Comment by Evan98521** [comment]
> 配合下截图
演示网站
系统管理-》系统角色-》操作->用户-》操作->编辑
控制台也会有一样的警告问题

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
可以临时在user.data.ts文件中设置查询表单绑定的id值处理
 ```
{
    label: '名字',
    field: 'realname',
    component: 'JInput',
    colProps: { span: 6 },
    componentProps: {
       id: 'name'
    }
  }
```
