### ISSUE TITLE
vite等依赖冲突问题

### ISSUE THREAD

**Issue by damage-o** [jeecgboot/jeecgboot-vue3#496]
##### 截图&代码：

 WARN  Issues with peer dependencies found
.
├─┬ vite-plugin-optimize-persist 0.1.2
│ └── ✕ unmet peer vite@^2.0.0: found 3.2.5
├─┬ vite-plugin-package-config 0.1.1
│ └── ✕ unmet peer vite@^2.0.0: found 3.2.5
└─┬ emoji-mart-vue-fast 11.2.0
  └─┬ vue-virtual-scroller 1.1.2
    ├── ✕ unmet peer vue@^2.6.11: found 3.2.47
    └─┬ vue-resize 0.4.5
      └── ✕ unmet peer vue@^2.3.0: found 3.2.47

The integrity of 17116 files was checked. This might have caused installation to take longer.

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
无法重现
