### ISSUE TITLE
JAR分离打包部署，启动程序时包数组索引越界异常。从而程序运行不起来

### ISSUE THREAD

**Issue by yuanjiangzhen** [jeecgboot/jeecgboot-vue3#498]
##### 版本号：
3.5.0

##### 问题描述：
JAR分离打包部署，启动程序时包数组索引越界异常。从而程序运行不起来

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18722441/234308756-9dfacfcb-7d5f-49b5-b104-4087f0c1f94f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
74
看看是不是启动编码问题
