### ISSUE TITLE
.env.development配置代理不生效

### ISSUE THREAD

**Issue by damage-o** [jeecgboot/jeecgboot-vue3#499]
##### 截图&代码：
.env.development配置：
# 跨域代理，您可以配置多个 ,请注意，没有换行符
VITE_PROXY = [["/jeecgboot","http://127.0.0.1:9999"],["/upload","http://localhost:3300/upload"]]
# 控制台不输出
VITE_DROP_CONSOLE = false
#后台接口父地址(必填)
VITE_GLOB_API_URL=/jeecgboot
#后台接口全路径地址(必填)
VITE_GLOB_DOMAIN_URL=http://127.0.0.1:9999/

gateway服务正常，并可以生成验证码图片
http://127.0.0.1:9999/sys/randomImage/1629428467008?_t=1682472977400
{"success":true,"message":"","code":0,"result":"data:image/jpg;base64,/9j/4AAQSkZJ**********c56nAH8gKfRRQBGYIWnWdoozKowshUbgPY/iaWKJIYxHGu1F6DPT2Ht7dqKKAH0iqqjCqAMk4A7nk0UUALRRRQAgVVLEKAWOSQOp6f0FLRRQAiIsaKiKFVRgKBgAUtFFAH//Z","timestamp":1682474333222}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么意思？

**Comment by damage-o** [comment]
> 什么意思？

目前使用的springcloud, system-cloud和gateway服务正常了，并且可以使用浏览器生成验证码图片，
但在启动好的前端vue无法生成验证码图片，提示：“网络请求错误,未找到该资源!”
配置如上，不知道是什么原因。

**Comment by damage-o** [comment]
> 什么意思？

与之前的3.4.4版本的.env.development配置内容是一样的。

**Comment by damage-o** [comment]
访问http://127.0.0.1:3100/jeecgboot/sys/randomImage/1629428467008?_t=1682472977400 时页面反馈：


Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Wed Apr 26 10:12:23 CST 2023
[f5684802-91] There was an unexpected error (type=Not Found, status=404).

**Comment by damage-o** [comment]
问题已解决，在git上下载最新代码（不是release 3.5.1）
