### ISSUE TITLE
在线开发下的菜单无法访问

### ISSUE THREAD

**Issue by suqisuqi** [jeecgboot/jeecgboot-vue3#501]
##### 截图&代码：
<img width="1280" alt="1682480213516" src="https://user-images.githubusercontent.com/28977985/234463680-aadf63a2-c289-4af8-bdaa-9d73712babe4.png">

<img width="1280" alt="1682480263849" src="https://user-images.githubusercontent.com/28977985/234463778-be8c335f-8b78-41ee-be46-18be9fb71943.png">

**Comment by zhangdaiscott** [comment]
？

**Comment by suqisuqi** [comment]
> ？

我的问题没表述清楚吗。生成代码的界面打不开，请问是啥原因呀

**Comment by zhangdaiscott** [comment]
跟sys_permission_v2有什么关系

**Comment by suqisuqi** [comment]
> 跟sys_permission_v2有什么关系

sys_permission表里没有代码生成的相关菜单，我想用代码生成的功能，把sys_permission_v2表里代码生成的相关菜单复制到sys_permission表里了

**Comment by zhangdaiscott** [comment]
怎么可能没有，还原自己的修改，再看问题

**Comment by suqisuqi** [comment]
> 怎么可能没有，还原自己的修改，再看问题
sys_permission表里数据是从后台代码的db里初始化的，地址是：https://github.com/jeecgboot/jeecg-boot/blob/master/db/jeecgboot-mysql-5.7.sql  
是用这个sql语句里的sys_permission吧。确实没有代码生成的相关菜单，您确认一下有吗
