### ISSUE TITLE
online表单开发，新增和编辑时，数据库属性标签页的新增报错，无法新增

### ISSUE THREAD

**Issue by kevinboy322** [jeecgboot/jeecgboot-vue3#504]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/42327860/234819574-fb6e5ff8-4387-4dff-bab5-4c6160c10cbb.png)
![image](https://user-images.githubusercontent.com/42327860/234820234-457dbab4-4e2d-4ab4-a671-06e0033a9721.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你更新最新代码，最近修复了
