### ISSUE TITLE
生成代码VUE3还是原生 TABLE表头都不会固定，超过10行一页，整页会随着滚动

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecgboot-vue3#505]
##### 问题描述：

生成代码不论是VUE3还是原生的 TABLE表头都不会固定，超过10行一页，整页随着滚动

##### 截图&代码：
![28104017](https://user-images.githubusercontent.com/54636793/235041499-5585add8-a77a-4268-8e98-1ce31654d024.png)

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
您只需要将list页面中的`useListPage`,  `tableProps`属性中的`canResize`改成true，或者去掉就可以了
![image](https://user-images.githubusercontent.com/30997828/236160438-cc05de64-6ad5-4e77-ba57-29c3594f3e7b.png)

**Comment by lijinlang** [comment]
> 您只需要将list页面中的`useListPage`, `tableProps`属性中的`canResize`改成true，或者去掉就可以了，默认为true ![image](https://user-images.githubusercontent.com/30997828/236160438-cc05de64-6ad5-4e77-ba57-29c3594f3e7b.png)

谢谢您，刚试了把canResize改为true就固定住了，现在又出现底下合计区域多出了一个滚动条，上面列横向滚动，合计不会随着滚动，如果把canResize改为false的话，合计会随着上面的列横向滚动，但是表头又不会固定，感觉还是有点问题
