### ISSUE TITLE
引入fengmap.js插件 本地启动正常 部署到测试环境报错

### ISSUE THREAD

**Issue by wangxs2** [jeecgboot/jeecgboot-vue3#507]
##### 版本号：
3.4.5

##### 问题描述：
引入fengmap.js插件 本地启动正常 部署到测试环境报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/37064079/235283425-90d2e200-61af-419e-b5ff-dd35aabd0ab3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
个性化的改造，得自己研究
