### ISSUE TITLE
如何实现路由参数改变，页面不刷新

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#509]
##### 版本号：
3.5.1

##### 问题描述：

如何实现路由参数改变，页面不刷新

类似于有道云笔记，打开新的文件夹，路由参数变了，但是页面不进行刷新

**Comment by qinghechaoge** [comment]
还没解决 这么着急关掉干什么？

**Comment by zhangdaiscott** [comment]
只负责bug处理，需求请自己解决
