### ISSUE TITLE
online 表单点击新增，表单弹窗默认全屏

### ISSUE THREAD

**Issue by 1033965** [jeecgboot/jeecgboot-vue3#512]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 1033965** [comment]
![image](https://user-images.githubusercontent.com/105904512/236596545-2100eb44-bada-462f-ad62-95e7c1abd1b9.png)
补充附表设计页面

**Comment by zhangdaiscott** [comment]
全屏设置不是给代码生成用的
