### ISSUE TITLE
生成代码后控件对不齐有没有相关属性

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecgboot-vue3#513]
##### 问题描述：

生成代码后控件对不齐，参照文档设置了colProps总是对不齐

##### 截图&代码：

![微信图片_20230506135840](https://user-images.githubusercontent.com/54636793/236603473-4b9766c1-5515-4418-9c8b-0db2e680d3c8.png)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
试试设置baseColProps看是否对齐，![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/46c360b1-c3fb-4068-9304-80b6e3367977)

**Comment by lijinlang** [comment]
> 试试设置baseColProps看是否对齐 ![image](https://user-images.githubusercontent.com/65587928/238848502-46c360b1-c3fb-4068-9304-80b6e3367977.png)
> 
> 日期控件可以设置宽度来达到对齐效果 ![image](https://user-images.githubusercontent.com/65587928/238849898-746ff733-bf82-4459-92e7-85bbbe6b20fc.png)
> 
> ![image](https://user-images.githubusercontent.com/65587928/238850353-ce2254d1-791f-4207-9251-c8896b803154.png)

谢谢您，baseColProps: {span: 8} 生成代码默认就有的，日期宽度是可以通过style可以解决，另外那个备注不能对齐应该是比例问题，现在好像没有相应的属性可以去调比例，应该还是要作者才能解决。
