### ISSUE TITLE
jeecgboot-vue3.5.1 在chrome81及以下版本浏览器上无法加载出页面

### ISSUE THREAD

**Issue by damage-o** [jeecgboot/jeecgboot-vue3#514]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18347954/236617349-9c1bc841-bf24-4a9a-99dd-b5b40b1d2cfd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
太老的版本不支持，可以用vue2版本
