### ISSUE TITLE
Error: [JVxeTable] hidden 组件尚未注册，获取增强失败

### ISSUE THREAD

**Issue by baobeiyatou** [jeecgboot/jeecgboot-vue3#515]
##### 版本号：
3.5.0

##### 问题描述：
前端Online表单开发功能，点击新增提示
Uncaught (in promise) Error: [JVxeTable] hidden 组件尚未注册，获取增强失败

##### 截图&代码：

![image](https://user-images.githubusercontent.com/39516154/236748936-cebd9db6-a534-4f94-97dd-35b2107927cc.png)
![image](https://user-images.githubusercontent.com/39516154/236748960-a69ddedf-f1ba-4b76-b2e4-0fc8f21e11e3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新代码到最新
