### ISSUE TITLE
table列如何设置filters根据接口返回值来定义

### ISSUE THREAD

**Issue by CaoUncle** [jeecgboot/jeecgboot-vue3#518]
##### 问题描述：
table列如何设置filters根据接口返回值来定义

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by CaoUncle** [comment]
sq是啥？

**Comment by CaoUncle** [comment]
> sq

sq是啥

**Comment by yang-xianzhu** [comment]
同问，目前找不到怎么关联到后端配置的字典，如果没有，我觉得可以扩展一下

**Comment by yang-xianzhu** [comment]
> > sq
> 
> sq是啥

找到对应方法了
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/92789120/5aa4105a-d179-474b-b993-5489a7081f5b)
