### ISSUE TITLE
生成代码后如何调用积木报表

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecgboot-vue3#519]
##### 问题描述：

在online中配置好积木报表后，生成代码没有了打印功能，这个该如何调用

##### 截图&代码：

![微信图片_20230509171922](https://user-images.githubusercontent.com/54636793/237058216-c99ca2e5-3fb7-4945-bb0f-c078f4ad36d9.png)

**Comment by zhangdaiscott** [comment]
得手工集成了，就是点击打开href即可
