### ISSUE TITLE
富文本编辑器不支持从word粘贴图文

### ISSUE THREAD

**Issue by maxiong1** [jeecgboot/jeecgboot-vue3#52]
##### 版本号：

当前演示版本
##### 问题描述：

富文本编辑器不支持从word粘贴图文
##### 截图&代码：
富文本编辑器不支持从word粘贴图文

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
yf

**Comment by accpman** [comment]
不支持
