### ISSUE TITLE
JVxeTable如何实现双击单元格，显示清除跟选择的图片按钮

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecgboot-vue3#520]
##### 问题描述：
请教下在主子表中，JVxeTable如何实现双击单元格，显示一个清除跟选择的图片按钮，可以在单元格中使用插槽吗，另外双击占满整个单元格，这种有地方可以修改吗

##### 截图&代码：

![微信图片_20230510173102](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/5f151228-7635-4764-a3f1-4cec78ca4f2c)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/63a01f70-532d-48ef-8b1b-5415f4ec9197)

**Comment by zhangdaiscott** [comment]
自己改源码吧
