### ISSUE TITLE
点击提交按钮之后，列表页面没有刷新，必须在列表页面手动点击刷新按钮才会刷新

### ISSUE THREAD

**Issue by YaoYaqiong** [jeecgboot/jeecgboot-vue3#525]
版本号： 3.5.1

前端版本：vue3版

问题描述：点击提交按钮之后，列表页面没有刷新，必须在列表页面手动点击刷新按钮才会刷新。

截图&代码：
<img width="483" alt="截屏2023-05-12 09 28 03" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/71279930/2d26deb7-1e78-42da-9ced-5490c2cd67f6">

**Comment by zhangdaiscott** [comment]
是你自己写的代码吧，参考下我们默认生成的代码怎么写的

**Comment by YaoYaqiong** [comment]
默认的reload()方法调用之后没有效果，如果使用了window.location.reload()会全局刷新，但是这个不满足需求

**Comment by YaoYaqiong** [comment]
![Uploading 截屏2023-05-12 10.38.11.png…]()
![Uploading 截屏2023-05-12 10.50.48.png…]()

**Comment by zhangdaiscott** [comment]
图裂

**Comment by YaoYaqiong** [comment]
已解决 感谢感谢
