### ISSUE TITLE
RangePicker 设置预设范围按钮样式问题

### ISSUE THREAD

**Issue by xiaogangya12138** [jeecgboot/jeecgboot-vue3#526]
##### 截图&代码：
代码:   {
    field: 'orderTime',
    component: 'RangePicker',
    label: '下单时间',
    componentProps: {
      valueType: 'Date',
      showTime: true,
      ranges: {
        Today: [dayjs(), dayjs()] as RangeValue,
        'This Month': [dayjs(), dayjs().endOf('month')] as RangeValue,
      },
    },
    colProps: {
      span: 5,
    },
  },

截图:
![951683857590_ pic](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/864ca81e-de26-4c20-99cb-f939ce7a4706)

但是如果直接使用 RangePicker 组件不会有此问题 
代码:<a-form-item label="下单日期" name="rangeTime" class="m-bottom-10">
            <a-range-picker format="YYYY-MM-DD" v-model:value="searchModular.timeValue" :showToday="false" :onChange="onChange" :ranges="ranges" />
          </a-form-item>

截图:
![961683857766_ pic](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/e395ac5c-f700-452f-a4df-33f4a19d2db0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lsqGitHub716** [comment]
更新到最新版试试，测试未发现你说的情况
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/eb39cd3c-ab44-4478-bdc9-5020c7041879)

**Comment by xiaogangya12138** [comment]
感谢您回复!
我再补充一下问题出现的原因,我整体把代码贴出来
代码:
<template>
  <BasicTable @register="registerTable" />
</template>
<script lang="ts" setup>
  import { BasicTable } from '/@/components/Table';
  import { useListPage } from '/@/hooks/system/useListPage';
  import dayjs, { Dayjs } from 'dayjs';
  import { FormSchema } from '/@/components/Table';
  const searchFormSchema: FormSchema[] = [
    {
      field: 'orderTime',
      component: 'RangePicker',
      label: '下单时间',
      componentProps: {
        valueType: 'Date',
        showTime: true,
        ranges: {
          今天: () => {
            [dayjs(), dayjs()];
          },
          昨天: () => {
            [dayjs().subtract(1, 'day'), dayjs().subtract(1, 'day')];
          },
          近7天: () => {
            const startDate = dayjs().subtract(6, 'day').startOf('day');
            const endDate = dayjs().endOf('day');
            return [startDate, endDate];
          },
          本月: () => {
            const startDate = dayjs().startOf('month');
            const endDate = dayjs().endOf('month');
            return [startDate, endDate];
          },
        },
      },
      colProps: {
        span: 5,
      },
    },
  ];

  const { tableContext } = useListPage({
    designScope: 'sup-template',
    tableProps: {
      title: '',
      rowKey: 'orderId',
      formConfig: {
        schemas: searchFormSchema,
        fieldMapToTime: [
          ['createTime', ['createAtBeginDate', 'createAtEndDate'], 'YYYY-MM-DD HH:mm:ss'],
          ['orderTime', ['orderAtBeginDate', 'orderAtEndDate'], 'YYYY-MM-DD HH:mm:ss'],
        ],
      },
    },
  });
  const [registerTable] = tableContext;
</script>

效果图:
![截图](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/72334da3-e46d-4071-bdb8-d346cb82a7dd)


您上面提到的是在 BasicForm 组件中是用  component: 'RangePicker', 这里是在BasicTable的组件中使用 然后出现这样的情况 初步猜测可能是 BasicForm与 BasicTable 之间存在一些差异 导致这样的结果!
望回复,谢谢🙏

**Comment by xiaogangya12138** [comment]
感谢您回复!
我再补充一下问题出现的原因,我整体把代码贴出来
代码:
<template>
  <BasicTable @register="registerTable" />
</template>
<script lang="ts" setup>
  import { BasicTable } from '/@/components/Table';
  import { useListPage } from '/@/hooks/system/useListPage';
  import dayjs, { Dayjs } from 'dayjs';
  import { FormSchema } from '/@/components/Table';
  const searchFormSchema: FormSchema[] = [
    {
      field: 'orderTime',
      component: 'RangePicker',
      label: '下单时间',
      componentProps: {
        valueType: 'Date',
        showTime: true,
        ranges: {
          今天: () => {
            [dayjs(), dayjs()];
          },
          昨天: () => {
            [dayjs().subtract(1, 'day'), dayjs().subtract(1, 'day')];
          },
          近7天: () => {
            const startDate = dayjs().subtract(6, 'day').startOf('day');
            const endDate = dayjs().endOf('day');
            return [startDate, endDate];
          },
          本月: () => {
            const startDate = dayjs().startOf('month');
            const endDate = dayjs().endOf('month');
            return [startDate, endDate];
          },
        },
      },
      colProps: {
        span: 5,
      },
    },
  ];

  const { tableContext } = useListPage({
    designScope: 'sup-template',
    tableProps: {
      title: '',
      rowKey: 'orderId',
      formConfig: {
        schemas: searchFormSchema,
        fieldMapToTime: [
          ['createTime', ['createAtBeginDate', 'createAtEndDate'], 'YYYY-MM-DD HH:mm:ss'],
          ['orderTime', ['orderAtBeginDate', 'orderAtEndDate'], 'YYYY-MM-DD HH:mm:ss'],
        ],
      },
    },
  });
  const [registerTable] = tableContext;
</script>

效果图:
![截图](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/366101f2-84c9-402a-8b00-84e71f12d2f0)

您上面提到的是在 BasicForm 组件中是用 component: 'RangePicker', 这里是在BasicTable的组件中使用 然后出现这样的情况 初步猜测可能是 BasicForm与 BasicTable 之间存在一些差异 导致这样的结果!
望回复,谢谢🙏

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by xiaogangya12138** [comment]
请问 能否贴下一修改的地方 我们直接修改?

**Comment by xiaogangya12138** [comment]
如果改动牵扯的地方不多 我们就在本地修改了

**Comment by lsqGitHub716** [comment]
BasicTable.vue 组件增加样式

```
.ant-picker-preset {
    .ant-tag {
      margin-right: 8px !important;
    }
  }
```
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/3cb4614a-f7b2-4d62-ba39-9ba92b268a3e)

**Comment by xiaogangya12138** [comment]
谢谢
