### ISSUE TITLE
jeecgboot-vue3版本现在支持qiankun子应用吗？

### ISSUE THREAD

**Issue by lm627691338** [jeecgboot/jeecgboot-vue3#529]
##### 版本号：
3.5.0

##### 问题描述：
是否支持qiankun子应用？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
支持默认把相关代码去掉了，自己补上即可
