### ISSUE TITLE
用户管理处编辑了用户的部门后，表格没刷新

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#53]
##### 版本号：
3.2.0

##### 问题描述：
用户管理处编辑了用户的部门后，表格没刷新

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/165721041-a44c79c5-352d-4495-b84c-2af01c04c894.png)

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
解决，下个版本发布
