### ISSUE TITLE
JVxeTable 的JVxeTypes.image类型，无法全部删除上传图片

### ISSUE THREAD

**Issue by sfox-xg** [jeecgboot/jeecgboot-vue3#530]
##### 问题描述：
JVxeTable 的JVxeTypes.image类型，无法全部删除上传图片

##### 截图&代码：
src/components/JVxeCustom/src/hooks/useFileCell.ts 中
  // 更多上传回调
  function onModalChange(path) {
    if (path) {
      innerFile.value.path = path;
      handleChangeCommon(innerFile.value);
    }
  }
应改为：
  function onModalChange(path) {
    if (path) {
      innerFile.value.path = path;
      handleChangeCommon(innerFile.value);
    } else {
      handleChangeCommon(null);
    }
  }

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl
