### ISSUE TITLE
在线开发，当有多个附表时，查看详情，附表的界面出现错乱

### ISSUE THREAD

**Issue by BadSmile01** [jeecgboot/jeecgboot-vue3#532]
##### 版本号：
3.5.1

##### 问题描述：
在线开发，配置一主二附表的时候，在功能测试时，使用查看详情功能时，点击标签页切换附表的界面时，界面排版会出现错乱，规律是默认显示的附表界面是正确的，切换到另外一个布局是乱的

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/97794e67-f6dd-4198-8b37-9ff9dd898758)

![22](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/5645fa75-814e-4c2b-a340-548c1aa989f5)

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布

**Comment by qinghechaoge** [comment]
你的在线表单 怎么是jvxetable风格的  我生成的代码 都是BasicTable风格的呢
