### ISSUE TITLE
在线开发，表描述无法同步到数据

### ISSUE THREAD

**Issue by BadSmile01** [jeecgboot/jeecgboot-vue3#534]
##### 版本号：
3.5.1

##### 问题描述：
在线开发，表描述无法同步到数据

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/d7e53f0d-f807-4973-88f5-611cf0eaacc2)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/c8c7936a-724d-4006-86b7-8e6dca826a89)

**Comment by zhangdaiscott** [comment]
这个未做，不需要
