### ISSUE TITLE
在线开发，编辑时字典绑定的字段无法正确回显字典名称

### ISSUE THREAD

**Issue by BadSmile01** [jeecgboot/jeecgboot-vue3#535]
##### 版本号：
3.5.1

##### 问题描述：
绑定了数据字典的字段，在“编辑”的时候无法回显字典名称，但是列表、详情、搜索框中均能正确回显

##### 截图&代码：
![100](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/2fb43a50-443e-4235-9d41-4237b468d625)

![200](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/068f4bde-4544-4930-854d-a30a3736ea24)

![300](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/028e6345-8514-4add-8a8e-835d8476abfd)

![400](https://github.com/jeecgboot/jeecgboot-vue3/assets/12042770/02cf3745-476b-4649-848d-614f255f9b9f)

**Comment by zhangdaiscott** [comment]
有什么特殊的，请详细说明

**Comment by BadSmile01** [comment]
当单击编辑时，绑定了数据字典的字段，应该能正确显示出来字典的neme，但是目前只会显示该字段实际数据库库中的值，比如状态字段：1 表示 正常，0表示冻结，绑定了数据字典，那么在界面上查看和列表中，状态字段均只能看到正常/冻结这是正确的，但是在编辑的时候，却只能显示1/0 ，相当于把数据库中实际的值显示出来了，应该自动显示对应的字典值才对，见上面反馈时的图一，显示的是1，我其实配置的是下拉列表控件，应该自动选中1对应的字典值“在线”才对

**Comment by climpeaker** [comment]
对，我也遇到类似情况了，一些补充一个issue

**Comment by BadSmile01** [comment]
> 有什么特殊的，请详细说明

已经补充，请帮忙看下

**Comment by zhangdaiscott** [comment]
字段类型是？

**Comment by BadSmile01** [comment]
> 字段类型是？

int类型的

**Comment by BadSmile01** [comment]
> 字段类型是？

应该是个bug吧，字段修改为String类型就可以了，int类型就不行

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布
