### ISSUE TITLE
docker 发布后的前端登录页刷新 报错

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#536]
##### 版本号：

3.4.4

##### 问题描述：
docker 发布后的前端登录页刷新 报错 403 Forbidden

不加/login正常，进去页面后 也都正常可以刷新
就只有加了/login情况会报错
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/fb13c234-3f43-4711-b620-d1809364b527)

**Comment by zhangdaiscott** [comment]
加上这段试试
https://help.jeecg.com/publish/quick.html
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/2491f8b0-5927-4bd7-b8ea-ac4bd2f0f002)

**Comment by qinghechaoge** [comment]
> 加上这段试试 https://help.jeecg.com/publish/quick.html ![image](https://user-images.githubusercontent.com/3162115/238935615-2491f8b0-5927-4bd7-b8ea-ac4bd2f0f002.png)

已经加过了，不加这段，所有的页面都不能刷新。目前只是登录页不能刷新

**Comment by qinghechaoge** [comment]
解决了，因为我静态文件下也有一个login文件夹导致的
