### ISSUE TITLE
JSelectDept组件受 dynamicDisabled 影响？

### ISSUE THREAD

**Issue by Glory-W** [jeecgboot/jeecgboot-vue3#538]
##### 版本号：
3.5.1

##### 问题描述：
useForm方式使用表单；
是否授权给所有人勾选时，其他项禁用（如图二）；
是否授权给所有人未勾选时，其他项可选择，但是部门组件点击选择，弹窗内的部门树是禁用状态，这是什么原因啊？（如图三）。

##### 截图&代码：
图一：
<img width="1080" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39987019/12f26ff6-1bfd-4abb-a6a8-b0306f9a41fa">
图二：
<img width="553" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39987019/877a0efb-0008-458a-9280-66065b7d6869">
图三：
<img width="669" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39987019/479ff4a1-7e59-4e93-8843-2ec86ee5f483">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by Glory-W** [comment]
@zhangdaiscott 什么意思啊？

**Comment by lsqGitHub716** [comment]
首先dynamicDisabled 设置后确实会被当成参数传递给组件；
其次按照您的写法测试，未发现您说的问题，您是否还有其他特殊配置？
[测试](https://i.imgtg.com/2023/05/22/OaqUBC.gif)

**Comment by Glory-W** [comment]
@lsqGitHub716 
<img width="1114" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39987019/9dfc8ce6-ff8a-4bcc-8ed4-ab2a5954c95a">
<img width="713" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39987019/465f8aed-b692-4635-ac16-58500576389e">
好像没做什么特殊的配置，这样的写法有问题么？

**Comment by lsqGitHub716** [comment]
写法没看出啥问题，但是你那边为什么在不禁用状态下，打开部门的modal，内部还是禁用的呢？我这写的和你一样了都，也没复现出来
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/edbcd561-55a9-402a-ad1b-6c47ac814bd8)

**Comment by Glory-W** [comment]
@lsqGitHub716 useForm写法一致，问题是否出在 JSelectDept 组件上面？我这边代码与github 上代码是一致的。

**Comment by lsqGitHub716** [comment]
你可以先临时在JSelectDept.vue的getBindValue属性中定义disabled，防止dynamicDisabled 污染；
按照你的设置，应该正常情况下，禁用了，这个组件也点不开；点开了，应该也就是非禁用的状态
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/b79548ef-86a0-4a48-8778-94c0dcc27f9e)

**Comment by Glory-W** [comment]
@lsqGitHub716 
<img width="801" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39987019/a3f18463-36de-4e68-a3f2-3a9354d30086">
去掉这个默认值就好了，这边不能设置默认值？

**Comment by lsqGitHub716** [comment]
问题已修改，下版本发布
