### ISSUE TITLE
树字典，勾选，然后批量删除，系统错误

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#54]
##### 版本号：
3.2.0

##### 问题描述：
树字典，勾选，然后批量删除，系统错误

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/165748339-b0ff5e08-bc64-4793-8dd7-3ae0ffd0877f.png)

**Comment by zhangdaiscott** [comment]
sq

**Comment by 1298191366** [comment]
已修复，待新版本发布
