### ISSUE TITLE
子表新增记录时，JPopup param 定义参数如何传入主表id值？

### ISSUE THREAD

**Issue by 45592858** [jeecgboot/jeecgboot-vue3#540]
##### 版本号：
3.5.0

##### 问题描述：
子表新增记录时，JPopup param 定义参数如何传入主表id值？详细见附图

##### 截图&代码：

![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/17882261/6c8a7420-bee2-48ce-b056-dbf7628593fa)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
formModel表单的双向绑定对象，这个里面包含表单的所有数值
```
{ 
  component:'Input',
  componentProps: ({ schema, formActionType, formModel }) => {
    return {
      // xxxx props
      }
    };
  };
}
```

**Comment by 45592858** [comment]
尝试了，但不成功，代码及现象如下，求指教：

**Comment by 45592858** [comment]
浏览器控制台日志：打开对话框，没打开下拉列表，就已经请求了一次 online report，并且是 404 异常
SxdsjzxptExamSxkcKtkSxsCq.data.ts:240 from data.ts: undefined
SxdsjzxptExamSxkcKtkSxsCq.data.ts:253 into 2222222222222222
SxdsjzxptExamSxkcKtkSxsCqXsModal.vue:32 from Modal: Proxy(Object) {mainId: '1673974131180208130'}
SxdsjzxptExamSxkcKtkSxsCq.data.ts:240 from data.ts: 1673974131180208130
SxdsjzxptExamSxkcKtkSxsCq.data.ts:242 into 1111111111111111
usePopBiz.ts:539 params {pageNo: 1, pageSize: 10, onlRepUrlParamStr: ''}
GroupRequest.ts:11 --------popup----------getFrom  DB-------with---no--groupId 
GroupRequest.ts:11 --------popup----------getFrom  DB-------with---no--groupId 
xhr.js:210     GET http://localhost:3100/jeecgboot/online/cgreport/api/getData/?pageNo=1&pageSize=10&onlRepUrlParamStr=&_t=1687945183005 404 (Not Found)
dispatchXhrRequest @ xhr.js:210
xhrAdapter @ xhr.js:15
dispatchRequest @ dispatchRequest.js:58
Promise.then（异步）
request @ Axios.js:88

Modal file 的代码：
    //接收主表id
    const mainId = inject('mainId');
    // Emits声明
    const emit = defineEmits(['register','success']);
    const isUpdate = ref(true);
    //表单配置
    const [registerForm, {setProps,resetFields, setFieldsValue, validate}] = useForm({
        //labelWidth: 150,
        schemas: sxdsjzxptExamSxkcKtkSxsCqXsFormSchema,
        showActionButtonGroup: false,
        baseColProps: {span: 24}
    });
    //表单赋值
    const [registerModal, {setModalProps, closeModal}] = useModalInner(async (data) => {
        //重置表单
        await resetFields();
        setModalProps({confirmLoading: false,showCancelBtn:!!data?.showFooter,showOkBtn:!!data?.showFooter,minHeight:380});
        isUpdate.value = !!data?.isUpdate;
        console.log("from Modal:", data.record);
        //if (unref(isUpdate)) {
            //表单赋值
            await setFieldsValue({
                ...data.record,
            });
        //}
        // 隐藏底部时禁用整个表单
       setProps({ disabled: !data?.showFooter })
    });
    //设置标题
    const title = computed(() => (!unref(isUpdate) ? '新增' : '编辑'));
    //表单提交事件
    async function handleSubmit(v) {


data.ts 的代码：
export const sxdsjzxptExamSxkcKtkSxsCqXsFormSchema: FormSchema[] = [
  // TODO 子表隐藏字段，目前写死为ID
  {
    label: '',
    field: 'id',
    component: 'Input',
    show: false
  },
  {
    label: '',
    field: 'mainId',
    component: 'Input',
    show: false
  },
  {
    label: '姓名',
    field: 'name',
    component: 'JPopup',
    componentProps:({ schema, formActionType, formModel }) => {
      let { setFieldsValue } = formActionType;
      //console.log(schema);
      //console.log(formModel);
      console.log("from data.ts:", formModel.mainId);
      if (formModel.mainId) {
        console.log("into 1111111111111111");
        let tmpId = `'${formModel.mainId}'`;
        return {
          setFieldsValue,
          code: 'report_student_cqfilter',
          //param: {mainid: "'1654777165625425921'"},
          param:  {mainid: tmpId},
          fieldConfig: [{ source: 'id', target: 'studentId' }, { source: 'name', target: 'name' }, { source: 'student_no', target: 'studentNo' }],
          multi: true,
        }
      } else {
        console.log("into 2222222222222222");
        return {
          setFieldsValue,
          code: 'report_student',
          fieldConfig: [{ source: 'id', target: 'studentId' }, { source: 'name', target: 'name' }, { source: 'student_no', target: 'studentNo' }],
          multi: true,
        }
      }
    },
