### ISSUE TITLE
登录页报错

### ISSUE THREAD

**Issue by lhzlovewyp** [jeecgboot/jeecgboot-vue3#542]
##### 版本号：
3.5.1

##### 问题描述：
访问登录页面报错，登录页面无法打开，控制台有js报错

##### 截图&代码：
<img width="972" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/10278542/57b2e538-3377-4c65-97aa-3e0d27e8c080">
控制台报错代码：
<img width="699" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/10278542/fe98c430-7942-45f7-baa6-4c488d5c1230">

**Comment by zhangdaiscott** [comment]
确认下依赖安装或者node版本，这是环境问题
