### ISSUE TITLE
UserSelectModal被引用但是没被使用，造成/sys/user/list接口被乱请求现象

### ISSUE THREAD

**Issue by 33033624** [jeecgboot/jeecgboot-vue3#543]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/19551550/642a02c5-2403-4f24-8542-531d816a78fe)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by lsqGitHub716** [comment]
功能正在完善中，后期UserSelectModal会被用到，您那边暂时用不到，可以先删掉
