### ISSUE TITLE
报表设计器404

### ISSUE THREAD

**Issue by JackFan90** [jeecgboot/jeecgboot-vue3#544]
##### 版本号：
3.5.1

##### 问题描述：
前后端都是最新版本的代码，报表设计器无法打开，报404

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by JackFan90** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/58178594/22522671-2eac-4159-8f61-ae7539661950)

**Comment by zhangdaiscott** [comment]
自己排查

**Comment by JackFan90** [comment]
找不到问题出在哪，这个URL是后端的地址是吗？前端的doaminURL也没有修改啊

**Comment by JackFan90** [comment]
前端URL的问题

**Comment by hutianxi** [comment]
> 前端URL的问题

大佬同样的问题  您咋解决的
