### ISSUE TITLE
docker上传前端，显示上传了1.5个G

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#546]
##### 版本号：
3.5.0
##### 问题描述：
我用docker-compose-test.yml发布的时候，每次都要上传1.5个G，我的dist文件夹才90M
帮忙看看是我配置有问题吗

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/9aa116e0-a8c9-4ee5-b6c4-ad0eb6e01c85)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/2a6ce7d2-af41-4c27-afb9-70d80a39feff)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/a0175594-5b2e-46da-b3d1-fb8ec12afe1d)

**Comment by zhangdaiscott** [comment]
你应该在线上生成镜像，不是上次镜像

**Comment by qinghechaoge** [comment]
> 你应该在线上生成镜像，不是上次镜像

啥意思啊 先把dist文件夹上传  再做镜像吗？
