### ISSUE TITLE
BasicTable 组件中使用 InputGroup配置 不显示问题

### ISSUE THREAD

**Issue by xiaogangya12138** [jeecgboot/jeecgboot-vue3#548]
##### 截图&代码：
export const searchFormSchema: FormSchema[] = [  {
    field: 'rangeInput',
    label: '输入范围',
    component: 'InputGroup',
    required: true,
    slot: 'fac',
  },
];

vue 文件 :
   <BasicTable @register="registerTable" >
      <template #fac="{ model, field }">
        <a-input-group compact>
          <a-select v-model:value="activeKey" class="pay-select">
            <a-select-option value="zfb"> 支付宝 </a-select-option>
            <a-select-option value="yl"> 银联 </a-select-option>
          </a-select>
          <a-input class="pay-input" v-model:value="model[field]" />
        </a-input-group>
      </template>
</BasicTable>

<script lang="ts" setup>
//...引入资源

  const { prefixCls, tableContext, onImportXls, onExportXls } = useListPage({
    designScope: 'sup-template',
    tableProps: {
      api: getOrderList,
      formConfig: {
        schemas: searchFormSchema,
      },
  });
 const [registerTable, { reload, clearSelectedRowKeys }, { rowSelection, selectedRowKeys }] = tableContext;

</script>

页面显示:
![001](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/2bf0d8d4-6a0d-46c6-a481-04aafb459acb)

但是在BasicForm 中可以正常显示
![002](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/26702853-e1ce-4533-9eb7-91ac02362a6e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
BasicTable 组件 查询form表单区域配置的slot，在使用时需要以form-xxxx为前缀，才会被视为form的slot；

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/84a39850-e9ab-4bb3-a1f3-192fe93d8b8e)
