### ISSUE TITLE
页面引入Modal组件，弹窗自动弹出 且无法关闭

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecgboot-vue3#550]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/69864f1c-7d16-4d80-bff8-54129cc531d6)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/4f86a07b-f20f-4f44-ab92-5b3c8afb6a48)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个应该是你写法有问题，具体问题请自己排查
