### ISSUE TITLE
发布后缓存问题

### ISSUE THREAD

**Issue by mjlwq** [jeecgboot/jeecgboot-vue3#552]
如何给发布后文件添加时间戳解决缓存问题

**Comment by mjlwq** [comment]
添加了这个不清楚发布有问题没得
rollupOptions:{
        output: {
          chunkFileNames: "assets/js/[name]-[hash]" + Timestamp + ".js",
          entryFileNames: "assets/js/[name]-[hash]" + Timestamp + ".js",
          assetFileNames: "assets/[ext]/[name]-[hash]" + Timestamp + ".[ext]"
        }
      },

**Comment by zhangdaiscott** [comment]
nginx设置下
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/dc7bc242-8f51-4579-9fb8-92193089fa0a)
