### ISSUE TITLE
自定义按钮JS增强openCustomModal弹窗中日期时间控件问题

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#554]
##### 版本号：
3.5.1  vue3

##### 问题描述：
使用自定义按钮JS增强openCustomModal弹窗，其中有日期时间控件字段，操作时发现这样的问题：编辑弹窗与自定义弹窗，谁先操作，谁的日期时间控件就正常，而接着去操作另一个弹窗后，日期时间控件就失效，不能弹框选取日期时间。（这个问题不知道你们能不能还原？具体描述与截图见下面）

##### 截图&代码：
编辑页面中有日期时间控件，另外设置了一个自定义按钮，可以弹窗修改部分字段，其中也包括日期时间控件：
![1684738380094](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/fd6680ee-f3a0-4dca-b270-08d1df1184de)

操作时，进入该菜单页面
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/49e32178-ce48-4d1f-b777-ffc857a9a8a7)
先操作“编辑”，弹窗，日期时间控件正常，可以弹框选择日期和时间：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/c3407d6f-38b5-47dd-93fc-9378e6b4865d)
关闭弹窗后，再点击“更多”里的自定义按钮“反馈”，弹窗后，日期时间控件失效，无法弹出日期时间选择框：
![1684739635034](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/657c3b0e-4e48-4fc4-9d71-79314d7e7895)
再到“编辑”弹窗里，日期时间控件仍然是正常的。

重新进入该菜单页面
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/75aa5e1c-7cbc-4fd7-8dd5-5eb1d3036f87)
这回先点击“更多”里的自定义按钮“反馈”， 弹窗后，日期时间控件正常：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/5ef4533e-8416-4046-aab6-aa82fa37f08e)
关闭弹窗后，再点击操作“编辑”弹窗，日期时间控件失效，不能弹出日期时间选择框：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/3658433d-288b-4f23-8643-657ad5b7b8e8)

这应该是一个BUG，看看你们那边能不能重现这种问题，以便能尽快予以优化。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
存在该问题已修改，等下个版本发布
