### ISSUE TITLE
开发环境，vscode断点调试，文件或行数对不上

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/jeecgboot-vue3#555]
##### 版本号：
3.5

##### 问题描述：
开发环境，vscode断点调试，如果源代码是<script lang="ts" name="XXX" setup>这种形式，文件或行数对不上
原因是vite-plugin-vue-setup-extend插件引起，删掉正常，但是keepAlive会失效，如需保持keepAlive，不能使用setup语法糖，需改为defineComponent形式。
或者把vite-plugin-vue-setup-extend换成unplugin-vue-setup-extend-plus，也可以正常debug

##### 截图&代码：
build\vite\plugin\index.ts
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/10290156/f07cab27-2909-45ac-820b-fdd9ae70cd0b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
