### ISSUE TITLE
JImageUpload组件value赋初始值没显示图片

### ISSUE THREAD

**Issue by yi0708** [jeecgboot/jeecgboot-vue3#556]
版本号：3.5

问题描述：
JImageUpload组件value赋初始值没显示图片，原因是监听value少了immediate: true

截图&代码：
src\components\Form\src\jeecg\components\JImageUpload.vue

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by 1033965** [comment]
请问问题解决了吗，我这个上传图片也预览不了
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/105904512/86ad0134-8b44-4001-9122-5c49ec9e276b)

**Comment by yi0708** [comment]
我这边上传预览没问题，而且官方也修复了我提的这个bug。

**Comment by 1033965** [comment]
OKOK，谢谢，找到问题所在了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月07日 16:32 |
| 收件人 | jeecgboot/jeecgboot-vue3 ***@***.***> |
| 抄送人 | 1033965 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [jeecgboot/jeecgboot-vue3] JImageUpload组件value赋初始值没显示图片 (Issue #556) |

我这边上传预览没问题，而且官方也修复了我提的这个bug。
