### ISSUE TITLE
jeecgboot-vue3版本CAS单点登录

### ISSUE THREAD

**Issue by cyangshengbin** [jeecgboot/jeecgboot-vue3#557]
##### 版本号：
当前最新版本

##### 问题描述：
在开发文档开到有介绍单点登录，提示有cas-db这个项目，但是在代码仓库里面没有找到。

##### 截图&代码：
![F44 M3PDK($SGZ`JA1$5GEQ](https://github.com/jeecgboot/jeecgboot-vue3/assets/130720768/7adc6c2e-1371-482b-b207-4016ec4fa94a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
非开源内容，可以自己实现该部分
