### ISSUE TITLE
表单列中，在onchange事件中只能获取到当前字段的值，无法获取到其他字段，无法赋值

### ISSUE THREAD

**Issue by YaoYaqiong** [jeecgboot/jeecgboot-vue3#558]
版本号： 3.5.1

前端版本：vue3版

问题描述：若不通过js增强，实现：通过数量和单价计算出总价。现在在onchange事件中只能获取到当前字段的值，无法获取到其他字段，无法赋值

##### 截图&代码：
<img width="1177" alt="截屏2023-05-23 09 45 32" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/71279930/c113d146-345a-41dc-ae31-fb984807a181">

```
{
    label: '商品单价',
    field: 'prodUnitPrice',
    component: 'InputNumber',
    required: true,
    colProps: {
      span: 10,
    },
    componentProps: {
      onChange: (v1) => {
        formSchema.forEach((item) => {
          if (item.field === 'prodTotalPrice') {
            item.defaultValue = '11';
          }
        });
      },
    },
  },
  {
    label: '商品数量',
    field: 'prodNum',
    component: 'InputNumber',
    required: true,
    colProps: {
      span: 10,
    },
    componentProps: {
      onChange: (v) => {
        console.log(v, 'v=======');
      },
    },
  },
  {
    label: '商品总价',
    field: 'prodTotalPrice',
    component: 'InputNumber',
    required: true,
    colProps: {
      span: 10,
    },
  },
```

**Comment by zhangdaiscott** [comment]
sq

**Comment by YaoYaqiong** [comment]
啥意思勒

**Comment by liaojiyuan** [comment]
componentProps值可以是一个对象，或者函数 [参考文档](https://help.jeecg.com/component/Form.html#template-%E6%96%B9%E5%BC%8F)
`{
    label: '商品单价',
    field: 'prodUnitPrice',
    component: 'InputNumber',
    required: true,
    colProps: {
      span: 24,
    },
    componentProps: ({ formModel, formActionType }) => {
      return {
        placeholder: '请输入商品单价',
        style:'width:100%;',
        onChange: (e: any) => {
          const { setFieldsValue } = formActionType
          console.log(formModel)
          if (e && formModel.prodNum) {
            const total = Number(e * formModel.prodNum || 0).toFixed(2)
            setFieldsValue({ prodTotalPrice :total})
          }
        },
      }
    },
  },
  {
    label: '商品数量',
    field: 'prodNum',
    component: 'InputNumber',
    required: true,
    colProps: {
      span: 24,
    },
    componentProps: ({ formModel, formActionType }) => {
      return {
        placeholder: '请输入商品数量',
        style: 'width:100%;',
        onChange: (e: any) => {
          const { setFieldsValue } = formActionType
          console.log(formModel)
          formModel.prodTotalPrice=undefined
          if (e && formModel.prodUnitPrice) {
            const total = Number(e * formModel.prodUnitPrice || 0).toFixed(2)
            setFieldsValue({ prodTotalPrice: total })
            console.log(formModel)
          }
        },
      }
    },
  },
  {
    label: '商品总价',
    field: 'prodTotalPrice',
    component: 'InputNumber',
    required: true,
    colProps: {
      span: 24,
    },
    componentProps: {
      disabled: true,
      style: 'width:100%;',
    }
  },`

**Comment by lsqGitHub716** [comment]
[参考文档](https://help.jeecg.com/component/Form.html#formschema)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/2b32c212-ce85-464a-9db2-3b9aacf66b67)
