### ISSUE TITLE
useSelectBiz.ts 监听有问题每次都会执行2次

### ISSUE THREAD

**Issue by mjlwq** [jeecgboot/jeecgboot-vue3#559]
/**
   * 监听selectValues变化
   */
  watch(
    selectValues,
    () => {
      console.log(selectValues);
      if (selectValues['change'] == false) {
        //update-begin---author:wangshuai ---date:20220412  for：[VUEN-672]发文草稿箱编辑时拟稿人显示用户名------------
        let params = {};
        params[props.rowKey] = selectValues['value'].join(',');
        //update-end---author:wangshuai ---date:20220412  for：[VUEN-672]发文草稿箱编辑时拟稿人显示用户名--------------
        loadingEcho.value = isFirstLoadEcho;
        isFirstLoadEcho = false;
        getDataSource(params, true)
          .then()
          .finally(() => {
            loadingEcho.value = isFirstLoadEcho;
          });
      }
      //设置列表默认选中
      checkedKeys['value'] = selectValues['value'];
    },
    { immediate: true }
  );

**Comment by mjlwq** [comment]
第一次打开窗口

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试一下是否因为设置了{ immediate: true }导致的

**Comment by liaozhiyang** [comment]
能提供复现的具体步骤吗？

**Comment by liaozhiyang** [comment]
这个方法用的地方不少，是不是这个页面有两个组件引用了此方法？能提供具体的界面吗？
