### ISSUE TITLE
npm install 报错v18.16.0

### ISSUE THREAD

**Issue by davewang** [jeecgboot/jeecgboot-vue3#561]
##### 问题描述：
(base) ➜  jeecgboot-vue3 git:(main) npm install                                                     
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: jeecgboot-vue3@3.5.0
npm ERR! Found: vite@3.2.6
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0" from vite-plugin-optimize-persist@0.1.2
npm ERR! node_modules/vite-plugin-optimize-persist
npm ERR!   dev vite-plugin-optimize-persist@"^0.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/ubuntu/.npm/_logs/2023-05-25T05_32_17_661Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-05-25T05_32_17_661Z-debug-0.log

##### 截图&代码：
(base) ➜  jeecg-boot git:(main) lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
(base) ➜  jeecg-boot git:(main) uname -a
Linux instance-20221227-1143 5.15.0-1026-oracle #32-Ubuntu SMP Mon Dec 5 11:00:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

(base) ➜  jeecg-boot git:(main) node -v
v18.16.0

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
用pnpm或者yarn试试
