### ISSUE TITLE
打包过后暗色主题部分失效

### ISSUE THREAD

**Issue by YueCHEN195** [jeecgboot/jeecgboot-vue3#563]
##### 版本号：

v 3.5.1

##### 问题描述：

打包过后暗色主题不生效，但是npm run dev是好的。在scoped标记的style标签内，暗色主题的类没有加上data-v，导致暗色主题不生效。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/57787499/66ce7e48-6241-4141-9f3f-04b82c481c72)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/57787499/df9baf69-99ca-453d-8ace-3ba0276b40af)

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
