### ISSUE TITLE
求助，一对多代码主表单如何操作subTab

### ISSUE THREAD

**Issue by fireinjava** [jeecgboot/jeecgboot-vue3#564]
##### 版本号：
master

##### 问题描述：
假设主表单这边一个下拉项操作后，我想更新下方subTab的数据列或数据，请教下要如何操作？ 
目前是生成vue3原生代码解决的，想请教下有没更优方案。谢谢！

HroEmployee.data.ts
//表单数据
export const formSchema: FormSchema[] = [
   {
     label: '下拉1',
      field: 'companyId',
      component: 'JDictSelectTag',
      componentProps: ({ formModel, formActionType }) => {
          return {
             dictCode: 'company',
             onChange: (e: any, option) => {
               **// TODO 这边要怎么操作SubTable，比如要切换 columns，不同下拉项 columns 不一样**
            },
        };
      },
  },

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/5036983/866e0ba8-d3ef-4d36-a778-85930b751f9e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
onchange事件里面，通过绑定的表单model属性来操作数据；
如果使用的是JvxeTable的话，也可以通过ref获取操作表单数据
