### ISSUE TITLE
table 使用属性sorter排序字段不生效

### ISSUE THREAD

**Issue by nullnullruye** [jeecgboot/jeecgboot-vue3#566]
##### 版本号：
3.5.1

##### 问题描述：
组件位置  src/views/demo/table/Basic.vue  
问题： columns 使用属性  sorter: true  排序字段不生肖

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/67568362/ad49c6fb-8a0f-4199-beb6-7362348075a1)

**Comment by zhangdaiscott** [comment]
sq

**Comment by nullnullruye** [comment]
> sq
是后台sql的问题吗？ 我刚刚又使用了vben-admin 测试排序的 看着是可以的
