### ISSUE TITLE
在线等大佬回复：在data.ts中使用JSelectDept，提交表单时如何同时拿到部门id和名称给后台？

### ISSUE THREAD

**Issue by yang-jh971** [jeecgboot/jeecgboot-vue3#567]
##### 问题描述：项目中多处使用到了部门选择组件，但只能使用rowKey：‘***’去单独设置取值字段，但实际需求需要同时取到选择的部门的id和name，并且在提交表单时一起传递给后台处理数据。
当前有自己使用pinia去储存用户当前选择的部门信息，以拿到部门id和name，但是如果一个界面出现多个部门选择组件就会有Bug，而且此方式使用起来极其麻烦，研究了很久源码，奈何技术不够，请大佬们帮忙解答。。。 

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/105487241/ad13caab-d468-4dff-ae5d-0611ebcffa40)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/105487241/1f7826f6-35a5-45cf-bcbb-744b5e655309)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持，自己扩展就行

**Comment by mrmyn** [comment]
请问楼主现在解决了没，能否贴个如何解决的。。。确实看不懂这个封装的组件
