### ISSUE TITLE
online表单关于下拉框数据联动问题以及子表Popup控件问题

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#569]
##### 版本号：
3.5.1  vue3

##### 问题描述：
1、online表单中，下拉框组件，使用表字典获取数据，字典table中也可以带"?create_by=${sysUserCode}'之类的参数，但参数值必须是常量或系统变量。实际项目中会有这样的普遍需求：即当form中其它某一个字段(比如公司ID)变化后，下一个下拉字段的数值范围希望也能随之变化（比如公司ID下的采购订单或其他），如果不变化，那么下拉选择时将会比较麻烦（出现所有公司的采购订单），而且很难保证不会人为选择错误。有没有办法处理这种数据联动问题（online配置的情况下）？曾设想可能的解决办法就是：允许字典表where后的参数值可以使用form表单的字段数据，比如配置为where company_id=@{company_id}，系统处理时，遇到@号进行form表单数据替换（与$号类似），且重新刷新缓存。但苦于没有online源码，所以改造不了。不知你们能不能予以这样优化？

2、在实际使用中，我利用Popup组件试图解决上面所说的数据联动需求问题，Popup组件的字典table配置为在线报表，可以带参，虽然参数的传递仍然无法使用form表单字段变量（也是必须为常量或系统变量），但我采用后端程序改造，可以在点击Popup弹框之前修改在线报表参数的值，从而实现传递参数的目的，勉强能够达到需求目的。
      然而，在使用过程中，发现这样的问题：主表或单表form中此种方式处理的Popup弹框很正常，出来的数据均已符合我的期望。但子表存在问题，默认风格行编辑的情况下，Popup弹框出现的数据不受在线报表参数值的变化影响（似乎一直在使用缓存数据！）。但奇怪的是，使用子表的弹窗新增或编辑功能，一切又很正常。这说明子表默认的行编辑情况下程序处理存在bug，希望能够予以优化。（vue2的ERP方式也不存在类似问题。所以看下来，子表默认风格时的行编辑额模式下，确实存在许多问题的，包括我以前多次提出的提交后先删除再新增的问题。）

下面用截图进一步说明：

##### 截图&代码：
1、大致需求说明
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/bd8afe6b-2226-4021-a821-287c39fbfc68)
2、在线报表rpt_po_line配置
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/0e1305a9-9244-4aa5-8607-8c0d6a6c656a)
3、主表表单配置（为比较说明而临时把“备注”配置为Popup弹框组件）
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/81994ffc-76a8-4b16-a515-a5ea734bef4e)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/24426533-29dc-4a73-942c-2e1f655237e9)

4、子表表单配置
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/db2cf82b-3d74-4cc8-b861-e1da0994a7b1)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/53017e13-edc6-4f4c-bde8-d052a319774d)
5、通过JS增强传递在线报表的参数
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/dbae68be-6a7c-4b92-9a61-9660abdaca4e)
相应的后端程序改造：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/70c43f0f-4650-412d-a3a6-0fa23fa25914)
6、运行效果
----主表表单子弹弹窗正常：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/ed76d806-d611-49a7-b9b5-51312a36d6e8)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/35149632-7ad9-40ca-ac0d-c1741a448d7b)
----子表，默认风格行编辑方式，没有达到预期效果：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/923a024f-ddc3-4873-ac9d-5a23e67d899c)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/517be3c7-bbc3-489f-becf-34ef0d9e77c0)
----子表，弹窗新增或编辑，又是可以的，说明行编辑方式存在bug，需要优化。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/c8f413be-af7d-4164-b381-3920c253a026)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/842cc6b9-e04f-42b2-bb5d-1fda7bfaff33)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/4f62f5d2-7727-43f7-ad68-8e340ee72e5e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以通过js增强，自己随意实现

**Comment by gxzhou** [comment]
> 你可以通过js增强，后台请求数据接口自己实现，这样就灵活了，我们的online报表不支持传递业务参数

这里有关传递业务数据的处理只是一种例子，是为了把问题解释清楚，并不要求你们予以实现的。而这里所描述的主要问题是：为什么行编辑和弹窗编辑会对相关处理不一样，会出现不同的效果？这会不会是bug，会不会是可能缓存处理上的问题？如果是的话，我知道你们是很容易解决的。要是能解决了，多好啊！

另外， 通过JS增强从后台获取到数据以后，怎么去修改下拉选择的内容呢？这个我没学会。能不能教一下，谢谢。
