### ISSUE TITLE
JVXETable横向滚动错位

### ISSUE THREAD

**Issue by JSON777818** [jeecgboot/jeecgboot-vue3#571]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/51874546/f96860bf-145f-40f5-814d-281cf7b56b8a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by liaozhiyang** [comment]
JVxeTable的高度没包含横向滚动条，JVxeTable的height:484改成492即可
