### ISSUE TITLE
JVxeTable setValues无法设置类型为hidden列的值

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecgboot-vue3#573]
##### 问题描述：
JVxeTable setValues 方法 
let column = xTable.getColumnByField(colKey); 
获取不到Column  type=JVxeTypes.hidden的列对象。
提示  useMethods.ts:587 [JVxeTable] setValues 没有找到key为"testProject"的列

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/603eb7d9-9a35-41a7-a97e-5139857848b4)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/ca7c3e95-6606-46d4-b3ee-88563e9d10a0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
未复现该问题，请更新到最新版后再试，并且检查 `vxe-table` 是否是`4.1.0`版本。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34293221/c577deaa-9d2f-4719-a422-f354b180fc02)

**Comment by PjqDD** [comment]
获取不到+1
通过   getTableData() 获取不到 type=JVxeTypes.hidden 的数据 
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/53d42673-68d4-4025-9987-4a12364817bd)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/b43f4832-de26-488c-92e1-819e48c7446a)
