### ISSUE TITLE
LineMulti 显示出来是柱状图,应该是折线图

### ISSUE THREAD

**Issue by suisou** [jeecgboot/jeecgboot-vue3#576]
##### 版本号：

3.5.1
##### 问题描述：

LineMulti 显示出来是柱状图

##### 截图&代码：

`<LineMulti :chartData="chartdata"></LineMulti>`

chartdata:
[
     {
         "name": "1月",
         "value": 320,
         "type": "2021"
     },
     {
         "name": "2月",
         "value": 457,
         "type": "2021"
     },
     {
         "name": "3月",
         "value": 182,
         "type": "2021"
     },
     {
          "name": "1月",
          "value": 240,
          "type": "2022"
      },
      {
          "name": "2月",
          "value": 357,
          "type": "2022"
      },
      {
          "name": "3月",
          "value": 456,
          "type": "2022"
      }
 ]

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/11958407/47456edb-d5a3-4f19-a4b2-d375d2c9a8df)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
