### ISSUE TITLE
ant版本从2.28升级到了3.2.0出现了一些样式以及功能问题 请问怎么解决

### ISSUE THREAD

**Issue by m2075498242** [jeecgboot/jeecgboot-vue3#577]
##### 版本号：
3.4.0

##### 问题描述：

我在将ant版本从2.28升级到了3.2.0出现了一些问题  日期组件格式转化出现了问题   还有一些样式问题  请问如何解决避免 
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/89441679/c712ea65-3b44-4836-8a49-b1fa205f3152)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/89441679/d5b68ce0-ac65-49fd-8026-3e5e761b33cd)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己升的，我们负责不了，你可以升级jeecgboot到最新版
 "ant-design-vue": "^3.2.12",

**Comment by m2075498242** [comment]
因为底层有修改 如果升级jeecgboot到最新版 会有什么影响呢
