### ISSUE TITLE
内网部署前端首页请求500多次，导致被拦截，请教如何减少请求次数或者合并请求文件

### ISSUE THREAD

**Issue by 490937333** [jeecgboot/jeecgboot-vue3#578]
##### 版本号：
v3.4.3 vue3 + jeecgboot3.4.3

##### 问题描述：
内网部署前端首页http请求500多次，导致监测被拦截，请教如何减少请求次数或者合并请求文件

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
发具体情况，你发这样的帖子让我们猜吗
