### ISSUE TITLE
JSearchSelect 组件bug

### ISSUE THREAD

**Issue by fireinjava** [jeecgboot/jeecgboot-vue3#579]
##### 版本号：
vue3

##### 问题描述：
下拉搜索组件，dictOptions 
https://github.com/jeecgboot/jeecgboot-vue3/blob/master/src/components/Form/src/jeecg/components/JSearchSelect.vue

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/5036983/fb3b927d-32d8-4c7b-9e5b-e7a7fae51ec0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by lsqGitHub716** [comment]
问题已记录，后续我们会优化组件，您可以临时按照此方式修改
