### ISSUE TITLE
获取验证码接口404

### ISSUE THREAD

**Issue by LiChaoyang123** [jeecgboot/jeecgboot-vue3#58]
##### 截图&代码：
![企业微信20220429-160937](https://user-images.githubusercontent.com/27845466/165907550-ec1ff030-7d0c-4370-860f-a29f5f10e93a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by aaronlean** [comment]
> 后台启动了吗
解决了吗？

**Comment by LiChaoyang123** [comment]
> 后台启动了吗

后台启动就可以了

**Comment by Doracoin** [comment]
遇到了使用`yarn serve`正常使用，`yarn build`后的静态网站验证码依然404的情况，
为什么在development配置中设置了`VITE_PROXY`，在production中则不设置

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2503893#_141
![image](https://user-images.githubusercontent.com/3162115/181186150-e3349be3-1766-49eb-9333-999d98905924.png)

**Comment by Doracoin** [comment]
> http://vue3.jeecg.com/2503893#_141 ![image](https://user-images.githubusercontent.com/3162115/181186150-e3349be3-1766-49eb-9333-999d98905924.png)

十分感谢，明白它的原理了，谢谢
