### ISSUE TITLE
父容器高度不够会导致下拉选择框或者日期选择框显示不全

### ISSUE THREAD

**Issue by zhangwenqi997** [jeecgboot/jeecgboot-vue3#580]
##### 版本号：
v3.5.1  vue3 + jeecgboot3.5.1

##### 问题描述：
使用下拉框或者日期选择等组件时，父容器高度不够会导致下拉选择框或者日期选择框显示不全，请问应该如何解决？

##### 截图&代码：
![1686204136885](https://github.com/jeecgboot/jeecgboot-vue3/assets/54975511/dd58bb10-0279-4e7a-926a-3fce43249ba9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yang-jh971** [comment]
在data.ts中，找到你定义的时间选择器的地方。在componentProps里面加上getPopupContainer: () => document.body就可以了

**Comment by zhangwenqi997** [comment]
> 在data.ts中，找到你定义的时间选择器的地方。在componentProps里面加上getPopupContainer: () => document.body就可以了

可以了，谢谢
