### ISSUE TITLE
多个缓存路由复用同一个组件时，菜单展开不正常

### ISSUE THREAD

**Issue by pangzhen** [jeecgboot/jeecgboot-vue3#582]
##### 版本号：
master

##### 问题描述：
多个缓存路由复用同一个组件时，菜单展开不正常
路由配置如下图
<img width="1095" alt="截屏2023-06-10 13 28 05" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/58fc23ba-340d-45b0-9095-ae2a969c1dca">
<img width="565" alt="截屏2023-06-10 13 28 25" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/fc8a6652-7b81-4e08-acec-2846a941cbfa">
<img width="569" alt="截屏2023-06-10 13 28 42" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/60ab4499-c171-4622-b9fe-7a103062a0d6">
<img width="619" alt="截屏2023-06-10 13 31 33" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/94f056fb-f0ec-4a4a-a4a5-2fce02dae1d6">

菜单展开的正确路径是[/salary/2023, /salary/:y/:m/:t, /salary/2023/01/ziyou ]
由于menu.path = realPath; 会把/salary/:y/:m/:t,替换为 /salary/2023/01/ziyou 导致只有两级路径[/salary/2023,/salary/2023/01/ziyou ]，所以菜单展开不正常

提交了pr
https://github.com/jeecgboot/jeecgboot-vue3/pull/581
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by pangzhen** [comment]
路由配置你漏了组件名称，
路由配置里的组件名称要写上，不然路由缓存不生效，
在页面加上显示当前时间，tab来回切换，如果时间不变才是路由缓存了
