### ISSUE TITLE
vuerouter4.1.4更新导致路由缓存页面刷新出现404错误

### ISSUE THREAD

**Issue by pangzhen** [jeecgboot/jeecgboot-vue3#583]
##### 版本号：
master

##### 问题描述：
vuerouter4.1.4更新导致路由缓存页面刷新出现404错误
<img width="1095" alt="截屏2023-06-10 13 28 05" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/68f5a0e1-7a44-4835-88b4-50082e64f17d">
<img width="565" alt="截屏2023-06-10 13 28 25" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/08ab66db-5a32-4693-b955-6c7b4e3d6dff">
<img width="569" alt="截屏2023-06-10 13 28 42" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/8547d9ec-849b-47e1-9450-0637faeed114">
<img width="1062" alt="截屏2023-06-10 15 07 25" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/9472744/f58625ba-67a9-462a-8b31-da7d4b0e3fd6">

点击右上角刷新按钮会通过REDIRECT_NAME页面来刷新，但此时params参数不在path里面定义，vuerouter4.1.4版本开始会中断这种反模式的params传参，导致出现404

提交pr：
https://github.com/jeecgboot/jeecgboot-vue3/pull/584

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by liaozhiyang** [comment]
按照你的配置路由跟params参数其实无关，菜单最后一级的动态路由匹配才跟params有关。
经测试4.1.4版本，没发现页面刷新出现404错误。能提供更加详细的步骤吗？
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/7994227e-c967-47ad-84eb-75aab6baed55)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/36f8f1b9-4081-48e4-bf4b-2466443ac5f3)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/4cca6086-d557-4d97-bf37-fa3f1daf5b93)

**Comment by pangzhen** [comment]
路由配置里的组件名称要写上，不然路由缓存不生效，
在页面加上显示当前时间，tab来回切换，如果时间不变才是路由缓存了
