### ISSUE TITLE
@jeecg/online 包不应该直接引用 vite 配置的别名

### ISSUE THREAD

**Issue by kaivanwong** [jeecgboot/jeecgboot-vue3#586]
##### 截图&代码：
![企业微信截图_16865404983491](https://github.com/jeecgboot/jeecgboot-vue3/assets/47177021/1f28e92e-5b22-4a25-9947-b70a39c00652)
![企业微信截图_16865406891107](https://github.com/jeecgboot/jeecgboot-vue3/assets/47177021/2b8fbc02-d0c1-4f0c-ae6f-967e2edeae51)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你只能兼容jeecg的默认包名
