### ISSUE TITLE
online表单开发权限控制，“功能测试”正常，代码生成后就不可用了

### ISSUE THREAD

**Issue by zhaohuaxiaoy** [jeecgboot/jeecgboot-vue3#588]
##### 版本号：
3.5.2

##### 问题描述：
图1是online表单开发"功能测试"，“新增”按钮正常隐藏，字段“小程序openid”也正常隐藏
图2是代码生成后效果，“新增”按钮不隐藏，“小程序openid”也没隐藏
图3是权限控制界面

##### 截图&代码：
![未命名 1](https://github.com/jeecgboot/jeecgboot-vue3/assets/13568008/318c4239-1db5-4de0-8738-d0430518e744)
![未命名 2](https://github.com/jeecgboot/jeecgboot-vue3/assets/13568008/434a6eab-839b-497f-9a6c-f028f2e13b03)
![未命名 3](https://github.com/jeecgboot/jeecgboot-vue3/assets/13568008/33da3da4-2796-4b65-81ec-15440a362be5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码生成后，得用生成代码的授权方式
