### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by qq1014022914** [jeecgboot/jeecgboot-vue3#589]
##### 版本号：
3.5.2

##### 问题描述：
 ERR_PNPM_NO_VERSIONS  No versions available for vue-plugin-preset. The package may be unpublished.

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by qq1014022914** [comment]
补充一下。这个实在是不知道为什么会一直编译失败。
gpt给出的答案是：
这个错误提示表示无法找到vue-plugin-preset的任何版本。这可能是因为该包已被删除或未发布。您可以尝试以下解决方案： 
1. 检查包名称是否正确：请确保您输入的包名称正确，包括大小写和拼写。如果有任何错误，请更正它们并再次运行安装命令。 
2. 检查包是否已发布：您可以在npm官网（https://www.npmjs.com/）上搜索该包，看看它是否已被删除或未发布。如果是这种情况，请尝试使用其他替代包或联系包的维护者了解更多信息。 
3. 检查您的网络连接：请确保您的网络连接正常，如果您使用的是代理，请确保代理设置正确。 
4. 清除缓存并重新安装：您可以尝试清除npm或pnpm的缓存，并重新安装该包。可以使用以下命令清除缓存：
npm cache clean --force
或者
pnpm cache clear --force
然后再次运行安装命令。 
 
如果以上方法都无法解决问题，您可以尝试使用其他替代包或联系该包的维护者了解更多信息。

**Comment by zhangdaiscott** [comment]
你更新到最新，vue-plugin-preset已经删掉了
