### ISSUE TITLE
打包后运行登录界面是空白的

### ISSUE THREAD

**Issue by hezhengJava** [jeecgboot/jeecgboot-vue3#59]
##### 版本号：
v1.0.0

##### 问题描述：
1.yarn build 打包之后，再执行 yarn preview:dist  打开登录界面是空白的，控制台没输出明显异常。把打包好的文件放到nginx，问题也一样。
2.yarn serve 启动没有问题。
 
##### 截图&代码：
![image](https://user-images.githubusercontent.com/35255323/166129377-938bffef-02dc-452f-817b-a2fda123b6fd.png)

**Comment by zhangdaiscott** [comment]
不清楚，自己的环境找问题
