### ISSUE TITLE
列表数据行选择实在太卡，是不是BasicTable有问题，VUE2版本没这问题

### ISSUE THREAD

**Issue by 9822132** [jeecgboot/jeecgboot-vue3#592]
##### 问题描述：

列表选择实在太卡，例如选50条一页，不管是全选还是单选，都要卡个几秒，就算10条一页选择也是明显卡顿，以前VUE2版本还没这个问题，VUE3性能反而变的更慢了，大家都没有发现这个问题吗，用官方的演示地址去测测看，比如业务申请--请假申请，分页选择50条一页，去选择看看，不管选一行还是全选多行，都会卡的无语

##### 截图&代码：
![微信图片_20230616103114](https://github.com/jeecgboot/jeecgboot-vue3/assets/136682719/e7c681f6-2875-4139-8483-0479525efd6f)

![微信图片_20230616104929](https://github.com/jeecgboot/jeecgboot-vue3/assets/136682719/c8a03a4f-f8c3-4c34-a19d-d851dcf7ecd1)

**Comment by zhangdaiscott** [comment]
修复了，更新代码
