### ISSUE TITLE
仪表盘设计功能中的“数据源”配置页面显示异常

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#595]
##### 版本号：
3.5.2

##### 问题描述：
浏览器缩小后，数据源配置对话框中的表格不支持左右滚动，表格宽度超出了对话框的宽度。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/dcfa708c-0544-4699-bb5d-c9e1e6d0ed9c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
