### ISSUE TITLE
online表单开发报错， 列表信息丢失

### ISSUE THREAD

**Issue by yang-jh971** [jeecgboot/jeecgboot-vue3#596]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/105487241/61c61653-d88c-48ca-9a76-40c7651505fe)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么情况下？如何重现
