### ISSUE TITLE
开发环境首次加载700+请求

### ISSUE THREAD

**Issue by konogousanda** [jeecgboot/jeecgboot-vue3#597]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/41279435/897b949c-e91a-47f8-b61c-86ebc58eaae7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
这个首次确实请求比较多，但是之后就走的就是缓存了。改动较大，我们后期会慢慢优化，你可以把你们项目中不需要用到的功能去掉，会快很多。

**Comment by xxlngng** [comment]
在线等

**Comment by zhangdaiscott** [comment]
3.5.5发布后，开发环境首屏也很快了，所以这个问题可以暂时忽略，如果需要更少的加载，可以按照自己的情况，把某些大组件改成按需加载
