### ISSUE TITLE
页面总是会自动刷新，请问在哪里关闭呢？

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecgboot-vue3#598]
##### 问题描述：
1.页面总是会自动刷新，是否是websocket的问题？请问在哪里关闭呢？
2.长时间不操作页面，有时还会崩溃

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么效果？
