### ISSUE TITLE
自带打印组件调用printJS方法，打印预览时无法分页

### ISSUE THREAD

**Issue by yandong941221** [jeecgboot/jeecgboot-vue3#599]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/75298811/1f298e9b-4427-497e-84ae-1023f71976cb)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/75298811/5cff34f3-e5e5-4271-b2be-5a3155be9675)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by bantu4me** [comment]
怎么处理的啊，怎么这个issue就被关了呢？我看3.5的版本依旧有这个问题

**Comment by yandong941221** [comment]
没用框架里的打印，使用的 printjs 原生的，实现的打印
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月19日 11:45 |
| 收件人 | ***@***.***> |
| 抄送人 | donny ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jeecgboot/jeecgboot-vue3] 自带打印组件调用printJS方法，打印预览时无法分页 (Issue #599) |

怎么处理的啊，怎么这个issue就被关了呢？我看3.5的版本依旧有这个问题

**Comment by bantu4me** [comment]
好的，谢谢。先研究下

**Comment by bantu4me** [comment]
> 没用框架里的打印，使用的 printjs 原生的，实现的打印 ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年07月19日 11:45 | | 收件人 | ***@***.***> | | 抄送人 | donny ***@***.***>, Author ***@***.***> | | 主题 | Re: [jeecgboot/jeecgboot-vue3] 自带打印组件调用printJS方法，打印预览时无法分页 (Issue #599) | 怎么处理的啊，怎么这个issue就被关了呢？我看3.5的版本依旧有这个问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我看框架里面也有引用printJS组件，你是直接用的这个吗？我用这个组件还是有问题

**Comment by annihilationism** [comment]
你的可以了嘛，我也遇到这个问题
