### ISSUE TITLE
注册页面和手机登录页面急需要增加图形验证码保护

### ISSUE THREAD

**Issue by weixuezhang** [jeecgboot/jeecgboot-vue3#60]
##### 版本号：
v1.0.0

##### 问题描述：
注册页面和手机登录页面缺少图形验证码保护，容易遭到恶意攻击，无谓消耗系统短信流量，直至系统无法注册。因此，急需增加图形验证码。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种自己二开就可以了

**Comment by weixuezhang** [comment]
如果增加图形验证码保护功能，将省去千万用户重复开发此功能的工作，意义多大呀！另外也一定能吸引更多用户采用jeecg-boot，这不也是很好的事情吗？如果没有这个功能，用户可能因此招致损失，那责任会归咎到jeecg-boot上。

**Comment by eyuan** [comment]
> 如果增加图形验证码保护功能，将省去千万用户重复开发此功能的工作，意义多大呀！另外也一定能吸引更多用户采用jeecg-boot，这不也是很好的事情吗？如果没有这个功能，用户可能因此招致损失，那责任会归咎到jeecg-boot上。

jeecg说他不是厦大的:<

**Comment by weixuezhang** [comment]
jeecg如果自以为“大”的话，那离开始变小就不远了。。。
