### ISSUE TITLE
table全选/勾选卡顿

### ISSUE THREAD

**Issue by Hoshi-Wang** [jeecgboot/jeecgboot-vue3#600]
##### 版本号：
3.5.2

##### 问题描述：
table表格全选数据，数据30条就开始卡顿，50条卡顿明显（用户不能接受），超过500条时直接卡死（没办法客户就是有这种需求...）
issuse/503好像没有完全修复这个问题
##### 截图&代码：
<img width="871" alt="Snipaste_2023-06-21_09-51-20" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/77822185/cd7705ad-d308-4fe9-a097-b5740444c43d">

**Comment by zhangdaiscott** [comment]
100条已经不卡，除非你本地开启了vue-tools

**Comment by Hoshi-Wang** [comment]
生产环境100条勾选上会卡上1.5s，我的电脑配置还算可以了，普通用户配置没有那么好，他们浏览器也不会装vue-tools，我用浏览器性能工具分析看到卡顿60%的时间都是在执行js，应该还有其它的问题存在

**Comment by zhangdaiscott** [comment]
那就是你代码没更新到最新

**Comment by Hoshi-Wang** [comment]
弱智回答
