### ISSUE TITLE
导航栏模式为顶部菜单点击一直在加载中

### ISSUE THREAD

**Issue by pangshuyuan** [jeecgboot/jeecgboot-vue3#601]
##### 截图&代码：导航栏模式配置为顶部菜单后，点击菜单，显示加载按钮后无反应，网页控制台报错
Error: Invalid route component
    at extractComponentsGuards (vue-router.esm-bundler.js:1987:27)
    at vue-router.esm-bundler.js:3143:22
演示版本无此问题
<img width="1438" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/43928356/d4e34441-06c3-4da8-a690-125d01b99c44">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试一下看看报错的菜单配置的路径或者组件地址是否正确

**Comment by zhangdaiscott** [comment]
未重现，暂时关闭
