### ISSUE TITLE
请帮忙看看，form中的JPopup组件根据参数从报表配置中获取数据表，但param参数值不能改变？该怎么做？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecgboot-vue3#602]
##### 版本号：
3.5.1

##### 问题描述：
在form中使用了jpopup组件，根据param参数从报表配置的sql语句中获取数据表，sql语句配了一个动态参数，可以通过param的值来筛选不同的数据。但是程序只能使用param第一次赋的值，后面我采用多种方法改变param的值，都无效，是怎么回事？应该如何操作？

我尝试过的办法包括
1. 直接赋新值给param，如param1.value = { abc: " 'PU_P001' " }，但程序还是使用的旧值。
2. 使用formElRef.value.updateSchema更新这个jpopup组件所在的字段，同时给param赋新值，也无效。程序还是是用旧值。
3. 后来又使用formElRef.value.removeSchemaByFiled('processcode'); formElRef.value?.appendSchemaByField... 想先移除整个jpopup所在的字段，再添加新的包含jpopup组件的字段进去，等于整个替换掉老的组件，这样来实现赋给param新值，结果还是不行，程序还是用旧值。。。
这下就不知道怎么办了。。。

请高手帮帮忙，指点一下怎么办？

目的就是，让jpopup可以根据不同的筛选条件param，从配置报表配置的code中筛选合适的数据表出来。

谢谢！

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/425bdceb-6f46-4263-875a-f5eae0abab40)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/6924b46d-4055-4324-8fe8-b649042e01a0)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/d7e3e0b7-d753-458b-a525-d0709068cd8b)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/9d1e6041-126a-4b4b-9129-29e73a314473)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
使用 reactive 即可。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34293221/b4827017-bfa0-42a5-9963-c18b89b0df8f)
