### ISSUE TITLE
图表组件数据问题

### ISSUE THREAD

**Issue by EgoElysia** [jeecgboot/jeecgboot-vue3#603]
##### 版本号：
3.5.2

##### 问题描述：
如果两个图表组件的option指向同一个变量而且option里设置了series会导致后面的图表数据覆盖前面的图标数据
建议对数据进行深拷贝
##### 截图&代码：
原代码： if (props.option) {
          Object.assign(option, props.option);
        }
新初始化图表时：        if (props.option) {
          Object.assign(option, cloneDeep(props.option)); // 使用 cloneDeep 进行深拷贝
        }
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/127327672/f06f6e06-f07e-4d93-a516-b6983fc264be)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
