### ISSUE TITLE
代码生成无法使用

### ISSUE THREAD

**Issue by baihua666** [jeecgboot/jeecgboot-vue3#604]
##### 版本号：
master分支最新代码

##### 问题描述：
代码生成器生成的ZIP文件，在MAC无法打开，换了几个解压软件都打不开

##### 截图&代码：
<img width="460" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/5125983/fa8c58ed-8415-4c57-b8e7-9ab1458c67fa">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
？mac不兼容
