### ISSUE TITLE
vue3 部署之后点击浏览器自带的刷新按钮后token没有加到请求headers里

### ISSUE THREAD

**Issue by crazyxb** [jeecgboot/jeecgboot-vue3#605]
##### 版本号：
3.4.0

##### 问题描述：
程序达成JAR包部署之后，在进入到具体页面后点击浏览器的刷新界面会报TOKEN失效的错误，经检查是没有往后端传token造成的

##### 截图&代码：
正常界面
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38426984/972ce816-d1cd-42a9-82ae-451b8295a3b0)

点击浏览器自带的刷新按钮后
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38426984/39b5577e-6820-41be-9c72-6d0ab3b924e5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
我们发布没这问题，不清楚你为什么

**Comment by crazyxb** [comment]
使用npm run build 后将dist下文件拷贝到后端statics下后打包，我试了3.5的版本前后端的代码没有动过，按照这个操作后用浏览器自带的刷新还是会出现token没有往后台传的现象
