### ISSUE TITLE
使用iframe装载public文件夹下的html时路由菜单404

### ISSUE THREAD

**Issue by cui5782052** [jeecgboot/jeecgboot-vue3#606]
##### 版本号：
3.5.1

##### 问题描述：
我页面使用了iframe，想要使用src到本地的public文件夹下的html，配置没有跳转到public下的html，是不是被菜单拦截了，没有拿到public下的静态文件

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/62142959/57862737-b89a-4bd0-a1ce-dbcb436d7402)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/62142959/bd9caf26-b737-4e42-a4ea-37c3a152f38b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
我们没这么用过

**Comment by icoco** [comment]
> ##### 版本号：
> 3.5.1
> 
> ##### 问题描述：
> 我页面使用了iframe，想要使用src到本地的public文件夹下的html，配置没有跳转到public下的html，是不是被菜单拦截了，没有拿到public下的静态文件
> 
> ##### 截图&代码：
> ![image](https://private-user-images.githubusercontent.com/62142959/248543759-57862737-b89a-4bd0-a1ce-dbcb436d7402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDI4MjEsIm5iZiI6MTcwNDEwMjUyMSwicGF0aCI6Ii82MjE0Mjk1OS8yNDg1NDM3NTktNTc4NjI3MzctYjg5YS00YmQwLWExY2UtZGJjYjQzNmQ3NDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA5NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzdhNTMxYjEyN2UyY2E0ZTRiYTVjZGY5YzY3NDcyMmY4YmVlYWI1YjJhMGU0Yzc0ZTcyOTVhY2NlNzJmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ipHhqOL8rbkvrTdNrVsR4OmlkD_EdC8D8aMZjRM5Log) ![image](https://private-user-images.githubusercontent.com/62142959/248543781-bd9caf26-b737-4e42-a4ea-37c3a152f38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDI4MjEsIm5iZiI6MTcwNDEwMjUyMSwicGF0aCI6Ii82MjE0Mjk1OS8yNDg1NDM3ODEtYmQ5Y2FmMjYtYjczNy00ZTQyLWE0ZWEtMzdjM2ExNTJmMzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA5NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZmVhYTRkNDQ1MDBkMThkMmI3NWM2OTgwZGM0YjY0OWU2NGUyYjQ4OWYwMDBkODU4ODU2NTE1NzI0ODFjMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I23AxqfoF1bfqoJc054NcUcRUoFgrHVr4o7J1E4hyNw)
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；

solved ?

**Comment by axinger** [comment]
@icoco 你解决了吗? 我也遇到这样问题了

**Comment by icoco** [comment]
sure,    use spring MVC, add new api ( maybe '/webview')  handle the request , eg: /webview/page=xxx

xxx locate in the public folder
