### ISSUE TITLE
dark 模式下底部 footer 文字 hover 样式导致文字消失

### ISSUE THREAD

**Issue by liwenfengg** [jeecgboot/jeecgboot-vue3#608]
##### 版本号：
3.5.2

##### 问题描述：
dark 模式下底部 footer 文字 hover 样式导致文字消失

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/40257198/eb24e915-3904-41b8-9e9f-7ee60414ccfe)

<img width="989" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/40257198/f1491dd3-d475-48d4-8514-0f3e0a4394a8">

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
