### ISSUE TITLE
JSelectUser组件  删除不了数据

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecgboot-vue3#609]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/487bf707-a64f-4992-af64-01a567f7cf08)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/d94a89c4-1d27-477c-9e3d-dcb6add378d2)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/f97d0364-7add-44ca-9dba-39be706eb81c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
