### ISSUE TITLE
JSelectUserByDept 组件在BaseForm 模式使用，第一次编辑显示选中的用户，第二次编辑，编辑框不再显示选中的用户

### ISSUE THREAD

**Issue by laozhu001** [jeecgboot/jeecgboot-vue3#61]
##### 版本号：
3.2

##### 问题描述：
JSelectUserByDept 组件在BaseForm 模式使用，打开编辑时，第一次显示已经保存的用户名，关闭，再次打开时，编辑框没有显示保存的用户名

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by laozhu001** [comment]
问题录屏文件如下
https://yffmblockly.oss-cn-beijing.aliyuncs.com/media/%E5%BD%95%E5%88%B6_2022_05_07_23_25_36_992.mp4

**Comment by sjlei** [comment]
@laozhu001  录屏看了，还是没有复现。按照你的操作方式，点编辑，关了弹窗，再点编辑，JSelectUserByDept可以正常显示选中的用户的。这问题可能是你改出来的，需要你自己debug了

https://user-images.githubusercontent.com/34293221/167781244-50a0ec24-2138-4a96-b3ab-16044ca3872f.mp4
