### ISSUE TITLE
vue3 部署之后点击浏览器自带的刷新按钮后token没有加到请求headers里

### ISSUE THREAD

**Issue by crazyxb** [jeecgboot/jeecgboot-vue3#610]
##### 问题描述：
使用npm run build 后将dist下文件拷贝到后端statics下后打包，我试了3.5的版本前后端的代码没有动过，按照这个操作部署后用浏览器自带的刷新还是会出现token没有往后台传的现象，我记得vue2是修改mode:history为hash就不会出现这种问题，vue3版本是需要在哪里修改吗？
程序打成JAR包部署之后，在进入到具体页面后点击浏览器的刷新界面会报TOKEN失效的错误，经检查是没有往后端传token造成的

##### 截图&代码：
正常的
![1687940392334](https://github.com/jeecgboot/jeecgboot-vue3/assets/38426984/1b075308-c721-4f4c-abfc-a98d87ff6328)

点击浏览器自带的刷新按钮之后
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38426984/b6036027-a611-4ba4-b7cf-ae775a52fb9c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
能不能录个视频演示下

**Comment by crazyxb** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/assets/38426984/8ad50f39-b17d-4813-9d38-c12663eb7daf


https://github.com/jeecgboot/jeecgboot-vue3/assets/38426984/29e9ba06-5595-442e-91ec-3ff2156f38bc

**Comment by crazyxb** [comment]
找到原因了，打包时在router下index.ts将createWebHistory改成createWebHashHistory打包就可以了
createRouter({
  //history: createWebHistory(import.meta.env.VITE_PUBLIC_PATH),
  history: createWebHashHistory(import.meta.env.VITE_PUBLIC_PATH),
  routes: basicRoutes as unknown as RouteRecordRaw[],
  strict: true,
  scrollBehavior: () => ({ left: 0, top: 0 }),
});
