### ISSUE TITLE
登陆后无法返回原页面

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#611]
版本号： 3.5.1
问题描述：登陆过时跳转登陆页，登陆后返回首页而不是原页面。
如：登陆地址是 http://boot3.jeecg.com/login?redirect=/system/user, 登陆后跳转的仍然是首页而不是/system/user, redirect参数无效

**Comment by zhangdaiscott** [comment]
这个已经修复，演示环境一直没发布

**Comment by q060831** [comment]
@zhangdaiscott 
看了最新版的代码,登录后都是调用`src/store/modules/user.ts`的`afterLoginAction`方法,而且每种登录都是没有传递`goHome`参数,即`goHome`参数只能是`true`,也就是说肯定会执行
`
goHome && (await router.replace((userInfo && userInfo.homePath) || PageEnum.BASE_HOME));
`
拉了最新的代码，本地部署后也是跳转到首页
