### ISSUE TITLE
系统监控中的REDIS监控页面打开，再关闭后，没有关闭计时器

### ISSUE THREAD

**Issue by pjhyz1012** [jeecgboot/jeecgboot-vue3#615]
##### 问题描述：
系统监控中的REDIS监控页面打开，再关闭后，依旧不停在向后台请求数据，没有关闭计时器。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/45746114/7f58e672-07fd-4dce-88d7-b4a3e9fc0afe)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
已修复，下一个版本发布。
