### ISSUE TITLE
Popup弹窗选择组件 选择的online 报表无法出现查询条件

### ISSUE THREAD

**Issue by OzWangCNH** [jeecgboot/jeecgboot-vue3#616]
##### 版本号：

3.5.2
##### 问题描述：
使用在线的Online报表设置，SQL查询语句输入，一切正常，但是选择查询条件字段后，不会出现查询的界面。按照我的理解，应该是onl_cgreport_head中相应的字段出现问题，search_mode 不能正常使用，但is_search为1是正常。 但无论怎么选is_search永远为0.

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/138422993/7fdacf0c-5f97-4454-bcf3-9c9b9d94eded)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
按照issue要求补充详细说明

**Comment by zhangdaiscott** [comment]
你如果是手工改的数据库是有问题的，因为online接口有redis缓存
