### ISSUE TITLE
验证码404

### ISSUE THREAD

**Issue by zonghengliao** [jeecgboot/jeecgboot-vue3#618]
##### 版本号：
3.5.2

##### 问题描述：
部署完一直验证码404

##### 截图&代码：
报这个错误
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/129018641/9ac39944-6889-4c3c-9149-6afc417cc610)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/129018641/3b152c12-28ef-40ea-9248-16c93067e3be)
env文件设置
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/129018641/5f351357-16b4-4003-8a03-a9a0780a1b2e)
nginx设置
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/129018641/f6065bf5-2959-46e3-9f57-2c73c4c52f50)
jeecg-boot后端的application-prod.yml设置
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/129018641/889e8adf-6765-420a-9ba2-fe775fffa2a7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后台地址通吗

**Comment by zonghengliao** [comment]
已经解决了。还是路由地址问题。
