### ISSUE TITLE
首屏加载出现：Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by liu-peiyu** [jeecgboot/jeecgboot-vue3#619]
##### 版本号：
3.5.2

##### 问题描述：
将最新版的源代码拉取下来不做任何改动，然后按官方教程，node版本16.15.0 直接执行pnpm install  再执行pnpm build 将打包文件部署到nginx，部署之后第一次可以正常进入到登录页面，再用其它浏览器或强制刷新ctrl+f5之后访问就会出现如下错误提示：
```
Uncaught SyntaxError: Invalid or unexpected token
```
测试游览器均为最新版现代浏览器，已多次复现

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/17582403/9341e8d0-5b78-4a27-95a9-59da355f3528)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/17582403/d8783f9c-3920-4ae4-9add-59e179f8f722)
nginx配置代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/17582403/972312d8-a180-4082-b3ea-8d404adf5feb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liu-peiyu** [comment]
新测将版本降低到3.5.1last就没有这个问题

**Comment by zhangdaiscott** [comment]
你是vue几？
