### ISSUE TITLE
表格固定列，加了合计后，合计栏前后会发生错位

### ISSUE THREAD

**Issue by lizhenlangvip** [jeecgboot/jeecgboot-vue3#622]
##### 问题描述：
1、table表格 [固定列，加了合计后，合计栏前后会发生错位，

2、更新了最新代码[【QQYUN-5571】自封装选择列，解决BasicTable数据多，行选择卡顿问题](https://github.com/jeecgboot/jeecgboot-vue3/commit/e9c2854b43e6efdb73ab0a684a01b29d15300876) ，

发现执行成功回调方法后，实际selectedRowKeys数组已经清掉，所选记录打勾未清除，还显示打勾状态
function handleSuccess() {
   (selectedRowKeys.value = []) && reload();
}

##### 截图&代码：
![微信图片_20230704222530](https://github.com/jeecgboot/jeecgboot-vue3/assets/136687312/6bfb3949-359b-4eec-8179-fd64efac3252)

**Comment by sjlei** [comment]
https://help.jeecg.com/component/Table.html
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34293221/ffe2c950-96a8-4076-a99d-9fa65ce0ab52)
试试给你的表格加一下这个更新日志里的配置。
`expandIconColumnIndex: 1`，如果1不行就调整到2，以此类推，应该是展开行的加号错位导致

**Comment by lizhenlangvip** [comment]
> https://help.jeecg.com/component/Table.html ![image](https://user-images.githubusercontent.com/34293221/251613975-ffe2c950-96a8-4076-a99d-9fa65ce0ab52.png) 试试给你的表格加一下这个更新日志里的配置。 `expandIconColumnIndex: 1`，如果1不行就调整到2，以此类推，应该是展开行的加号错位导致

展开这个没问题，是执行了成功回调方法后，选择的行前面的勾并未取消，还是显示打勾状态
function handleSuccess() {
(selectedRowKeys.value = []) && reload();
}

**Comment by sjlei** [comment]
你的 selectedRowKeys 是定义在哪里的？有没有传递给 `rowSelection` 配置？
类似下面的写法：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34293221/2b972f17-9df4-444f-9592-4e3ee972a9b0)

**Comment by lizhenlangvip** [comment]
> @lizhenlangvip 你的 selectedRowKeys 是定义在哪里的？有没有传递给 `rowSelection` 配置？ 类似下面的写法： ![image](https://user-images.githubusercontent.com/34293221/251725629-2b972f17-9df4-444f-9592-4e3ee972a9b0.png)
> 
> `rowSelection` 要显式传递给BasicTable ![image](https://user-images.githubusercontent.com/34293221/251726230-be227921-39f6-415a-8f46-20f8e15ec3af.png)


代码自动生成的，应该是这个提交的自定义列代码问题

![微信图片_20230707212129](https://github.com/jeecgboot/jeecgboot-vue3/assets/136687312/bd100ac5-9dce-4e17-b8f0-85555806b870)
![微信图片_20230707212134](https://github.com/jeecgboot/jeecgboot-vue3/assets/136687312/b4d5ac48-db29-4812-931b-99b4db944fa1)

**Comment by sjlei** [comment]
问题已修复，下版本发布。
