### ISSUE TITLE
更新到最新的代码，自封装选择列，开发的时候选择Table行不卡顿，编译发布后依然很卡

### ISSUE THREAD

**Issue by lizhenlangvip** [jeecgboot/jeecgboot-vue3#626]
##### 问题描述：

更新到自封装选择列，解决BasicTable数据多卡顿 最新的代码，开发的时候选择行不卡顿，编译发布后依然很卡，没多少改变。
试了下官网的演示程序，也是一样很卡。不是浏览器缓存问题，在新的电脑上打开也是一样很卡
[【QQYUN-5571】自封装选择列，解决BasicTable数据多，行选择卡顿问题](https://github.com/jeecgboot/jeecgboot-vue3/commit/e9c2854b43e6efdb73ab0a684a01b29d15300876)

**Comment by zhangdaiscott** [comment]
官网的演示一直没发布，是老的代码
