### ISSUE TITLE
component模式的 JPopup 组件选中数据后进行其他操作

### ISSUE THREAD

**Issue by zhangwenqi997** [jeecgboot/jeecgboot-vue3#627]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/54975511/063e095c-cd2c-470e-adb6-c04a0faf1d21)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前修改会抛出 popUpChange，已经提交
