### ISSUE TITLE
第一次新增数据列表不显示

### ISSUE THREAD

**Issue by shy2013** [jeecgboot/jeecgboot-vue3#628]
##### 问题描述：
职务管理空列表的情况下新增一条数据，接口正确返回但列表不显示数据，并且也发现很多空列表第一次新增数据都有这个问题

##### 截图&代码：

![93e7f18184da8eb5eaa3a102d4239de7](https://github.com/jeecgboot/jeecgboot-vue3/assets/26700438/20a48072-8559-464f-9815-17b2aa3ab9fb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by shy2013** [comment]
> zy

您好，您这边可以复现吗

**Comment by liaozhiyang** [comment]
是项目down初始化第一次新增吗？我删除了现有的列表成空，能正常新增显示，没复现这个问题

**Comment by shy2013** [comment]
> 是项目down初始化第一次新增吗？我删除了现有的列表成空，能正常新增显示，没复现这个问题

是初始化第一次新增，而且很多这样的新增都不显示，我稍后录一个视频
