### ISSUE TITLE
使用vite .env.test 配置文件打包后，  Ant-Design-Vue3中的<a-date-picker> 组件无法选择日期

### ISSUE THREAD

**Issue by baobeiyatou** [jeecgboot/jeecgboot-vue3#629]
##### 版本号：
3.5.0

##### 问题描述：
使用vite .env.test 配置文件打包后，  Ant-Design-Vue3中的<a-date-picker> 组件无法选择日期。

##### 截图&代码：
![1689130855194](https://github.com/jeecgboot/jeecgboot-vue3/assets/39516154/d1aabcaf-36ab-425d-8dd0-337d1642c18b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
test模式有些问题，已经去掉了

**Comment by Kevin-269581661** [comment]
怎么解决？我也遇到这个问题，本地运行不会有这个问题，打包了就会
