### ISSUE TITLE
下拉框越界不会自动收缩

### ISSUE THREAD

**Issue by depthwood** [jeecgboot/jeecgboot-vue3#63]
##### 版本号：
官方vue3演示环境

##### 问题描述：
下拉框内容越界不会自动收缩，好像演示的下拉框都有这个问题
复现步骤：
1.点击展开图中审批人下拉框
2.滚动鼠标
3.审批人已经消失，下拉框内容还显示在界面上

##### 截图&代码：
![image](https://user-images.githubusercontent.com/65118489/166904724-acaffa93-db91-42d6-b07f-5ab350dddbf0.png)
![image](https://user-images.githubusercontent.com/65118489/166904763-2e76c871-de38-4c5a-809b-7562c6e9efcf.png)
![image](https://user-images.githubusercontent.com/65118489/166905237-e172d5ae-b32c-4419-a4a3-071482120b46.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by tygithub1** [comment]
示例页面只是简单演示该组件的用法，实际开发中无论是用的antd-vue的select组件，还是jeecgboot二次封装的字典选择组件，都有相应的解决方案 
![image](https://user-images.githubusercontent.com/27989856/168511047-a9c73f2d-7b5a-4b3d-af2d-6c3e8a1b8af1.png)
请参考相关文档
