### ISSUE TITLE
更新到最新的代码，用户选择组件 JSelectUser ，选中后没有数据回传

### ISSUE THREAD

**Issue by PjqDD** [jeecgboot/jeecgboot-vue3#630]
版本号：3.5.2
问题描述：
用户选择组件 JSelectUser ，点击行选中数据时，数据没有回传（不是勾选复选框）

出现问题时间：同步最新代码后：
[【QQYUN-5571】自封装选择列，解决BasicTable数据多，行选择卡顿问题](https://github.com/jeecgboot/jeecgboot-vue3/commit/e9c2854b43e6efdb73ab0a684a01b29d15300876)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/cf7f6629-e745-42e0-aced-9ddd8ec05f06)

**Comment by PjqDD** [comment]
又发现一个，应该属于同类型问题：JPopup 组件无法点击行选中数据

**Comment by zhangdaiscott** [comment]
更新代码吧
https://github.com/jeecgboot/jeecgboot-vue3/commit/557597390caab42727b4cfc33f10ceee358addbd

**Comment by PjqDD** [comment]
还有问题，我提新的Issues吧
