### ISSUE TITLE
更新到最新的代码，JPopup 组件选中数据错乱

### ISSUE THREAD

**Issue by PjqDD** [jeecgboot/jeecgboot-vue3#633]
##### 问题描述：1、（1）JPopup 组件无法点击行选中数据，只能点击行取消选中.（2）选中数据后，再次进入弹窗，点击行无法取消选中（截图3）
2、JPopup 组件 数据选择有问题（更新到最新代码好像多了个数据回显功能？），多次勾选后会提示：至少选择一条记录

##### 实现步骤：
（1）JPopup组件弹窗内 勾选两条数据，点击确定，会提示：只能选择一条记录，取消一条选中，再次点击确定，数据选择完毕。
（2）再次点击JPopup组件，打开弹窗（会默认选中上次选中的数据），再勾选一条数据，会提示：只能选择一条记录，取消一条选中，再次点击确定，会提示：至少选择一条记录（截图1）
（3）有时选完数据后，再次点击JPopup组件，打开弹窗，会有两条数据选中，这个没测出来具体是怎么操作的（截图2）

出现问题时间：同步最新代码后
[【QQYUN-5571】自封装选择列，解决BasicTable数据多，行选择卡顿问题](https://github.com/jeecgboot/jeecgboot-vue3/commit/e9c2854b43e6efdb73ab0a684a01b29d15300876)

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/16ee13a0-349e-413e-905f-58501582e7ce)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/f8d75f4c-22f2-48cd-8519-627e22e707d9)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/b08b7f6d-d4bd-4243-a708-c494b53f430e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
