### ISSUE TITLE
VITE_GLOB_DOMAIN_URL=http://设置成localhost/jeecgboot，上传报跨域错

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecgboot-vue3#635]
##### 问题描述：
VITE_GLOB_DOMAIN_URL=http://localhost/jeecgboot，访问接口数据没问题，上传时报跨域错.
VITE_GLOB_DOMAIN_URL=http://192.168.0.101/jeecgboot 必须设置成ip，上传才没问题，，可是需求要求，nginx不能写死ip，网站文件不能写死ip
nginx配置没问题，设置成server_name    localhost;

##### 截图&代码：
![~RT%WVV$J3JI6(9E0`N8ZJS](https://github.com/jeecgboot/jeecgboot-vue3/assets/57313995/714a4351-fba9-498a-8ca0-237dc3492443)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个就是后台接口地址，如果你有个性化的要求，你得自己扩展了
