### ISSUE TITLE
Online在线生成的列表页第一次新增数据后列表不能自动刷新

### ISSUE THREAD

**Issue by fyx2012** [jeecgboot/jeecgboot-vue3#637]
##### 截图&代码：

<img width="1389" alt="1" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/12606493/8e0f7693-f7c1-4cbe-9039-6f65bdc88554">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/628

未重现

**Comment by fyx2012** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/assets/12606493/67cf8549-abd2-4158-a0a3-38f5bbf646e9

**Comment by fyx2012** [comment]
> #628
> 
> 未重现
你好 我录制了一个视频 复现了一下问题

https://github.com/jeecgboot/jeecgboot-vue3/assets/12606493/7a81ef28-8897-4029-8bfc-121749e3b5d3
