### ISSUE TITLE
1.仪表盘重新修改名称，弹窗提示null，2.复制面板预览编辑失败

### ISSUE THREAD

**Issue by zander92** [jeecgboot/jeecgboot-vue3#639]
##### 版本号：
V3.5.2

##### 问题描述：
1.编辑名称，保存提示，null
2.复制面板后，编辑设计副本面板，打开页面空白
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31072462/0602758f-d808-49d9-8dac-fd5b6a29c36c)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31072462/04600bfc-03e4-4b5a-ad4b-11fa09659e2a)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31072462/265b12a8-cc31-4019-b8df-cb0a5ac3fa9c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lsqGitHub716** [comment]
测试未复现你说的问题。前端清除一下缓存，重新下依赖。还有报错的话，代码跟一下，截图看一下你这个null的具体原因
