### ISSUE TITLE
vue3项目中在main.js内引入的windi会影响到html2canvas绘制的图片样式

### ISSUE THREAD

**Issue by Libpzzz** [jeecgboot/jeecgboot-vue3#640]
##### 问题描述：
vue3项目中，在main.js内引入的windicss会影响到html2canvas绘制的图片样式
import 'virtual:windi-base.css';
import 'virtual:windi-components.css';
import 'virtual:windi-utilities.css';
import 'virtual:windi-devtools';
如果将这四个引入注释就可以了，但是会影响到其他页面的样式
##### 截图&代码：
没有注释时：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/91443254/6de03849-0ab9-4bd5-a52c-e02abb5ed90c)

注释样式：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/91443254/cf3ebe65-8e74-4701-902e-3f363ece6b09)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录  zy

**Comment by liaozhiyang** [comment]
是img{display: block}属性影响到了canvas绘制样式错乱问题。
解决方案1：全局img{display:inline-block} 覆盖之前的img样式（有可能会影响到其它页面样式）。
解决方案2：点击生成图片的时先创建一个全局的样式覆盖，图片生成之后再删除。
//点击事件创建全局覆盖样式
let styleEle;
styleEle=document.createElement("style");
styleEle.textContent="img{display:inline-block;!important}"
document.querySelector("head").appendChild(styleEle);
//生成之后再删除
document.querySelector("head").removeChild(styleEle)

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/55b35611-3897-4021-8163-b6be57502add)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/59277e12-aa78-41a6-b688-b340387e9f73)
