### ISSUE TITLE
调整表格搜索表单的span配置无效

### ISSUE THREAD

**Issue by Leafskyyy** [jeecgboot/jeecgboot-vue3#641]
##### 版本号：
3.5.1

##### 问题描述：
调整表格搜索表单的span配置无效，完全不影响表单组件大小

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/132561176/68665fc6-1872-4573-a8e5-53cf627e19a7)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/132561176/4282ddbc-6bb8-4b23-ad8e-2f22216aa1d0)

**Comment by zhangdaiscott** [comment]
收录

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
