### ISSUE TITLE
仪表盘API数据源开发问题

### ISSUE THREAD

**Issue by zander92** [jeecgboot/jeecgboot-vue3#642]
##### 版本号：
V3.5.2

##### 问题描述：
在jeecgboot后端编写get请求接口，但是在仪表盘配置API数据源时，如何带入token参数？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31072462/16b13a9a-aa93-4340-9056-558ab434b399)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31072462/d6f905cd-2a8b-40ac-97d3-9ccb23c86cad)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31072462/9cea0a94-6104-4c41-8e00-74a982d9db4a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已修改
