### ISSUE TITLE
怎样实现通过当前页面中的按钮，关闭当前页面及其tag的功能

### ISSUE THREAD

**Issue by allure11** [jeecgboot/jeecgboot-vue3#643]
##### 版本号：
jeecgboot-vue3 

##### 问题描述：
怎样实现通过当前页面中的按钮，关闭当前页面的功能

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/86544479/c884e861-07a4-405f-bcb3-a1d82e0c0cbd)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://boot3.jeecg.com/comp/basic/tabs
