### ISSUE TITLE
引入jquery 本地引入正常  部署到nginx上就出现错误，是路径哪里不对吗？

### ISSUE THREAD

**Issue by Aiwaha** [jeecgboot/jeecgboot-vue3#644]
##### 问题描述：

引入jquery 本地引入正常  部署到nginx上就出现错误，是路径哪里不对吗？
##### 截图&代码：
错误
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31761347/ddb59c90-789f-442c-8725-8f96f810e36b)
代码中引入
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/31761347/8621a134-7561-4257-8a34-c18fefd08190)

### 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
二开问题，我们无法处理
