### ISSUE TITLE
合并单元格

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecgboot-vue3#645]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ciahua** [comment]
版本号：v3.5.2
vue3

问题描述：
我希望在表格内，对相邻行，如果内容一样，就合并成同一个单元格，比如同一列的上一行是“张三”，下一行也是“张三”，那么这两行的单元格就合并为同一个单元格，要如何实现？

截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37827583/87c86bbc-245c-45f3-b0f7-fac7882642a7)

**Comment by zhangdaiscott** [comment]
我们只负责处理平台本身bug
