### ISSUE TITLE
第一次新增数据列表不显示（附有视频和后端返回）

### ISSUE THREAD

**Issue by shy2013** [jeecgboot/jeecgboot-vue3#646]
##### 问题描述：
职务管理空列表的情况下新增一条数据，接口正确返回但列表不显示数据，并且也发现很多空列表第一次新增数据都有这个问题

##### 截图&代码：
![93e7f18184da8eb5eaa3a102d4239de7](https://github.com/jeecgboot/jeecgboot-vue3/assets/26700438/20a48072-8559-464f-9815-17b2aa3ab9fb)

https://github.com/jeecgboot/jeecgboot-vue3/assets/26700438/333fb7eb-80d6-44f3-a96e-76df2543a1c6

<img width="1186" alt="a53450a54fc2eb35377fc964917be2b6" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/26700438/ad6c125e-a2df-484b-ba7b-9424fc6f7cd6">
<img width="1201" alt="7e236aa142318e68e04028e8bc5f3ef4" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/26700438/0df6bdf9-6a5b-4769-bec1-07f8c343eb08">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by shy2013** [comment]
@zhangdaiscott @liaozhiyang请在帮忙看一下，多谢

**Comment by zhangdaiscott** [comment]
职务管理我们测试没问题，不如你自己debug跟踪下代码看看为什么
