### ISSUE TITLE
前端请求参数进行签名的密钥问题

### ISSUE THREAD

**Issue by BruceLiu3385** [jeecgboot/jeecgboot-vue3#647]
##### 版本号：
3.5.2

##### 问题描述：
我在学习jeecgboot-vue3源码的过程中，了解到了请求参数需要进行签名算法生成签名的部分。发现签名的密钥，就只是硬编码到了前端，这样是不是很容易就在浏览器中找到签名的密钥signatureSecret了，这样就不会很安全吧？即使前端得不到这个密钥，是不是也应该将签名密钥不固定才对？

如果通过user-based siging的方式来处理签名密钥，就是每个用户的签名密钥不一样才对，而且是有时效性的。比如用登录认证后的token作为这个用户的签名密钥，用户登录认证成功后，得到token，当这个用户的token作为他请求api时参数的签名密钥得到签名X-sign，再通过https传输，防止中间人获取，传到后端，后端再通过这个用户的token对签名进行验签。这样会更安全一些

##### 截图&代码：

![HM1V@9VB41$02DWA8B}YP~P](https://github.com/jeecgboot/jeecgboot-vue3/assets/7733877/b2243102-cf6d-4101-b96d-56580582f549)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/7733877/a3c7195a-c7db-49a1-840a-2b485b62da01)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by EightMonth** [comment]
jeecg并不会提供安全性方案的参考，本身也不并是这方面的专家，推荐尝试以下方式：
将密钥作为前端应用的环境变量进行配置。在打包或部署前端应用时，可以将密钥配置为环境变量，并在应用运行时通过环境变量读取密钥。这样可以将密钥从源代码中分离出来，避免意外泄露。

**Comment by BruceLiu3385** [comment]
> jeecg并不会提供安全性方案的参考，本身也不并是这方面的专家，推荐尝试以下方式： 将密钥作为前端应用的环境变量进行配置。在打包或部署前端应用时，可以将密钥配置为环境变量，并在应用运行时通过环境变量读取密钥。这样可以将密钥从源代码中分离出来，避免意外泄露。

即使把密钥放在环境变量中，通过前端js调试也是可以打印出具体的密钥值的。最好是基于用户登录后才获取到这个用户专有的密钥值，而且也是要有时效性的，后端刷新同步更新到前端，这样前端加密后端解密也同步的使用这同一个密钥。

**Comment by EightMonth** [comment]
不过我觉得即使明文显示出来，也并无不妥吧。因为这个值说是个密钥，其实就是个MD5的盐值，为加密而用的，MD5盐值的意义在于防止密码破解和确保信息传输完整一致。

**Comment by BruceLiu3385** [comment]
> 不过我觉得即使明文显示出来，也并无不妥吧。因为这个值说是个密钥，其实就是个MD5的盐值，为加密而用的，MD5盐值的意义在于防止密码破解和确保信息传输完整一致。
> 
> 在这个点，可以参考一下公私钥加解密套用理解一下。

其实主要问题就在于如果所有盐值都一样，加密算法又都是一样的，就保证不了传输数据是完整不被篡改了。敏感数据截获篡改后，再通过这个盐值算好新的密文，值到后端进行解密，也能通过了，就修改了原始数据

**Comment by EightMonth** [comment]
问题不应该是这么考虑的，首先第一点，是合法用户还是非法用户。
一、如果是合法用户，不存在自己破解自己的说法，所以我们主要还是看非法用户。
二、非法用户，非法用户必然是想获取我们的用户名密码，进而获取token，达到破解系统的目的，而盐值的目的恰恰在于让密码不可以被明文获取，只会被密文获取，同等与密码一类的敏感数据都是如此。

三、即使非法用户拿到了密钥或盐值，他们也仅仅只是掌握了加密手段，但是被加密的数据是否被系统认可，还有系统的逻辑处理与判断。

四、综合上面所有的情况，可以得出结论，不存在你说的将敏感数据截获再篡改的情况。

如果说你依然觉得存在问题的话，麻烦以jeecg系统为例，指出存在以上讨论的问题点，我们可以据实讨论。

**Comment by BruceLiu3385** [comment]
> 问题不应该是这么考虑的，首先第一点，是合法用户还是非法用户。 一、如果是合法用户，不存在自己破解自己的说法，所以我们主要还是看非法用户。 二、非法用户，非法用户必然是想获取我们的用户名密码，进而获取token，达到破解系统的目的，而盐值的目的恰恰在于让密码不可以被明文获取，只会被密文获取，同等与密码一类的敏感数据都是如此。
> 
> 三、即使非法用户拿到了密钥或盐值，他们也仅仅只是掌握了加密手段，但是被加密的数据是否被系统认可，还有系统的逻辑处理与判断。
> 
> 四、综合上面所有的情况，可以得出结论，不存在你说的将敏感数据截获再篡改的情况。
> 
> 如果说你依然觉得存在问题的话，麻烦以jeecg系统为例，指出存在以上讨论的问题点，我们可以据实讨论。

jeecg这一块主要是将前端要传给后端的值要进行保护，比如 本来传的是100元，他前端有算法，一般是把各参数进行规则排序后，再加上密钥用加密算法生成一个密文的串作为签名连同参数一起传到后端。后端要做的就是把前端传来的参数，进行同样的算法，用同一个密钥再加密生成签名，看与前端传来的签名是否一致，如果一致，说明数据参数没有进行篡改过。

数据在传输过程中想篡改很容易的，如果不用https  。中间人攻击，中间路由节点劫持等……，这样根本不用验证用户是否登录就可以完成 的。 可以了解下

**Comment by BruceLiu3385** [comment]
> > 问题不应该是这么考虑的，首先第一点，是合法用户还是非法用户。 一、如果是合法用户，不存在自己破解自己的说法，所以我们主要还是看非法用户。 二、非法用户，非法用户必然是想获取我们的用户名密码，进而获取token，达到破解系统的目的，而盐值的目的恰恰在于让密码不可以被明文获取，只会被密文获取，同等与密码一类的敏感数据都是如此。
> > 三、即使非法用户拿到了密钥或盐值，他们也仅仅只是掌握了加密手段，但是被加密的数据是否被系统认可，还有系统的逻辑处理与判断。
> > 四、综合上面所有的情况，可以得出结论，不存在你说的将敏感数据截获再篡改的情况。
> > 如果说你依然觉得存在问题的话，麻烦以jeecg系统为例，指出存在以上讨论的问题点，我们可以据实讨论。
> 
> jeecg这一块主要是将前端要传给后端的值要进行保护，比如 本来传的是100元，他前端有算法，一般是把各参数进行规则排序后，再加上密钥用加密算法生成一个密文的串作为签名连同参数一起传到后端。后端要做的就是把前端传来的参数，进行同样的算法，用同一个密钥再加密生成签名，看与前端传来的签名是否一致，如果一致，说明数据参数没有进行篡改过。
> 
> 数据在传输过程中想篡改很容易的，如果不用https 。中间人攻击，中间路由节点劫持等……，这样根本不用验证用户是否登录就可以完成 的。 可以了解下

如果中间人截获了请求数据，把参数100改成1元，再用同样算法生成一个签名后，继续发往服务器……服务器验证不出来的

**Comment by EightMonth** [comment]
100块这个数据已经被加密了，又如何被解密，然后篡改成1块呢

**Comment by BruceLiu3385** [comment]
> 100块这个数据已经被加密了，又如何被解密，然后篡改成1块呢

不是解密，jeecg传的是原参数数据，参数可以得到的，他只是基于自己的那个固定的密钥去生成一个签名，连同参数一起传到后端，后端来验证签名是否跟后端重新计算的签名是否一致，同样算法计算参数得到的签名是否一样。没有解密的动作。

**Comment by EightMonth** [comment]
参数被加密是在JS代码层面的，该阶段处理无法被外界获取，如果到http请求层面，参数已经被JS加密成密文了，所以你说的原参数数据，是无法被获取再然后篡改加密伪造数据传给后端。

**Comment by BruceLiu3385** [comment]
> 参数被加密是在JS代码层面的，该阶段处理无法被外界获取，如果到http请求层面，参数已经被JS加密成密文了，所以你说的原参数数据，是无法被获取再然后篡改加密伪造数据传给后端。
> 
> 另外，如果能做到中间拦截请求，为什么不直接获取到token，就完成了破解系统的目的，然后就随意操作了，你的言论太过于理想化，我觉得我们应该基于实际情况考虑。

截获token也完全可以的，这就是为什么要有https的原因

**Comment by EightMonth** [comment]
那这就是项目实际部署的时候应该设置的安全考虑了，而不是在jeecg层面纠结。

**Comment by BruceLiu3385** [comment]
> 那这就是项目实际部署的时候应该设置的安全考虑了，而不是在jeecg层面纠结。

每个层面自己能做的也要将自己该做的部分尽量做好才对，如果客户不愿意必须安装ssl，也想安全方面尽量做到更安全一些怎么办？其实在一定程度上，不使用ssl，像你说的token截获也是有办法提高到很高的安全级别的。换句话说，即使使用https，也不能保证绝对安全，要做的就是要提高安全级别！

**Comment by EightMonth** [comment]
我个人认为jeecg使用密钥对请求参数进行加密处理，再后把数据给到后端，不让请求参数被解密出来，就已经是在数据传输上做到了最大的安全处理，前端本来也只需要管控好数据传输上的安全即可。数据传输已经被加密传输了，即使不安全ssl证书，也可以保护绝大多数的安全了，安装ssl证书只是更加多了一层保障，并不是一定要安装。
至于你说的请求被拦截，我不知道你了解不了解这块的难度，据我了解，拦截请求几乎只能在服务器上安装木马才能做到的，如果硬件都被入侵了，又谈什么软件上的安全呢。

**Comment by BruceLiu3385** [comment]
> 我个人认为jeecg使用密钥对请求参数进行加密处理，再后把数据给到后端，不让请求参数被解密出来，就已经是在数据传输上做到了最大的安全处理，前端本来也只需要管控好数据传输上的安全即可。数据传输已经被加密传输了，即使不安装ssl证书，也可以保护绝大多数的安全了，安装ssl证书只是更加多了一层保障，并不是一定要安装。 至于你说的请求被拦截，我不知道你了解不了解这块的难度，据我了解，拦截请求几乎只能在服务器上安装木马才能做到的，如果硬件都被入侵了，又谈什么软件上的安全呢。

我提的issue主要说的意思就是他这种密钥不变，并且硬编码到前端，代码又是开源的，这块做跟没做基本没啥区别了

**Comment by BruceLiu3385** [comment]
> > 我个人认为jeecg使用密钥对请求参数进行加密处理，再后把数据给到后端，不让请求参数被解密出来，就已经是在数据传输上做到了最大的安全处理，前端本来也只需要管控好数据传输上的安全即可。数据传输已经被加密传输了，即使不安装ssl证书，也可以保护绝大多数的安全了，安装ssl证书只是更加多了一层保障，并不是一定要安装。 至于你说的请求被拦截，我不知道你了解不了解这块的难度，据我了解，拦截请求几乎只能在服务器上安装木马才能做到的，如果硬件都被入侵了，又谈什么软件上的安全呢。
> 
> 我提的issue主要说的意思就是他这种密钥不变，并且硬编码到前端，代码又是开源的，这块做跟没做基本没啥区别了

ssl主要是保护传输过程数据的安全哦，在传输节点上被截获不能被解密，他用的是非对称加密，要有三方颁发的证书，公钥，私钥……

**Comment by BruceLiu3385** [comment]
> > > 我个人认为jeecg使用密钥对请求参数进行加密处理，再后把数据给到后端，不让请求参数被解密出来，就已经是在数据传输上做到了最大的安全处理，前端本来也只需要管控好数据传输上的安全即可。数据传输已经被加密传输了，即使不安装ssl证书，也可以保护绝大多数的安全了，安装ssl证书只是更加多了一层保障，并不是一定要安装。 至于你说的请求被拦截，我不知道你了解不了解这块的难度，据我了解，拦截请求几乎只能在服务器上安装木马才能做到的，如果硬件都被入侵了，又谈什么软件上的安全呢。
> > 
> > 
> > 我提的issue主要说的意思就是他这种密钥不变，并且硬编码到前端，代码又是开源的，这块做跟没做基本没啥区别了
> 
> ssl主要是保护传输过程数据的安全哦，在传输节点上被截获不能被解密，他用的是非对称加密，要有三方颁发的证书，公钥，私钥……

算了，不扯了。
