### ISSUE TITLE
Online在线生成的列表页第一次新增数据后列表不能自动刷新（已录制视频）

### ISSUE THREAD

**Issue by fyx2012** [jeecgboot/jeecgboot-vue3#648]
##### 截图&代码：

https://github.com/jeecgboot/jeecgboot-vue3/assets/12606493/a0946118-f701-485b-a1b5-ced80dc4199a

<img width="1389" alt="1" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/12606493/3310ecc8-cc60-442f-8d45-51aee296e69f">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你们是一个团队？
https://github.com/jeecgboot/jeecgboot-vue3/issues/646

**Comment by fyx2012** [comment]
@zhangdaiscott 您好 该问题已解决 是因为接口返回列表数据时 total字段类型为string类型引起的 感谢您的宝贵时间排查并回复我
