### ISSUE TITLE
前端组件params传参获取不到值

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/jeecgboot-vue3#649]
##### 版本号：
3.5.0

##### 问题描述：
组件传params 无法获取到实体参数

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50694382/24e823ac-5468-4231-8ee7-c0e15e9695b9)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50694382/a99c8e15-95c6-435e-ae08-1047bf3acb38)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/ae4db334-d114-42e9-a525-0051b61d918d)
<img width="836" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/c1da0f40-91d1-4f1e-b537-0c57f028189d">
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/50eba420-a2c3-4b52-8b44-62a6d5fa18a5)
经测试，正常。你可以找个官方的组件例子试下
