### ISSUE TITLE
能否优化下菜单管理功能，菜单行编辑按钮增加角色授权按钮链接

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#65]
##### 版本号：
V1.0.0

##### 问题描述：
能否优化下菜单管理功能，菜单行编辑按钮增加角色授权按钮链接。
开发了新功能，配置菜单，然后就是菜单授权角色，往往一个菜单需要授权给多个角色，希望在菜单管理行按钮有个授权功能，直接授权给多个角色，而非跑到角色管理处对多个角色分别授权菜单。

**Comment by zhangdaiscott** [comment]
？

**Comment by eyuan** [comment]
> ？

![image](https://user-images.githubusercontent.com/1910132/167324244-81735de6-5325-42a2-9fba-d662b4bc5838.png)

**Comment by zhangdaiscott** [comment]
不采纳
