### ISSUE TITLE
下拉组件重置问题

### ISSUE THREAD

**Issue by fireinjava** [jeecgboot/jeecgboot-vue3#651]
##### 版本号：
v3.5.0

##### 问题描述：
问题1：下拉组件如 JSearchSelect 重置的时候不要判断length>0，因为updateSchema时可能需要清空下拉项；
比如二级联动，可能下一级本来就是空的呢

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/5036983/b2557b2a-c576-4b0c-8405-fa62f6580137)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改
