### ISSUE TITLE
vue3原生表单校验问题

### ISSUE THREAD

**Issue by gaophash** [jeecgboot/jeecgboot-vue3#653]
##### 版本号：jeecgboot-vue3 
                         version: 3.4.4

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/104067340/72074264-73e4-42e5-819e-f513f680ea2f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 zp

**Comment by lsqGitHub716** [comment]
麻烦把编辑表单弹窗的代码截图一下

**Comment by lsqGitHub716** [comment]
Vue3代码生成原生单表，测试校验未发现你说的问题。请详细描述一下你本地问题的复现步骤，以便我们追踪问题。
![表单校验](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/0765b67d-0a07-472e-aedb-89266107322d)

**Comment by lsqGitHub716** [comment]
Vue3代码生成原生单表，测试校验未发现你说的问题。请详细描述一下你本地问题的复现步骤，以便我们追踪问题。
![表单校验1](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/fe3c9de0-07c3-4a87-80b9-ac92b13b41a5)
