### ISSUE TITLE
仪表盘设计器，添加到菜单栏时样式错位，预览没问题

### ISSUE THREAD

**Issue by Tech--man** [jeecgboot/jeecgboot-vue3#654]
##### 截图&代码：

<img width="1051" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/5569639/dbac783a-f551-4a18-a0e1-a2b463cd0b48">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
可以临时将样式 import 'jeecg-drag-design/lib/index.css'; 引入到全局中来解决这个问题
