### ISSUE TITLE
引入Form组件以后，界面的按钮显示文字不正常

### ISSUE THREAD

**Issue by chenjian823** [jeecgboot/jeecgboot-vue3#659]
##### 版本号：
3.5.3 

##### 问题描述：
引入Form组件以后，界面的按钮显示文字不正常
import { BasicForm } from './Form';

##### 截图&代码：
![53c3a37e8b0780a0b8e5246e686cad1a](https://github.com/jeecgboot/jeecgboot-vue3/assets/29327357/5f27a51f-8380-4a6d-b6a4-95f747956ff7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以采用异步方式引入，这么引入的确有问题
