### ISSUE TITLE
表格列的配置（是否显示、冻结等）关闭页面后，再点击页面进入，配置丢失了

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#66]
##### 版本号：
v1.0.0

##### 问题描述：
表格列的配置（是否显示、冻结等）关闭页面后，再点击页面进入，配置丢失了。
这个是用户级别的配置吗？还是会话级别的配置？如果只是页面级别配置，这个功能就比较鸡肋了。
如果用户级别配置后，是这个用户的偏好设置，那么这个用户打开页面看到的表格显示的列就是他配置后的效果，再提供管理员后台重置用户配置的功能就更好了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/167294306-4af0a25d-502a-424a-847a-6c0c02fbf6d8.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
已加入缓存功能，新版本发布
