### ISSUE TITLE
online表单配置java增强，测试的时候可以使用，但是生成后配置到菜单里就失效了

### ISSUE THREAD

**Issue by dugudongfangshuo** [jeecgboot/jeecgboot-vue3#660]
##### 版本号：
3.5.3

##### 问题描述：
online表单配置java增强，测试的时候可以使用，但是生成后配置到菜单里就失效了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码生成就跟online没关系了
