### ISSUE TITLE
打包部署后显示操作列的表格的列设置没有字段，不显示操作列的列设置有字段

### ISSUE THREAD

**Issue by XQ-yang** [jeecgboot/jeecgboot-vue3#664]
##### 截图&代码：
有操作列的：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55075798/02ecf53e-6079-4c3c-a79a-f9ef4a48b113)

没有操作列的：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55075798/5d404622-6847-4796-b01d-085747dc373a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
升级最新的试试，我看线上是好使的。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/ff95a273-f53c-44b6-9886-1e8292660f06)
