### ISSUE TITLE
示例代码错误，需要修改

### ISSUE THREAD

**Issue by zhichengbohui** [jeecgboot/jeecgboot-vue3#665]
##### 截图&代码：
![JMA0{F8(WRVTY94LUS%W`}M](https://github.com/jeecgboot/jeecgboot-vue3/assets/40782576/cc53b4fa-e514-4be2-95a0-1101642ab652)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
已经修正，下一个版本发布
