### ISSUE TITLE
Online表单开发的页面 是否支持 路由缓存?

### ISSUE THREAD

**Issue by xiaogangya12138** [jeecgboot/jeecgboot-vue3#667]
##### 版本号：
3.4.3-GA（发布时间：2022-10-31）

##### 问题描述：
Online表单开发功能，配置菜单时，配置路由缓存无效，需要怎样配置才能生效？

##### 截图&代码：
![企业微信截图_16907952376460](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/a4f4b2af-9279-467e-ade7-3ee33710d1b8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by liaozhiyang** [comment]
支持，编辑菜单抽屉里面组件名称需要设置成：OnlineAutoList
默认主题组件名：OnlCgformTabList
ERP主题(一对多)主题组件名：CgformErpList
内嵌子表主题(一对多)主题组件名：OnlCgformInnerTableList
TAB主题(一对多)组件名：OnlCgformTabList

**Comment by MeraJiang** [comment]
> 支持，编辑菜单抽屉里面组件名称需要设置成：OnlineAutoList 默认主题组件名：OnlCgformTabList ERP主题(一对多)主题组件名：CgformErpList 内嵌子表主题(一对多)主题组件名：OnlCgformInnerTableList TAB主题(一对多)组件名：OnlCgformTabList

这个有实现吗?自己修改还是源码本来就自带的?我配了没起效果

**Comment by MeraJiang** [comment]
> 不支持

那商业版支持吗?

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/onlinebiaodanyemianhuancun.html

**Comment by zhangdaiscott** [comment]
vue3版本online菜单缓存用法
https://help.jeecg.com/online/form/cache.html
