### ISSUE TITLE
登陆后无法返回原页面

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#669]
版本号：3.5.3

问题描述：

此问题之前问过，回复说是已修复，可是我更新最新代码后还是不行。
#611 

看了最新版的代码,登录后都是调用src/store/modules/user.ts的afterLoginAction方法,而且每种登录都是没有传递goHome参数,即goHome参数只能是true,也就是说肯定会执行
`goHome && (await router.replace((userInfo && userInfo.homePath) || PageEnum.BASE_HOME));`
拉了最新的代码，本地部署后也是跳转到首页

**Comment by zhangdaiscott** [comment]
还没发布
