### ISSUE TITLE
表格的行选择提示是否可控

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#671]
版本号：3.5.3

问题描述： 表格的行选择提示是否可控

截图&代码：

![Dingtalk_20230801142811](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/74aa105f-0a9e-4c59-9873-bd613e2688af)

**Comment by zhangdaiscott** [comment]
可控是什么意思？

**Comment by q060831** [comment]
控制是否显示

**Comment by zhangdaiscott** [comment]
没这功能，个性需求可以自己扩展
