### ISSUE TITLE
打包部署到生产环境读取数据字典比开发环境慢20多倍

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#679]
版本号：3.5.3

问题描述：

使用`cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 vite build && esno ./build/script/postBuild.ts`打包读取数据字典缓存比开发环境慢20多倍
使用`cross-env NODE_OPTIONS=--max-old-space-size=8192 vite build && esno ./build/script/postBuild.ts`打包却没有这个问题
开发环境和生辰环境使用的是同一后台,打包后部署的生产环境是一样的

截图&代码：
开发环境:
![开发环境](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/f5cb5743-90f9-45c2-96e5-b1fc008bd908)

有`NODE_ENV=production`:
![生产环境](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/e6402d77-e851-41e9-be2d-a44b94c2afb7)

没有`NODE_ENV=production`:
![没有NODE_ENV=production的生产环境](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/be76df0b-3b5c-4c13-bc54-9f6d1a4396f1)

**Comment by liaozhiyang** [comment]
这是哪个方法？是读取本地缓存字典还是接口字典？能给出更详细的信息吗？

**Comment by q060831** [comment]
调用的是这个getDictItemsByCode方法

**Comment by q060831** [comment]
![Dingtalk_20230810092629](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/6b88d87c-146c-4513-ad94-bd863c9352f2)

**Comment by q060831** [comment]
另附nginx的压缩配置:

![Dingtalk_20230810095836](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/3016c202-9591-4c77-808b-2cd2c3cdc319)

**Comment by kaivanwong** [comment]
我也遇到了，生产环境很卡

**Comment by q060831** [comment]
找到问题所在了,是调用缓存导致的,Persistent.getLocal每次调用都要200多毫秒,而使用Persistent.getSession则不会

**Comment by zhangdaiscott** [comment]
在性能方面，sessionStorage 和 localStorage 的速度基本上是相同的。
是不是因为线上开启加密导致的？
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/21002e06-dd88-4909-aaf8-9ff9c4a959ed)

**Comment by q060831** [comment]
跟踪排查中

**Comment by q060831** [comment]
就是这个了
![Dingtalk_20230830094853](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/7d47c148-6a7f-405b-8262-4133c7f1926a)

**Comment by q060831** [comment]
这怎么优化啊?

**Comment by zhangdaiscott** [comment]
抽个不加密的方法，针对字典这块调用不加密的方法
