### ISSUE TITLE
JVxeTable 获取不到Column type=JVxeTypes.hidden的值。

### ISSUE THREAD

**Issue by PjqDD** [jeecgboot/jeecgboot-vue3#682]
##### 版本号：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/4d2f44a8-af32-4719-a51f-6e8b6cfbb484)

##### 问题描述：
JVxeTable 获取不到Column type=JVxeTypes.hidden的值。

获取所有数据 getTableData() 方法 和 获取选中数据  getSelectionData() 方法 都获取不到 type=JVxeTypes.hidden的值

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/8c31809c-f535-444d-a2cb-40bc068c3dd6)

![Snipaste_2023-08-04_09-28-57](https://github.com/jeecgboot/jeecgboot-vue3/assets/44695129/8dc66ac9-7b43-4c51-83d9-f88302d6d237)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/8f5e9465-a093-4a5a-85c8-e4e4246bf7ff)
查看了下无此问题，能提供更详细的信息吗？接口中是否存在hideHiddenData字段？
项目中的综合示例查看下是否有这个问题？
src/views/demo/jeecg/JVxeTableDemo/JVxeDemo1.vue
