### ISSUE TITLE
导入excel如果数据超过几十条复选框就只能展示前三个，新增数据不会出现这种情况，拉代码重新生成都试过了，不行

### ISSUE THREAD

**Issue by 87uq** [jeecgboot/jeecgboot-vue3#685]
##### 版本号：
3.5.3

##### 问题描述：
导入excel如果数据超过几十条复选框就只能展示前三个，新增数据不会出现这种情况，拉代码重新生成都试过了，不行

##### 截图&代码：
![68c7fac3c352314dba3a7759950932b](https://github.com/jeecgboot/jeecgboot-vue3/assets/141549308/cc4b498e-c8f6-4f1f-9d1c-85a10b249c53)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
有更细致的信息吗？我测试了100多条数据导入没复现此问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/96d94860-f967-47dc-b75e-66208132366e)

**Comment by liaozhiyang** [comment]
什么浏览器？什么版本？

**Comment by liaozhiyang** [comment]
没复现一模一样的，你本地代码把useCustomSelection.tsx文件bodyCustomRender方法，像下图一样注释这段代码试试？有了结果可告知下我们
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/2035f129-3481-4fc4-9c32-6b1232a7090f)

**Comment by 87uq** [comment]
> 没复现一模一样的，你本地代码把useCustomSelection.tsx文件bodyCustomRender方法，像下图一样注释这段代码试试？有了结果可告知下我们 ![image](https://user-images.githubusercontent.com/8199499/262566576-2035f129-3481-4fc4-9c32-6b1232a7090f.png)

已经解决了，是开发的错误，每次传的数据都太多
