### ISSUE TITLE
popup弹窗搜索选择bug

### ISSUE THREAD

**Issue by jujubetree** [jeecgboot/jeecgboot-vue3#686]
##### 版本号：
3.4.4

##### 问题描述：
*popup弹窗搜索选择bug，弹窗中搜索后，选择多条记录，继续使用其他关键字搜索，响应页面显示已选择第一条，取消该选择后会取消上一个关键字搜索所选择的记录*

##### 截图&代码：
*这里我搜索285 手动选中两条*
![微信截图_20230809133832](https://github.com/jeecgboot/jeecg-boot/assets/49394098/a5e11a03-9695-4c9d-99ed-3340b8d4bfc6)

*我继续搜索442 并未手动选择，但显示已选中第一条*
![微信截图_20230809133931](https://github.com/jeecgboot/jeecg-boot/assets/49394098/d644a581-c6bd-4b27-bb82-403642f367df)

*我手动选择下面四条*
![微信截图_20230809133832](https://github.com/jeecgboot/jeecg-boot/assets/49394098/e31a5cc0-1b10-46f1-baca-6a02c25315e5)

*我继续搜索548 并未手动选择，但显示已全选，文字显示我只选中6条*
![微信截图_20230809134232](https://github.com/jeecgboot/jeecg-boot/assets/49394098/557668e3-fd8b-48ab-8279-a1c0fd6b67da)

*当我点击确认后，真实数据也只有我手动选择的六条，问题在于我如果取消默认选择的那一条，系统会取消我在前一个关键字搜索的页面所选择的那条记录*
*即我在第一个搜索页选择了a，在第二个搜索页中显示我也选择了b（其实我没有选），这时我如果点击取消选择b，其实是把a取消了。如果我直接点击确认，实际结果没有b的数据*

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持你这么用

**Comment by jujubetree** [comment]
不支持怎么用？不能多次搜索是吗
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月11日 10:28 |
| 收件人 | jeecgboot/jeecgboot-vue3 ***@***.***> |
| 抄送人 | jujubetree ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jeecgboot/jeecgboot-vue3] popup弹窗搜索选择bug (Issue #686) |

不支持你这么用

**Comment by zhangdaiscott** [comment]
是的
