### ISSUE TITLE
JSelectUser组件内如果有值 编辑时浏览器卡死

### ISSUE THREAD

**Issue by fenghao7** [jeecgboot/jeecgboot-vue3#687]
##### 版本号：
3.5.3

##### 问题描述：
点击JSelectUser，如果控件内有用户，直接点选择，浏览器卡死，系统崩溃，如果先把浏览器内用户删掉，没有用户就不会卡死

##### 截图&代码：

![Z1$PL438WU~PD2)`F60UZJ3](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/5da620de-959a-4f08-9fae-e43a3fb00615)
![2~ JT$YN02GP_$A(ZRT~DFG](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/1eea0748-21c3-496b-92e4-cb8a4ebf6c27)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy
