### ISSUE TITLE
BasicTable 选择列有时候不显示

### ISSUE THREAD

**Issue by fenghao7** [jeecgboot/jeecgboot-vue3#688]
##### 版本号：

3.5.3
##### 问题描述：
BasicTable 选择列有时候不显示，不管是radio还是checkbox，但有时候又能显示。用3.5.0就没有这个问题

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/55013e34-0dd3-4555-b10a-e2ce75d0fc59)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/8a258c78-5da2-465d-b785-3a9d57a0aef3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请提供详细的重现步骤

**Comment by fenghao7** [comment]
就是在erp风格下，选择列有时候会渲染不出按钮,**只渲染3行**，但有时候又可以渲染出来，在3.5.0版本里都可以渲染出来

没渲染出来:
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/8ac50c4d-548a-4c56-905c-370602dd3da6)
渲染出来:
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/67f84bb3-9470-4ada-bfa2-695911472d60)
3.5.0:
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/84d54ed0-519c-4da7-add2-cfcec4a7c372)

**Comment by fenghao7** [comment]
3.5.3
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/b05511f2-b806-4b83-9265-9829df000e8d)

**Comment by liaozhiyang** [comment]
没复现一模一样的，你本地代码把useCustomSelection.tsx文件bodyCustomRender方法，像下图一样注释这段代码试试？有了结果可告知下我们
<img width="457" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/b966472c-3fbb-4c82-9278-146321f87b26">

**Comment by fenghao7** [comment]
按图把useCustomSelection.tsx文件bodyCustomRender方法注释了就好了







Bill
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecgboot-vue3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecgboot-vue3] BasicTable 选择列有时候不显示 (Issue #688)





 
没复现一模一样的，你本地代码把useCustomSelection.tsx文件bodyCustomRender方法，像下图一样注释这段代码试试？有了结果可告知下我们

**Comment by fenghao7** [comment]
按图把useCustomSelection.tsx文件bodyCustomRender方法注释了就好了
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/654ebcdb-8582-470d-b751-9b37dd06e6a9)
