### ISSUE TITLE
系统登录时  getUserInfo  接口无法返回数据

### ISSUE THREAD

**Issue by usdt** [jeecgboot/jeecgboot-vue3#689]
##### 版本号：
3.5.3

##### 问题描述：
输入用户名和密码点击登录，系统提示登录成功， 但是下一步  执行到 getUserInfo 是提示接口超时，没有数据返回。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后台地址配置了吗
