### ISSUE TITLE
jvxeTable demo即时保存报错

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#69]
##### 版本号：
V1.0.0-beta

##### 问题描述：
点击保存时报错，是demo代码的错误，还是jvxetable组件实现的问题？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/167556194-5c214ec7-6215-4c2d-b8aa-a3336c8b4713.png)
function handleTableSave({ $table, target }) {
  // 校验整个表格
  $table.validate().then((errMap) => {
    // 校验通过
    if (!errMap) {
      // 获取所有数据
      let tableData = target.getTableData()

**Comment by zhangdaiscott** [comment]
你的本地还是演示环境？

**Comment by eyuan** [comment]
> 你的本地还是演示环境？
都有。。。
![image](https://user-images.githubusercontent.com/1910132/167754503-5c22ce72-89c7-494f-a003-edd0e9c29221.png)

**Comment by eyuan** [comment]
![image](https://user-images.githubusercontent.com/1910132/167754551-a4d2d3a0-7681-4afa-9df8-5a85de4b31d9.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
