### ISSUE TITLE
代码生成的一多对表单，修改完代码，浏览器卡死

### ISSUE THREAD

**Issue by sunjie798893816** [jeecgboot/jeecgboot-vue3#690]
##### 版本号：
3.5.3

##### 问题描述：
代码生成的 一对多表单，修改完代码，在点击添加按钮，浏览器就卡死了。需要关闭浏览器重新打开才可以。

node版本v18.17.1
vite版本 ^3.0.2

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/11585853/d71d5097-626f-43d0-a972-b5df1e2a3bb8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
录个视频

**Comment by sunjie798893816** [comment]
> 录个视频

https://www.bilibili.com/video/BV12r4y1Z7Be/?vd_source=688b939cc5c9397215f26c67fe1b512c  视频地址

这个视频总过发生2个问题

1、第一次修改完数据，缺少一个引号，提示报错，加上引号后，热更新没有生效，页面没有自动刷新
2、重新修改数据后，热更新生效，列表自动刷新，此时点击添加按钮，没有弹窗，刷新浏览器，一直加载，直到卡死

**Comment by zhangdaiscott** [comment]
代码升级到最新看看，做了优化

**Comment by sunjie798893816** [comment]
> 代码升级到最新看看，做了优化

我刚更新了最新代码，还是不行

**Comment by jy05568536** [comment]
我也遇到同样的，100%卡死，无语
