### ISSUE TITLE
JvxeTable 没有设置选中项的方法  setSelection

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecgboot-vue3#691]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/586095d5-82ef-45d5-a144-932b4c0420cf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
vxe-table原生就有此api，setRadioRow(row)、setCheckboxRow(rows, checked)。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/19b0c6ec-9348-406d-8ec2-08c44c556727)
