### ISSUE TITLE
FormSchema[] 组件间通信疑问

### ISSUE THREAD

**Issue by pear-li10151** [jeecgboot/jeecgboot-vue3#692]
##### 版本号：
v3.5.3

##### 问题描述：
我在 formSchema中引用了一个自定义的文件上传组件，有如下两个需求
1.在文件上传完成后，form表单向后台提供的数据中除了需要包含文件的url信息，还需要包含额外的后台返回的数据。
2.在文件上传完成后，需要将非v-model的参数传递给 formSchema 的其他组件。
请问以上两个需求该如何编写 FormSchema[]
官方文档中未找到对应材料，若上述操作存在共识的现存解决方案，请提供检索方式，谢谢。

##### 截图&代码：
代码截图链接
https://iknow-pic.cdn.bcebos.com/f2deb48f8c5494ee287690803ff5e0fe98257ed7

![代码截图](https://iknow-pic.cdn.bcebos.com/f2deb48f8c5494ee287690803ff5e0fe98257ed7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
formSchema 用不明白，可以用原生方式
