### ISSUE TITLE
404页面返回首页问题

### ISSUE THREAD

**Issue by cdsuifeng** [jeecgboot/jeecgboot-vue3#694]
##### 版本号：
3.5.3
vue3
##### 问题描述：
为当前用户自定义了首页，当访问404页面时，点击返回首页，这时会加载默认首页，不会加载自定义的首页。

##### 截图&代码：
首页配置
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23712951/febc8eff-f339-4142-a9da-4416a23086d7)
访问404页面
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23712951/3c505d9d-a967-4c88-9722-83a8f1a05c88)
加载默认首页  dashboard/analysis
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23712951/c6be78f5-3ad0-4f3a-97f4-6f875f9f8ce7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
