### ISSUE TITLE
Online报表设计器中查询条件不支持参数和非结果集字段

### ISSUE THREAD

**Issue by wangqian0628** [jeecgboot/jeecgboot-vue3#695]
##### 问题描述：
Online报表设计器中参数无法添加查询条件
目前有2个问题：
1、不需要显示在结果集中的字段就无法作为查询条件；
2、参数无法作为查询条件；

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不考虑你的需求
