### ISSUE TITLE
Vue3自定义模板saveOrUpdate始终判定isUpdate为false,导致编辑数据会同时再保存一条数据

### ISSUE THREAD

**Issue by 120720979** [jeecgboot/jeecgboot-vue3#696]
##### 版本号：
jeecgboot-vue3 3.5.3
##### 问题描述：
点击保存saveOrUpdate始终判定isUpdate为false,导致编辑数据会同时再保存一条数据
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23047004/4a6be974-2778-46ea-839e-f95d0f3eccd9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不可能有这样低级的问题，如果重现？

**Comment by lsqGitHub716** [comment]
麻烦把新增编辑弹窗的代码截图一下

**Comment by lsqGitHub716** [comment]
Vue3代码生成原生单表，测试未发现你说的情况。请详细描述一下你本地问题的复现步骤，以便我们追踪问题。
![表单测试](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/d91d61d8-6d84-42fa-bccf-324b7fdecf81)
