### ISSUE TITLE
请问怎么升级vue3，只能下载最新的之后覆盖吗

### ISSUE THREAD

**Issue by Hange000** [jeecgboot/jeecgboot-vue3#698]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Hange000** [comment]
现在我遇到的问题是远程下拉框多选获取不到值

**Comment by zhangdaiscott** [comment]
按照issue要求发帖
