### ISSUE TITLE
怎么升级vue3，只能下载之后覆盖所有的文件吗

### ISSUE THREAD

**Issue by Hange000** [jeecgboot/jeecgboot-vue3#700]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/53067464/97c7b65e-0e9c-4353-817c-77f663ed7f16)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
通过git合并
