### ISSUE TITLE
table组件,一页数据为100条或更多时,列选择框会消失

### ISSUE THREAD

**Issue by clx20000410** [jeecgboot/jeecgboot-vue3#705]
##### 版本号：
3.5.3

##### 问题描述：
table组件,当一页大于等于100条数据时,列选择只显示三个,当一页数据显示50个时候则不会出现.

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/75774737/a1c1a346-0302-408e-8d66-9f902feff7ce)

**Comment by zhangdaiscott** [comment]
录个视频

**Comment by clx20000410** [comment]
Uploading toolnb-20230817114851.mp4…

**Comment by clx20000410** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/assets/75774737/2a6b66cb-524a-4213-bfc7-220edd724357

**Comment by zhangdaiscott** [comment]
什么浏览器？

**Comment by clx20000410** [comment]
谷歌

**Comment by zhangdaiscott** [comment]
版本号

**Comment by clx20000410** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/75774737/ccdc16fd-7395-4d71-a22a-cc89020bd2f8)

**Comment by clx20000410** [comment]
![1692278564267](https://github.com/jeecgboot/jeecgboot-vue3/assets/75774737/61c4d7b4-cb85-4b6e-b8b6-1bc617a5d102)
火狐也是这样  112.0.2（64位）
