### ISSUE TITLE
nginx 部署没有访问后台问题

### ISSUE THREAD

**Issue by AndrewLiuZhangZong** [jeecgboot/jeecgboot-vue3#706]
##### 问题描述：nginx 代理 pnpm build 打包后的dist，后台端口是18080
nginx配置
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/40905530/86c5bb5f-fa53-40bf-a1be-00af47b92213)
.env.production配置
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/40905530/0e424b4c-2322-40bf-ad5c-4a16d4733033)

##### 截图&代码：

 访问的时候前台没有调用18080接口的后台地址，而是还是3100前端地址，好像没有请求代理
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/40905530/34950aa0-7f23-4725-914c-da7ba40fb761)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/publish/quick.html

**Comment by AndrewLiuZhangZong** [comment]
如果没有域名哪

**Comment by AndrewLiuZhangZong** [comment]
> https://help.jeecg.com/publish/quick.html

如果没有域名该怎样配置

**Comment by zhangdaiscott** [comment]
1、nginx映射
2、后台完整地址

无域名没关系

**Comment by AndrewLiuZhangZong** [comment]
server {
    listen       3100;
    server_name  localhost;
    #前端打的dist资源存放目录
    root		 /www/wwwroot/visionfile/web/dist;
    location / {
         # 用于配合 browserHistory使用
		 try_files $uri $uri/ /index.html;
    }
	location  /jeecgboot/ {
		#后台接口地址(我们部署去掉了/jeecg-boot项目名，如果你有请加上）
		proxy_pass         http://127.0.0.1:18080/;
		proxy_redirect off;
		#真实IP获取
		proxy_set_header  Host             $host;
		proxy_set_header  X-Real-IP        $remote_addr;
		set $my_proxy_add_x_forwarded_for $proxy_add_x_forwarded_for;
		if ($proxy_add_x_forwarded_for ~* "127.0.0.1"){
		   set $my_proxy_add_x_forwarded_for $remote_addr;
		}
		proxy_set_header   X-Forwarded-For $my_proxy_add_x_forwarded_for;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}


这样配置nginx 对吗

**Comment by AndrewLiuZhangZong** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/40905530/d1e36d4a-1ccb-44aa-997e-cea72fb9cb3a)
前端配置这样的
