### ISSUE TITLE
Online表单和Auto表单：新增，修改，查看只能是弹出窗口么？是否可以使用tab页面方式（类似菜单页面）

### ISSUE THREAD

**Issue by jeking217** [jeecgboot/jeecgboot-vue3#708]
##### 版本号：
线上demo版本：http://boot3.jeecg.com 应该是3.5.3吧？

##### 问题描述：
问题：Online表单和Auto表单：新增，修改，查看只能是弹出窗口么？是否可以使用tab页面方式（类似菜单页面）
背景：对于一些复杂的业务表单，表单本身比较复杂，使用弹出窗口方式不太友好，希望能使用菜单页面那样打开，请问需要如何配置？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/26854286/9e4b0f3b-7447-4887-b0a1-c29c70dd79cf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
