### ISSUE TITLE
在线生成表格 下拉控件 配置字典 前端表格中显示不出来

### ISSUE THREAD

**Issue by ShellMount** [jeecgboot/jeecgboot-vue3#709]
##### 版本号：
 最新版本

##### 问题描述：
在线生成表格 下拉控件 配置字典 前端表格中显示不出来

##### 截图&代码：
![issue01](https://github.com/jeecgboot/jeecgboot-vue3/assets/12572507/7384fe73-a9ec-4cbc-ba5c-3c02a32a297e)

**Comment by zhangdaiscott** [comment]
列表翻译有问题？

**Comment by zhangdaiscott** [comment]
无回复，关闭
