### ISSUE TITLE
使用JDictSelectTag组件时，type为默认或select 且数据字典的键值为数字时，点击select框页面会卡死

### ISSUE THREAD

**Issue by liu-peiyu** [jeecgboot/jeecgboot-vue3#71]
##### 问题描述：
在数据字典里面增加字典值为数字型的值时，用JDictSelectTag组件，当type为默认或select时，点击select框页面会直接卡死

##### 截图&代码：
1、设置数据类型的字典
![image](https://user-images.githubusercontent.com/17582403/168189594-ccc676ab-0346-4791-8486-50bbd49a170b.png)
2、配置表单
![image](https://user-images.githubusercontent.com/17582403/168190716-480ae8c7-874d-42bf-a28d-dc9b8fadc45a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
按照您的配置测试未发现页面卡死的情况，请您F12打开控制台，查看一下具体的报错原因
