### ISSUE TITLE
生成代码后查询按钮在无查询字段时依然展示

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/jeecgboot-vue3#711]
##### 版本号：
3.5.3

##### 问题描述：
online表单开发中并未设置查询字段，但是在生成代码后显示查询按钮

##### 截图&代码：
![1692761047612](https://github.com/jeecgboot/jeecgboot-vue3/assets/71683167/bd8aba01-b653-4434-be67-9d7a166c1db8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个细节自己调整就行了
