### ISSUE TITLE
代码生成后没有高级查询了，online测试中是存在的

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/jeecgboot-vue3#712]
##### 版本号：
3.5.3

##### 问题描述：
代码生成后没有高级查询了，online测试中是存在的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
生成后，手工加入了，不支持生成
