### ISSUE TITLE
Java增强spring-key形式，删除之前，单条数据生效，批量不生效。

### ISSUE THREAD

**Issue by tiansili** [jeecgboot/jeecgboot-vue3#714]
##### 版本号：
3.5.3

##### 问题描述：
需求描述：删除之前，校验数据是否有关联关系，如果有提示报错，不允许删除

使用Java增强，参考该文档https://help.jeecg.com/online/enhanceJava/quick.html
Java中编写增强类，页面表单开发中，增加Java增强，spring-key形式

单条数据删除时，能够正常校验，并报错提示
选中多条，使用批量删除，没有作用

##### 截图&代码：

截图略，简而言之，单条数据生效，批量不生效。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
scott

**Comment by zhangdaiscott** [comment]
请截图看下如何配置的

**Comment by zhangdaiscott** [comment]
无回复的话，暂时关闭了
