### ISSUE TITLE
tinymce is not defined

### ISSUE THREAD

**Issue by bibichuan** [jeecgboot/jeecgboot-vue3#717]
##### 版本号：
3.5.3

##### 问题描述：
使用 pnpm install 或者是使用 yarn install,下载官方代码，然后运行，在window下显示：tinymce is not defined，问题出在这个 

node_modules/@qiaoqiaoyun/drag-free/lib/index.umd.min.js 模块中。

##### 截图&代码：

![jeecg_1](https://github.com/jeecgboot/jeecgboot-vue3/assets/14054904/82d140e2-780f-4399-8577-43114a585b96)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
下载的最新代码？还是自己更新的部分

参考这个修改全局注册代码
https://github.com/jeecgboot/jeecgboot-vue3/commit/602116e2fa63db23dd4032cbb17f60d12904e522

**Comment by bibichuan** [comment]
下载了最新的代码，然后我在原码的基础上开了一个分支，最后把原先的代码重新拷贝复制了一份，替换之后，问题没有了，算是解决了这个问题。但是为什么会出现这个问题，以及真正的解决方案，我也不知道了。

**Comment by zhangdaiscott** [comment]
应该合并的有问题

**Comment by zhangdaiscott** [comment]
降低仪表盘版本

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/10ede309-7415-45e0-a1d2-0adcf9b53491)
