### ISSUE TITLE
Online表单下拉搜索框设置为必填时 进入编辑页面会立即触发必填验证

### ISSUE THREAD

**Issue by zhangning12138** [jeecgboot/jeecgboot-vue3#719]
##### 问题描述：
Online表单,在控件类型为下拉搜索框并设置为必填时,进入编辑页面该字段会立即触发必填验证,即使这个字段是有值的,也会触发,且无法直接点击确定,必须重新选择一次才可以.
通过js增强的form,对其赋值也没有效果.

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/54303531/483bfd65-915f-405f-a119-0a04e5f7a672)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangning12138** [comment]
下拉搜索框的选项来源于table类型的字典

**Comment by zhangning12138** [comment]
回退到v3.5.3就没问题了

**Comment by ve03** [comment]
@zhangning12138 
![11](https://github.com/jeecgboot/jeecgboot-vue3/assets/157146280/942263a2-6adf-4528-90ec-dd5b4dfe030a)
