### ISSUE TITLE
JVxeDragSortCell应能控制是否显示"插入一行"菜单

### ISSUE THREAD

**Issue by sfox-xg** [jeecgboot/jeecgboot-vue3#72]
##### 版本号：
1.0.0

##### 问题描述：
JVxeTable使用排序时，JVxeDragSortCell应能控制是否显示"插入一行"菜单

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
