### ISSUE TITLE
yarn/pnpm install都导致电脑崩溃

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecgboot-vue3#720]
##### 版本号：
最新版本： 3.5.3（发布时间：2023-07-24）

##### 问题描述：
我把node_modules删了，yarn install，始终出现下面的界面

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/14859466/2786375c-8661-405a-bdfc-fc5ab093b01c)

然后，2个多小时过去了，还没编译完，提示内存爆了，就闪退了。试了几天，每天试好几次，还是如下图，请问应该如何解决？

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/14859466/2867f706-d9b3-4088-b503-371819c5e479)

##### 截图&代码：
yarn install和pnpm install都试了，没用。16G运存，不知道应该如何解决

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
命令更名有问题，改成这个
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/155bf592-3a87-4aa5-8507-bac96a1c262b)
