### ISSUE TITLE
替换成unocss在dev环境下暗黑模式正常，在prod模式下，打包后暗黑模式失效

### ISSUE THREAD

**Issue by GitACDreamer** [jeecgboot/jeecgboot-vue3#721]
##### 版本号：
3.5.3

##### 问题描述：
同步最新代码，打包前端放置nginx,暗黑模式失效，多个页面如此，echarts图表也失效

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/19402747/b85e02d0-f58c-4e88-95c1-da5c45b19f38)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/19402747/b7d41d2c-d7e9-4201-a54f-06d05be7edfd)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
打包nginx访问测试没问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/2ad7c6ac-875d-4897-a3ee-df85f4e99a8d)

你这边有特殊设置，具体说明

**Comment by GitACDreamer** [comment]
@zhangdaiscott 我这边样式以前做过小改动。。我自己排查下先，但是有个疑问是，dev是OK的，打包后失效了，比较头疼，谢谢
