### ISSUE TITLE
登录web后vscode控制台输出错误“无法读取file://xxxxxxxxxxxxx"

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#722]
##### 版本号：
JeecgBoot: 3.5.3，于2023.8.28日下午14:30左右下载
Nvm: v17.9.1
pnpm: 8.2.0

##### 问题描述：
工作目录：d:\Work\Gitlab\Maxbase\maxbase-vue

下载最新版本，pnpm install正常，无任何错误信息。

用vscode运行项目，在登录到系统或按F5刷新界面后，控制台输出如下错误信息：
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/vue-grid-layout%403.0.0-beta1_%40interactjs%2Bcore%401.10.18_%40interactjs%2Butils%401.10.18/node_modules/vue-grid-layout/dist/webpack%3A/VueGridLayout/node_modules/%40interactjs/core/defaultOptions.js 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\vue-grid-layout@3.0.0-beta1_@interactjs+core@1.10.18_@interactjs+utils@1.10.18\node_modules\vue-grid-layout\dist\webpack:\VueGridLayout\node_modules\@interactjs\core\defaultOptions.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/vue-grid-layout%403.0.0-beta1_%40interactjs%2Bcore%401.10.18_%40interactjs%2Butils%401.10.18/node_modules/vue-grid-layout/dist/webpack%3A/VueGridLayout/node_modules/mitt/dist/mitt.es.js 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\vue-grid-layout@3.0.0-beta1_@interactjs+core@1.10.18_@interactjs+utils@1.10.18\node_modules\vue-grid-layout\dist\webpack:\VueGridLayout\node_modules\mitt\dist\mitt.es.js.map'
storePathTitle /dashboard/analysis
MenuItem.vue:110
[ECharts] DEPRECATED: [radar.indicator]text is deprecated, use name instead.

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/f4636832-8b87-450c-a9db-4c259426e206)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/ac4a1c35-c0e3-4f06-93f9-8289508091d3)
这么配置下试试

**Comment by citynook** [comment]
@zhangdaiscott 下载最新版本，重新安装依赖，进入主页的过程中，控制台依旧会报如下错误：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/c392c333-b61f-4354-8d54-87fd81e85af3)

**Comment by zhangdaiscott** [comment]
不清楚，你的环境问题

**Comment by citynook** [comment]
@zhangdaiscott 刚重新下载了最新的版本，安装并运行后，依旧报同样的错误。
本地环境：
nodejs: v17.9.1
pnpm: 8.2.0
vscode: 1.81.1

npmrc文件：
shamefully-hoist=true
strict-peer-dependencies=false
registry=https://registry.npmmirror.com/

说明：3.5.2版本运行时不会报这类的错误，从3.5.3版本开始才有，应该和依赖变更有关系，和我本地环境无关。
我根据错误尝试定位到目录：'d:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\vue-grid-layout@3.0.0-beta1_@interactjs+core@1.10.18_@interactjs+utils@1.10.18\node_modules\vue-grid-layout\dist\webpack:\VueGridLayout\node_modules\@interactjs\core\defaultOptions.js.map'

但只能定位到'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\vue-grid-layout@3.0.0-beta1_@interactjs+core@1.10.18_@interactjs+utils@1.10.18\node_modules\vue-grid-layout\dist'目录，后面的路径找不到，才报的这个错误。

请问贵方测试时用的哪个版本的Nodejs&pnpm，以及镜像服务器路径？
