### ISSUE TITLE
在线表单列表字段过多时,列头和数据对不齐

### ISSUE THREAD

**Issue by zhangning12138** [jeecgboot/jeecgboot-vue3#723]
##### 问题描述：
在线表单的列表字段过多时,列头和数据对不齐

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/54303531/0d442a45-8020-41eb-94a4-019cb328baaa)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。你可在src/components/Table/src/hooks/useTableScroll.ts文件按照如下图注释掉代码即可。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/34b47939-f4e5-41c7-a6bd-13aa81d6e9e5)

**Comment by parkle-suen** [comment]
这个问题又出现了, v3.7.4版本, 一模一样的问题. 而且我打开代码看过, 已经是如楼上所说的, 已经注释掉+60的代码, 但是问题依旧存在
