### ISSUE TITLE
✘ [ERROR] Could not resolve "Vue"

### ISSUE THREAD

**Issue by kavencat** [jeecgboot/jeecgboot-vue3#725]
##### 版本号：
jeecgboot-vue3@3.5.3

##### 问题描述：
✘ [ERROR] Could not resolve "Vue"

    node_modules/.pnpm/@qiaoqiaoyun+drag-free@1.1.3_@aesoper+normal-utils@0.1.5_@interactjs+core@1.10.18_@interactjs_dlfodwp3kuqlaikzkckspnuuju/node_modules/@qiaoqiaoyun/drag-free/lib/index.umd.min.js:1:1276:
      1 │ ...,require("lodash-es"),require("Vue"),require("@ant-design/icons-...
        ╵                                  ~~~~~

  You can mark the path "Vue" as external to exclude it from the bundle, which
  will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "CodeMirror"

    node_modules/.pnpm/@qiaoqiaoyun+drag-free@1.1.3_@aesoper+normal-utils@0.1.5_@interactjs+core@1.10.18_@interactjs_dlfodwp3kuqlaikzkckspnuuju/node_modules/@qiaoqiaoyun/drag-free/lib/index.umd.min.js:1:1532:
      1 │ ...array.reduce.js"),require("CodeMirror"),require("axios"),require...
        ╵                              ~~~~~~~~~~~~

  You can mark the path "CodeMirror" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/42998638-64ab-41bf-baeb-d98ff1a071bc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/ac4a1c35-c0e3-4f06-93f9-8289508091d3)
这么配置下试试

**Comment by kavencat** [comment]
按图配置报错没有，不过首页打不开

**Comment by zhangdaiscott** [comment]
截图说明

**Comment by kavencat** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/26bc5329-a194-4886-93fb-157e42fb1653)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/2625639f-a4b9-4c0d-8da9-f21e2f54f7cd)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/77e5b257-9ba2-4710-b3cc-10674ff248e4)

**Comment by zhangdaiscott** [comment]
F12 错误

**Comment by kavencat** [comment]
registerGlobComp.ts:63  Uncaught SyntaxError: The requested module '/node_modules/.pnpm/registry.npmmirror.com+@qiaoqiaoyun+drag-free@1.1.3_@aesoper+normal-utils@0.1.5_@interactjs+c_bo5pgsbikblhey22xqzi7ki5xq/node_modules/@qiaoqiaoyun/drag-free/lib/index.umd.min.js?v=84e57086' does not provide an export named 'default' (at registerGlobComp.ts:63:8)

**Comment by kavencat** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/863eae89-f430-48ea-ae53-753e15b565ae)

**Comment by zhangdaiscott** [comment]
你是下载的完整最新代码吗

**Comment by zhangdaiscott** [comment]
把依赖删了，重新install看看

**Comment by kavencat** [comment]
/usr/local/bin/pnpm run reinstall

> jeecgboot-vue3@3.5.3 reinstall /home/linuxlite/www/jeecgboot-vue3
> rimraf pnpm-lock.yaml && rimraf yarn.lock && rimraf package.lock.json && rimraf node_modules && pnpm i

Progress: resolved 137, reused 137, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 WARN  deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
 WARN  deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
 WARN  deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
 WARN  deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
 WARN  deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
 WARN  deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
 WARN  deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
Packages: +1813
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1853, reused 1811, downloaded 0, added 1813, done

dependencies:
+ @ant-design/colors 7.0.0
+ @ant-design/icons-vue 6.1.0
+ @iconify/iconify 3.1.1
+ @jeecg/online 3.5.3-vite4
+ @logicflow/core 1.2.12
+ @logicflow/extension 1.2.13
+ @qiaoqiaoyun/drag-free 1.1.3
+ @vue/runtime-core 3.3.4
+ @vue/shared 3.3.4
+ @vueuse/core 10.4.1
+ @vueuse/shared 10.4.1
+ @zxcvbn-ts/core 3.0.3
+ ant-design-vue 3.2.20 (4.0.1 is available)
+ axios 1.5.0
+ china-area-data 5.0.1
+ clipboard 2.0.11
+ codemirror 5.65.14 (6.0.1 is available)
+ cron-parser 4.9.0
+ cropperjs 1.6.0
+ crypto-js 4.1.1
+ dayjs 1.11.9
+ dom-align 1.12.4
+ echarts 5.4.3
+ emoji-mart-vue-fast 15.0.0
+ enquire.js 2.1.6
+ intro.js 7.2.0
+ lodash-es 4.17.21
+ lodash.get 4.4.2
+ md5 2.3.0
+ mockjs 1.1.0
+ nprogress 0.2.0
+ path-to-regexp 6.2.1
+ pinia 2.1.4 (2.1.6 is available)
+ print-js 1.6.0
+ qrcode 1.5.3
+ qrcodejs2 0.0.2
+ qs 6.11.2
+ resize-observer-polyfill 1.5.1
+ showdown 2.1.0
+ sortablejs 1.15.0
+ tinymce 5.10.7 (6.6.2 is available)
+ vditor 3.9.4
+ vue 3.3.4
+ vue-cropper 0.6.2
+ vue-cropperjs 5.0.0
+ vue-i18n 9.2.2
+ vue-infinite-scroll 2.0.2
+ vue-json-pretty 2.2.4
+ vue-print-nb-jeecg 1.0.12
+ vue-router 4.2.4
+ vue-types 5.1.1
+ vuedraggable 4.1.0
+ vxe-table 4.1.0 (4.5.6 is available)
+ vxe-table-plugin-antd 3.0.5 (3.0.7 is available)
+ xe-utils 3.5.12
+ xss 1.0.14

devDependencies:
+ @commitlint/cli 17.7.1
+ @commitlint/config-conventional 17.7.0
+ @iconify/json 2.2.107
+ @purge-icons/generated 0.9.0
+ @rys-fe/vite-plugin-theme 0.8.6
+ @types/codemirror 5.60.9
+ @types/crypto-js 4.1.1
+ @types/fs-extra 11.0.1
+ @types/inquirer 9.0.3
+ @types/intro.js 5.1.1
+ @types/jest 29.5.4
+ @types/lodash-es 4.17.8
+ @types/mockjs 1.0.7
+ @types/node 20.5.7
+ @types/nprogress 0.2.0
+ @types/pinyin 2.10.0
+ @types/qrcode 1.5.1
+ @types/qs 6.9.7
+ @types/showdown 2.0.1
+ @types/sortablejs 1.15.1
+ @typescript-eslint/eslint-plugin 6.4.1
+ @typescript-eslint/parser 6.4.1
+ @vitejs/plugin-legacy 4.1.1
+ @vitejs/plugin-vue 4.3.3
+ @vitejs/plugin-vue-jsx 3.0.2
+ @vue/compiler-sfc 3.3.4
+ @vue/test-utils 2.4.1
+ autoprefixer 10.4.15
+ commitizen 4.3.0
+ conventional-changelog-cli 3.0.0 (4.0.0 is available)
+ cross-env 7.0.3
+ cz-git 1.7.1
+ czg 1.7.1
+ dotenv 16.3.1
+ eslint 8.48.0
+ eslint-config-prettier 8.10.0 (9.0.0 is available)
+ eslint-define-config 1.23.0
+ eslint-plugin-jest 27.2.3
+ eslint-plugin-prettier 5.0.0
+ eslint-plugin-vue 9.17.0
+ esno 0.17.0
+ fs-extra 11.1.1
+ http-server 14.1.1
+ husky 8.0.3
+ inquirer 9.2.10
+ is-ci 3.0.1
+ jest 29.6.4
+ less 4.2.0
+ lint-staged 13.2.3 (14.0.1 is available)
+ npm-run-all 4.1.5
+ picocolors 1.0.0
+ postcss 8.4.28
+ postcss-html 1.5.0
+ postcss-less 6.0.0
+ prettier 3.0.2
+ pretty-quick 3.1.3
+ rimraf 5.0.1
+ rollup 3.28.1
+ rollup-plugin-visualizer 5.9.2
+ stylelint 15.10.3
+ stylelint-config-prettier 9.0.5
+ stylelint-config-recommended 13.0.0
+ stylelint-config-recommended-vue 1.5.0
+ stylelint-config-standard 34.0.0
+ stylelint-order 6.0.3
+ ts-jest 29.1.1
+ ts-node 10.9.1
+ typescript 5.2.2
+ unocss 0.55.3
+ vite 4.4.9
+ vite-plugin-compression 0.5.1
+ vite-plugin-html 3.2.0
+ vite-plugin-imagemin 0.6.1
+ vite-plugin-mkcert 1.16.0
+ vite-plugin-mock 2.9.8 (3.0.0 is available)
+ vite-plugin-purge-icons 0.9.2
+ vite-plugin-pwa 0.16.4
+ vite-plugin-style-import 2.0.0
+ vite-plugin-svg-icons 2.0.1
+ vite-plugin-vue-setup-extend-plus 0.1.0
+ vue-eslint-parser 9.3.1
+ vue-tsc 1.8.8

 WARN  Issues with peer dependencies found
.
├─┬ stylelint-config-prettier 9.0.5
│ └── ✕ unmet peer stylelint@">= 11.x < 15": found 15.10.3
└─┬ @qiaoqiaoyun/drag-free 1.1.3
  └─┬ vue3-colorpicker 2.2.2
    └── ✕ unmet peer @vueuse/core@^10.1.2: found 6.9.2 in @qiaoqiaoyun/drag-free

Done in 5m 16.6s

进程已结束，退出代码为 0

**Comment by kavencat** [comment]
同样的错误

**Comment by kavencat** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/57c62752-a79f-47b5-b16c-785c67decab6)

**Comment by zhangdaiscott** [comment]
不太清楚，你可以先把仪表盘删了

**Comment by kavencat** [comment]
删了后整个无法运行

**Comment by zhangdaiscott** [comment]
注释掉仪表盘，需要修改三个地方
修改src/components/registerGlobComp.ts

1、引入
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/b61d4014-3bdc-43f8-8e89-5f62b08db891)
2、富文本注册注释
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/9ae1f846-fbf4-4d93-85ad-8748b5cf1bb4)

3、仪表盘注册注释
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/6f004499-8eb0-4027-86b0-c0ef376212c3)

**Comment by kavencat** [comment]
注释掉后
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/1b9723bb-3ec2-42af-8910-68f8320178ae)

**Comment by zhangdaiscott** [comment]
你还改了别的代码？这是online的

**Comment by kavencat** [comment]
好像是第一个位置多注了一行

**Comment by kavencat** [comment]
这个问题有找到原因没

**Comment by zhangdaiscott** [comment]
我们本地没有问题，群里其他人也没有反馈类似问题的

**Comment by zhangdaiscott** [comment]
你通过这个地址下载代码试试，看看是不是下载代码有问题
https://gitee.com/jeecg/jeecgboot-vue3

**Comment by kavencat** [comment]
是@qiaoqiaoyun/drag-free引起的

**Comment by kavencat** [comment]
我认为有可能是大小写造成

**Comment by kavencat** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/5834e8be-4056-438d-bfb1-620f86b0387e)

是由到小写造成；

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/35b89435-b004-4b43-95f2-74a5e49eb208)

这个问题就不是很清楚了

**Comment by zhangdaiscott** [comment]
升级到这个版本试试
```
  "@qiaoqiaoyun/drag-free": "^1.1.4",
```
