### ISSUE TITLE
JPopup组件里的表格全选没有选中数据

### ISSUE THREAD

**Issue by alteryan** [jeecgboot/jeecgboot-vue3#726]
##### 问题描述：
勾选表格的全选按钮，点击确认时，没有数据被选中，提示至少选中一条记录

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/87793606/a2f14e52-0c4e-4872-a6aa-c03636a64cfb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by alteryan** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/87793606/ed234e4f-356c-4166-8dbf-82a4445842a8)
点击全选时的报错

**Comment by liaozhiyang** [comment]
已修复，下一版本更新。
