### ISSUE TITLE
jeecgboot-vue3@3.5.3 build 出错

### ISSUE THREAD

**Issue by kavencat** [jeecgboot/jeecgboot-vue3#728]
##### 版本号：
jeecgboot-vue3@3.5.3

##### 问题描述：
jeecgboot-vue3@3.5.3 build 出错

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/99724336/9d3aa3a3-56c9-4dc0-a10c-a067bef53e43)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码是下载的最新版还是自己合并的？

**Comment by kavencat** [comment]
最新版无合并

**Comment by zhangdaiscott** [comment]
手工改下这块代码试试，我们没问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/f860723c-b76b-4fec-ab24-0e15fffc0307)

**Comment by kavencat** [comment]
是Form文件夹名在各文件的有大写有小写造成

**Comment by zhangdaiscott** [comment]
猜是这样的，具体是那个

**Comment by kavencat** [comment]
好多的

**Comment by zhangdaiscott** [comment]
最新代码吗？我们的代码在linux下编译是没问题的

**Comment by zflzqy** [comment]
同问，发现好几个文件了，本来应该是/src/components/Form路径，代码里写的/src/components/form,Linux下区分大小写导致无法打包

**Comment by zhangdaiscott** [comment]
一会提交修复
