### ISSUE TITLE
MarkDown组件的结果显示问题

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#729]
##### 版本号：
jeecdboot-vue3   3.5.3

##### 问题描述：
1、Online表单使用了MarkDown组件，在该字段设置为“只读”后，”编辑“form中能不能直接显示结果，而不要显示已不可修改的MarkDown源码？（目前需要抓门点击“预览”才会达到索要的效果，能否有啥扩展参数设置，直接决定是显示“源码”或“源码+预览”或“预览”？）
2、“详情”的form显示的不是最终结果，而是MarkDown源码，这个应该不合理。

##### 截图&代码：
1、“编辑”form中的“只读”MarkDown组件域：
![1693275567374](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/cd72ea0e-f57c-4f66-9470-b3aa15b45c46)
只读Markdown组件域，最好能直接显示“预览”的结果状态（图中的“请求示例”那样，目前是点击“预览”后才这样的），只读域，最好mwrkDown的编辑框以及一些功能图标也不必显示。

2、“详情”中的Markdown组件域：
![1693275764007](https://github.com/jeecgboot/jeecgboot-vue3/assets/36326638/0a61d84a-80a2-4d04-bff7-2d7cfb31bcae)
详情理论上是查看某个对象的详细信息的，利用MarkDown进行编辑的信息，应该要显示最终结果的样子才对，显示mwrkdown源码会引起困惑。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个得我们二开实现

**Comment by gxzhou** [comment]
> 这个得我们二开实现

是需要生成代码后再实现吗？

**Comment by zhangdaiscott** [comment]
zy
