### ISSUE TITLE
生成主附表代码问题

### ISSUE THREAD

**Issue by AntsMa** [jeecgboot/jeecgboot-vue3#730]
##### 版本号：

jeecdboot-vue3 3.5.3

##### 问题描述：
菜单：底代码开发-Online表单开发
问题：代码生成附表时需要选择主表，但是选择主表时提示只能选择一条

##### 截图&代码：
function ie() {
    if (i.value.length === 0)
      l.warning("请先选中一条记录");
    else if (i.value.length > 1)
      l.warning("代码生成只能选中一条记录");
    else {
      let e = i.value[0];
      e ? e.isDbSynch != "Y" ? l.warning("请先同步数据库！") : e.tableType == 3 ? l.warning("请选中该表对应的主表") : O.openModal(!0, { code: e.id }) : l.warning("请选中当前页的数据！");
    }
  }

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34825320/411c2724-7146-4377-9493-49994f0f8a59)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34825320/39de4708-2a61-4938-807a-baa490dea4ec)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangning12138** [comment]
提示说的是 请选中该表对应的主表
只选主表就好了 附表也会跟着一起生成出来
