### ISSUE TITLE
docker镜像问题，打包部署之后无法访问

### ISSUE THREAD

**Issue by zflzqy** [jeecgboot/jeecgboot-vue3#731]
##### 问题描述：
docker镜像问题，打包部署之后无法访问

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38182329/8dfe5a5a-89c6-4136-ae1d-a1066b070943)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
是不是打包失败了，看打包日志

**Comment by zflzqy** [comment]
[log.txt](https://github.com/jeecgboot/jeecgboot-vue3/files/12470720/log.txt)
j'eJenkins的打包日志

**Comment by zhangdaiscott** [comment]
没报错

**Comment by zflzqy** [comment]
是的，但是docker启动之后访问就出现这个

**Comment by zflzqy** [comment]
我尝试直接挂nginx下也会有这个问题，但是用win打包的东西没问题，linux打包的有问题，不知道为啥

**Comment by zhangdaiscott** [comment]
代码更新到最新了吗

**Comment by zflzqy** [comment]
是最新版的

**Comment by zflzqy** [comment]
"@qiaoqiaoyun/drag-free": "^1.0.52",
回退到这个版本正常了，先这样用着把

**Comment by zhangdaiscott** [comment]
升级到这个版本试试
```
  "@qiaoqiaoyun/drag-free": "^1.1.4",
```
