### ISSUE TITLE
vue3页签可以只保留一个吗，点击菜单的时候不打开新页签

### ISSUE THREAD

**Issue by yy0514** [jeecgboot/jeecgboot-vue3#733]
##### 问题描述：
vue3页签可以只保留一个吗，点击菜单的时候不打开新页签

##### 截图&代码：
![1693364446833](https://github.com/jeecgboot/jeecgboot-vue3/assets/100107431/f260b756-8db8-434d-acf7-4e58ae1c3f12)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/d2c6a390-00e3-4e30-bc6d-7c7119aeb5c1)
