### ISSUE TITLE
依赖升级后兼容旧浏览器打包失败

### ISSUE THREAD

**Issue by wildyyyyyy** [jeecgboot/jeecgboot-vue3#734]
##### 版本号：
3.5.3

##### 问题描述：
依赖升级后兼容旧浏览器打包失败

##### 截图&代码：

<img width="2007" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/103614225/3e3e851c-239b-4840-b565-9c051b8fa5f0">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
此插件是准备删掉的，你是什么需求场景
