### ISSUE TITLE
升级3.5.3后 打包成功，但浏览器运行报错

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#735]
##### 版本号：
3.5.3

##### 问题描述：
升级3.5.3后 打包成功，但浏览器运行报错

##### 截图&代码：
![5121d29d4ed7f074f7ae512ab3638a6](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/67010a50-a883-47cf-9d5b-71d108df5c75)

![8e59956a8c9f2d4a0dd10ea2db4b0a2](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/92582788-ddca-4a66-a0ae-e0d1475a7424)

**Comment by zhangdaiscott** [comment]
这个错误不清楚

**Comment by IIIIIIIIF** [comment]
请问怎么解决的
