### ISSUE TITLE
Popup弹框bug

### ISSUE THREAD

**Issue by 78739749haiyang** [jeecgboot/jeecgboot-vue3#736]
##### 截图&代码：
![KG~IUC9YD8CUSS}$W(24GKW](https://github.com/jeecgboot/jeecgboot-vue3/assets/98626116/a55cca12-a6d8-4a09-acb4-2b7f0feec551)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码更新
