### ISSUE TITLE
JVxeTable  手动设置选中列表的某一项，没有效果bug

### ISSUE THREAD

**Issue by lliaoliao** [jeecgboot/jeecgboot-vue3#737]
##### 版本号：
3.4.3-GA

##### 问题描述：
JVxeTable 手动设置选中列表的某一项，没有效果bug

##### 截图&代码：
![1693473045499](https://github.com/jeecgboot/jeecgboot-vue3/assets/7638063/972557db-ac6d-414f-aa27-9676701be42b)
![1693473076386](https://github.com/jeecgboot/jeecgboot-vue3/assets/7638063/1dd28a4b-fbfb-4158-b5f6-1220b4296e07)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy
