### ISSUE TITLE
升级后报红，并且代码提示没有了

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecgboot-vue3#738]
##### 版本号：
3.5.4

##### 问题描述：
升级之后，tableRef.value?.removeRows 等方法报红，并且没有了语法提示
示例页面  JVxeDemo1.vue
##### 截图&代码：
升级前 正常
![61fb4478ec46891a86e94572b85ce3e](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/01d59601-769e-4988-8e17-3204c4aefd83)
升级后 有问题
![c08f911d6caf2a7e826d5ec4c67e879](https://github.com/jeecgboot/jeecgboot-vue3/assets/3311840/604143b0-e60b-4e45-bc26-9c08a09dc288)

**Comment by zhangdaiscott** [comment]
降低版本，install
```
    "typescript": "^4.9.5",
```
