### ISSUE TITLE
vue3版角色权限配置，无法全选菜单

### ISSUE THREAD

**Issue by BadSmile01** [jeecgboot/jeecgboot-vue3#74]
##### 版本号：
jeecg boot vue3 1.1.0-beta

##### 问题描述：
角色权限配置，无法全选菜单

##### 截图&代码：
![333332](https://user-images.githubusercontent.com/12042770/168608305-79d16e01-9b47-4fbd-a9af-d5246dd3a0aa.png)

**Comment by zhangdaiscott** [comment]
右上角

**Comment by BadSmile01** [comment]
不是呀，右上角是全选所有菜单和子菜单的，我说的是比如有一个一级菜单，我勾选他，应该他的下级会自动全部勾选，目前是没有效果的，比如 “系统监控”，我勾选，他的下级会自动全部勾选，我取消他的勾选，他的下级也会自动取消勾选，并不是全局勾选和取消不可以用

**Comment by selicens** [comment]
不是哦，他有一个层级独立和层级关联，层级独立是父级、子级都要选，层级关联是选择父级，子级就会全选，默认的是层级独立，修改是将组件的checkStrictly参数true改为false即可
