### ISSUE TITLE
列设置隐藏列，拖动排序隐藏列自动显示的问题

### ISSUE THREAD

**Issue by zhangwenqi997** [jeecgboot/jeecgboot-vue3#740]
##### 截图&代码：
![1693794514362](https://github.com/jeecgboot/jeecgboot-vue3/assets/54975511/69cf7cfc-8825-4dcb-9c62-b7496d7d4f2d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
