### ISSUE TITLE
Online配置系统编码填值规则后，代码生成时无法使用编码填值规则

### ISSUE THREAD

**Issue by modakai** [jeecgboot/jeecgboot-vue3#741]
##### 版本号：
后端 3.5.3
前端 Vue2 的版本
##### 问题描述：
在Online 在线表单中配置了系统编码规则，但是当代码生成后，却用不了，在Online中却可以使用。在查看官方文档后是好像是要自己去对应的Vue组件中调用，但是我不知道在哪调用他，去修改 model 里面的值。希望可以指条明路

##### 截图&代码：
Online在线表单中的样子： 发放单号是可以自动生成的
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/124060255/a944e7c6-18dd-44ad-a0be-32082bb67ffe)
代码生成后的样子：代码生成后发放单好无法自动生成
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/124060255/4f92c393-eadc-44a2-beb7-543fe00b6a39)
不知道在哪个文件的哪个方法里面上加官方文档给出的案例
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/124060255/58a44ba3-bf49-4b40-ae65-0576c63aadaf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持生成，需要手工补充逻辑
