### ISSUE TITLE
online表单开发的编辑对话框中，“树开表单列”是什么意思？

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#743]
##### 版本号：
3.5.3

##### 问题描述：
online表单开发的编辑对话框中，“树开表单列”是什么意思？是不是标题写错了？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/11ec8514-cfab-4217-8230-87e5c6c7fc2b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
就是给那个字段加展开按钮 “+”
