### ISSUE TITLE
表单组件label的helpMessage图标显示错位

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/jeecgboot-vue3#744]
##### 版本号：
3.5.4

##### 问题描述：
表单组件label的helpMessage图标显示错位没有居中，在“自定义组件示例”模块可以重现访问题

##### 截图&代码：
<img width="1427" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/d094ff83-b760-43ce-a480-d3d24f2f22c1">

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。需把src/design/ant/index.less文件中的span.anticon:not样式注释掉。
