### ISSUE TITLE
jeecg-vue3标签图标

### ISSUE THREAD

**Issue by JL1421** [jeecgboot/jeecgboot-vue3#745]
##### 版本号：
JeecgBoot 3.5.0

##### 问题描述：
 #如何去掉标签(地址栏)上的图标？

##### 截图&代码：
![1693897015656](https://github.com/jeecgboot/jeecgboot-vue3/assets/48303925/d8991111-dcd4-4569-9a4c-fbb952b5fe08)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
F12定位
