### ISSUE TITLE
前端项目安装之后启动报错

### ISSUE THREAD

**Issue by 354752672** [jeecgboot/jeecgboot-vue3#747]
##### 版本号：
3.5.4

##### 问题描述：
前端项目npm install之后启动项目报错

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/56473652/c46ae2f0-5647-4e8e-925e-0aff00a8d1a4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 7hxx** [comment]
我也突然报这个错误

**Comment by 354752672** [comment]
> 我也突然报这个错误

你解决了吗

**Comment by cdsuifeng** [comment]
"vue-i18n": "^9.2.2", 应该和这个包有关，去掉 ^ 就可以了

**Comment by 354752672** [comment]
> "vue-i18n": "^9.2.2", 应该和这个包有关，去掉 ^ 就可以了
好了，感谢！
