### ISSUE TITLE
JEditor 组件使用时控制台出现多条告警

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/jeecgboot-vue3#751]
##### 版本号：
3.5.4

##### 问题描述：
1、使用JEditor组件浏览器控制台出现5条告警，具体告警信息见图
2、当配置:showImageUpload="false"时，:disabled="true"配置失效；

##### 截图&代码：
1、告警
<j-editor v-model:value="mainData.remarks"  height="300" />
<img width="423" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/b6bc56c9-f9ca-4672-9f84-0e2c5f21a79f">

2、配置:showImageUpload="false"时，disabled配置失败
<j-editor v-model:value="mainData.remarks" :showImageUpload="false"时，:disabled="true"  height="300" />

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试未复现你说的情况，请尝试更新版本或者将你的配置和问题多截图复述一下
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65587928/1b601d85-8fc9-4cc1-8613-3beb7fa0f3bf)

**Comment by harveyLXH** [comment]
JEditor菜单有错位的问题

**Comment by harveyLXH** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/28383928/e208a7d4-634c-4c40-9a5a-f9a3b56725a8)

**Comment by hhxyjsj** [comment]
> 测试未复现你说的情况，请尝试更新版本或者将你的配置和问题多截图复述一下 ![image](https://user-images.githubusercontent.com/65587928/268583383-1b601d85-8fc9-4cc1-8613-3beb7fa0f3bf.png)

我这边现在更新3.5.5也一样，另外这个问题在你们的试用环境（http://boot3.jeecg.com）也能复现，如下图：

![WX20230926-135344@2x](https://github.com/jeecgboot/jeecgboot-vue3/assets/31506377/9ed89dfe-6b1d-47a7-9e77-9fc3bdf09f20)

**Comment by harveyLXH** [comment]
http://boot3.jeecg.com/comp/jeecg/basic (示例链接-富文本框位置菜单错误)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/28383928/bd29f0e5-7135-4c74-850a-463e6076ebcf)
