### ISSUE TITLE
下载源码直接pnpm install完再 pnmp serve打开页面失败，IDE报 Failed to resolve entry for package "@intlify/shared". 

### ISSUE THREAD

**Issue by rocye** [jeecgboot/jeecgboot-vue3#753]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/7664911/8bb8a52d-ac2f-4e64-b62c-b67283610e4d)

**Comment by zhangdaiscott** [comment]
最新版是3.5.4

**Comment by rocye** [comment]
好的谢谢，我尝试直接在github上拉master分支，第一步install 第二步 pnpm dev 这次成功进入登录页了
