### ISSUE TITLE
JPopup表格的选择列固定配置不生效

### ISSUE THREAD

**Issue by alteryan** [jeecgboot/jeecgboot-vue3#757]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/87793606/19564e44-edb6-45e7-ba21-5611d808e404)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你可先按照如下更改。
src/components/Table/src/hooks/useCustomSelection.tsx
<img width="889" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/ef4671c3-8481-42dc-901c-59af82fc62a8">
