### ISSUE TITLE
期望jvxetable有查询条件插槽，类似vben table

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#76]
##### 版本号：
v1.0.0-beta

##### 问题描述：
期望jvxetable有查询条件插槽，类似vben table。
jvxetable的样式没有vbentable的好看，但编辑事件触发保存还是相当好的。

##### 截图&代码：
jvxetable
![image](https://user-images.githubusercontent.com/1910132/169006730-184679ca-6b98-42a6-8757-a0ba0e221f4e.png)
vben table
![image](https://user-images.githubusercontent.com/1910132/169006867-29e564ca-0f48-48fc-8016-670a1c2460e8.png)

**Comment by zhangdaiscott** [comment]
好
