### ISSUE TITLE
前台页面怎么配置菜单，打开浏览器新标签页面跳转？

### ISSUE THREAD

**Issue by 01-jiang** [jeecgboot/jeecgboot-vue3#760]
##### 版本号：

3.5.2
##### 问题描述：
菜单怎么配置跳转打开浏览器新标签页面？不是后台路径页面，是前台已经写好的页面，正常配置内部打开没问题。设置外部打开后，打开新标签页面后有重定向到了首页

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
个性化的需求，自己搞吧
