### ISSUE TITLE
JPopup组件【全选】确认，显示“只能选择一条记录”，官方演示画面可再现

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/jeecgboot-vue3#761]
##### 版本号：
3.5.4

##### 问题描述：
JPopup组件【全选】确认，显示“只能选择一条记录”，官方演示画面可再现

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/10290156/d24decdd-838c-4a1e-a128-05126426e507)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码更新到最新，应该改过了

**Comment by zhangdaiscott** [comment]
演示地址好像没更新了，使用github最新代码即可

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
1.JPopup组件【全选】，显示“只能选择一条记录”。这是正常的，默认是只能选择一条。
2."另外以下这行代码在有翻页的情况，前页的选择丢失"，这个地方已修复，下一版本发布。

**Comment by antbuster** [comment]
> 1.JPopup组件【全选】，显示“只能选择一条记录”。这是正常的，默认是只能选择一条。
JPopup组件支持多选的呀，“【全选】，显示“只能选择一条记录”。这是正常的”是什么逻辑？而且手工多选是可以的，【全选】就有错
