### ISSUE TITLE
谷歌浏览器一直卡在加载页面，且谷歌控制台css引用报错

### ISSUE THREAD

**Issue by MrQiaoLei** [jeecgboot/jeecgboot-vue3#762]
##### 版本号：
jeecgboot-vue3 版本：3.5.4     谷歌版本：版本 86.0.4240.198（正式版本） （32 位）

##### 问题描述：
谷歌浏览器一直卡在加载页面，且谷歌控制台报错。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/17661940/315a6e9f-4b80-4f48-906d-7e0406209bb1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
谷歌版本太老不支持
