### ISSUE TITLE
Popup报表弹窗全选问题

### ISSUE THREAD

**Issue by 2846781956** [jeecgboot/jeecgboot-vue3#765]
##### 版本号：
3.5.4版本

##### 问题描述：
首次点击进入报表弹窗，全选之后点击确认会显示至少选择一条记录。
![1695094663139](https://github.com/jeecgboot/jeecgboot-vue3/assets/95627491/e2ad88b0-d173-405e-84ba-a8fff5384552)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
是不是只允许选择一条

**Comment by 2846781956** [comment]
![1695103221638](https://github.com/jeecgboot/jeecgboot-vue3/assets/95627491/a3dc38cb-8f10-4514-bbdf-6c82cd81dca0)
设置是可以多选的

**Comment by antbuster** [comment]
#761 
回答也是很莫名的
>1.JPopup组件【全选】，显示“只能选择一条记录”。这是正常的，默认是只能选择一条。

明明手动多选没错，【全选】就有错

**Comment by 2846781956** [comment]
![1695182236775](https://github.com/jeecgboot/jeecgboot-vue3/assets/95627491/a4a520fb-3df6-41f2-9a9d-cd8c4f488ea8)
似乎换一下值就可以了，不知道会不会有其它问题。

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/commit/da55e94a66d58f306852256d90de10c382ac13af
