### ISSUE TITLE
显示登录成功，但是又返回token失效，请重新登录

### ISSUE THREAD

**Issue by ZeLinkJie** [jeecgboot/jeecgboot-vue3#766]
##### 问题描述：
登录后间隔几个小时后重新登录，显示登录成功，但是有返回token失效，请重新登录，需要删除redis数据才行，希望能在代码层面解决这个问题

##### 截图&代码：

![微信图片_20230919132706](https://github.com/jeecgboot/jeecgboot-vue3/assets/108724499/9945f151-489f-452f-85e0-b27223d7bcb4)

![微信图片_20230919090915](https://github.com/jeecgboot/jeecgboot-vue3/assets/108724499/bb0d4e27-1e0a-4ce0-aff4-95f1bd9c9eb3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
如何重现？

**Comment by ZeLinkJie** [comment]
这是偶尔发生的 不知道怎么重现
