### ISSUE TITLE
js 自定义按钮表达式 怎么支持多个字段判断？

### ISSUE THREAD

**Issue by Kevin-269581661** [jeecgboot/jeecgboot-vue3#769]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/44706087/28a3679e-9433-4f74-b7d0-492402626a97)

使用了 && 或者 || 无效，查阅文档没有找到相关描述

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
已新增，下一版本发布
