### ISSUE TITLE
期望jvxetable有类似vben table的help message的配置功能

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#77]
##### 版本号：
v1.0.0-beta

##### 问题描述：
期望jvxetable有类似vben table的help message的配置功能

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/169013729-99a1b903-d2f6-446e-9486-765c1fc56e46.png)

**Comment by zhangdaiscott** [comment]
请写一个总的
