### ISSUE TITLE
存在一个导致全部页面都异常报错的问题

### ISSUE THREAD

**Issue by Niconiconi233** [jeecgboot/jeecgboot-vue3#770]
##### 版本号：
3.5.5
##### 问题描述：
在进入性能监控->磁盘监控后如果在点击不管是服务器信息还是JVM信息、Tomcat信息都会导致全部页面报错，只能整个网页刷新才能恢复正常
##### 截图&代码：
<img width="1522" alt="屏幕截图 2023-09-21 004407" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39131279/512ea887-9881-4326-b7f5-a57d4fc34a5a">
首次进入磁盘监控页面是正常显示的
例如点击Tomcat信息后控制台就报错了
<img width="1665" alt="屏幕截图 2023-09-21 004450" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39131279/9517fc54-c748-45e6-adc4-b99b3e554acf">
<img width="686" alt="屏幕截图 2023-09-21 004604" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39131279/8a2b32d3-4c84-409b-a85f-58ca918dda28">

此时再点击其他页面也会同样报错
<img width="1866" alt="屏幕截图 2023-09-21 004708" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39131279/96cc4229-a550-4ed0-ba66-9dcaa916c50b">
重新克隆了前端代码也是一样的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by zhangdaiscott** [comment]
更新代码把
