### ISSUE TITLE
JSearchSelect 自定义数据时搜索失效

### ISSUE THREAD

**Issue by Feng-Xg** [jeecgboot/jeecgboot-vue3#771]
##### 版本号：
VUE3

##### 问题描述：
使用JSearchSelect组件，数据来源于固定内容。输入搜索时，输入text不能搜索到，输入value可以搜索到选项内容。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
经测试JSearchSelect组件可输入text能搜索到，无法重现，可否提供更详细的信息？
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/45aae71b-94ab-42be-874a-9db09312b3e2)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/c8ac3905-c6c6-40fe-93e3-1f350b683213)
你可查看组件&功能-->Jeecg组件示例-->自定义组件示例页面中的字典搜索（同步） 看是否正常？

**Comment by Feng-Xg** [comment]
@liaozhiyang 
使用字典作为数据时搜索text没有问题，我是没有定义dict，使用自定义接口的text和value数据，这个时候搜索输入text查询不到，输入value内容才可以。

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/19472852/62fc0059-27a3-4110-aadd-6a0888a9c9f4)

**Comment by zhangdaiscott** [comment]
那就是你自己的接口没实现模糊查询功能，需要你自己实现
