### ISSUE TITLE
主附表生成代码后，子表创建了数据无法加载

### ISSUE THREAD

**Issue by xiaobai-hz** [jeecgboot/jeecgboot-vue3#773]
##### 版本号：
3.5.5

##### 问题描述：
代码生成后，在弹窗中创建子表的数据，下次再打开就没有数据了

##### 截图&代码：
原来的生成代码
      async function edit(row) {
        //主表数据
        await queryMainData(row.id);
        //子表数据
        const wmsWarehousesClassifyDataList = await queryWmsWarehousesClassifyListByMainId(row['id']);
        wmsWarehousesClassifyTable.dataSource = [...wmsWarehousesClassifyDataList.records];
        const wmsMapDotDataList = await queryWmsMapDotListByMainId(row['id']);
        wmsMapDotTable.dataSource = [...wmsMapDotDataList];
      }
![8J{FHS)K$}O~LI0 SSE{$IU](https://github.com/jeecgboot/jeecgboot-vue3/assets/133614282/2a3c1787-66e3-4d55-861a-91cc44439bab)
更改后的代码
      async function edit(row) {
        //主表数据
        await queryMainData(row.id);
        //子表数据
        const wmsWarehousesClassifyDataList = await queryWmsWarehousesClassifyListByMainId(row['id']);
        wmsWarehousesClassifyTable.dataSource = [...wmsWarehousesClassifyDataList.records];
        const wmsMapDotDataList = await queryWmsMapDotListByMainId(row['id']);
        wmsMapDotTable.dataSource = [...wmsMapDotDataList.records];
      }
![GRCJATFXY@8W(TJQRA BB{B](https://github.com/jeecgboot/jeecgboot-vue3/assets/133614282/4f68ff6e-3e81-4bbe-889b-9554c3a563bc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试未复现你说的问题，方便请提供一下你生成的代码文件
