### ISSUE TITLE
一般的列表增加了resizable: true,  那么浏览器console就会出现大量的 "width". 这种未定义错误

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/jeecgboot-vue3#774]
##### 版本号：
3.5.5

##### 问题描述：
只要在列表一般的列表增加了resizable: true,  那么浏览器console就会出现大量的 "width". 这种未定义错误，
代码里面有几个resizeble 就出现几条这种警告，应该是个小问题， 就是width前缀增加: 即可。

##### 截图&代码：
export const columns: BasicColumn[] = [
   {
    title: '客户名称',
    align:"center",
    sorter: true,
    dataIndex: 'name',
     resizable: true,
   },
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/82691864/5616a75c-1659-49a3-b19a-a79fa6fdd80f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
设置了resizable: true属性，就必须设置width属性。具体可查看antd-design-vue文档。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/a019ec12-264d-4958-a6bf-e522c908e39e)
