### ISSUE TITLE
 BasicTable组件rowSelection 点击全选 会选择被禁用的选项

### ISSUE THREAD

**Issue by yutaiwei** [jeecgboot/jeecgboot-vue3#775]
##### 版本号：
3.5.2

##### 问题描述：
 BasicTable组件rowSelection 点击全选 会选择被禁用的选项

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23471495/d0cd3acb-6f8c-4b55-9272-bb6f46d61145)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码先更新到最新
