### ISSUE TITLE
设置canResize，引起合计栏滚动条及列错位，显示100条/页，复选框只能显示3个的问题

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecgboot-vue3#776]
##### 问题描述：

7月的时候已经提过相同的问题，当时有邮件发来说问题已经解决了，今天代码更新到最新了，好像这几个问题都没解决。

1、当canResize设置为true时，合计栏出现滚动条，当通过列设置隐藏后，合计列对应的列不会自动隐藏引起上下错位

2、当canResize设置为false时，且100条/页，前面的复选框只能显示3个，后面的不会显示，当canResize设置为true时，100个复选框又可以显示出来。

##### 截图&代码：

![微信图片_20230924153448](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/ddd57abf-51a5-42b6-a41f-24a6d05eddb7)

![微信图片_20230924153536](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/8ff2d7da-d12a-4169-b1ea-f417eb0f6b68)

![微信图片_20230924153920](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/dea0528d-ae80-4301-a900-1b39151a9750)

**Comment by zhangdaiscott** [comment]
zy

**Comment by jhaso1988** [comment]
<img width="976" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/45a2358a-a373-40a8-a381-4489a69fde0a">
复选框数据建议多一些，就直接出来了

**Comment by jhaso1988** [comment]
<img width="986" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/588b7055-b070-4381-90c4-1c4c9d277f32">
我测试100条

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
1.canResize设置true，复选框只显示3个。可按如下图修改
src/components/Table/src/hooks/useCustomSelection.tsx
<img width="911" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/7c553b62-0a0e-474e-9a7d-3da6a6248e78">
2.两个滚动条（官方认为可接受），可通过样式去掉。
src/components/Table/src/components/TableFooter.vue
<img width="977" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/6e88f265-c2a0-4dfd-9356-7d8e856051e7">
3.设置隐藏列之后合计列不跟着隐藏。这边看是正常的。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/011d81a0-be55-49a5-86e4-f2bc8d9df7d7)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/051a4ef8-bf66-40a2-b647-1df38ff7a850)

**Comment by lijinlang** [comment]
我试了不行，列隐藏显示后合计与上面列对不齐

https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/ac5b827f-03fe-4244-956a-5eaa3b6063d9

**Comment by lijinlang** [comment]
多加几列试试，我的还是不行，第一列是固定列
![1008102244](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/bce9f841-ed98-4d93-9fa0-80076627bd18)

**Comment by m2075498242** [comment]
这样是可以 但是表头就不是固定的了
