### ISSUE TITLE
列表  分类字典不显示

### ISSUE THREAD

**Issue by sunjie798893816** [jeecgboot/jeecgboot-vue3#777]
##### 版本号：
3.5.5  vue3版本

##### 问题描述：
代码更新完后，列表上 分类字典数据不显示了

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/11585853/e628da6e-81b0-4b18-9ebe-ca237b89c360)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/11585853/386f3613-9854-4b19-bf76-49eb85a05dec)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/11585853/7b19ecfd-aaee-4f0d-b13a-ebb0e19fb08c)

对比了之前的代码，加载完字典后diaoyongle调用了 setAuthCache(DB_DICT_DATA_KEY,allDictDate) 这个方式，可是渲染时候，却没有从这个缓存去取，只从数据字典缓存取。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
官网是登录之后从/user/getUserInfo接口拿到了用户信息和所有的字典，然后把字典都放入了pinia，后续业务里面取字典数据都走pinia，从pinia拿数据比从local要快，特别是生产环境（生产对local数据进行了加密，取的时候还得解密）。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/f16e92b0-a903-4df5-90ed-e4af1a76832a)
src/store/modules/user.ts
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/81bc0b0d-ba06-417b-993e-c8c50d48de9c)

看你的代码不是从/user/getUserInfo取的字典使用了别的接口，那你在你的initDictCinfig函数里面拿到了所有在字典数据，就往pinia里面存下即可useUserStore有个setAllDictItems方法。

**Comment by jhaso1988** [comment]
需要在实体上配置注解  eg: @Dict(dicCode = "unitName") ,还要在字典表中配置，后端问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/c0377dff-4b92-47ba-adc3-e9420afa0cd8)

**Comment by sunjie798893816** [comment]
> 官网是登录之后从/user/getUserInfo接口拿到了用户信息和所有的字典，然后把字典都放入了pinia，后续业务里面取字典数据都走pinia，从pinia拿数据比从local要快，特别是生产环境（生产对local数据进行了加密，取的时候还得解密）。 ![image](https://user-images.githubusercontent.com/8199499/270281663-f16e92b0-a903-4df5-90ed-e4af1a76832a.png) src/store/modules/user.ts ![image](https://user-images.githubusercontent.com/8199499/270283657-81bc0b0d-ba06-417b-993e-c8c50d48de9c.png)
> 
> 看你的代码不是从/user/getUserInfo取的字典使用了别的接口，那你在你的initDictCinfig函数里面拿到了所有在字典数据，就往pinia里面存下即可useUserStore有个setAllDictItems方法。

这是分类字段 不是普通的字典  分类字典没有随着系统存入缓存

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你在下载的代码入口页面可按如下修改。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/f66662d7-2a6f-4ca3-8b09-c89bacb57b77)
