### ISSUE TITLE
无法调用 Table 内部方法及 table 参数配置

### ISSUE THREAD

**Issue by jhaso1988** [jeecgboot/jeecgboot-vue3#779]
##### 问题描述：
http://static.kancloud.cn/zhangdaiscott/vue3/3082560
参考这个样例，想获取表格数据，使用tableAction无法调用 Table 内部方法及 table 参数配置
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/e61792a8-aad2-4ba1-aca9-9a8ad4fce3fb)

<img width="956" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/a9cd837a-1c32-4634-b871-45f8e8da6409">

  let dataSource = tableAction.getDataSource();
是报错的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这个必须是异步的操作，同步这时候BasicTable实例还获取不到。你要获取第一个可以在fetch-success事件中操作。
 [可查看此文档](https://help.jeecg.com/component/BasicTable.html])
