### ISSUE TITLE
JSelectUserByDept 组件在BaseForm 模式使用，updateSchema传初始值无效

### ISSUE THREAD

**Issue by mlt131220** [jeecgboot/jeecgboot-vue3#78]
##### 问题描述：
JSelectUserByDept 组件在BaseForm 模式使用时，使用updateSchema方法更新字段初始值无效，未触发JSelectUserByDept 内部的initValue方法

##### 截图&代码：
在 useModalInner 内使用updateSchema无效；
![image](https://user-images.githubusercontent.com/48863081/169496717-7ba7e5c3-a559-4c15-8595-0aca375f2847.png)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
表单属性赋值用的是这个方法： setFieldsValue({...属性值})

**Comment by lsqGitHub716** [comment]
表单字段赋值用的是这个方法： setFieldsValue({...属性值})
