### ISSUE TITLE
SaaS模式中X-Tenant-Id服务端没有校验，存在安全风险

### ISSUE THREAD

**Issue by qingfengljh** [jeecgboot/jeecgboot-vue3#784]
##### 版本号：
3.5.3

##### 问题描述：
目前SaaS实现方式中tenant_id通过header传递，传回到服务端时没有校验该用户是不是真实的tenant_id，如果恶意程序把登录后的账号，更改tenant_id为别人的tenant_id，就能操作别人的数据了。

**Comment by qingfengljh** [comment]
建议调整方式：登录前用户选择哪个租户（如有多个租户，如只有一个直接得到tenant_id），确认租户后进行时机的登录，把tenantId放在jwt的Token中传递。切换租户则重新登录。

**Comment by zhangdaiscott** [comment]
后台拦截器里面有校验
