### ISSUE TITLE
> 你的数据库应该没升级，你需要手工给角色分配权限

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#789]
> 你的数据库应该没升级，你需要手工给角色分配权限

我用的增量升级的，怎么会要手工分配权限呢？如何分配？”角色管理“中可以看到菜单项授权的呀？

_Originally posted by @gxzhou in https://github.com/jeecgboot/jeecgboot-vue3/issues/783#issuecomment-1738954656_
            

修改系统菜单信息，确认保存时也是报“没有权限，请联系管理员授权。
1、在升级到3.5.5之前，一切都是正常的；
2、在升级源代码后，执行”3.5.3升级到3.5.5升级脚本.sql“升级了数据库的；
3、为什么管理员还需要联系“管理员”授权？
4、目前暂时在源码中注释掉@RequiresPermissions("system:role:deleteBatch")类似语句后，可以正常使用。但这样肯定没有达到 权限控制的目的，应该如何设置对应的相关权限，增量升级数据库是否部完善，望能给与帮助，谢谢。
![25b62901a9936a0aecabe51e246305f](https://user-images.githubusercontent.com/36326638/273374229-52570e1e-fe73-437b-862d-4b1a62ed2a0e.png)

**Comment by zhangdaiscott** [comment]
如果你不能直接用全新的数据库脚本
system:role:deleteBatch 这些权限如果没有的话，你只能手工配置了，这个是个笨方法

**Comment by gxzhou** [comment]
张老师好，手工配置的方法有文档说明吗？不会哎。













在 2023-10-07 15:34:24，"JEECG" ***@***.***> 写道：

如果你不能直接用全新的数据库脚本
system:role:deleteBatch 这些权限如果没有的话，你只能手工配置了，这个是个笨方法
