### ISSUE TITLE
系统菜单，编辑内容时，显示文本框不居中

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecgboot-vue3#790]
##### 问题描述：
点击sql增强，JAVA增强，定时任务等菜单编辑按钮时，菜单显示不居中

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/66394184/317aab1c-a135-4548-83ee-8d83d4bcde57)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/66394184/873186f3-1d43-4ac2-8e08-b40c5eaa2477)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已经修复，下一版本发布
