### ISSUE TITLE
目前没有整理整理的专门的权限升级sql，印象中以前的版本提供过

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecgboot-vue3#792]
目前没有整理整理的专门的权限升级sql，印象中以前的版本提供过
如果你不能直接用全新的数据库脚本
system:role:deleteBatch 这些权限如果没有的话，你只能手工配置了，这个是个笨方法

_Originally posted by @zhangdaiscott in https://github.com/jeecgboot/jeecgboot-vue3/issues/789#issuecomment-1751651323_

如何手动配置权限，有哪里有文档说明吗？不会哎。

**Comment by gxzhou** [comment]
我现在不知道咋弄了，数据库又不能做全量升级，又不知道咋增加权限控制，管理员连用户管理啥的都不能做了。望提供帮助，谢谢。

**Comment by zhangdaiscott** [comment]
看看这个文档，看能看明白吗
https://help.jeecg.com/vue3/auth/listbutton.html

**Comment by gxzhou** [comment]
好的，我先看看吧，估计够呛能看明白。多谢。
