### ISSUE TITLE
微服务的架构，后台父地址只会永远匹配跨域代理的第一个地址，代理数组的第二个地址怎么映射?

### ISSUE THREAD

**Issue by 279y** [jeecgboot/jeecgboot-vue3#793]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/66414490/08f75360-342e-4bc6-be31-cdbda0079eac)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
第二个地址应该是在第一个地址基础上的二级地址
类似 /system/user/

**Comment by 279y** [comment]
按截图代码，如果正确匹配第二个地址的话，地址是/system/system2吗？
