### ISSUE TITLE
前端根据权限来判断按钮显示不显示问题：有时会出现后端已返回code但是按钮不显示

### ISSUE THREAD

**Issue by lili250128** [jeecgboot/jeecgboot-vue3#795]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/134998538/66feb245-747c-48c8-88f9-3ec7a8e39fad)
这张图时页面上不显示按钮的情况时，但是后端返回了code
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/134998538/3db6a16f-e3a7-4476-91ab-8b702c5cd53d)
这张是刷新页面之后按钮出现了

function getTableAction(record): ActionItem[] {
    return [
      {
        label: '编辑',
        onClick: handleEdit.bind(null, record),
        ifShow: () => hasPermission('OrgManagement:Edit'),
      },
      {
        label: '删除',
        ifShow: () => hasPermission('OrgManagement:Delete'),
        popConfirm: {
          title: '是否确认删除',
          confirm: handleDelete.bind(null, record),
          placement: 'topRight',
        },
      },
    ];
  }
代码是这样写的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by EightMonth** [comment]
暂未在开源版本中发现该问题，如果想做按钮权限的控制，建议升级到最新版本查看，或参考如下方式
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23272421/9dc85122-0e2d-4ce9-8c2e-010b59b5b29a)
https://help.jeecg.com/vue3/auth/listbutton.html
