### ISSUE TITLE
JEditor 点击媒体、或链接图标没有出现上传按钮

### ISSUE THREAD

**Issue by yuanxu-xsmy** [jeecgboot/jeecgboot-vue3#796]
##### 版本号：
V3.5.4

##### 问题描述：
JEditor 点击媒体、或链接图标没有出现上传按钮

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/76983819/aa1b5b34-b8e3-4c1a-87ab-9e68ca5e00d1)

tinyMCE 官方是有的：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/76983819/8af21548-d282-4045-a222-0758baa565ae)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by EightMonth** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23272421/8be93d69-5bb9-40a0-86db-856e34f8a105)
如果需要上传按钮，自行添加这个配置即可，jeecg默认不添加
