### ISSUE TITLE
文件上传报错

### ISSUE THREAD

**Issue by fenghao7** [jeecgboot/jeecgboot-vue3#799]
##### 版本号：
3.5.5

##### 问题描述：
换成3.5.5以后，所有的文件上传或excel导入都出错了，返回的不再是json数据，而是一段html代码。在开发环境是好的，但部署到nginx就不行了。一开始以为是nginx配置问题，后来发现用3.5.0的前端代码就没问题，换成3.5.5就不行了

##### 截图&代码：

![%8V_ _82Q`NO}YHIXK95AUN](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/4742e348-7c54-4bd3-9956-60bec1c4bb71)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后台报什么错，你是不是前台和后台没有同步升级

**Comment by fenghao7** [comment]
后台不报错，后台代码没有问题，我把前台改成3.5.0，后台还是用3.5.5，是好的。就是前台一旦使用3.5.5就返回一段html，文件也没有穿上去。但是开发环境都是好的，只有在部署了以后就这样了

**Comment by zhangdaiscott** [comment]
那还是部署问题，我们的演示环境无问题
