### ISSUE TITLE
  安全问题，如何隐藏 url请求地址尾缀 方法名

### ISSUE THREAD

**Issue by wangheso** [jeecgboot/jeecgboot-vue3#800]
##### 问题描述：
  安全问题，如何隐藏 url请求地址尾缀 方法名

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么意思？

**Comment by wangheso** [comment]
<img width="377" alt="例子" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/141013711/4c3eaeb2-6bfd-4f0c-a93f-59dfefc7f2f9">
就像这个 红色 框里的  真实尾缀 为后台请求的方法，替换掉，避免其他人 知道你的方法名，这个 怎么处理。

**Comment by zhangdaiscott** [comment]
这个只能你自己搞，没有现成方案
