### ISSUE TITLE
BasicTable 组件的多选框的【全选】取消操作会清空所有选择项

### ISSUE THREAD

**Issue by tanyicheng** [jeecgboot/jeecgboot-vue3#801]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
BasicTable 的多选框全选第一页，第二页，然后取消第二页的全选，会清空所有全选（包含第一页的）

##### 截图&代码：
操作步骤：全选第一页，第二页的数据
![image](https://github.com/jeecgboot/jeecg-boot/assets/36302295/c302170f-328b-4f94-8dd2-8765bb53c641)

然后取消第二页的全选，结果清空了所有的选择项
![image](https://github.com/jeecgboot/jeecg-boot/assets/36302295/e692ad3b-4e37-4173-a1ad-31821013d39e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
是这么做的，因为我们支持分页选择

**Comment by tanyicheng** [comment]
支持分页选择我能理解，但是在第二页点击取消「全选」按钮，同时也会取消第一页或其他页面的选中项，这似乎有点不太合理，我觉得至少应该保证这个「全选」功能选中和取消操作是一致的，要么面向全局，要么仅针对当前页有效。现在的「全选」按钮，在勾选时，只有当前页选中（面向分页），取消勾选时，所有分页的选中项都取消（面向全局），真的确定这么设计合理吗？
