### ISSUE TITLE
column.slots弃用如何修改项目组件

### ISSUE THREAD

**Issue by 354752672** [jeecgboot/jeecgboot-vue3#802]
##### 版本号：
3.5.2

##### 问题描述：
报错：[ant-design-vue: Table] `column.slots` is deprecated. Please use `v-slot:headerCell` `v-slot:bodyCell` instead.
Vue3升级column.slots弃用页面报错，如何修改？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/56473652/c90156b0-db95-4176-a05e-635c5b826227)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
参考最新版的代码，代码生成器改法
