### ISSUE TITLE
Vue3 获取用户信息接口，返回用户对象里面没有角色 roles 字段 

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecgboot-vue3#805]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/1ebbb285-6ba6-4b26-bbc2-e1a69d13748c)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/ba363dce-5f15-499f-8be5-eee36e294824)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/e2cfe208-5dbf-451a-bdf8-66c36c4b93ff)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
? 这个界面不用管，我们前端权限功能是没有问题的
