### ISSUE TITLE
生产环境登录时间过长 达一分钟

### ISSUE THREAD

**Issue by 18612962616** [jeecgboot/jeecgboot-vue3#806]
##### 问题描述： 生产环境登录时间过长 达一分钟
是不是登陆人的权限菜单越多 点登陆进入首页的时间就越长？ 
我现在的管理员账号 在生产环境点击登录 要转一分钟才进到首页 员工账号菜单少 20秒左右 整体时间太长 怎样能优化下呢
我通过浏览器工具录制登录期间性能报告  里面主要是大量的asyncImportRoute 每一个都在1-3秒左右 看起来像是在加载每一个菜单
怎样能改善这个问题呢 
##### 截图&代码：

![微信图片_20231019011308](https://github.com/jeecgboot/jeecgboot-vue3/assets/35988128/418090a1-2921-48ce-a6d9-33b8837f15c3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以在后台登录接口加日志，看下接口响应时间，这种问题一般跟前端无关

**Comment by 18612962616** [comment]
检查了登录后台login接口和 getUserInfo接口 各发现了一个数据字典的查询 
userInfo(sysUser, result);

obj.put("sysAllDictItems", sysDictService.queryAllDictItems());

而我之前的一个功能要每个月往字典表里插1000条数据 导致了这两步时间长  
那如果我不做大面积修改对这几千条数据的插入和读取的逻辑  只是改登录的这两个接口的这两个读取  可否剔除对那几千条特殊dict_id的查询？

**Comment by 18612962616** [comment]
但是  本地和生产连接同一个库 本地管理员登录要比生产快的多 5 6秒就完成了登录 服务器需要一分钟   难道是两边redis的区别？

**Comment by 18612962616** [comment]
服务器加了日志观察  数据字典不是主要问题 在服务器上也只执行了几秒而已  剩下50多秒 后台没有日志了

**Comment by zhangdaiscott** [comment]
自己分析下吧，我们没遇到过类似情况

**Comment by heySimonGreen** [comment]
我也遇到了登录需要很久，一分钟左右

**Comment by heySimonGreen** [comment]
楼主解决了记得回复一下，我设置了提醒

**Comment by xiaodidi-js** [comment]
是因为菜单太多导致吗？
