### ISSUE TITLE
旧的vue2版本如何升级

### ISSUE THREAD

**Issue by PangHuwo** [jeecgboot/jeecgboot-vue3#807]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
vue2与vue3是完整不同的两套前端，不支持升级
