### ISSUE TITLE
JVxeTable 的设定某行某列的值方法setValues 需要一个样例，一直调试不通过

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/jeecgboot-vue3#809]
##### 版本号：
3.5.5

##### 问题描述：
JVxeTable 的设定某行某列的值方法setValues 需要一个样例，需要根据条件级联某行某列的值的变化。

##### 截图&代码：

JVxeTable 的设定某行某列的值方法setValues 需要一个样例，需要根据条件级联某行某列的值的变化。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这是在综合示例页面做的一个例子，你可把代码贴上去运行下。
在src/views/demo/jeecg/JVxeTableDemo/JVxeDemo1.vue文件
onMounted(() => {
    setTimeout(() => {
      const dataSource = tableRef.value!.getTableData();
      tableRef.value!.setValues([{"rowKey":dataSource[0].id,values:{number:333,"input":"中国人"}}]);
    }, 5e3);
  })
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/ad816b98-76d6-4ae9-ab79-6bf9b11d16ae)

**Comment by liaozhiyang** [comment]
这是在综合示例页面做的一个例子，你可把代码贴上去运行下。
在src/views/demo/jeecg/JVxeTableDemo/JVxeDemo1.vue文件
onMounted(() => {
setTimeout(() => {
const dataSource = tableRef.value!.getTableData();
tableRef.value!.setValues([{"rowKey":dataSource[0].id,values:{number:333,"input":"中国人"}}]);
}, 5e3);
})
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/e410d152-7c1e-4a26-9329-7745a04c3d61)

**Comment by afearboy** [comment]
好的，我试试
