### ISSUE TITLE
页面有时间加载出现问题

### ISSUE THREAD

**Issue by m2075498242** [jeecgboot/jeecgboot-vue3#810]
##### 版本号：
3.4.0

##### 问题描述：
不知道是什么情况  就出现了这种莫名其妙的状况  
鼠标随便晃两下，有的时候就会出现这种情况

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/89441679/745d2a90-f255-42b7-b57b-e9b967ffa43d)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/89441679/965b72e3-9e51-48ea-b53a-82086a33a73d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
老版本无法支持，可以先升级到最新版
