### ISSUE TITLE
pnpm install  出错

### ISSUE THREAD

**Issue by zcq111** [jeecgboot/jeecgboot-vue3#811]
##### 问题描述：
启动时提示找不到包：

 WARN  GET https://registry.npm.taobao.org/@jeecg/online/-/@jeecg/online-3.5.3-vite4.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npm.taobao.org/vue-print-nb-jeecg/-/vue-print-nb-jeecg-1.0.12.tgz error (ERR_PNPM_TARBALL_INTEGRITY). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/vue-print-nb-jeecg/-/vue-print-nb-jeecg-1.0.12.tgz error (ERR_PNPM_TARBALL_INTEGRITY). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_404  GET https://registry.npm.taobao.org/@jeecg/online/-/@jeecg/online-3.5.3-vite4.tgz: Not Found - 404

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/39423986/50ff775b-f65f-4982-b03a-c259ff9e0ea1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by byteforgecn** [comment]
我把pnpm-lock.yaml删了重新生成就好了
