### ISSUE TITLE
登录报错 Cannot destructure property "userlnfo' of (intermediate value)' as it is undefined.

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecgboot-vue3#812]
##### 版本号：

3.6.0
##### 问题描述：
登录时有一个报错
Cannot destructure property "userlnfo' of (intermediate value)' as it is undefined.
##### 截图&代码：
![d85589c84e3dfd5f61764977a3bcaab](https://github.com/jeecgboot/jeecgboot-vue3/assets/28818320/ca876c5d-403b-4e4b-a160-af6f5da23457)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
redis清空下数据

**Comment by zhangdaiscott** [comment]
清下浏览器缓存试试

**Comment by snkever** [comment]
试过清理浏览器缓存，chrome、edge、IE，只有edge和IE会报这个错误。

**Comment by 520-x** [comment]
同样遇到过

**Comment by EightMonth** [comment]
> 试过清理浏览器缓存，chrome、edge、IE，只有edge和IE会报这个错误。 Message ID: ***@***.***>

后台是否执行过3.6.0的升级脚本

**Comment by EightMonth** [comment]
另外 请问 这是用的线上demo，还是本地部署的呢，如果是本地部署的话，麻烦提供一下后台报错信息

**Comment by snkever** [comment]
数据库直接用的最新的jeecgboot-mysql-5.7.sql（Date: 18/10/2023 13:55:25）脚本新建的。java后台没有报错信息

**Comment by EightMonth** [comment]
问题原因：https://hm.baidu.com/hm.js?0febd9e3cacb3f627ddac64d52caac39 JS加载失败

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
已修复
