### ISSUE TITLE
online表单生成时，创建字段后删除，页面属性、检验字段、外键处对应字段无法删除

### ISSUE THREAD

**Issue by zhangblin** [jeecgboot/jeecgboot-vue3#813]
##### 问题描述：
online表单开发时，在数据库属性页面新增字段后删除，页面属性、校验字段、外键 处仍存在

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/22977702/d14bb272-7d7e-40c1-87c5-356f04cf3530)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/22977702/c7a77867-d5ab-41a1-8961-3fc8cadf766a)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/22977702/63f4cfdc-840c-483a-857d-5f30d48976f7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
此bug已经发现，过几天升级online模块就修复了
