### ISSUE TITLE
代码生成目录无法选择或浏览

### ISSUE THREAD

**Issue by hjhcos** [jeecgboot/jeecgboot-vue3#814]
##### 版本号：
v3.4.4

##### 问题描述：
在Online表单开发中，选择一张表点击代码生成按钮，其弹出得弹窗中代码生成目录无法选择或浏览

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/54499588/c960744c-3612-4786-82e9-3d83cb4fef51)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
使用admin账号
