### ISSUE TITLE
在线生成删除多余字段后保存失败

### ISSUE THREAD

**Issue by 520-x** [jeecgboot/jeecgboot-vue3#815]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55725161/2e183300-ab52-4e8a-8cee-d1d5b89597d4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已经修复，会尽快发布
