### ISSUE TITLE
popup组件清除控件问题

### ISSUE THREAD

**Issue by sdmkjz** [jeecgboot/jeecgboot-vue3#816]
##### 截图&代码：
该为jpopup.vue文件，该代码也为之前的注释代码
<img width="1277" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39215692/83564c8d-77a3-4a70-ae0b-684d77953344">
<img width="488" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/39215692/7b94f104-b3fd-4dab-b1ac-d0031e050398">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你应该扩展popup对外抛出一个清理数据的方法，在外面去调用方法
