### ISSUE TITLE
BasicTable的actionColumn 这个列是否可以合并行

### ISSUE THREAD

**Issue by luster9** [jeecgboot/jeecgboot-vue3#817]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/41810149/80086cb7-c390-4b94-86d8-f54f9788df06)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
合并行是什么效果?

**Comment by andsoncat** [comment]
> 合并行是什么效果?

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/20204317/ed5796a9-7314-4b46-8f4b-5b246e4184bf)

我也有同样的问题，请看图片我合并了4行，但是左边的checkbox和右边的操作栏都有rowSpan属性设置就最好了

**Comment by luster9** [comment]
> > 合并行是什么效果?
> 
> ![image](https://user-images.githubusercontent.com/20204317/277851001-ed5796a9-7314-4b46-8f4b-5b246e4184bf.png)
> 
> 我也有同样的问题，请看图片我合并了4行，但是左边的checkbox和右边的操作栏都有rowSpan属性设置就最好了

就是这样的问题，操作栏列能否合并行

**Comment by zhangdaiscott** [comment]
操作列好像不支持
