### ISSUE TITLE
单体升级为微服务时，nacos会报错

### ISSUE THREAD

**Issue by miaomiaozjh** [jeecgboot/jeecgboot-vue3#818]
##### 版本号：
3.6.0

##### 问题描述：
单体升级为微服务时，nacos会报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34296748/b1784049-da36-42bd-9dd1-9937c88a0daf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by miaomiaozjh** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34296748/f5649dbf-f2b8-409f-aed9-7562634d36bf)
一直报错，应该如何配置解决呢

**Comment by EightMonth** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/23272421/6ea2131f-359d-4e3c-aaee-5f7183939b32)
我想问题应该出现在这个地方，麻烦楼主检查下
