### ISSUE TITLE
更新完登录后点击 【低代码开发】-》Online表单开发 控制台报错 reading 'shapeFlag'

### ISSUE THREAD

**Issue by jhaso1988** [jeecgboot/jeecgboot-vue3#819]
##### 问题描述：更新完登录后点击 【低代码开发】-》Online表单开发 控制台报错
runtime-dom.esm-bundler.js:943 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'shapeFlag')
，然后点击所有页面都看不到页面，
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/7aff938f-5ca9-4c2a-82e4-0af047601535)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是增量升级吗？还是下载的默认版本

**Comment by jhaso1988** [comment]
我是增量升级 ，我现在改成了全量升级，我先排查一下
