### ISSUE TITLE
用户职位可以保存，但不能显示

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/jeecgboot-vue3#821]
##### 版本号：

3.6
##### 问题描述：
在用户模块，职位选择保存后，不能读取。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/82691864/bdd507db-acd7-4db1-a8b8-524e54a73d4b)
后台没有任何错误，数据库版本也是最新的3.6

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by afearboy** [comment]
但是官方的Demo 是可以保存和显示。下载的不能显示。

**Comment by zhangdaiscott** [comment]
你是增量升级，还是下载的默认版本

**Comment by afearboy** [comment]
直接全新版本

**Comment by afearboy** [comment]
数据库前端后端都是最新下载的。

**Comment by afearboy** [comment]
我看了sys_user_postion表记录是保存了的。

**Comment by zhangdaiscott** [comment]
ws

**Comment by tanyicheng** [comment]
我也遇到了，增量脚本里还把 post 字段删除了，望尽早修复
<img width="1118" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/36302295/e4ca3607-efab-4cac-b7c7-87768fa70154">
<img width="691" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/36302295/bb74176a-4d38-4c76-9267-3c50383875f0">
