### ISSUE TITLE
跨域问题：本地开发上传图片跨域

### ISSUE THREAD

**Issue by encod** [jeecgboot/jeecgboot-vue3#822]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/33222599/7e3bda65-1762-4294-a454-9e94eeb57d42)

代码配置如图：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/33222599/0a5268a1-f7a8-4adf-bff2-88fd8c110fc5)

原本按照文档配置过，如图，还是无效：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/33222599/64deb10b-d3f1-4003-b758-473de767c642)

请问该具体如何配置呢？后端接口已经开启了跨域了，前端本地开发还是跨域怎解？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/1ab64769-f22a-457c-9980-03e0bdf074c7)

配置完整的后台地址，不要映射
