### ISSUE TITLE
JUpload上传组件如果不是一次选择多个文件的话，多个文件后面的filesize获取不到

### ISSUE THREAD

**Issue by fenghao7** [jeecgboot/jeecgboot-vue3#826]
##### 版本号：
3.5.6

##### 问题描述：
不是同时上传两个及两个以上文件，只能获取第一个文件的filesize，而如果一次选择多个文件，则没有问题，查控制台发现因为除第一个文件外，后面的文件返回的格式不对，是一个代理。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/90027522/3ef7abc8-a556-47bb-a88a-44c25e163246)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这是ant-design-vue原生a-upload组件绑定change事件函数的参数，之前上传成功的参数是没有filesize的，只有当前上传的文件才会返回filesize的。如有特殊个性化需求需要自己实现。[antd upload](https://3x.antdv.com/components/upload-cn/#change)

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。（如果是填的默认值或者是回显是没有filesize的，只有上传时有）
<img width="667" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/8c06070a-92b5-40ed-b660-dbeeb483c200">

你本地可按如下图修改在src/components/Form/src/jeecg/components/JImageUpload.vue文件。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/a4535dcd-97fe-4aaf-828d-c36debf7a604)

function handleChange({ file, fileList, event }) {
        initTag.value = false;
        // update-begin--author:liaozhiyang---date:20231113---for：【issues/846】上传多个列表只显示一个
        // uploadFileList.value = fileList;
        if (file.status === 'error') {
          createMessage.error(`${file.name} 上传失败.`);
        }
        let fileUrls = [];
        let noUploadingFileCount = 0;
        if (file.status != 'uploading') {
          fileList.forEach((file) => {
            if (file.status === 'done') {
              fileUrls.push(file.response.message);
            }
            if (file.status != 'uploading'){
              noUploadingFileCount++;
            }
          });
          if (file.status === 'removed') {
            handleDelete(file);
          }
          if (noUploadingFileCount == fileList.length) {
            state.value = fileUrls.join(',');
            emit('update:value', fileUrls.join(','));
            // update-begin---author:wangshuai ---date:20221121  for：[issues/248]原生表单内使用图片组件,关闭弹窗图片组件值不会被清空------------
            nextTick(() => {
              initTag.value = true;
            });
            // update-end---author:wangshuai ---date:20221121  for：[issues/248]原生表单内使用图片组件,关闭弹窗图片组件值不会被清空------------
          }
        }
        // update-begin--author:liaozhiyang---date:20231113---for：【issues/846】上传多个列表只显示一个
      }
