### ISSUE TITLE
useCustomSelection.tsx 同步选中内容有问题

### ISSUE THREAD

**Issue by wangyujiaoflag** [jeecgboot/jeecgboot-vue3#828]
##### 问题描述：
前提：JSelectUser组件中，之前选中的内容不会展示在表格中，然后在此基础上继续选择编辑
问题：无法选中，js内存飙升、浏览器卡爆（之前的版本不存在此问题）

排查了一下，在代码逻辑中这种情况 selectedKeys 和 selectedRows长度永远不可能相同，所以会不停触发 syncSelectedRows -> setSelectedRowKeys

改成下面这样就没问题了
<img width="333" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/41095916/bbbe434a-3e78-428d-a450-31c8658f194e">

##### 截图&代码：

<img width="289" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/41095916/04cfb72b-5849-4690-acf9-157c0c3087fa">
<img width="487" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/41095916/976cb488-0e25-4c54-9926-1f7e77ad435a">

<img width="1438" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/41095916/cedc0e31-2165-4663-b801-2fef282d5ad4">

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
查看了下确实这段代码有问题，可以删除。
请问你那监听selectRows是在哪种场景需要呢？我看了下代码点击CheckBox和通过方法setSelectedRowKeys设置选中都可以触发emitChange方法，再次监听会触发多次的。

**Comment by liaozhiyang** [comment]
确实是有这个问题，但是这段代码不能删除，是为了处理别的场景使用的。这个地方可以做下兼容，造成死循环是因为在这场景下selectedRows.value 每次都会得到新的值触发watch然后selectedRows.value和selectedKeys.value长度又不相等，再次执行selectedRows.value赋新值，依次循环。

我们是这样做的兼容，你看下是否适用：
src/components/Table/src/hooks/useCustomSelection.tsx文件
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/7035b4d3-beb2-4538-ad52-2a731c5cb2b6)
const isSomeRowKeys = selectedKeys.value === rowKeys;

if(!(isSomeRowKeys && equal(selectedRows.value,trueSelectedRows))){
      selectedRows.value = trueSelectedRows;
      emitChange();
    }

function equal(oldVal, newVal) {
    let oldKeys = [],
      newKeys = [];
    if (oldVal.length === newVal.length) {
      oldKeys = oldVal.map((item) => getRecordKey(item));
      newKeys = newVal.map((item) => getRecordKey(item));
      for (let i = 0, len = oldKeys.length; i < len; i++) {
        const findItem = newKeys.find((item) => item === oldKeys[i]);
        if (!findItem) {
          return false;
        }
      }
      return true;
    }
    return false;
  }

**Comment by wangyujiaoflag** [comment]
<img width="1387" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/41095916/510e31ca-5b0a-418d-814c-29bb91346bed">
不太行😂，如上，这样上方的提示条里不统计之前已选中的数目，且反显的是当前选中的内容，不是继续追加

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/8e3459e6-5d0e-4c4b-b738-55782b4075ba)
我这边测试正常啊，你是否还改了其他地方？

**Comment by wangyujiaoflag** [comment]
我又测试了下，没有问题了，但是这段代码的逻辑没懂，可以解释一下为什么这样兼容吗
