### ISSUE TITLE
同一个表单里面不同输入框的关联查询

### ISSUE THREAD

**Issue by HbeH** [jeecgboot/jeecgboot-vue3#829]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/10784431/628bd398-597e-4dc8-9131-b8a7b447f675)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/10784431/2c81fd08-ca58-4b08-a99b-6989d2aeb99e)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/10784431/37e46d1a-2e6f-4ca9-be1f-0e07c3b82012)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/10784431/a678d008-7f60-4c28-850f-f64d85fb69ac)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/enhanceJs/form/liandong.html
