### ISSUE TITLE
jeecgboot是不是推荐用 antdesignvue？可以用elementui吗？

### ISSUE THREAD

**Issue by zhoumi711231** [jeecgboot/jeecgboot-vue3#83]
##### 版本号：
1.0

##### 问题描述：
jeecgboot是不是推荐用 antdesignvue？可以用elementui吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
哪前端重写，成本何其高
