### ISSUE TITLE
 3.6.0版本 通知公告中发布的富文本消息，在我的消息中查看没有样式 

### ISSUE THREAD

**Issue by jhaso1988** [jeecgboot/jeecgboot-vue3#834]
##### 问题描述：
通知公告中发布的富文本消息，在我的消息中查看没有样式 
我的消息的 消息详情 中使用  v-html 中样式丢失
 eg:      <span v-html="content.msgContent" class="article-content"></span>

##### 截图&代码：
发布时候的详情
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/3d941c70-2b1f-4e85-87f5-d5c39c72bfcf)
我的详情 查看时 没有样式
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/8cf2e3f9-8a16-495e-a915-78048ef82b48)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by jhaso1988** [comment]
将msgContent 考本出来，写了一个单独的Vue3 的项目使用v-html 测试 能够正常展示
"msgContent": "\u003Cp style=\"text-align: center;\"\u003E\u003Cspan style=\"text-decoration: line-through; color: #e03e2d;\"\u003E\u003Cstrong\u003Ezhangsan测试按钮\u003C/strong\u003E\u003C/span\u003E\u003C/p\u003E\n\u003Cp style=\"text-align: justify;\"\u003E\u003Cspan style=\"text-decoration: line-through; color: #e03e2d;\"\u003E\u003Cstrong\u003E今天开始测试\u003C/strong\u003E\u003C/span\u003E\u003C/p\u003E\n\u003Cp style=\"text-align: justify;\"\u003E\u003Cspan style=\"text-decoration: line-through; color: #e03e2d;\"\u003E\u003Cstrong\u003E\u003Cimg src=\"http://yi7jia-test.oss-cn-zhangjiakou.aliyuncs.com/jeditor/Y7JB_1698851872938.jpeg\" alt=\"\" width=\"640\" height=\"640\" /\u003E\u003C/strong\u003E\u003C/span\u003E\u003C/p\u003E"
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/5d86b403-e397-4020-962f-31c4a4ae623c)

使用jeecg-boot 测试发现style 的样式都没有了
<img width="902" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/34854608/aa27a0c6-0bfc-40d5-8dd7-d5e37df266aa">

**Comment by zhangdaiscott** [comment]
sq

**Comment by jhaso1988** [comment]
为了提高贵公司的服务体验，建议回消息时回汉字，sq都代表什么意思也不太清楚

**Comment by 1298191366** [comment]
已修复，待新版本发布
