### ISSUE TITLE
顶部菜单混合模式导航栏BUG

### ISSUE THREAD

**Issue by luoxing66** [jeecgboot/jeecgboot-vue3#835]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/51052831/a61d85a4-466d-47e4-9555-a7bb44185ebc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
我这没复现，有更详细的操作步骤吗？

![截图01](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/0b2f8a60-2cbf-4944-ace0-2d6d2d0bac74)
