### ISSUE TITLE
使用BasicTable表格的更多操作按钮禁用属性BUG

### ISSUE THREAD

**Issue by 757382771zhangchao** [jeecgboot/jeecgboot-vue3#839]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/71924047/be08cb84-c5cd-407b-9056-efd38b988ce7)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/71924047/fa1fadf4-6582-4097-b6d7-59019e1e27ff)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/71924047/d195642c-b37e-4241-954d-b6f14e25b955)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本更新。
你本地可按如图下更改，在src/components/Dropdown/src/Dropdown.vue文件。
<img width="1120" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/50d75c51-72dc-4546-8634-6613074c0f5a">
<img width="1018" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/c147e891-e609-4669-9db7-b65fcd4d0b7c">

:visible="popConfirmShow" @visibleChange="handleVisibleChange($event, item)"

const popConfirmShow = ref(false);
  const handleVisibleChange = (value, item) => {
    !item.disabled && (popConfirmShow.value = value);
  }

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
可在src/components/Dropdown/src/Dropdown.vue文件按如下图修改
<img width="992" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/513d37a9-d45b-466d-9dc9-ee9bd71872f2">
