### ISSUE TITLE
jvxetable的checkbox自动更新

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#84]
##### 版本号：
v.1.0.0-beta

##### 问题描述：
使用editClose事件响应单元格编辑， @edit-closed="handleEditClosed"，下拉、文本输入都可以，但checkbox不行。

##### 截图&代码：

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1910132/170631962-d893e81c-e1b3-40b5-ab97-f9691eeacb8d.png">

``` js
 { key: 'enabled', title: '启用', width: 60, type: JVxeTypes.checkbox,customValue: ['是','否'] }, 
  { key: 'sampleGroupType', title: '类型', width: 120, type: JVxeTypes.select,allowSearch:true,dictCode:'lims_sample_group_template_type' },
 ```

``` js
function handleEditClosed(event) {
  let { $table, row, column } = event
  let field = column.property
  // 判断单元格值是否被修改
  if ($table.isUpdateByRow(row, field)) {
    // 校验当前行
    $table.validate(row).then((errMap) => {
      // 校验通过
      if (!errMap) { 
        // let hideLoading = createMessage.loading(`正在保存"${column.title}"`, 0); 
        saveOrUpdate(row,true).then(res => {
          // createMessage.success(`"${column.title}"保存成功！`)
          // 局部更新单元格为已保存状态
          $table.reloadRow(row, null, field)
        }).finally(() => {
          // hideLoading()
        })
      }
    })
  }
}
````

**Comment by eyuan** [comment]
测试发现没有触发editClose，而是和不带input的列的点击一样，触发了click，因为配置了clickSelect，所以进一步触发了selectRowChange

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
editClose 事件只有当组件从编辑状态切换成文本状态时才会触发，因为 checkbox 等组件一直处于编辑状态的，所以无法触发该事件。
对于此类组件可以使用 valueChange 事件来处理。
示例页面已更新，将在下版本发布。

![image](https://user-images.githubusercontent.com/34293221/171112817-7ac765ca-9626-4753-adde-f36b36f856f9.png)
![image](https://user-images.githubusercontent.com/34293221/171113032-dee79b1c-26d4-4f6c-9432-cf78d5769989.png)
