### ISSUE TITLE
j-date 组件怎么设置成只能选择时分秒的形式呢？

### ISSUE THREAD

**Issue by ytwgogo** [jeecgboot/jeecgboot-vue3#841]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://www.antdv.com/components/date-picker-cn/#DatePicker-
