### ISSUE TITLE
使用mars3d非常卡顿

### ISSUE THREAD

**Issue by icooooler** [jeecgboot/jeecgboot-vue3#842]
##### 版本号：
3.6.0

##### 问题描述：
在项目中引入[mars3d](http://mars3d.cn/example.html)这个三维gis库，渲染地图时候非常卡顿，是否有什么冲突

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你应该看mars3d集成问题

**Comment by icooooler** [comment]
我测试了一下，并不是mars3d的问题，而是只要在项目中使用cesium相关的gis框架就很卡顿，包括直接在项目中使用原生cesium也是一样，现在大屏+gis的需求还是很高的，希望能帮忙看一下什么问题
