### ISSUE TITLE
jeecgboot-vue3访问无反应，不定期出现以下截图提示

### ISSUE THREAD

**Issue by chaoskwok** [jeecgboot/jeecgboot-vue3#843]
##### 问题描述：jeecgboot-vue3访问无反应，不定期出现以下截图提示
                              JEECGBOOT启动正常，浏览器访问也正常
                              jeecgboot-vue3启动也正常
                              部署说明上的步骤均已完成

##### 截图&代码：
![jeecgerror](https://github.com/jeecgboot/jeecgboot-vue3/assets/119489868/345dd0c1-cd6d-4605-9195-0358097b10ea)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
我们没遇到过，如果你可以提供重现步骤，我们才可以处理

**Comment by chaoskwok** [comment]
> 我们没遇到过，如果你可以提供重现步骤，我们才可以处理

这个。。。基本上都按照官方介绍操作的，都不知道怎么描述

**Comment by chaoskwok** [comment]
> 我们没遇到过，如果你可以提供重现步骤，我们才可以处理

两个服务都正常启动了，或者有没有办法进一步的打开VUE的日志？

**Comment by zhangdaiscott** [comment]
问问你身边的人

**Comment by chaoskwok** [comment]
我是身边第一个试用jeecgboot的

**Comment by chaoskwok** [comment]
已解决
powershell被禁，nodejs无法正常安装
获取powershell权限后重装nodejs，恢复正常
