### ISSUE TITLE
JVxeTable 右上角不能控制显隐

### ISSUE THREAD

**Issue by Adolphchen666** [jeecgboot/jeecgboot-vue3#844]
##### 版本号：
3.5.1

##### 问题描述：

因为JVxeTable type 设置成JVxeTypes.hidden setValue 方法会有问题，因此看了3.6.0的更新，手动升级了 vxe-table的版本 并且把xe-utils的版本也升级了，之后替换了components/jeecg/JVxeTable 文件夹中的内容，VxeTypes.hidden的问题解决了，但是现在出现了没有勾选框的bug，并且右上角的工具栏 也不能选择了
##### 截图&代码：

![截屏2023-11-07 09 01 05](https://github.com/jeecgboot/jeecgboot-vue3/assets/103155969/ea1dd33a-30f2-4d63-8119-cbe18fcba342)

<img width="1188" alt="截屏2023-11-07 09 03 36" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/103155969/a8481111-52b0-4323-87f1-c170b2e61322">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
运行3.6.0版本看是否存在问题，别是你自己升级有遗漏导致

**Comment by liaozhiyang** [comment]
经测试在3.5.1版本上面升级vxe-table并未复现此问题，你可查看是否样式有冲突直接给隐藏了。或者下载一个干净版本的升级下看是否会重现此问题。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/939ed376-fc82-4417-8a0b-b1c6472bf191)
