### ISSUE TITLE
JImageUpload 开启 multiple, 上传多个图片，返回的上传成功文件列表中只有第一个文件名称

### ISSUE THREAD

**Issue by dennislan** [jeecgboot/jeecgboot-vue3#846]
##### 问题描述：
JImageUpload 开启 multiple, 上传多个图片，返回的上传成功文件列表中只有第一个文件名称

##### 截图&代码：
FormSchema 栏位定义如下：
{
    label: 'xxxx',
    field: 'xxxx',
    component: 'JImageUpload',
    componentProps: {
      accept: 'image/*',
      fileMax: 20,
    },
    dynamicRules: () => {
      return [{ required: true }];
    },
  },

PS. 貌似问题一直存在，3.5.x 中也有此问题，不是升级造成的

有时间请帮忙看看，感谢！

**Comment by zhangdaiscott** [comment]
截图或者录视频说明

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
效果如图：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/3bd19c1f-3b56-4564-84a3-ecf3418c6ab3)

你本地可按如下图修改在src/components/Form/src/jeecg/components/JImageUpload.vue文件。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/f54805ee-d8d4-4841-9ed7-80bb5f8e8e36)

function handleChange({ file, fileList, event }) {
        initTag.value = false;
        // update-begin--author:liaozhiyang---date:20231113---for：【issues/846】上传多个列表只显示一个
        // uploadFileList.value = fileList;
        if (file.status === 'error') {
          createMessage.error(`${file.name} 上传失败.`);
        }
        let fileUrls = [];
        let noUploadingFileCount = 0;
        if (file.status != 'uploading') {
          fileList.forEach((file) => {
            if (file.status === 'done') {
              fileUrls.push(file.response.message);
            }
            if (file.status != 'uploading'){
              noUploadingFileCount++;
            }
          });
          if (file.status === 'removed') {
            handleDelete(file);
          }
          if (noUploadingFileCount == fileList.length) {
            state.value = fileUrls.join(',');
            emit('update:value', fileUrls.join(','));
            // update-begin---author:wangshuai ---date:20221121  for：[issues/248]原生表单内使用图片组件,关闭弹窗图片组件值不会被清空------------
            nextTick(() => {
              initTag.value = true;
            });
            // update-end---author:wangshuai ---date:20221121  for：[issues/248]原生表单内使用图片组件,关闭弹窗图片组件值不会被清空------------
          }
        }
        // update-begin--author:liaozhiyang---date:20231113---for：【issues/846】上传多个列表只显示一个
      }
