### ISSUE TITLE
强烈建议多租户做成创建一个租户公司就建一个库，就是多租户多库

### ISSUE THREAD

**Issue by andsoncat** [jeecgboot/jeecgboot-vue3#849]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个工作量较大，开源版本我们暂时不会做，需要可以自己扩展也简单
