### ISSUE TITLE
下拉字典搜索框不起效，按文档配置后效果为文本框，demo例子里没有

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#85]
# 版本号：
V1.0.0-beta

# 问题描述：
下拉字典搜索框不起效，按文档配置后效果为文本框，demo例子里没有。
想实现的效果是下拉从一个字典表中拉取值。另外能否从online查询，甚至后台url中取值？selectDictSearch给出的表中取值功能受限，例如需要表中某些数据值而非全部。

# 截图&代码：
## 文档描述
下拉字典搜索框
类型：JVxeTypes.selectDictSearch
参数：
async：是否异步搜索
dict：仅async=true时生效，字典code（数据库表名,显示字段名,存储字段名）
示例："sys_user,realname,username"
options：仅async=false时生效，搜索选项
tipsContent：提示内容，默认：请输入搜索内容
## 使用
··· js
  { key: 'plantName', title: '登样班组', width: 200, type: JVxeTypes.selectDictSearch,async:true,dict:'lims_plant,plant_name,id' },
···
## 效果
<img width="311" alt="image" src="https://user-images.githubusercontent.com/1910132/170634469-1a283b1e-5977-48b1-a163-ab613079ec76.png">

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试未发现您说的问题，您可以参考一下下面的示例，或者把您的完整的示例代码截图贴出来
![image](https://user-images.githubusercontent.com/65587928/170976144-8637dc6c-4012-4495-9c54-124f3f0b5184.png)
