### ISSUE TITLE
jVxeTable 使用JvxeType.Popup 能存id 在组件上显示title 么

### ISSUE THREAD

**Issue by Adolphchen666** [jeecgboot/jeecgboot-vue3#851]
##### 版本号：
3.5.1

##### 问题描述：
jVxeTable 使用JvxeType.Popup 能存id 在组件上显示title 么

##### 截图&代码：

<img width="436" alt="截屏2023-11-09 09 45 13" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/103155969/1b05c565-4aa4-4a58-81e1-33bb563423fd">

![截屏2023-11-09 09 46 15](https://github.com/jeecgboot/jeecgboot-vue3/assets/103155969/5dce3264-606a-4f72-a3f6-b810488c0326)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以弄一个隐藏字段，存ID，在弄一个显示字段显示文本
