### ISSUE TITLE
filterDictTextByCache方法导致列表操作卡顿

### ISSUE THREAD

**Issue by 15098731779** [jeecgboot/jeecgboot-vue3#853]
##### 版本号：
vue3 /  3.5.2

##### 问题描述：
列表使用这个方法翻译，会导致列表卡顿严重，本地调试没有问题，打包后会出现问题
##### 截图&代码：

![1699595477118](https://github.com/jeecgboot/jeecgboot-vue3/assets/63895685/28a7db89-f97b-4952-8d4a-e54b7d3f6434)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级到最新版看看，不行就用后台注解方式

**Comment by 15098731779** [comment]
> 升级到最新版本看看，不行就用后台注解方式

已改为后台注解方式，排查过一段时间，没有发现原因
