### ISSUE TITLE
Table 做嵌套子表格时发出警告`expandIconColumnIndex` is deprecated. Please use `Table.EXPAND_COLUMN` in `columns` instead.

### ISSUE THREAD

**Issue by yuanxu-xsmy** [jeecgboot/jeecgboot-vue3#854]
##### 问题描述：
Table 做嵌套子表格时发出警告：`expandIconColumnIndex` is deprecated. Please use `Table.EXPAND_COLUMN` in `columns` instead.

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/76983819/dda04a0b-fcdd-4885-a1dc-918930ceee2a)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/76983819/2bc47bfe-f0a8-4179-a787-57378c721f4d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
警告不影响功能，暂时忽略把

**Comment by Yinmengfox** [comment]
@zhangdaiscott 现在这个错误已经导致展开行无法打开,能帮忙看下?
