### ISSUE TITLE
用户管理-岗位仍然不回显

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/jeecgboot-vue3#855]
##### 版本号：
3.6.0 最新版本

##### 问题描述：
在用户管理中赋予用户的岗位，保存提示成功，但打开时仍然没有岗位的显示，但后台代码使用岗位字段的时候其实是值的，也可以用，但前端就是不显示岗位。

在官网中是正常可以回显的。使用了最新发布的后台前端代码，问题依然。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已提交https://github.com/jeecgboot/jeecg-boot/commit/b3e4a73a342445f1ed1555c8f927b04a8d6b27d0
