### ISSUE TITLE
JVxeTable 用户选择后无法触发单元格编辑

### ISSUE THREAD

**Issue by hqy411** [jeecgboot/jeecgboot-vue3#856]
##### 截图&代码：

{ key: 'userId', title: '用户', align: "center", width: 160, type: JVxeTypes.userSelect},

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉;
