### ISSUE TITLE
使用Online 表单功能  能否配置每个列开启拖动 resizable 属性

### ISSUE THREAD

**Issue by xiaogangya12138** [jeecgboot/jeecgboot-vue3#857]
##### 问题描述：
使用Online 表单功能 能否配置每个列开启拖动 resizable 属性 并且设置初始width
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/4607a600-6c0f-47d4-b1f2-be0cf1f2b664)

ps:如果不能配置是否可以在那个文件里可以单独修改?

##### 截图&代码：

![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/61934813/1a07808e-3b8b-4e4f-9158-451b66914db5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前没实现这功能
