### ISSUE TITLE
json格式数据 多数据源配置动态API 图表显示异常

### ISSUE THREAD

**Issue by ZorionS01** [jeecgboot/jeecgboot-vue3#858]
##### 版本号：
vue2 / 2.2.1

##### 问题描述：
json格式 图表多数据源动态API配置 数据展示不出来 配置后 图表显示异常 
##### 截图&代码： 原始数据是下面这种json格式
[{
	"total": "13",
	"name": "逆行",
	"exact": "13",
	"type": "100.00"
}, {
	"total": "35",
	"name": "视频丢失",
	"exact": "34",
	"type": "97.14"
}] 
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/106093796/b7c36a6c-e6e6-48e0-b04b-ec3800615cc2)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你都用json数据格式了，`多数据源配置动态API`这句话又是什么意思

**Comment by ZorionS01** [comment]
多数据源配置动态API就是你用积木报表中的图表功能的时候选用API数据集 ，添加图表不是有API数据类型动态数据集，这个选绑定的数据集的时候不是API集吗 这个API集合积木文档上就是要求json格式但是我的绑定的API集合也是json格式 只是键名没有value 横坐标可以正确显示出来，但是纵坐标数据就不对了，上面截图就是。 上面的原始数据 和 绑定我的API数据集运行后 json格式也错了

**Comment by ZorionS01** [comment]
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/106093796/3e134ddc-853c-441b-9e32-18d97082b44a)
 
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/106093796/97b876a2-7b2b-4a8a-abe1-418478250591)
右侧绑定数据集也是json格式 但是图表纵坐标显示的不对呀

**Comment by zhangdaiscott** [comment]
接口返回格式，必须跟我们的文档一致

**Comment by ZorionS01** [comment]
格式必须一样的话，那我返回对象里面的键值对数也不一样啊  那我怎么改？

**Comment by zhangdaiscott** [comment]
肯定得你自己改

**Comment by ZorionS01** [comment]
我说的是键值对数不同 只要格式和文档一样就可以渲染出来吗？

**Comment by ZorionS01** [comment]
{
	"data": [{
		"total": "13",
		"name": "逆行",
		"exact": "13",
		"type": "100.00"
	}, {
		"total": "35",
		"name": "视频丢失",
		"exact": "34",
		"type": "97.14"
	}, {
		"total": "399",
		"name": "行人",
		"exact": "376",
		"type": "94.24"
	}]
} 写了适配器接口返回格式改成这种了 API数据源那里解析又报错了 只能解析出来data
