### ISSUE TITLE
关于vue3版本添加菜单的问题

### ISSUE THREAD

**Issue by nineov** [jeecgboot/jeecgboot-vue3#86]
##### 版本号：

1.1.0-beta
##### 问题描述：
后台添加菜单后，无法正确打开，不清楚如何添加相关的路由地址和组件才能正常访问

##### 截图&代码：

![image](https://user-images.githubusercontent.com/37391614/170805721-38895c56-b980-4da7-a751-d4344b2c10c8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/170819526-05f25760-8314-452d-ab09-134e77db5468.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/170820804-974f1341-118d-4197-84b9-ac95260dd265.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/170820804-974f1341-118d-4197-84b9-ac95260dd265.png)
