### ISSUE TITLE
dev模式，修改代码后modal卡死，新增详情编辑一点就卡死

### ISSUE THREAD

**Issue by jy05568536** [jeecgboot/jeecgboot-vue3#860]
##### 版本号：
最新master

##### 问题描述：
问题同 #690，希望重视这个问题，100%出现，这个问题导致热更新完全不可用，严重影响开发效率

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/5037606/3c4fe252-6b1c-4a70-a159-a26154f7439c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by jy05568536** [comment]
此行代码出了问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/5037606/e37969d5-ae93-42f9-9137-f36ce56e82ad)

**Comment by zhangdaiscott** [comment]
zy

**Comment by sunjie798893816** [comment]
> 此行代码出了问题 ![image](https://user-images.githubusercontent.com/5037606/283665726-e37969d5-ae93-42f9-9137-f36ce56e82ad.png)

兄弟 问题解决没，我现在还卡死的了，每次就只能关了浏览器重启

**Comment by jy05568536** [comment]
> > 此行代码出了问题 ![image](https://user-images.githubusercontent.com/5037606/283665726-e37969d5-ae93-42f9-9137-f36ce56e82ad.png)
> 
> 兄弟 问题解决没，我现在还卡死的了，每次就只能关了浏览器重启

没有，等待官方解决吧

**Comment by jy05568536** [comment]
没有解决，那行代码出问题只是表象，感觉是vite的bug

**Comment by liaozhiyang** [comment]
能给出一段代码吗？看看是什么应用场景下会必现，否则不太好定位

**Comment by jy05568536** [comment]
> 能给出一段代码吗？看看是什么应用场景下会必现，否则不太好定位

随便生成一个一对多的代码，然后run dev，修改前端代码，修改后点新增编辑详情就卡死，很好复现

**Comment by sunjie798893816** [comment]
> 能给出一段代码吗？看看是什么应用场景下会必现，否则不太好定位

之前我那个 issues里面 有视频 ，随便改个字 就卡死了

**Comment by GitHub-yaorao** [comment]
一对多的时候。一模一样，百分百出现

**Comment by jy05568536** [comment]
> 以前处理过 #229 

不是这个问题，同#690，就是当前最新的master，用代码生成一个一对多的，一试就知道了，100%复现

**Comment by liaozhiyang** [comment]
可以暂时先按如下修复热更新卡死的问题，真正的根源问题还得摸索下。
在src/components/jeecg/JVxeTable/src/componentMap.ts文件
<img width="1211" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/22094a52-254f-40ef-be91-eeeaee21e2a9">

const JVxeComponents = 'JVxeComponents__'
if(import.meta.env.DEV && componentMap.size === 0 && window[JVxeComponents] && window[JVxeComponents].size > 0){
  componentMap = window[JVxeComponents];
}

<img width="1194" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/12c90e92-d39f-4446-ad4b-e3019ce1197f">

import.meta.env.DEV && (window[JVxeComponents] = componentMap);
