### ISSUE TITLE
积木报表JSON格式API解析异常 图表功能不能正常使用

### ISSUE THREAD

**Issue by ZorionS01** [jeecgboot/jeecgboot-vue3#864]
##### 版本号：
vue2/2.2.1

##### 问题描述：

符合积木报表文档JSON格式数据但API数据源报表制作 解析错误
##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/106093796/95ef9414-a4ea-436c-b3a2-22dba553c4a6)
返回的数据源格式为
{
"data": [{
"total": "13",
"name": "逆行",
"exact": "13",
"type": "100.00"
}]
} 
API解析后只能解析出data 
如果改成
 [{
"total": "13",
"name": "逆行",
"exact": "13",
"type": "100.00"
}] 这种数据格式就能解析成功 但是 后面图表动态数据源绑定数据集的时候 又要求最上面那种data为键名的json数据格式

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ZorionS01** [comment]
这是一个bug吗？ 
图表绑定的数据集要求的格式与API解析json数据格式又不一样 
那这样只能满足API解析成功 如若图表要是绑定这个数据集 那就显示不了数据

**Comment by zhangdaiscott** [comment]
你的意思是json数据格式和api的数据格式不一致？
这个并不一定非要一致，因为api可能会涉及分页，json就不分页
