### ISSUE TITLE
JCodeEditor组件初始化时没有设置mode

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#869]
版本号：3.6.0

问题描述：JCodeEditor组件初始化时没有设置mode,只有初始化后通过变更language才能设置mode

 截图&代码：

![Dingtalk_20231122083850](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/c4adc110-91f0-4255-9618-c5dc10d401e7)
![Dingtalk_20231122083912](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/88b46515-aa19-4875-87fd-0efaef5920d4)

**Comment by q060831** [comment]
另外当mode为application/json时，赋值会有问题

**Comment by zhangdaiscott** [comment]
zy

**Comment by q060831** [comment]
> 另外当mode为application/json时，赋值会有问题，建议判断一下language
> 
> ```
> function setValue(value: string, trigger = true) {
>         if (value && isJsonObjectString(value) && props.language != 'application/json') {
>           value = JSON.stringify(JSON.parse(value), null, 2);
>         }
>         coder?.setValue(value ?? '');
>         innerValue = value;
>         trigger && emitChange(innerValue);
>       }
> ```

汗,这里不是类型的问题。而是当值像下面那样最后一个属性后面有逗号是出错
```
{
  "a": 1,
  "b": 2,
}
```

**Comment by liaozhiyang** [comment]
JCodeEditor初始化时没有设置mode已修复，下一版本发布
