### ISSUE TITLE
树JTreeSelect的使用，希望有通过URL调用的功能

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#87]
##### 版本号：
v1.0.0-beta

##### 问题描述：
系统中给的示例（选择permission、depart），两个表本事就是树形展示的数据结构，控件的api也是针对此类的。
``` table
dict | string |   | 表名,显示字段,存储字段 拼接的字符串 
```

但业务需求类似是，有班级表classes，然后学生表student（外键classid关联classes表id），类似这样的希望使用树控件选择学生记录，请问这种需求如何实现？
希望jtreeSelect支持设置一个url，url返回id\pid\text\value这样的VO来实现树选择。

拜托大佬。

**Comment by zhangdaiscott** [comment]
支持配置表
![image](https://user-images.githubusercontent.com/3162115/170861816-5d646955-01eb-4145-9202-ed8fb94f8f2d.png)
