### ISSUE TITLE
online动态控件的显隐

### ISSUE THREAD

**Issue by MeraJiang** [jeecgboot/jeecgboot-vue3#870]
##### 版本号：
vue3@3.6.0
##### 问题描述：
表单新增页面,选择类型,根据类型来显示另一个字段的动控件

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
无此功能
