### ISSUE TITLE
online子表tab的显隐怎么实现

### ISSUE THREAD

**Issue by MeraJiang** [jeecgboot/jeecgboot-vue3#871]
##### 版本号：
vue3@3.6.0

##### 问题描述：
子表tab的显隐怎么实现

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
描述过于简单

**Comment by MeraJiang** [comment]
> 描述过于简单
当选择表单的某个类型字段,根据类型不同,可控制是否展示其中对应的子表tab控件信息

**Comment by zhangdaiscott** [comment]
没这功能
