### ISSUE TITLE
JSelectUser选择用户、JSelectPosition岗位选择、JSelectDept部门选择组件的样式问题

### ISSUE THREAD

**Issue by youngswell** [jeecgboot/jeecgboot-vue3#875]
##### 截图&代码：
岗位选择组件引用代码
```html
<j-select-position
  v-model:value="formData.inspectionGroup"
  style="width: 100%"
  placeholder="请输入质检组"
  :disabled="disabled"
/>
```
展示样式
![Dingtalk_20231124101520](https://github.com/jeecgboot/jeecgboot-vue3/assets/26730076/9c53a59b-8841-43bc-8618-7ce07b3df194)

**Comment by zhangdaiscott** [comment]
占一行不是通过这个参数，是外面的item布局

**Comment by youngswell** [comment]
设置style="width: 100%"无法铺满外容器，3.6.1还没解决吗？
