### ISSUE TITLE
前端页面加载问题

### ISSUE THREAD

**Issue by dxiyang** [jeecgboot/jeecgboot-vue3#88]
##### 版本号：
Jeecgboot-Vue3 v1.0.0   最新代码

##### 问题描述：

一个前端页面会将所有的组件全部加载出来的设计原因是什么？这样前端内存占用很大，为什么不是按需加载？ 

##### 截图&代码：
打开一个页面会将所有组件注册

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
vben的实现
