### ISSUE TITLE
前端请求接口超时 [接口请求超时,请刷新页面重试!]

### ISSUE THREAD

**Issue by zhc077** [jeecgboot/jeecgboot-vue3#885]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/5212547/efdbf493-ae83-4569-9b99-ddb26a10330a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
那个接口

**Comment by zhc077** [comment]
具体和哪个接口没有关系，只是出现了种情况
![Uploading 微信图片_20231129
![微信图片_20231129145313](https://github.com/jeecgboot/jeecgboot-vue3/assets/5212547/3cd8ef78-0eec-45e5-8dfc-840b76438607)
145307.png…]()

**Comment by zhangdaiscott** [comment]
axiso改下超时配置
src/utils/http/axios/index.ts
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/6712ea7a-f42f-4d65-8438-e15adf41c3e3)
