### ISSUE TITLE
Markdown编辑器在Edge浏览器中失效

### ISSUE THREAD

**Issue by PhoenixJane** [jeecgboot/jeecgboot-vue3#89]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/76688284/171314319-70d43dab-4b9f-4833-afe8-e6bee38ea380.png)
![image](https://user-images.githubusercontent.com/76688284/171314457-931c2277-02f8-47a9-aae4-35a4cba68fc4.png)

**Comment by zhangdaiscott** [comment]
什么浏览器，发问题能专业点不

**Comment by PhoenixJane** [comment]
> 什么浏览器，发问题能专业点不

微软的Edge浏览器，还能是哪个？

**Comment by PhoenixJane** [comment]
官方JEEBOOT VUE3版本在线演示里的编辑器，markdown也全挂了

**Comment by PhoenixJane** [comment]
@zhangdaiscott 问题解决了，vben里的markdown用的是第三方插件vditor，这个插件里的cdn外链出现问题了，希望光网能提供个外链。
