### ISSUE TITLE
当表格无数据且显示合计栏，关闭tab页后，BasicTable报错

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecgboot-vue3#894]
##### 问题描述：
1、当表格无数据且显示合格栏，关闭tab页后，BasicTable报错，点击其它菜单也都会报错，如果表格已经有数据或先增加一条记录记录后就不会报错

##### 截图&代码：
![微信图片_20231128222232](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/7ce7ffb5-43f0-4ff1-a509-b1936500abd6)
![微信图片_20231128221757](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/dd5e0891-1eaf-479a-923b-8a0ab0504533)
![微信图片_20231128221542](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/cbe1b4de-2899-473d-9e1a-92abc557aaec)
![微信图片_20231128221414](https://github.com/jeecgboot/jeecgboot-vue3/assets/54636793/dbe23382-fb39-49df-abc6-600174d2bc1f)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这段代码可以直接删除，当时为了解决合计栏滚动条和上面的table滚动条不能同步的问题，后来合计栏的滚动条被隐藏了即这段代码就失效了。

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/4af2fa0d-4b6d-4212-acb9-bd7b2f2af2ab)


之前会有两个滚动条
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/0e8dca05-8f47-4901-8eb6-111bba3dfe31)

**Comment by zhangdaiscott** [comment]
已修复，上传代码
