### ISSUE TITLE
本地跑如何走mock？按照文档改了env.development文件上的配置，但是请求接口一直是500

### ISSUE THREAD

**Issue by kevinZzzzzzz** [jeecgboot/jeecgboot-vue3#895]
##### 截图&代码：

<img width="1416" alt="截屏2023-11-29 下午4 28 40" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/56809607/b5602426-845c-4dc4-b8c3-59c8f224778d">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
mock只是部分测试接口，你这边如果是登录的话，必须走jeecgboot后台，没有mock概念
