### ISSUE TITLE
正式版的变动应该会很大吧？

### ISSUE THREAD

**Issue by YANGHAOHEHE** [jeecgboot/jeecgboot-vue3#9]
目前项目正好有一个较大的空窗期，我正在把原来基于vue2的重构成vue3
发现目前beta版有不少需要完善的，一个用“defHttp”这个替代了之前的getaction等请求，但是vue3版基于的框架好像一旦请求成功了就会弹出一个“操作成功！”的消息框，并且请求失败的话也没有之前那样的消息框弹出，而只能从控制台看到异常。
正式版如果21号出的话，是不是有不少底层要调整呀。

**Comment by zhangdaiscott** [comment]
正式版改动很小，只会修复bug
参考jeecgboot最新版，后台做了适配，你肯定是老jeecgboot，自己参考修改

**Comment by YANGHAOHEHE** [comment]
> 正式版改动很小，只会修复bug 参考jeecgboot最新版，后台做了适配，你肯定是老jeecgboot，自己参考修改

谢谢回复。我估计得在axios.ts里看一下原因了
