### ISSUE TITLE
能否更新一下vben

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecgboot-vue3#90]
##### 版本号：
1.1.0-beta

##### 问题描述：
[【兼容性问题】华为手机自带浏览器菜单颜色异常](https://github.com/vbenjs/vue-vben-admin/issues/1344)
目前的版本里存在这个问题，按照issue里的说法升级vben有用

##### 截图&代码：

![image](https://user-images.githubusercontent.com/14859466/171323275-b954d9f9-327b-43f1-9440-ace5369847a5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecgboot-vue3/issues/I5GLQU
