### ISSUE TITLE
useCustomHook.ts缺失，自定义按钮js增强无法使用自定义hook

### ISSUE THREAD

**Issue by joesZheng** [jeecgboot/JeecgBoot-vue3#900]
版本号：jeecgBoot3.6。0
前端版本：vu3
问题描述：
online表单开发新建表单成功后，增加自定义按钮后，使用js增强hook写法，根据使用文档发现代码文件中没有发现src/views/super/online/cgform/hooks/auto/useCustomHook.ts的文件，导致无法使用自定义的hook
![1701411098240](https://github.com/jeecgboot/jeecgboot-vue3/assets/107098867/4533344a-70d5-40ae-ad87-eae564e4e4f0)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/107098867/a850f105-91e0-46ad-ba9e-500156083171)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
开源版无法使用
