### ISSUE TITLE
弹窗表单使用JPopup组件配置param参数后异常

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecgboot-vue3#901]
版本号：3.6.0

问题描述：JPopup组件配置了param在初始化时会发出两次没有报表id的请求,不配置param没问题，初始化不请求，只有点击弹窗才请求且没报错

截图&代码：
![1](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/cfb6b4ed-11a2-4d85-b52b-2a2f873fde8c)

![2](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/08401979-cda5-46db-8db4-60fc0c7e636f)

**Comment by q060831** [comment]
问题找到了,为啥直接监听对象,转一下啊，初始化时监听到对象两次变更，但实际上值没变

![2](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/9bda1551-7b61-4c3d-a069-d6c6cb334bea)

**Comment by zhangdaiscott** [comment]
zy
