### ISSUE TITLE
The way the jeecgboot-vue3 used for pinia causing no pinia in vue.js devtools

### ISSUE THREAD

**Issue by softboy99** [jeecgboot/jeecgboot-vue3#911]
##### 版本号：
3.6.0

##### 问题描述：
Pinia panel not exist on vue devtools

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/228731/5be6c126-d0d4-43db-b621-81450ec8b3c0)

#### 友情提示（为了提高issue处理效率）：
最好改下写法

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
经测试，无法复现。建议升级到最新的6.5.1版本试试。（测试中devtools中Pinia和Routes插件有偶发的显示，刷新下就好了。）
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/a19f880d-0daf-41a7-b461-12d3d20cf1d4)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/96ebda80-6f83-4fd2-8656-302ee7c3f3c1)
