### ISSUE TITLE
VxeTable中列的属性visible: false设置无效，必须type: JVxeTypes.hidden才可以

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/jeecgboot-vue3#912]
##### 版本号：
3.6.0

##### 问题描述：
VxeTable中列的属性visible: false设置无效，列还是显示的。
必须type: JVxeTypes.hidden才可以。
导致无法通过响应式控制列的显示隐藏

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
![vxe-table](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/741443f0-2db4-4cd6-8036-4193c3514a22)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/2329e35d-7216-4d29-b374-e342edcb69c8)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/da1c3cea-4b61-4fb4-b239-6f6da0affc91)
通过“综合示例”的vxe-table例子测试columns中visible可以响应式控制隐藏。你对着上图的代码在例子中试试看否达到如上图效果
