### ISSUE TITLE
【bug】菜单管理界面，增加的按钮，即使没有授予权限，也可看到

### ISSUE THREAD

**Issue by softboy99** [jeecgboot/jeecgboot-vue3#916]
##### 版本号：
3.6.0

##### 问题描述：
【bug】菜单管理界面，增加的按钮，即使没有授予权限，也可看到

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/228731/b779a7bb-80da-491a-9cfb-adaee6016eed)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/228731/4911b2fd-aeb0-4f20-b74a-a73b0717e4c5)

**Comment by zhangdaiscott** [comment]
代码实现截图

**Comment by zhangdaiscott** [comment]
确定？

**Comment by softboy99** [comment]
我自己已经找到问题所在，就是组件复用的问题，不同菜单调用同一组件，但传递给组件的参数不通，对按钮的缺陷控制要求不同，换句话讲，A界面的该组件要求能看到和点击一些按钮，B界面的该组件不需要这些按钮

**Comment by zhangdaiscott** [comment]
没明白

**Comment by softboy99** [comment]
就是perimcode相同，但是，权限控制不同，A界面的该组件要求能看到和点击一些按钮，B界面的该组件不需要这些按钮

**Comment by zhangdaiscott** [comment]
那你设置不同的按钮标识不就行了？
