### ISSUE TITLE
使用JVxeTable组件，进行表单验证。会被下部总计行遮挡的问题

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecgboot-vue3#917]
##### 版本号：
3.6.0

##### 问题描述：
使用JVxeTable组件，进行表单验证。会被下部总计行遮挡的问题

##### 截图&代码：
![1701939471016](https://github.com/jeecgboot/jeecgboot-vue3/assets/28818320/a3c6c709-5fac-4522-926a-e17ef4157963)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
请截个全图

**Comment by snkever** [comment]
| |
snkever
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月8日 12:44 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jeecgboot/jeecgboot-vue3] 使用JVxeTable组件，进行表单验证。会被下部总计行遮挡的问题 (Issue #917) |

请截个全图

**Comment by liaozhiyang** [comment]
错误信息提示元素在是在滚动区域内，溢出这个区域就会被裁剪掉，所以css不可以行。底层基于的是vxe-table，暂未看到vxe-table有api可更改错误信息挂载到body等方法。建议表格区域的高度设置高一点。[vxe-table](https://vxetable.cn/)
