### ISSUE TITLE
jvxetable的自定义组件文档里没有，大佬是否可完善文档或提供demo？

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecgboot-vue3#92]
##### 版本号：
v1.0.0-beta

##### 问题描述：
jvxetable的自定义组件文档里没有，大佬是否可完善文档或提供demo？
当前提供的组件类型相比vbentable/antdesigntable的列类型要少很多，不知道是否有继续扩展的计划，或者提供自定义的demo

**Comment by zhangdaiscott** [comment]
jl

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2561638
