### ISSUE TITLE
BasicTable为树形表格时不能设置只展开第一个节点

### ISSUE THREAD

**Issue by wangz37-35** [jeecgboot/jeecgboot-vue3#921]
##### 版本号：
JEECG BOOT 低代码开发平台（Vue3前端）
===============
当前最新版本： 3.4.4（发布时间：2022-11-21）

##### 问题描述：
BasicTable为树形表格时不能设置只展开第一个节点
defaultExpandAllRows: true,
defaultExpandedRowKeys: expandedRowKeys.value,
expandedRowKeys: expandedRowKeys.value,
属性值全部无效，设置之后也不能展开第一个节点，默认及时不展开

##### 截图&代码：
const { prefixCls, tableContext } = useListPage({
    tableProps: {
      dataSource: dataSource.value,
      columns: columns,
      rowKey: 'id',
      useSearchForm: false,
      pagination: false,
      isTreeTable: true,
      clickToRowSelect: true,
      defaultExpandAllRows: true,
       defaultExpandedRowKeys: expandedRowKeys.value,
       expandedRowKeys: expandedRowKeys.value,
      rowSelection: {
        type: 'radio',
      },
      actionColumn: {
        fixed: 'right',
      },
    },
  });
 const [registerTable, { reload, getColumns, setTableData, getSelectRows, expandAll, collapseAll }, { rowSelection, selectedRowKeys }] =
    tableContext;

麻烦看一下这个

**Comment by zhangdaiscott** [comment]
可以自行参考最新版代码

**Comment by wangz37-35** [comment]
但是新版我全局检索了，但是没看见单独设置默认展开第一个节点的设置
