### ISSUE TITLE
JSelectUserByDept 组件 能否设置显示选中行数？ 

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecgboot-vue3#923]
##### 问题描述：

JSelectUserByDept 组件 能否设置显示选中行数？  
有设置 showHeader = true，但是没有作用。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/84e3045e-9ef5-47c3-a23f-5a0ee404eeca)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/38241168/ad283b08-ff13-4225-8736-ab445136880a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
个性化需求请自己扩展
