### ISSUE TITLE
build报错 Cannot destructure property 'port' of 'undefined' as it is undefined

### ISSUE THREAD

**Issue by yehuabin** [jeecgboot/jeecgboot-vue3#930]
##### 版本号：
v3.6.1

##### 问题描述：
build失败，无法正常发布
改成中文路径试过了，也不行
##### 截图&代码：
![20231214093856](https://github.com/jeecgboot/jeecgboot-vue3/assets/3366096/98d8f481-e9f7-468f-81a5-d5c74a3bc7a0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yehuabin** [comment]
改成中文路径试了也不行

**Comment by ITyaoji** [comment]
要升级一下esno到4.0.0
