### ISSUE TITLE
包含tab页的表格，导出问题

### ISSUE THREAD

**Issue by Apricity-yu** [jeecgboot/jeecgboot-vue3#933]
##### 问题描述：
表格中有tab页切换，切换后点击导出，分别导出两个表单，切换tab页数据通过setColumns（）方法更新表格数据，但是导出无法重新渲染获取切换的类别。只能初始化导出一个表格

##### 截图&代码：
exportConfig: {
      name: `${type.value === '1' ? '指标任务列表' : '活动任务列表'}`,
      params: {
        taskType: type.value,
      },
      url: getExportUrl,
    },

![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
建议先升级到最新版

**Comment by Apricity-yu** [comment]
最新版提供的方法是什么？在那个文件里？
