### ISSUE TITLE
npm run builld 打包报错

### ISSUE THREAD

**Issue by hzwjs** [jeecgboot/jeecgboot-vue3#935]
##### 版本号：
3.6.1

##### 问题描述：
npm run dev 可以跑成功
npm run builld 打包报错

##### 截图&代码：

<img width="1408" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8175184/fe19c512-924c-4b77-bf05-9a68af6f0c4d">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
好了  删除生成的uniapp代码
