### ISSUE TITLE
删除二次弹窗在接口报code500时，应该取消或者删除之后就不展示二次弹窗了

### ISSUE THREAD

**Issue by Apricity-yu** [jeecgboot/jeecgboot-vue3#936]
##### 版本号：

3.6.0
##### 问题描述：

当删除的时候调用删除接口，但是当接口报code500时，不能关闭删除的弹窗提示，但是取消和不报错的接口都可正常显示，请问删除失败的时候接口的回调函数是什么，怎么可以实现接口失败也关闭提示弹框
##### 截图&代码：
![1702883350605](https://github.com/jeecgboot/jeecgboot-vue3/assets/87852049/29e6b3bb-5f12-43c8-a725-665ec748d935)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已经修复，下一版本发布。
你本地可按如下图修复
在 src/components/Button/src/PopConfirmButton.vue
<img width="1053" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/bee84cbf-cf4a-419f-937d-8e48fc4ad136">
`const getBindValues = computed(() => {
        // update-begin--author:liaozhiyang---date:20231228---for：【issues/936】表格操作栏删除当接口失败时，气泡确认框不会消失
        const result: any = Object.assign(
          {
            okText: t('common.okText'),
            cancelText: t('common.cancelText'),
          },
          { ...props, ...unref(attrs) }
        );
        if (result.onConfirm) {
          const confirm = result.confirm;
          result.onConfirm = () => {
            return new Promise<void>((resolve) => {
              confirm()
                ?.finally(() => {
                  resolve();
                })
                .catch((err) => {
                  console.log(err);
                });
            });
          };
        }
        return result;
        // update-end--author:liaozhiyang---date:20231228---for：【issues/936】表格操作栏删除当接口失败时，气泡确认框不会消失
      });`

**Comment by liaozhiyang** [comment]
```
const getBindValues = computed(() => {
        // update-begin--author:liaozhiyang---date:20231228---for：【issues/936】表格操作栏删除当接口失败时，气泡确认框不会消失
        const result: any = Object.assign(
          {
            okText: t('common.okText'),
            cancelText: t('common.cancelText'),
          },
          { ...props, ...unref(attrs) }
        );
        if (result.onConfirm) {
          const confirm = result.confirm;
          result.onConfirm = () => {
            return new Promise<void>((resolve) => {
              confirm()
                ?.finally(() => {
                  resolve();
                })
                .catch((err) => {
                  console.log(err);
                });
            });
          };
        }
        return result;
        // update-end--author:liaozhiyang---date:20231228---for：【issues/936】表格操作栏删除当接口失败时，气泡确认框不会消失
      });
```

**Comment by liaozhiyang** [comment]
之前那个改法有副作用。
src/components/Button/src/PopConfirmButton.vue 需要回滚
<img width="1439" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/e23af9b5-f054-41a6-bed5-e5af723a7b1e">
```
const getBindValues = computed(() => {
        return Object.assign(
          {
            okText: t('common.okText'),
            cancelText: t('common.cancelText'),
          },
          { ...props, ...unref(attrs) }
        );
      });

```

正确改法：

src/components/Table/src/components/TableAction.vue
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/d0ea77d9-3864-47ef-b81a-1800d19b34f9)

```
const handelConfirm = (fn) => {
        if (typeof fn !== 'function') return fn;
        const anyc = () => {
          return new Promise<void>((resolve) => {
            const result = fn();
            if (Object.prototype.toString.call(result) === '[object Promise]') {
              result
                .finally(() => {
                  resolve();
                })
                .catch((err) => {
                  console.log(err);
                });
            } else {
              resolve();
            }
          });
        };
        return anyc;
      };


```
