### ISSUE TITLE
3.6.1 npm run build 失败

### ISSUE THREAD

**Issue by dahailiu123** [jeecgboot/jeecgboot-vue3#939]
##### 版本号：
3.6.1

##### 问题描述：
我用 online表单生产的代码，没有改动内容
npm run dev ok
npm run build 失败

##### 截图&代码：
![J@R3NPXU0Z@7~UZ6UYE~U51](https://github.com/jeecgboot/jeecgboot-vue3/assets/154294503/d1772cc9-3646-4ca6-9a60-f17299682b71)

 [vite:load-fallback] Could not load C:\Users\Administrator\Downloads\jeecgboot-vue3-3.6.1 (1)\jeecgboot-vue3-3.6.1\src/components/my-componets/my-date.vue (imported by src/views/my/shangpfl/vue-app/AdShangpflForm.vue): ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\jeecgboot-vue3-3.6.1 (1)\jeecgboot-vue3-3.6.1\src\components\my-componets\my-date.vue'

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by heySimonGreen** [comment]
我也遇到了这个问题，提示目录 \src\components\my-componets\my-date.vue 不存在，代码可以运行可以，但打包就是报这个错误。这个怎么解决呀

**Comment by heySimonGreen** [comment]
我自己在下面建了一个名称一模一样的文件，解决了上面的问题，但是新问题又出现了
![微信图片_20231221110807](https://github.com/jeecgboot/jeecgboot-vue3/assets/40664882/cc6c1908-7201-4eb5-8718-ef7bd83a18fb)

**Comment by zhangdaiscott** [comment]
好了  删除生成的uniapp代码
