### ISSUE TITLE
表格、表单示例大全源码

### ISSUE THREAD

**Issue by mengrose** [jeecgboot/jeecgboot-vue3#940]
##### 版本号：
3.6.1

##### 问题描述：
在官网演示的系统中表格、表单示例大全功能，但是在下载的源码中，找不到这两个功能的代码。能否可以把这个两个功能的源码上传到GitHub上，方便初学者参考、学习。

##### 截图&代码：
官网截图
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42018550/5ad53523-9746-4b9e-83d2-a165c0a448f8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
src/views/demo/document
[document.zip](https://github.com/jeecgboot/jeecgboot-vue3/files/13713266/document.zip)
