### ISSUE TITLE
在线仪表盘设计，【统计卡片组件】能否支持total字段左侧标题的文本自定义或者在主标题前面加上额外的前缀？

### ISSUE THREAD

**Issue by z0125** [jeecgboot/jeecgboot-vue3#944]
##### 版本号：

3.6.1

##### 问题描述：

在线仪表盘设计，【统计卡片组件】能否支持total字段左侧标题的文本自定义或者在主标题前面加上额外的前缀？

##### 截图&代码：
<img width="1362" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/20272855/d19947cf-013f-4b38-b971-2af569fa727b">

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/e14b31c2-bf26-4777-8fc7-c91084e094e2)

你改json里面的title不就可以了吗

**Comment by z0125** [comment]
改json里面的title的话，昨上角的标题就一起改了。两个数据指标不一样，左上角的代表周期范围，底部是全量合计，类似首页这边的形式。
<img width="1204" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/20272855/8360a28e-0b31-42df-9c19-69421c4e5381">

**Comment by zhangdaiscott** [comment]
不支持，你的需求不通用

**Comment by z0125** [comment]
这不通用吗？扩展一个参数能自定义底部的标题，没有定义的话使用卡片默认标题，应该有很多人有这个诉求吧，不然怎么区分文案呢

**Comment by z0125** [comment]
那请问首页的示例中底部的标题前面为什么要加一个“总”字呢？
<img width="450" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/20272855/829eb4d7-7955-42bd-b55d-891b181f5225">
