### ISSUE TITLE
BasicTable组件设置默认展开不生效；

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecgboot-vue3#945]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/cc9f5db8-716a-4a54-abc6-4668d9096513)
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/382d0baa-9222-4896-8a53-40d9f80c306c)

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你本地可先按如下修改：
在 src/components/Table/src/BasicTable.vue 文件加上如下图代码：

<img width="882" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/57d27933-80f5-44e2-924e-f40d3b401347">

nextTick(() => {
   getProps.value.defaultExpandAllRows && expandAll();
})

**Comment by caomeibuaichibaicai** [comment]
> 已修复，下一版本发布。 你本地可先按如下修改： 在 src/components/Table/src/BasicTable.vue 文件加上如下图代码：
> 
> <img alt="image" width="882" src="https://private-user-images.githubusercontent.com/8199499/292821291-57d27933-80f5-44e2-924e-f40d3b401347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjE0NzUsIm5iZiI6MTcxNjQ2MTE3NSwicGF0aCI6Ii84MTk5NDk5LzI5MjgyMTI5MS01N2QyNzkzMy04MGY1LTQ0ZTItOTI0ZS1mNDBkM2I0MDEzNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTA0NjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQ3NTg3ZTEwNTg5MmYyMTZjMGQ5YTUzMDZjMDc2ZmU4MDkwOWM0NDJjNmFiMGUyOGJjNDFlOWQxNDA2Y2IwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0SNDLTuXSYYHcmx_GdeVg2q-SsZpPYVMbA09NFyKLXA">
> nextTick(() => { getProps.value.defaultExpandAllRows && expandAll(); })
好像还是没有被修复，表格如果使用api获取表格数据的方法，在获取到数据后，并不会执行这个nextTick方法，我是自己在业务表格里面通过fetch-success事件，自定义触发展开的。。才解决的
`
const fetchSuccess = () => {
  nextTick(() => {
    expandAll();
  })
}
`
