### ISSUE TITLE
开发环境我的组织=》添加已有用户，打开弹窗时一直加载

### ISSUE THREAD

**Issue by Gordon-Liu-315** [jeecgboot/jeecgboot-vue3#95]
##### 版本号：
1.0.0

##### 问题描述：
开发环境我的组织=》添加已有用户，打开弹窗时一直加载，接口数据已返回，但页面一直加载中
删除下面第二张图那些代码就没问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/70005452/172773021-8ee6817c-7034-47dc-a35e-022a283cb660.png)

![ae79170d9270ead5884c94106fda710](https://user-images.githubusercontent.com/70005452/172774134-1eb6935d-602e-475d-a0c1-243f66759c76.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
老bug已修复,更新代码
