### ISSUE TITLE
低代码开发工具完成功能设计后，能否提供将配置信息导出为SQL脚本的功能，以便于向生产环境发布

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#950]
##### 版本号：
3.6.1

##### 问题描述：
在开发环境使用低代码工具（在线表单开发/在线报表配置/报表设计器/仪表盘设计器/）完成一个功能开发后，想将这个功能发布到生产环境，希望这些开发工具都能提供将这个功能导出为SQL脚本的菜单，包括相关的表及配置数据，通过这个SQL脚本将新功能发布到生产环境中。

或者提供一键发布的功能，可以一键将新功能发布到其它的环境中，这样就可以完成开发环境 -> 测试环境 -> 生产环境的逐级发布。

另外，建议这些开发工具提供版本管理功能，以便版本管控及回滚。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://cloud.jeecg.com/page?id=1322087025830039554
