### ISSUE TITLE
希望系统自带的功能页面能统一实现多语言

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#952]
##### 版本号：
3.6.1

##### 问题描述：
系统自带的很多功能，例如【系统管理】下的功能页面等，大多都没有实现多语言，希望官方能统一实现多语言。虽然也可以自己修改来实现，但如果官方对某些功能做了修改后，每次更新都要重新合并和多语言相关的代码，会非常麻烦。

##### 截图&代码：
只用【菜单管理】做为示例：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/bc3bbb03-b718-4d70-9a72-b23fa3289007)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
成本太高，有这需求的人又很少，不采纳
