### ISSUE TITLE
useListPage 公共组件有几处文本未提供本地化

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#954]
##### 版本号：
3.6.1

##### 问题描述：
useListPage 公共组件有几处文本未提供本地化

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/a625c93d-9ee6-44fa-8c33-b33b0f29e5c1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己改即可
