### ISSUE TITLE
数据字典的字典列表对话框中，按钮排列错位

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecgboot-vue3#958]
##### 版本号：
3.6.1

##### 问题描述：
中文语言正常，切换到英文语言后，界面上的按钮布局错误。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/f2ab0205-e8fe-4481-9619-2e1cf42373a8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy
