### ISSUE TITLE
配置好的微应用 在主应用中配置配置路由菜单展示

### ISSUE THREAD

**Issue by dmggs** [jeecgboot/jeecgboot-vue3#959]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/51844048/720ed917-db42-4b5b-9d2e-8ca865890c81)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy
