### ISSUE TITLE
JTreeSelect 下拉树自定义组件 查询不到数据

### ISSUE THREAD

**Issue by lyh33228** [jeecgboot/jeecgboot-vue3#96]
##### 版本号：
1.2.0

##### 问题描述：
下拉树 JTreeSelect 自定义组件 刷新不到数据

##### 截图&代码：

![image](https://user-images.githubusercontent.com/100585354/172968709-436e303a-bbca-4fe4-b0fe-ca426845ffa6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
怎么配置的

**Comment by lyh33228** [comment]
直接看列子 没有数据出来  ，没有进行配置 ，1.0的时候自动出来的吗

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
