### ISSUE TITLE
高级查询, 还原历史查询时不显示中文的字段名

### ISSUE THREAD

**Issue by hareGuu** [jeecgboot/jeecgboot-vue3#962]
##### 版本号：
vue3

##### 问题描述：
高级查询, 使用了从表, 选择了查询项后保存本次查询, 第二次查询, 还原历史查询时, 显示的是数据库中的表名和字段名, 而不是对应的中文名称, 同时, 下拉项也不可用了

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65012961/f25310b5-4f34-4783-af6a-30f7d5b2df30)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65012961/747fd15b-fd00-4b79-b62a-999af4a138f7)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/65012961/78a934a1-9990-46ec-93b2-22af1cb52d27)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
zy

**Comment by hareGuu** [comment]
> Zy

这是什么意思？

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
