### ISSUE TITLE
jeecgboot-vue3项目无法指定--mode development

### ISSUE THREAD

**Issue by zyh-akk** [jeecgboot/jeecgboot-vue3#964]
##### 截图&代码：
![WechatIMG67](https://github.com/jeecgboot/jeecgboot-vue3/assets/21376277/a9e4010d-7fa4-42c5-913a-3185d46f441e)
![WechatIMG68](https://github.com/jeecgboot/jeecgboot-vue3/assets/21376277/46f7b1f0-2a94-430f-9bf3-6fd157780851)

**Comment by zhangdaiscott** [comment]
目前不支持
