### ISSUE TITLE
升级到vite4.5.1后，打包失败

### ISSUE THREAD

**Issue by yuanguohao45** [jeecgboot/jeecgboot-vue3#965]
##### 版本号：
3.6.1

##### 问题描述：
升级到vite4.5.1后 打包报错如下图
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/42180636/e068279b-e553-4762-aa1b-e1d407596620)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
测试并没有问题
