### ISSUE TITLE
这个表名大写的导致发送消息测试失败了

### ISSUE THREAD

**Issue by wongzeqi** [jeecgboot/jeecgboot-vue3#967]
##### 截图&代码：

<img width="711" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/27459051/a4f2dd16-748d-4c8b-8e6a-ad1bb513be4a">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
补充相关信息
