### ISSUE TITLE
新角色新用户，导航至“账户设置” 404 （/system/usersetting)

### ISSUE THREAD

**Issue by PysomeZh** [jeecgboot/jeecgboot-vue3#969]
##### 版本号：
jeecgboot-vue3@3.6.1

##### 问题描述：
- 新建一个普通用户，分配了新建的角色。 登录之后，右上角“账户设置“ 不可用。
   - 新角色授予 ”系统管理“全部功能。（和 自建的两个业务管理功能a b，如下图）
- 切换为管理员账户则，功能正常。

##### 截图&代码：
角色拥有的功能权限
<img width="420" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/93236088/042311c6-bb67-401d-ad32-2baf4b18190c">

<img width="392" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/93236088/3c87a75a-c5b5-4ee1-add1-200585e91c85">
<img width="976" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/93236088/44c93c84-ef34-4e36-a9d5-0253c35ae3d7">

<img width="1163" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/93236088/e3c951fc-f2a1-419a-93b2-0052411789cb">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
刚测可以，你确保角色授权正确
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/974c0d21-2ff5-4fe7-a335-57ca4194620e)
