### ISSUE TITLE
jeecgboot3.5.4 打包上线后不能进入登录界面

### ISSUE THREAD

**Issue by TryEveryday** [jeecgboot/jeecgboot-vue3#973]
##### 版本号：

3.5.4
##### 问题描述：
jeecgboot3.5.4 打包上线后不能进入登录界面：报错Uncaught SyntaxError: Unexpected token '<' (at _app.config.js?v=3.5.4-1702868988687:1:1)；ncaught TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'e' as it is undefined.

##### 截图&代码：

![微信截图_20240103153958](https://github.com/jeecgboot/jeecgboot-vue3/assets/86995606/b6d8efcd-4aaa-47c8-856b-19a573ab9b04)

**Comment by zhangdaiscott** [comment]
1、打包的时候clean下
2、清下浏览器缓存
