### ISSUE TITLE
BasicTable行编辑（editRow、record.onEdit）,reload之后无法拿到二次编辑的值

### ISSUE THREAD

**Issue by HaoyuLee** [jeecgboot/jeecgboot-vue3#974]
##### 截图&代码：

官网示例可复现
1. 行编辑并保存
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37102468/32022ca4-3c1f-4f01-97c2-3fc91e6cb3dc)
2. reload 列表
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37102468/c8b3b9c4-836e-4cb9-b143-fb25831539e9)
3. 二次编辑-保存
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37102468/be5563e1-ecba-499d-a5ba-6ad5ece51b16)

**Comment by HaoyuLee** [comment]
可参考vben issues
[https://github.com/vbenjs/vue-vben-admin/issues/2384](https://github.com/vbenjs/vue-vben-admin/issues/2384)

**Comment by zhangdaiscott** [comment]
补充版本号

**Comment by HaoyuLee** [comment]
> 补充版本号

3.5.0，目前官网示例也存在这个问题

**Comment by zhangdaiscott** [comment]
zy

**Comment by HaoyuLee** [comment]
> zy

zy啥意思
补充一下，vben官方实例没发现这个问题

**Comment by liaozhiyang** [comment]
![截图01](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/3dadd785-1847-4c99-ad9e-acc65b428365)
在 comp/table/editRowTable （可编辑行）页面，我按照你的操作试了，debugger能看到 editValueRefs 属性啊，其他函数也存在record上面。有更详细的复现步骤吗？

**Comment by liaozhiyang** [comment]
在 comp/table/editRowTable （可编辑行）页面，我按照你的操作试了，debugger能看到 editValueRefs 属性啊，其他函数也存在record上面。有更详细的复现步骤吗？
视屏大于10M，上传不了。这是截图。两次都能拿到 editValueRefs ，中途有有用工具栏的刷新
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/0e3f16b1-110c-4187-8af0-730c2737335e)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/90f69c7b-08cd-44e5-bd79-499c0c7c8c08)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/a761a463-9f25-48cc-8b78-2ba24795d798)

**Comment by HaoyuLee** [comment]
> 在 comp/table/editRowTable （可编辑行）页面，我按照你的操作试了，debugger能看到 editValueRefs 属性啊，其他函数也存在record上面。有更详细的复现步骤吗？ 视屏大于10M，上传不了。这是截图。两次都能拿到 editValueRefs ，中途有有用工具栏的刷新 ![image](https://private-user-images.githubusercontent.com/8199499/294855342-0e3f16b1-110c-4187-8af0-730c2737335e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjQ5NzcsIm5iZiI6MTcwNTAyNDY3NywicGF0aCI6Ii84MTk5NDk5LzI5NDg1NTM0Mi0wZTNmMTZiMS0xMTBjLTQxODctOGFmMC03MzBjMjczNzMzNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDE1NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWFlZjQwMTc3NmVlODBhODRiMjFhYjExYzg1MzIxYTkwNTQ1MGI0YTUzOWVjMDY2NjBmOGI2NTZkNDMzMmNiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VLHMWMgQJFA04gnF90mdrbet8GR3fNuzhgrRmLKHMeU) ![image](https://private-user-images.githubusercontent.com/8199499/294855871-90f69c7b-08cd-44e5-bd79-499c0c7c8c08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjQ5NzcsIm5iZiI6MTcwNTAyNDY3NywicGF0aCI6Ii84MTk5NDk5LzI5NDg1NTg3MS05MGY2OWM3Yi0wOGNkLTQ0ZTUtYmQ3OS00OTljMGM3YzhjMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDE1NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRmMGZjMDg3MmI3MzA5ZjU0MWYxNTUzMmVmNjkwYTJkNTI4MGJiNDk4ODNjNGE2NmU0OGIzMjFmZWJiZjc2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iP7BZTSFA_7Pr2DDG67R6nABof53pRWjaaDUO0SzYGI) ![image](https://private-user-images.githubusercontent.com/8199499/294855524-a761a463-9f25-48cc-8b78-2ba24795d798.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjQ5NzcsIm5iZiI6MTcwNTAyNDY3NywicGF0aCI6Ii84MTk5NDk5LzI5NDg1NTUyNC1hNzYxYTQ2My05ZjI1LTQ4Y2MtOGI3OC0yYmEyNDc5NWQ3OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDE1NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5OWMzM2Q0ZmYzOGNmMDg5MWIzN2RiMzc2MDNkMjVlNWJjNzhhNTM0MDg5ZjYxNzJiY2Y3NDJkOGRiYjI1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h6Bf6MD_IkO_cTM4SS15H5Bmommk7iAnj4i3ef8ReMg)

示例项目中的【可编辑行页面】确实没发现这个问题。您需要在【表格示例大全页面】->【可编辑行】复现。

**Comment by HaoyuLee** [comment]
> 在 comp/table/editRowTable （可编辑行）页面，我按照你的操作试了，debugger能看到 editValueRefs 属性啊，其他函数也存在record上面。有更详细的复现步骤吗？ 视屏大于10M，上传不了。这是截图。两次都能拿到 editValueRefs ，中途有有用工具栏的刷新 ![image](https://private-user-images.githubusercontent.com/8199499/294855342-0e3f16b1-110c-4187-8af0-730c2737335e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjQ5NzcsIm5iZiI6MTcwNTAyNDY3NywicGF0aCI6Ii84MTk5NDk5LzI5NDg1NTM0Mi0wZTNmMTZiMS0xMTBjLTQxODctOGFmMC03MzBjMjczNzMzNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDE1NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWFlZjQwMTc3NmVlODBhODRiMjFhYjExYzg1MzIxYTkwNTQ1MGI0YTUzOWVjMDY2NjBmOGI2NTZkNDMzMmNiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VLHMWMgQJFA04gnF90mdrbet8GR3fNuzhgrRmLKHMeU) ![image](https://private-user-images.githubusercontent.com/8199499/294855871-90f69c7b-08cd-44e5-bd79-499c0c7c8c08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjQ5NzcsIm5iZiI6MTcwNTAyNDY3NywicGF0aCI6Ii84MTk5NDk5LzI5NDg1NTg3MS05MGY2OWM3Yi0wOGNkLTQ0ZTUtYmQ3OS00OTljMGM3YzhjMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDE1NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRmMGZjMDg3MmI3MzA5ZjU0MWYxNTUzMmVmNjkwYTJkNTI4MGJiNDk4ODNjNGE2NmU0OGIzMjFmZWJiZjc2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iP7BZTSFA_7Pr2DDG67R6nABof53pRWjaaDUO0SzYGI) ![image](https://private-user-images.githubusercontent.com/8199499/294855524-a761a463-9f25-48cc-8b78-2ba24795d798.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjQ5NzcsIm5iZiI6MTcwNTAyNDY3NywicGF0aCI6Ii84MTk5NDk5LzI5NDg1NTUyNC1hNzYxYTQ2My05ZjI1LTQ4Y2MtOGI3OC0yYmEyNDc5NWQ3OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDE1NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5OWMzM2Q0ZmYzOGNmMDg5MWIzN2RiMzc2MDNkMjVlNWJjNzhhNTM0MDg5ZjYxNzJiY2Y3NDJkOGRiYjI1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h6Bf6MD_IkO_cTM4SS15H5Bmommk7iAnj4i3ef8ReMg)

```
```

**Comment by HaoyuLee** [comment]
刚刚我用官方仓库代码复现，**直接将登录页代码替换为前端文档中的示例代码**
复现代码如下
```
<template>
  <div class="p-4">
    <BasicTable @register="registerTable" @edit-change="onEditChange">
      <template #action="{ record, column }">
        <TableAction :actions="createActions(record, column)" />
      </template>
    </BasicTable>
  </div>
</template>
<script lang="ts">
  import { defineComponent, ref } from 'vue';
  import { BasicTable, useTable, TableAction, BasicColumn, ActionItem, EditRecordRow } from '/@/components/Table';
  import { optionsListApi } from '/@/api/demo/select';

  import { demoListApi } from '/@/api/demo/table';
  import { treeOptionsListApi } from '/@/api/demo/tree';
  import { cloneDeep } from 'lodash-es';
  import { useMessage } from '/@/hooks/web/useMessage';
  import { useListPage } from '/@/hooks/system/useListPage';

  const columns: BasicColumn[] = [
    {
      title: '输入框',
      dataIndex: 'name',
      editRow: true,
      editComponentProps: {
        prefix: '$',
      },
      width: 150,
    },
    {
      title: '默认输入状态',
      dataIndex: 'name7',
      editRow: true,
      width: 150,
    },
    {
      title: '输入框校验',
      dataIndex: 'name1',
      editRow: true,
      align: 'left',
      // 默认必填校验
      editRule: true,
      width: 150,
    },
    {
      title: '输入框函数校验',
      dataIndex: 'name2',
      editRow: true,
      align: 'right',
      editRule: async (text) => {
        if (text === '2') {
          return '不能输入该值';
        }
        return '';
      },
    },
    {
      title: '数字输入框',
      dataIndex: 'id',
      editRow: true,
      editRule: true,
      editComponent: 'InputNumber',
      width: 150,
    },
    {
      title: '下拉框',
      dataIndex: 'name3',
      editRow: true,
      editComponent: 'Select',
      editComponentProps: {
        options: [
          {
            label: 'Option1',
            value: '1',
          },
          {
            label: 'Option2',
            value: '2',
          },
          {
            label: 'Option3',
            value: '3',
          },
        ],
      },
      width: 200,
    },
    {
      title: '远程下拉',
      dataIndex: 'name4',
      editRow: true,
      editComponent: 'ApiSelect',
      editComponentProps: {
        api: optionsListApi,
        resultField: 'list',
        labelField: 'name',
        valueField: 'id',
      },
      width: 200,
    },
    {
      title: '远程下拉树',
      dataIndex: 'name8',
      editRow: true,
      editComponent: 'ApiTreeSelect',
      editRule: false,
      editComponentProps: {
        api: treeOptionsListApi,
        resultField: 'list',
      },
      width: 200,
    },
    {
      title: '日期选择',
      dataIndex: 'date',
      editRow: true,
      editComponent: 'DatePicker',
      editComponentProps: {
        valueFormat: 'YYYY-MM-DD',
        format: 'YYYY-MM-DD',
      },
      width: 150,
    },
    {
      title: '时间选择',
      dataIndex: 'time',
      editRow: true,
      editComponent: 'TimePicker',
      editComponentProps: {
        valueFormat: 'HH:mm',
        format: 'HH:mm',
      },
      width: 100,
    },
    {
      title: '勾选框',
      dataIndex: 'name5',
      editRow: true,

      editComponent: 'Checkbox',
      editValueMap: (value) => {
        return value ? '是' : '否';
      },
      width: 100,
    },
    {
      title: '开关',
      dataIndex: 'name6',
      editRow: true,
      editComponent: 'Switch',
      editValueMap: (value) => {
        return value ? '开' : '关';
      },
      width: 100,
    },
  ];
  export default defineComponent({
    components: { BasicTable, TableAction },
    setup() {
      const { createMessage: msg } = useMessage();
      const currentEditKeyRef = ref('');

      const { tableContext } = useListPage({
        designScope: 'basic-table-demo',
        tableProps: {
          title: '可编辑行示例',
          api: demoListApi,
          columns: columns,
          showIndexColumn: false,
          showTableSetting: true,
          tableSetting: { fullScreen: true },
          actionColumn: {
            width: 160,
            title: 'Action',
            dataIndex: 'action',
            slots: { customRender: 'action' },
          },
        },
      });

      //BasicTable绑定注册
      const [registerTable] = tableContext;

      function handleEdit(record: EditRecordRow) {
        currentEditKeyRef.value = record.key;
        record.onEdit?.(true);
      }

      function handleCancel(record: EditRecordRow) {
        currentEditKeyRef.value = '';
        record.onEdit?.(false, false);
      }

      async function handleSave(record: EditRecordRow) {
        /**
         * 复现步骤
         * 1. 首次正常编辑、保存
         * 2. 点击右上角刷新列表
         * 3. 再次编辑、保存，问题复现
         * */
        debugger;
        // 校验
        msg.loading({ content: '正在保存...', duration: 0, key: 'saving' });
        const valid = await record.onValid?.();
        if (valid) {
          try {
            const data = cloneDeep(record.editValueRefs);
            console.log(data);
            //TODO 此处将数据提交给服务器保存
            // ...
            // 保存之后提交编辑状态
            const pass = await record.onEdit?.(false, true);
            if (pass) {
              currentEditKeyRef.value = '';
            }
            msg.success({ content: '数据已保存', key: 'saving' });
          } catch (error) {
            msg.error({ content: '保存失败', key: 'saving' });
          }
        } else {
          msg.error({ content: '请填写正确的数据', key: 'saving' });
        }
      }

      function createActions(record: EditRecordRow, column: BasicColumn): ActionItem[] {
        if (!record.editable) {
          return [
            {
              label: '编辑',
              disabled: currentEditKeyRef.value ? currentEditKeyRef.value !== record.key : false,
              onClick: handleEdit.bind(null, record),
            },
          ];
        }
        return [
          {
            label: '保存',
            onClick: handleSave.bind(null, record, column),
          },
          {
            label: '取消',
            popConfirm: {
              title: '是否取消编辑',
              confirm: handleCancel.bind(null, record, column),
            },
          },
        ];
      }

      function onEditChange({ column, value, record }) {
        // 本例
        if (column.dataIndex === 'id') {
          record.editValueRefs.name4.value = `${value}`;
        }
        console.log(column, value, record);
      }

      return {
        registerTable,
        handleEdit,
        createActions,
        onEditChange,
      };
    },
  });
</script>

```

**Comment by HaoyuLee** [comment]
前几天我已经找到原因，在我们代码中自己解决了一下。
关键代码位置
```
// src/components/Table/src/components/editable/EditableCell.vue  348行
// 应该是只有该组件首次渲染时才会附加editValueRefs等属性，reload之后dataSource重新赋值，但是此处代码没有重新执行，也就丢失了这些属性
if (props.column.dataIndex) {
  if (!props.record.editValueRefs) props.record.editValueRefs = {};
  props.record.editValueRefs[props.column.dataIndex] = currentValueRef;
}
```

**Comment by HaoyuLee** [comment]
```

// 编辑状态下，表单值发生变化，检查record的editValueRefs属性存不存在（用于解决目前table组件再relaod之后丢失editValueRefs的问题）
watchEffect(() => {
  if (props.record) {
    if (!props.record.editValueRefs) props.record.editValueRefs = {};
    props.record.editValueRefs[props.column.dataIndex] = currentValueRef;
  }
      });
```

**Comment by liaozhiyang** [comment]
按照你所说的操作，从官方仓库下载的源码，在登录页面替换成你的代码，中间刷新然后再保存，editValueRefs没丢失呢
<img width="730" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/6f61bfce-90d7-4be4-8c20-48840c837380">

**Comment by april-zhy** [comment]
> 前几天我已经找到原因，在我们代码中自己解决了一下。 关键代码位置
> 
> ```
> // src/components/Table/src/components/editable/EditableCell.vue  348行
> // 应该是只有该组件首次渲染时才会附加editValueRefs等属性，reload之后dataSource重新赋值，但是此处代码没有重新执行，也就丢失了这些属性
> if (props.column.dataIndex) {
>   if (!props.record.editValueRefs) props.record.editValueRefs = {};
>   props.record.editValueRefs[props.column.dataIndex] = currentValueRef;
> }
> ```

我这边也有同样问题，在配置表格时，去掉“rowKey”配置，或者设置空，就能正常保存了。应该是设置了Rowkey之后，Vue的diff算法原因，record的部分方法没有追加上去（ submitCbs、validCbs、CancelCbs等），所以导致valid一直为false

@zhangdaiscott 烦请官方解决一下呢

**Comment by liaozhiyang** [comment]
> > 前几天我已经找到原因，在我们代码中自己解决了一下。 关键代码位置
> > ```
> > // src/components/Table/src/components/editable/EditableCell.vue  348行
> > // 应该是只有该组件首次渲染时才会附加editValueRefs等属性，reload之后dataSource重新赋值，但是此处代码没有重新执行，也就丢失了这些属性
> > if (props.column.dataIndex) {
> >   if (!props.record.editValueRefs) props.record.editValueRefs = {};
> >   props.record.editValueRefs[props.column.dataIndex] = currentValueRef;
> > }
> > ```
> 
> 我这边也有同样问题，在配置表格时，去掉“rowKey”配置，或者设置空，就能正常保存了。应该是设置了Rowkey之后，Vue的diff算法原因，record的部分方法没有追加上去（ submitCbs、validCbs、CancelCbs等），所以导致valid一直为false
> 
> @zhangdaiscott 烦请官方解决一下呢






按照所说没多方测试没复现。
你那边也是下方代码逻辑吧？你下方代码贴到项目中看是否正常？
<img width="531" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/cd806d3b-3828-4802-b8a4-f5554992c01e">
<img width="743" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/03574ce3-d676-4987-ac46-6e0f2c7c4bea">


```
<template>
  <div class="p-4">
    <BasicTable @register="registerTable" @edit-change="onEditChange">
      <template #action="{ record, column }">
        <TableAction :actions="createActions(record, column)" />
      </template>
    </BasicTable>
  </div>
</template>
<script lang="ts">
  import { defineComponent, ref } from 'vue';
  import { BasicTable, useTable, TableAction, BasicColumn, ActionItem, EditRecordRow } from '/@/components/Table';
  import { optionsListApi } from '/@/api/demo/select';

  import { demoListApi } from '/@/api/demo/table';
  import { treeOptionsListApi } from '/@/api/demo/tree';
  import { cloneDeep } from 'lodash-es';
  import { useMessage } from '/@/hooks/web/useMessage';

  const columns: BasicColumn[] = [
    {
      title: '输入框',
      dataIndex: 'name',
      editRow: true,
      editComponentProps: {
        prefix: '$',
      },
      width: 150,
    },
    {
      title: '默认输入状态',
      dataIndex: 'name7',
      editRow: true,
      width: 150,
    },
    {
      title: '输入框校验',
      dataIndex: 'name1',
      editRow: true,
      align: 'left',
      // 默认必填校验
      editRule: true,
      width: 150,
    },
    {
      title: '输入框函数校验',
      dataIndex: 'name2',
      editRow: true,
      align: 'right',
      editRule: async (text) => {
        if (text === '2') {
          return '不能输入该值';
        }
        return '';
      },
    },
    {
      title: '数字输入框',
      dataIndex: 'id',
      editRow: true,
      editRule: true,
      editComponent: 'InputNumber',
      width: 150,
    },
    {
      title: '下拉框',
      dataIndex: 'name3',
      editRow: true,
      editComponent: 'Select',
      editComponentProps: {
        options: [
          {
            label: 'Option1',
            value: '1',
          },
          {
            label: 'Option2',
            value: '2',
          },
          {
            label: 'Option3',
            value: '3',
          },
        ],
      },
      width: 200,
    },
    {
      title: '远程下拉',
      dataIndex: 'name4',
      editRow: true,
      editComponent: 'ApiSelect',
      editComponentProps: {
        api: optionsListApi,
        resultField: 'list',
        labelField: 'name',
        valueField: 'id',
      },
      width: 200,
    },
    {
      title: '远程下拉树',
      dataIndex: 'name8',
      editRow: true,
      editComponent: 'ApiTreeSelect',
      editRule: false,
      editComponentProps: {
        api: treeOptionsListApi,
        resultField: 'list',
      },
      width: 200,
    },
    {
      title: '日期选择',
      dataIndex: 'date',
      editRow: true,
      editComponent: 'DatePicker',
      editComponentProps: {
        valueFormat: 'YYYY-MM-DD',
        format: 'YYYY-MM-DD',
      },
      width: 150,
    },
    {
      title: '时间选择',
      dataIndex: 'time',
      editRow: true,
      editComponent: 'TimePicker',
      editComponentProps: {
        valueFormat: 'HH:mm',
        format: 'HH:mm',
      },
      width: 100,
    },
    {
      title: '勾选框',
      dataIndex: 'name5',
      editRow: true,

      editComponent: 'Checkbox',
      editValueMap: (value) => {
        return value ? '是' : '否';
      },
      width: 100,
    },
    {
      title: '开关',
      dataIndex: 'name6',
      editRow: true,
      editComponent: 'Switch',
      editValueMap: (value) => {
        return value ? '开' : '关';
      },
      width: 100,
    },
  ];
  export default defineComponent({
    components: { BasicTable, TableAction },
    setup() {
      const { createMessage: msg } = useMessage();
      const currentEditKeyRef = ref('');
      const tableContext = useTable({
        title: '可编辑行示例',
        titleHelpMessage: ['本例中修改[数字输入框]这一列时，同一行的[远程下拉]列的当前编辑数据也会同步发生改变'],
        api: demoListApi,
        columns: columns,
        showIndexColumn: false,
        showTableSetting: true,
        tableSetting: { fullScreen: true },
        rowKey: 'id',
        actionColumn: {
          width: 160,
          title: 'Action',
          dataIndex: 'action',
          slots: { customRender: 'action' },
        },
      });
      const [registerTable, { reload }] = tableContext;

      function handleEdit(record: EditRecordRow) {
        currentEditKeyRef.value = record.key;
        record.onEdit?.(true);
      }

      function handleCancel(record: EditRecordRow) {
        currentEditKeyRef.value = '';
        record.onEdit?.(false, false);
      }

      async function handleSave(record: EditRecordRow) {
        // 校验
        msg.loading({ content: '正在保存...', duration: 0, key: 'saving' });
        const valid = await record.onValid?.();
        if (valid) {
          try {
            const data = cloneDeep(record.editValueRefs);
            console.log('保存的数据:==>', data);
            //TODO 此处将数据提交给服务器保存
            // ...
            // 保存之后提交编辑状态
            const pass = await record.onEdit?.(false, true);
            if (pass) {
              currentEditKeyRef.value = '';
            }
            msg.success({ content: '数据已保存', key: 'saving' });
            reload();
          } catch (error) {
            msg.error({ content: '保存失败', key: 'saving' });
          }
        } else {
          msg.error({ content: '请填写正确的数据', key: 'saving' });
        }
      }

      function createActions(record: EditRecordRow, column: BasicColumn): ActionItem[] {
        if (!record.editable) {
          return [
            {
              label: '编辑',
              disabled: currentEditKeyRef.value ? currentEditKeyRef.value !== record.key : false,
              onClick: handleEdit.bind(null, record),
            },
          ];
        }
        return [
          {
            label: '保存',
            onClick: handleSave.bind(null, record, column),
          },
          {
            label: '取消',
            popConfirm: {
              title: '是否取消编辑',
              confirm: handleCancel.bind(null, record, column),
            },
          },
        ];
      }

      function onEditChange({ column, value, record }) {
        // 本例
        if (column.dataIndex === 'id') {
          record.editValueRefs.name4.value = `${value}`;
        }
        console.log(column, value, record);
      }

      return {
        registerTable,
        handleEdit,
        createActions,
        onEditChange,
      };
    },
  });
</script>

```
