### ISSUE TITLE
点击退出系统，弹出的温馨提示无法关闭

### ISSUE THREAD

**Issue by 18237966658** [jeecgboot/jeecgboot-vue3#976]
##### 版本号：
V 3.6.2

##### 问题描述：
点击退出系统，弹出的温馨提示无法关闭，请问createConfirm创建的弹框该如何关闭？ 
创建的弹框点击取消没有反应，点击确定 退出登录后 这个弹窗也不会消失

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50265705/60b4abc3-7459-4225-8522-bae87ef30c8d)
 /**
     * 退出询问
     */
    confirmLoginOut() {
      const { createConfirm } = useMessage();
      const { t } = useI18n();
      createConfirm({
        iconType: 'warning',
        title: t('sys.app.logoutTip'),
        content: t('sys.app.logoutMessage'),
        onOk: async () => {
          await this.logout(true);
        }
      });
    },

**Comment by yuanguohao45** [comment]
同问，所有的createConfirm ，点击任何按钮都关闭不了

**Comment by zhangdaiscott** [comment]
你是增量升级还是下载的全新代码？
> 增量升级，需要删除依赖，重新install，并clean:缓存再启动
我这边测试无问题

**Comment by 18237966658** [comment]
> 你是增量升级还是下载的全新代码？
> 
> > 增量升级，需要删除依赖，重新install，并clean:缓存再启动
> > 我这边测试无问题

我这边是今天上午克隆的 2024-01-03 19:44 最新一次提交的代码

**Comment by zhangdaiscott** [comment]
删除依赖，重新install，并clean:缓存再启动

我这边测没有问题

**Comment by 18237966658** [comment]
> 同问，所有的createConfirm ，点击任何按钮都关闭不了

你那边删除依赖，重新install，并clean:缓存再启动 可以吗？  我这边刚试了 还是不行


> 删除依赖，重新install，并clean:缓存再启动
> 
> 我这边测没有问题

按照您的步骤，删除了node_modules  重新 yarn install  然后  yarn cache clean  最后启动  点击退出时候的弹窗点击取消还是没有任何反应，控制台也没有报错

**Comment by 18237966658** [comment]
> 按照您的步骤，删除了node_modules 重新 yarn install 然后 yarn cache clean 最后启动 点击退出时候的弹窗点击取消还是没有任何反应，控制台也没有报错

**Comment by 18237966658** [comment]
> 删除依赖，重新install，并clean:缓存再启动
> 
> 我这边测没有问题

按照您的步骤，删除了node_modules 重新 yarn install 然后 yarn cache clean 最后启动 点击退出时候的弹窗点击取消还是没有任何反应，控制台也没有报错

**Comment by 18237966658** [comment]
> 删除依赖，重新install，并clean:缓存再启动
> 
> 我这边测没有问题

我切换到 V3.6.0版本也是这个问题，会不会跟环境有关？我的node版本是v18.13.0

**Comment by zhangdaiscott** [comment]
好像是vue版本号问题，固定版本号3.3.4就好了
https://github.com/jeecgboot/jeecg-boot/issues/5466

**Comment by 18237966658** [comment]
> 好像是vue版本号问题，固定版本号3.3.4就好了 [jeecgboot/jeecg-boot#5466](https://github.com/jeecgboot/jeecg-boot/issues/5466)

OK   固定版本号之后解决了  谢谢

**Comment by xinSanta** [comment]
> 同问，所有的createConfirm ，点击任何按钮都关闭不了

你最后解决了吗？这两天我也出现了这个问题
