### ISSUE TITLE
最新版多选框选择无法勾中

### ISSUE THREAD

**Issue by 191474639** [jeecgboot/jeecgboot-vue3#977]
##### 版本号：
3.6.2

##### 问题描述：
多选框选择无法勾中

##### 截图&代码：

![4c42bc0fb77bb03720e7ac8b99960f3a](https://github.com/jeecgboot/jeecgboot-vue3/assets/26876543/c76f1d99-8724-4a79-a072-fbd1dfc17d46)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 191474639** [comment]
![5bef807fa2873c5bfc2d33d1c6290eb8](https://github.com/jeecgboot/jeecgboot-vue3/assets/26876543/fb03eb2a-4984-40bb-bd37-f38518ffcd41)

**Comment by zhangdaiscott** [comment]
测试没问题，你是合并升级的？还是直接下载的最新代码

**Comment by 191474639** [comment]
先是合并不行，然后重新建了一个目录拉了代码（没有合并）还是一样的

**Comment by 18237966658** [comment]
> 先是合并不行，然后重新建了一个目录拉了代码（没有合并）还是一样的

老兄 我这边也有这个问题，你试试你那边点退出登录  点击取消按钮 那个弹出框会不会消失？

**Comment by zhangdaiscott** [comment]
好像是vue版本号问题，固定版本号3.3.4就好了
https://github.com/jeecgboot/jeecg-boot/issues/5466

**Comment by cuitiangang** [comment]
![ce880d0f58e584847ed3b59cd56ac56](https://github.com/jeecgboot/jeecgboot-vue3/assets/50402322/af1a63e4-7975-40bc-92d0-b967ddf70a3a)
vue的版本号固定了 3.3.4了  但是还是不行，我这个是分页参数切换成80条或者100条 就出现这种问题 只显示三个多选框了
