### ISSUE TITLE
部门管理新增之后，我的部门没有任何显示

### ISSUE THREAD

**Issue by rsjannle** [jeecgboot/jeecgboot-vue3#978]
##### 版本号：
jeecg-boot-master当前版本 v3.6.1 

##### 问题描述：
问题一：
部门管理新增之后，我的部门没有任何显示
后端报错
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/108064155/a2e3698b-c89b-4196-9ef5-b9d96003060e)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/108064155/29848a96-44a0-451f-a500-35c4f5dabb06)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/108064155/a1205d8d-ab4a-4858-a4d5-61dc48109d9c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是增量升级还是下载的全新代码？

我这边测试无问题

**Comment by hoperunChen** [comment]
「部门管理新增之后，我的部门没有任何显示」：我的部门只会显示当前登录用户负责的部门，如果当前用户没有关联负责部门，那么“我的部门”页面将不显示数据。请确保您当前登录用户有“负责部门”。
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/13013558/d1b81108-5e5c-41fe-bdad-54f4c71a58b9)

**Comment by rsjannle** [comment]
已解决，借鉴 [wongzeqi](https://github.com/wongzeqi)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/108064155/59157a83-c4ec-4524-8c28-9f5c48e72481)
