### ISSUE TITLE
BasicForm组件表单折叠会出现闪烁问题

### ISSUE THREAD

**Issue by meixueke** [jeecgboot/jeecgboot-vue3#981]
##### 版本号：
3.5.3

##### 问题描述：
打开页面会先出现图1，然后很快变为图2样式
页面刚进去他没有折叠，这个问题有办法解决吗

##### 截图&代码：
![图1](https://github.com/jeecgboot/jeecgboot-vue3/assets/155701279/e6a3362b-ccc0-427b-940e-393baed4f3c1)
![图2](https://github.com/jeecgboot/jeecgboot-vue3/assets/155701279/46a85dd5-cc86-4e21-95de-25fd5f1cc179)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
最新版有这问题吗
