### ISSUE TITLE
表格列排序问题

### ISSUE THREAD

**Issue by zhangwenqi997** [jeecgboot/jeecgboot-vue3#983]
##### 问题描述：
当表格进行列排序时，表格列会隐藏，重新刷新浏览器表格列会出现，但是再次进行列的排序还是会隐藏，请问是什么原因？

##### 截图&代码：

![1704681597173](https://github.com/jeecgboot/jeecgboot-vue3/assets/54975511/f828a691-3e3c-45a9-bf8e-316ad3140aa0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/984
