### ISSUE TITLE
表格列拖拽显示问题

### ISSUE THREAD

**Issue by zhangwenqi997** [jeecgboot/jeecgboot-vue3#984]
##### 问题描述：
当“状态”一列隐藏后，刷新浏览器，“状态”会显示在最上方；再次进行选中后，进行拖拽，“状态”一列没有显示在列表，需重新加载表格才会出现
![1704694634263](https://github.com/jeecgboot/jeecgboot-vue3/assets/54975511/c55f45c0-069f-46fc-9a3b-b2a892a0e3c2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级到最新版，或者参考提交的日志修复
