### ISSUE TITLE
表单按钮为什么不在一行上显示

### ISSUE THREAD

**Issue by dongyunsen** [jeecgboot/jeecgboot-vue3#985]
![微信图片_20240108153840](https://github.com/jeecgboot/jeecgboot-vue3/assets/58757576/e965f3f6-23c7-4737-97c3-941c06620066)

**Comment by zhangdaiscott** [comment]
收录 zy

**Comment by liaozhiyang** [comment]
你是把例子中的actionColOptions删除了吧？删除之后就走的是默认的span:4。例子中的span是个8，也改成8即可。然后wrapperCol设置成null，去掉 actionColOptions 中的响应式。
<img width="695" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/7a805e38-8bf5-43d7-b3b0-410a83522610">

你按如下配置试试：

<img width="709" alt="image" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/2cfb29a3-0a39-486f-8381-961867e0e6f7">

**Comment by dongyunsen** [comment]
没改任何东西，下载下来的代码直接跑的

**Comment by dongyunsen** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/58757576/01498e2b-da72-44aa-bbcb-b8f760e879c1)

**Comment by dongyunsen** [comment]
加 wrapperCol: null, 有用

**Comment by dongyunsen** [comment]
问题解决了，修改表单组件，将"width:100%"改为“width:250px”，如图
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/58757576/e9b66cf0-4fc1-4cf6-a704-1c32da320cd6)

**Comment by dongyunsen** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/58757576/360f1ce9-e7d8-4483-a156-203154b34dce)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/58757576/6f7be6c5-3701-4b5e-976f-40677e5ae985)
