### ISSUE TITLE
pnpm下载失败

### ISSUE THREAD

**Issue by yinxingen** [jeecgboot/jeecgboot-vue3#989]
##### 问题描述：
pnpm i 一直不成功
我把 pnpm-lock.yaml 删除了也无效。

##### 截图&代码：

![6151704857969_ pic](https://github.com/jeecgboot/jeecgboot-vue3/assets/33024195/da0ac98e-0491-44f4-9260-4129682eb2c8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
多试几次

**Comment by yinxingen** [comment]
已经下了一上午了，用了梯子也不行

**Comment by yinxingen** [comment]
这是我node和pnpm版本号
![6161704858910_ pic](https://github.com/jeecgboot/jeecgboot-vue3/assets/33024195/849fa20d-e19b-4dba-aee6-cc20bc75d114)

**Comment by zhangdaiscott** [comment]
@commitlint/config-conventional

不清楚你为啥下载不来，这个依赖可以删掉，不影响

**Comment by hjhcos** [comment]
你是不是配置过下载源，你这个可能是网络或镜像库的原因

**Comment by yinxingen** [comment]
应该是pnpm 镜像库 存在问题，我换成cnpm下载可以运行了。
