### ISSUE TITLE
环境配置成功，为什么请求路由会使本地呢？

### ISSUE THREAD

**Issue by dhanyue** [jeecgboot/jeecgboot-vue3#99]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/6113896/173731079-7dde25ae-ec6f-4a50-8546-45142460ed5c.png)
![image](https://user-images.githubusercontent.com/6113896/173731136-a679fca4-246c-469d-ae9d-8fbd208a5f75.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看文档，有两地方要配置

**Comment by dhanyue** [comment]
哪两个地方，已按照配置文档，不知是哪两个地方
