### ISSUE TITLE
Vue3版的前端，必须要求node版本要18+吗？

### ISSUE THREAD

**Issue by 18237966658** [jeecgboot/jeecgboot-vue3#990]
##### 版本号：
 3.6.2

##### 问题描述：

Vue3版的前端，必须要求node版本要18+吗？
install的时候 我的node 16+的版本 很多包都不支持

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50265705/7b83c679-f36a-4f23-8a92-4d0c34228d63)

**Comment by zhangdaiscott** [comment]
没要求啊，我的版本
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/572a8fae-a011-4c40-9355-291c5ddcc571)

**Comment by 18237966658** [comment]
> 没要求啊，我的版本 ![image](https://private-user-images.githubusercontent.com/3162115/295461830-572a8fae-a011-4c40-9355-291c5ddcc571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjYzNzAsIm5iZiI6MTcwNDg2NjA3MCwicGF0aCI6Ii8zMTYyMTE1LzI5NTQ2MTgzMC01NzJhOGZhZS1hMDExLTRjNDAtOTM1NS0yOTFjNWRkY2M1NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDU1NDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U0MWQyMTMxMjIyYjlmNjU3MzdmOTYwZTMxODA3ZGQzOTFiZGZhOGQ4MGQwNzU1MmU2ODQxNzkwZGZjMWRmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UmpuR6Twk1oL-3D2b7bwk38f_Cbgb8D32_B7EGB4I9k)

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50265705/50ce4697-a81a-4a73-a56f-1708ef044e8e)
我把版本升级到18+ 就可以正常install， 然后切换到 16.16.0 install就有很多包提示至少需要 >=18.x   ,代码是github上拉的最新版

**Comment by zhangdaiscott** [comment]
你看看你lock里面 vue  vite的版本号

**Comment by 18237966658** [comment]
> 你看看你lock里面 vue vite的版本号

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/50265705/531218d8-6051-4b82-bbe4-c5253d65545b)
vite 版本是1.22.17 是正常的吗？

**Comment by zhangdaiscott** [comment]
vue的版本降低为3.1.0

**Comment by 18237966658** [comment]
> vue的版本降低 "vue": "3.3.11",

好了 谢谢大佬！！！！！
