### ISSUE TITLE
online表单设计字段填写表单的宽度可以设计为可调节宽度吗？

### ISSUE THREAD

**Issue by dugudongfangshuo** [jeecgboot/jeecgboot-vue3#994]
##### 版本号：
jeecg-vue3 最新版

##### 问题描述：
online表单设计字段填写表单的宽度可以设计为可调节宽度吗？
字段过长，遮挡后修改起来很麻烦。
此外这个online模块没有开源哎，能开源吗，像这种小问题 开源了我自己修改一下也行呀

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/32250216/225f8b4b-2821-42a6-8490-c598ec2c30ae)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/e956bf42-7445-4ade-a685-e4627e4bfad3)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/3162115/8440e4c5-5c49-456a-aa5c-541bf8a51959)
