### ISSUE TITLE
左树右表功能可以加一下吗，还有主表支持树功能

### ISSUE THREAD

**Issue by dugudongfangshuo** [jeecgboot/jeecgboot-vue3#995]
##### 版本号：
jeecg-vue3 最新

##### 问题描述：
左树右表功能可以加一下吗，
还有主表支持树功能
这些功能用的多，按低代码平台得提供一下吧
多谢
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后期待规划，先收集到 https://github.com/jeecgboot/jeecg-boot/issues/1312
